<script type="text/javascript">
    function printPreview()
    {
        common_selectDialBox('employees');
        var url = sz_BaseUrl + '/static/m185/show';
        var data = $('#report').serialize();
        qssAjax.getHtml(url, data, function(jreturn) {
            $('#print-area').html(jreturn);
            removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
        });
    }

    function filterDepartment()
    {
        var url  = sz_BaseUrl + '/static/m185/departments/';
        var data = {factory:$('#factory').val()};
        var html = '<option value="">Chọn</option>';

        qssAjax.call(url, data, function(jreturn) {
            for(i in jreturn.data)
            {
                html += '<option value="'+jreturn.data[i].BoPhan+'">'+jreturn.data[i].BoPhan+'</option>'
            }

            $('#department').html(html);
        }, function(jreturn) {
            qssAjax.alert(jreturn.message);
        });
    }

    $(document).ready(function () {
        filterDepartment();
    });
</script>

<div class="clear"></div>
<div id="view">
    <div class="line-hr">
        <span> <?php echo Qss_Lib_System::getReportTitle('M185');?> </span>
    </div>
    <form id="report" method="post" action="">
        <table class="detail">
            <!-- Thời gian -->
            <tr>
                <th width="20%" class="report-param-label">
                    Thời gian <span class="red bold">(*)</span>
                </th>
                <td>
                    <?php echo $this->views->Report->Datepicker('start', date('01-m-Y'));?>
                    <?php echo $this->views->Report->Datepicker('end', date('t-m-Y'));?>
                </td>
            </tr>

            <!-- Nhân viên -->
            <tr>
                <th width="20%" class="report-param-label">
                    Nhân viên
                </th>
                <td>
                    <?php echo $this->views->Report->AjaxDialBox('employees', 'ODanhSachNhanVien', 'IOID', array('MaNhanVien', 'TenNhanVien'));?>
                </td>
            </tr>

            <!-- Nhà máy -->
            <tr>
                <th width="20%" class="report-param-label">
                    Nhà máy
                </th>
                <td>
                    <?php //echo $this->views->Report->SimpleComboBox('factory', $this->factories, 'style="width:200px;" onchange="filterDepartment()"');?>
                    <?php
                    $id            = 'factory';
                    $getFields     = array('num'=>3,
                        'objects'=>array('OPhongBan'=>array(
                            'id'=>'IOID'
                        ,'display1'=>'TenPhongBan'
                        ,'order' =>'TenPhongBan') ));
                    ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
                </td>
            </tr>

            <!-- Phiếu đề nghị -->
            <tr>
                <th width="20%" class="report-param-label">
                    Bộ phận
                </th>
                <td>
                    <?php //echo $this->views->Report->SimpleComboBox('department', $this->departments);?>
                    <?php
                    $id            = 'department';
                    $getFields     = array('num'=>3,
                        'objects'=>array('OBoPhan'=>array(
                            'id'=>'IOID'
                        ,'display1'=>'TenBoPhan'
                        ,'order' =>'TenBoPhan') ));
                    $filter         = array(
                        0 => array(
                            'id' => 'factory'
                        , 'refField' => array(
                                'OBoPhan' => 'Ref_MaPhongBan'
                            )
                        , 'required' => 1
                        )
                    );
                    ?><?php echo $this->views->Report->ComboBox($id,$getFields,$filter);?>
                </td>
            </tr>
        </table>
    </form>
    <p>

    <hr>
    <?php echo $this->views->Report->PrintToolbar();?>
    <div id="print-content">
        <div id="print-area"></div>
    </div>
</div>
