<?php
$widths = array(1.2, 3, 3, 3, 5, 5, 6, 4, 3, 3, 3, 2, 4);
$widths = Qss_Lib_Report::changeWidthToFitScreen3($widths);
$stt    = 0;
?>

<div class="landscape">
    <!-- REPORT TITLE -->
    <div id="head_print">
        <?php echo $this->views->Common->Landscape() ?>
        <?php //echo $this->views->Common->Legal() ?>
        <h2 class="center"><?php echo @Qss_Lib_System::getUpperCaseReportTitle('M846');?></h2>
    </div><!-- end div#head_print -->
    <br/>

    <!-- REPORT DATA -->
    <div id="container">
        <table cellpadding="0" cellspacing="0" border="1" class="border" style="">
            <?php $begin = 0;?>
            <tr class="bggrey">
                <th style="width:<?php echo $widths[$begin++];?>%">STT</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Số phiếu bảo trì</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Nhóm thiết bị</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Khu vực</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Tên thiết bị</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Mã thiết bị</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Tên công việc bảo trì</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Người chịu trách nhiệm bảo trì</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Ngày yêu cầu</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Ngày bắt đầu</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Ngày hoàn thiện</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Tình trạng</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Ghi chú</th>
            </tr>

            <?php foreach($this->report as $item):?>
                <tr>
                    <td class="center"><?php echo ++$stt;?></td>
                    <td class="left"><?php echo $item->SoPhieu;?></td>
                    <td class="left"><?php echo $item->NhomThietBi;?></td>
                    <td class="left"><?php echo $item->TenKhuVuc;?></td>
                    <td class="left"><?php echo $item->TenThietBi;?></td>
                    <td class="left"><?php echo $item->MaThietBi;?></td>
                    <td class="left"><?php echo $item->MoTa;?></td>
                    <td class="left"><?php echo $item->NguoiThucHien;?></td>
                    <td class="center"><?php echo $item->NgayYeuCau?Qss_Lib_Date::mysqltodisplay($item->NgayYeuCau):'';?></td>
                    <td class="center"><?php echo $item->NgayBatDau?Qss_Lib_Date::mysqltodisplay($item->NgayBatDau):'';?></td>
                    <td class="center"><?php echo $item->Ngay?Qss_Lib_Date::mysqltodisplay($item->Ngay):'';?></td>
                    <td class="center"><?php echo $item->Step;?></td>
                    <td class="left"><?php echo @$item->GhiChu;?></td>
                </tr>
            <?php endforeach;?>
        </table>

        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>

        </p>
    </div><!-- end div#container -->
</div><!-- END REPORT -->


