<?php 
$widths   = array(1,2,2,2,2,2,5,2);
$width    = 1200;
$padding  = 2;
$fit      = Qss_Lib_Report::changeWidthToFitScreen2($widths, $width, $padding);
?>

<div id="M413_invoice_wrap">
    <h3>
        Hóa đơn
    </h3>  
    
    <div class="clr">
        <input type="hidden" i> 
    </div>
    
    <div>
        <button type="button" class="btn btn-custom" onclick="M413.createInvoice();"> Tạo hóa đơn </button>
    </div>
    <br/>
    
    <div class="clear"></div>
    <table 
        class="border_table" 
        cellpadding="0" 
        cellspacing="0" 
        border="0" 
        style="width:<?php echo $width;?>px;  table-layout: fixed;" >
        <?php $begin = 0; ?>
        <?php $stt   = 0;?>
        <tr>
            <th style="width:<?php echo $fit[$begin++];?>px">STT</th>
            <th style="width:<?php echo $fit[$begin++];?>px">Số hóa đơn</th>
            <th style="width:<?php echo $fit[$begin++];?>px">Số hóa đơn giá trị gia tăng </th>
            <th style="width:<?php echo $fit[$begin++];?>px">Ngày</th>
            <th style="width:<?php echo $fit[$begin++];?>px">Tổng tiền</th>
            <th style="width:<?php echo $fit[$begin++];?>px">Tình trạng</th>
            <th style="width:<?php echo $fit[$begin++];?>px">Ghi chú</th>
            <th style="width:<?php echo $fit[$begin++];?>px">Thanh toán</th>
        </tr>  
        
        <?php foreach($this->invoices as $item):?>
        <tr>
            <td class="center"> <?php echo ++$stt;?> </td>
            <td class="left"> <?php echo $item->SoChungTu;?></td>
            <td class="left"> <?php echo $item->SoHoaDon;?></td>
            <td class="center"> <?php echo Qss_Lib_Date::mysqltodisplay($item->NgayChungTu);?></td>
            <td class="right"> <?php echo Qss_Lib_Util::formatMoney($item->GiaTri);?></td>
            <td class="center <?php echo $item->Color;?>"> <?php echo $item->Name;?></td>
            <td class="left"> <?php echo $item->GhiChu;?></td>
            <td class="center"> <button type="button" class="btn btn-custom" onclick=""> Thanh toán </button> </td>
        </tr>
        <?php endforeach;?>  
    </table>
    <br/>
    <hr/>    
</div><!-- end #M413_invoice_wrap -->