<script type="text/javascript">
    function printPreview()
    {
        var url = sz_BaseUrl + '/static/m418/show';
        var data = $('#report').serialize();
        qssAjax.getHtml(url, data, function(jreturn) {
            $('#print-area').html(jreturn);
            removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
        });
    }
</script>

<div class="clear"></div>
<div id="view">
    <div class="line-hr">
        <span> <?php echo Qss_Lib_System::getReportTitle('M418');?> </span>
    </div>
    <form id="report" method="post" action="">
        <table class="detail">
            <!-- Thời gian -->
            <tr>
                <th width="20%" class="report-param-label">
                    Thời gian <span class="red bold">(*)</span>
                </th>
                <td>
                    <?php echo $this->views->Report->Datepicker('start', date('01-m-Y'));?>
                    <?php echo $this->views->Report->Datepicker('end', date('t-m-Y'));?>
                </td>
            </tr>

            <tr>
                <th width="20%" class="report-param-label">
                    Vật tư
                </th>
                <td>
                    <?php echo $this->views->Report->SimpleListBox('item', '/static/m418/items/');?>
                </td>
            </tr>

            <tr>
                <th width="20%" class="report-param-label">
                    Serial
                </th>
                <td>
                    <?php echo $this->views->Report->SimpleListBox('serial', '/static/m418/serials/');?>
                </td>
            </tr>
        </table>
    </form>
    <p>

    <hr>
    <?php echo $this->views->Report->PrintToolbar();?>
    <div id="print-content">
        <div id="print-area"></div>
    </div>
</div>
