<form id='form_M049_filter' name='filter_form' method='post' onsubmit="rowSearch('M049'); return false;">
<input type='hidden' id='qss_form_tree' name='qss_form_tree' value='0'>
<table class="" cellpadding="0" cellspacing="0">
<tr style="border-bottom:1px #ccc dashed"><td><span>
					<?php echo $this->form->getFieldByCode("OCheDoCong","Ma")->szFieldName;?></span></td><td style="padding-left:5px;"><span><?php echo Qss_Lib_Template::sz_fGetFieldElement($this->form->getFieldByCode("OCheDoCong","Ma"),$this->filter);?></span></td></tr><tr style="border-bottom:1px #ccc dashed"><td><span>
					<?php echo $this->form->getFieldByCode("OCheDoCong","Ten")->szFieldName;?></span></td><td style="padding-left:5px;"><span><?php echo Qss_Lib_Template::sz_fGetFieldElement($this->form->getFieldByCode("OCheDoCong","Ten"),$this->filter);?></span></td></tr><tr style="border-bottom:1px #ccc dashed"><td><span>
					<?php echo $this->form->getFieldByCode("OCheDoCong","GioCongNgay")->szFieldName;?></span></td><td style="padding-left:5px;"><span><?php echo Qss_Lib_Template::sz_fGetFieldElement($this->form->getFieldByCode("OCheDoCong","GioCongNgay"),$this->filter);?></span></td></tr><tr style="border-bottom:1px #ccc dashed"><td><span>
					<?php echo $this->form->getFieldByCode("OCheDoCong","UngCong")->szFieldName;?></span></td><td style="padding-left:5px;"><span><?php echo Qss_Lib_Template::sz_fGetFieldElement($this->form->getFieldByCode("OCheDoCong","UngCong"),$this->filter);?></span></td></tr><tr style="border-bottom:1px #ccc dashed"><td><span>
					<?php echo $this->form->getFieldByCode("OCheDoCong","GioHanTangCaTuan")->szFieldName;?></span></td><td style="padding-left:5px;"><span><?php echo Qss_Lib_Template::sz_fGetFieldElement($this->form->getFieldByCode("OCheDoCong","GioHanTangCaTuan"),$this->filter);?></span></td></tr><tr style="border-bottom:1px #ccc dashed"><td><span>
					<?php echo $this->form->getFieldByCode("OCheDoCong","GioiHanTangCaThang")->szFieldName;?></span></td><td style="padding-left:5px;"><span><?php echo Qss_Lib_Template::sz_fGetFieldElement($this->form->getFieldByCode("OCheDoCong","GioiHanTangCaThang"),$this->filter);?></span></td></tr><tr style="border-bottom:1px #ccc dashed"><td><span>
					<?php echo $this->form->getFieldByCode("OCheDoCong","GioiHanTangCaNam")->szFieldName;?></span></td><td style="padding-left:5px;"><span><?php echo Qss_Lib_Template::sz_fGetFieldElement($this->form->getFieldByCode("OCheDoCong","GioiHanTangCaNam"),$this->filter);?></span></td></tr></table>
<div class="clearfix"></div><br/>
<table class="" cellpadding="0" cellspacing="0">
</table>
</form>
