<form id='form_M060_filter' name='filter_form' method='post' onsubmit="rowSearch('M060'); return false;">
<input type='hidden' id='qss_form_tree' name='qss_form_tree' value='0'>
<table class="" cellpadding="0" cellspacing="0">
</table>
<div class="clearfix"></div><br/>
<table class="" cellpadding="0" cellspacing="0">
</table>
</form>
<div style="width:200px">
<h3><?php echo $this->_translate(2)?></h3>
</div>
