<form id='form_M086_filter' name='filter_form' method='post' onsubmit="rowSearch('M086'); return false;">
<input type='hidden' id='qss_form_tree' name='qss_form_tree' value='0'>
<table class="" cellpadding="0" cellspacing="0">
<tr style="border-bottom:1px #ccc dashed"><td><span>
					<?php echo $this->form->getFieldByCode("OKeHoachDaoTao","MaKeHoach")->szFieldName;?></span></td><td style="padding-left:5px;"><span><?php echo Qss_Lib_Template::sz_fGetFieldElement($this->form->getFieldByCode("OKeHoachDaoTao","MaKeHoach"),$this->filter);?></span></td></tr><tr style="border-bottom:1px #ccc dashed"><td><span>
					<?php echo $this->form->getFieldByCode("OKeHoachDaoTao","TenKeHoach")->szFieldName;?></span></td><td style="padding-left:5px;"><span><?php echo Qss_Lib_Template::sz_fGetFieldElement($this->form->getFieldByCode("OKeHoachDaoTao","TenKeHoach"),$this->filter);?></span></td></tr></table>
<div class="clearfix"></div><br/>
<table class="" cellpadding="0" cellspacing="0">
</table>
</form>
