<form id='form_M322_filter' name='filter_form' method='post' onsubmit="rowSearch('M322'); return false;">
<input type='hidden' id='qss_form_tree' name='qss_form_tree' value='0'>
<table class="" cellpadding="0" cellspacing="0">
<tr style="border-bottom:1px #ccc dashed"><td><span>
					<?php echo $this->form->getFieldByCode("OBaoHiem","MaNhanVien")->szFieldName;?></span></td><td style="padding-left:5px;"><span><?php echo Qss_Lib_Template::sz_fGetFieldElement($this->form->getFieldByCode("OBaoHiem","MaNhanVien"),$this->filter);?></span></td></tr><tr style="border-bottom:1px #ccc dashed"><td><span>
					<?php echo $this->form->getFieldByCode("OBaoHiem","TenNhanVien")->szFieldName;?></span></td><td style="padding-left:5px;"><span><?php echo Qss_Lib_Template::sz_fGetFieldElement($this->form->getFieldByCode("OBaoHiem","TenNhanVien"),$this->filter);?></span></td></tr><tr style="border-bottom:1px #ccc dashed"><td><span>
					<?php echo $this->form->getFieldByCode("OBaoHiem","MucLuong")->szFieldName;?></span></td><td style="padding-left:5px;"><span><?php echo Qss_Lib_Template::sz_fGetFieldElement($this->form->getFieldByCode("OBaoHiem","MucLuong"),$this->filter);?></span></td></tr><tr style="border-bottom:1px #ccc dashed"><td><span>
					<?php echo $this->form->getFieldByCode("OBaoHiem","NgayBatDau")->szFieldName;?></span></td><td style="padding-left:5px;"><span><?php echo Qss_Lib_Template::sz_fGetFieldElement($this->form->getFieldByCode("OBaoHiem","NgayBatDau"),$this->filter);?></span></td></tr><tr style="border-bottom:1px #ccc dashed"><td><span>
					<?php echo $this->form->getFieldByCode("OBaoHiem","NgayKetThuc")->szFieldName;?></span></td><td style="padding-left:5px;"><span><?php echo Qss_Lib_Template::sz_fGetFieldElement($this->form->getFieldByCode("OBaoHiem","NgayKetThuc"),$this->filter);?></span></td></tr></table>
<div class="clearfix"></div><br/>
<table class="" cellpadding="0" cellspacing="0">
</table>
</form>
