<form id='form_M342_filter' name='filter_form' method='post' onsubmit="rowSearch('M342'); return false;">
<input type='hidden' id='qss_form_tree' name='qss_form_tree' value='0'>
<table class="" cellpadding="0" cellspacing="0">
<tr style="border-bottom:1px #ccc dashed"><td><span>
					<?php echo $this->form->getFieldByCode("ODieuChinhLuong","MaNV")->szFieldName;?></span></td><td style="padding-left:5px;"><span><?php echo Qss_Lib_Template::sz_fGetFieldElement($this->form->getFieldByCode("ODieuChinhLuong","MaNV"),$this->filter);?></span></td></tr><tr style="border-bottom:1px #ccc dashed"><td><span>
					<?php echo $this->form->getFieldByCode("ODieuChinhLuong","TenNV")->szFieldName;?></span></td><td style="padding-left:5px;"><span><?php echo Qss_Lib_Template::sz_fGetFieldElement($this->form->getFieldByCode("ODieuChinhLuong","TenNV"),$this->filter);?></span></td></tr><tr style="border-bottom:1px #ccc dashed"><td><span>
					<?php echo $this->form->getFieldByCode("ODieuChinhLuong","Thang")->szFieldName;?></span></td><td style="padding-left:5px;"><span><?php echo Qss_Lib_Template::sz_fGetFieldElement($this->form->getFieldByCode("ODieuChinhLuong","Thang"),$this->filter);?></span></td></tr><tr style="border-bottom:1px #ccc dashed"><td><span>
					<?php echo $this->form->getFieldByCode("ODieuChinhLuong","Nam")->szFieldName;?></span></td><td style="padding-left:5px;"><span><?php echo Qss_Lib_Template::sz_fGetFieldElement($this->form->getFieldByCode("ODieuChinhLuong","Nam"),$this->filter);?></span></td></tr><tr style="border-bottom:1px #ccc dashed"><td><span>
					<?php echo $this->form->getFieldByCode("ODieuChinhLuong","LoaiDieuChinh")->szFieldName;?></span></td><td style="padding-left:5px;"><span><?php echo Qss_Lib_Template::sz_fGetFieldElement($this->form->getFieldByCode("ODieuChinhLuong","LoaiDieuChinh"),$this->filter);?></span></td></tr><tr style="border-bottom:1px #ccc dashed"><td><span>
					<?php echo $this->form->getFieldByCode("ODieuChinhLuong","SoTien")->szFieldName;?></span></td><td style="padding-left:5px;"><span><?php echo Qss_Lib_Template::sz_fGetFieldElement($this->form->getFieldByCode("ODieuChinhLuong","SoTien"),$this->filter);?></span></td></tr><tr style="border-bottom:1px #ccc dashed"><td><span>
					<?php echo $this->form->getFieldByCode("ODieuChinhLuong","PhanTram")->szFieldName;?></span></td><td style="padding-left:5px;"><span><?php echo Qss_Lib_Template::sz_fGetFieldElement($this->form->getFieldByCode("ODieuChinhLuong","PhanTram"),$this->filter);?></span></td></tr></table>
<div class="clearfix"></div><br/>
<table class="" cellpadding="0" cellspacing="0">
</table>
</form>
