<div class="cal_content_title">
    <p class="cal_content_title_arrow"><a href="#1" onclick="showMonth('<?php echo $this->prev[0]?>','<?php echo $this->prev[1]?>');"><img src="/images/calendar/left_arrow_32.png"/></a></p>
	<p class="cal_content_title_info">Tháng <?php echo $this->m?>/<?php echo $this->y?></p>
    <p class="cal_content_title_arrow"><a href="#1" onclick="showMonth('<?php echo $this->next[0]?>','<?php echo $this->next[1]?>');"><img src="/images/calendar/right_arrow_32.png"/></a></p>
</div><!-- end .cal_title -->
<?php $starttime=strtotime($this->startdate);?>
<?php $endtime=strtotime($this->enddate);?>
<?php $startday = date('w',$starttime);?>

<div class="cal_content_grid cal_content_month">
	<div class="rows">
    	<?php for($i=1;$i<=$this->daysInMonth;$i++):?>
        <div class="cols cols_<?php echo $this->daysInMonth?> <?php if(($i + $startday) % 7 == 0 || ($i + $startday) % 7 == 1):?>cal_cols_holiday<?php endif;?>">
        	<?php echo $i?>
        </div><!-- end .cal_content_grid_cols -->
        <?php endfor;?>
    </div><!-- end .rows -->
    
	<?php $j=1;?>
	<?php $eventid = 0?>
	<?php foreach($this->data as $item):?>
		<?php $start=strtotime($item->SDate);?>
		<?php $end= strtotime($item->EDate);?>
		<?php if($eventid != $item->EventID):?>
			<?php if($eventid):?>	
				<?php $j++;?>
				<?php for($i=1;$i<=$this->daysInMonth;$i++):?>
					<div class="cols cols_<?php echo $this->daysInMonth?> <?php if(($i + $startday) % 7 == 0 || ($i + $startday) % 7 == 1):?>cal_cols_holiday<?php endif;?>">
						&nbsp;
					</div><!-- end .cal_content_grid_cols -->
				<?php endfor;?>
				</div>
			<?php endif;?>
			<div class="rows">
		<?php endif;?>
			<?php $mleft=1;?>
			<?php $mright=$this->daysInMonth;?>
			<?php switch ($item->Type){
				case 0:
				case 1:?>
					<?php if($start > $starttime):?>
						<?php $mleft=date('d',$start);?>
					<?php endif;?>
					<?php if(!$end):?>
						<?php $mright=date('d',$endtime);?>
					<?php elseif($end < $endtime):?>
						<?php $mright=date('d',$end);?>
					<?php endif;?>
				<?php break;?>
				<?php case 2:?>
					<?php for($i=1;$i<=$this->daysInMonth;$i++):?>
						<?php $tmptime = strtotime($this->y.'-'.$this->m.'-'.$i);?>
						<?php if(date('w',$tmptime) == $item->WDay):?>
							<?php $mleft=$i;?>
							<?php $mright=$i;?>
							<div class="event_parent"> 
								<?php if($start < $starttime):?>
									<div  class = "leftArrow"></div>
								<?php endif;?>
								<div class="event bgyellow" style="margin-left:<?php echo (100/$this->daysInMonth)*($mleft-1);?>%; width:<?php echo (100/$this->daysInMonth)*($mright-$mleft+1);?>%;  border:1px #ccc solid;" title="<?php echo $item->Title?> <?php echo $item->Description?>" onclick="rowEventEdit(<?php echo $item->EventID?>)"><?php echo $item->Title?></div>
								<?php if($end > $endtime):?>
									<div  class = "rightArrow"></div>
								<?php endif;?>
							</div>
						<?php endif;?>
					<?php endfor;?>
					
				<?php break;?>
				<?php case 3:?>
					<?php $tmptime = strtotime($this->y.'-'.$this->m.'-'.$item->Day);?>
					<?php if($tmptime < $starttime || $tmptime > $endtime) continue 2;?>
					<?php $mleft=date('d',$tmptime);?>
					<?php $mright=date('d',$tmptime);?>
				<?php break;?>
				<?php case 4:?>
					<?php $tmptime = strtotime($this->y.'-'.$item->Month.'-'.$item->Day);?>
					<?php if($tmptime < $starttime || $tmptime > $endtime) continue 2;?>
					<?php $mleft=date('d',$tmptime);?>
					<?php $mright=date('d',$tmptime);?>
				<?php break;?>
			<?php };?>
			
			 <div class="event_parent"> 
				<?php if($start < $starttime):?>
					<div  class = "leftArrow"></div>
				<?php endif;?>
				<div class="event bgyellow" style="margin-left:<?php echo (100/$this->daysInMonth)*($mleft-1);?>%; width:<?php echo (100/$this->daysInMonth)*($mright-$mleft+1);?>%;  border:1px #ccc solid;" title="<?php echo $item->Title?> <?php echo $item->Description?>" onclick="rowEventEdit(<?php echo $item->EventID?>)"><?php echo $item->Title?></div>
				<?php if($end > $endtime):?>
					<div  class = "rightArrow"></div>
				<?php endif;?>
			</div>
			
	<?php $eventid = $item->EventID?>
	<?php endforeach;?>
	<?php if($eventid):?>
		<?php $j++;?>
		<?php for($i=1;$i<=$this->daysInMonth;$i++):?>
			<div class="cols cols_<?php echo $this->daysInMonth?> <?php if(($i + $startday) % 7 == 0 || ($i + $startday) % 7 == 1):?>cal_cols_holiday<?php endif;?>">
				&nbsp;
			</div><!-- end .cal_content_grid_cols -->
		<?php endfor;?>
		</div>
	<?php endif;?>
	
    <?php while($j<30):?>
		<div class="rows">
			<?php for($i=1;$i<=$this->daysInMonth;$i++):?>
			<div class="cols cols_<?php echo $this->daysInMonth?> <?php if(($i + $startday) % 7 == 0 || ($i + $startday) % 7 == 1):?>cal_cols_holiday<?php endif;?>">
				&nbsp;
			</div><!-- end .cal_content_grid_cols -->
			<?php endfor;?>
		</div>
		<?php $j++;?>
    <?php endwhile;?>
</div><!-- end .cal_content_grid -->



