<div class="cal_content_title">
	<p class="cal_content_title_arrow"><a href="#1" onclick="showYear('<?php echo $this->y-1?>');"><img src="/images/calendar/left_arrow_32.png"/></a></p>
	<p class="cal_content_title_info">Năm <?php echo $this->y?></p>
    <p class="cal_content_title_arrow"><a href="#1" onclick="showYear('<?php echo $this->y+1?>');"><img src="/images/calendar/right_arrow_32.png"/></a></p>
</div><!-- end .cal_title -->

<div class="cal_content_grid cal_content_year">
	<div class="rows">
    	<?php for($i=1;$i<=12;$i++):?>
        <div class="cols cols_12">
        	Tháng <?php echo $i?>
        </div><!-- end .cols -->
        <?php endfor;?>
    </div><!-- end .rows -->
    
	<?php $j=1;?>
	<?php $starttime=strtotime($this->startdate);?>
	<?php $endtime=strtotime($this->enddate);?>
	<?php $group1 = 0?>
	<?php $group2 = 0?>
	<?php foreach($this->data as $item):?>
		<?php $start=strtotime($item->SDate);?>
		<?php $end= $item->EDate?strtotime($item->EDate):0;?>
		<?php if($group1 !== $item->Ref_MaDVBT):?>
			<div class="rows_group"><?php echo $item->TenDVBT?>
			</div>
		<?php endif;?>
		<?php if($group2 !== $item->Ref_NguoiThucHien):?>
			<div class="rows_group"><?php echo $item->NguoiThucHien?$item->NguoiThucHien:'Chưa giao việc'?>
			</div>
		<?php endif;?>
		<div class="rows">
			<?php $mleft=1;?>
			<?php $mright=12;?>
			<?php if($start > $starttime):?>
					<?php $mleft=date('m',$start);?>
			<?php endif;?>
			<?php if(!$end && !$aend):?>
				<?php $mright=12;?>
			<?php elseif($end < $endtime):?>
					<?php $mright=date('m',$end);?>
			<?php endif;?>
			<div class="event_parent"> 
				<?php if($start < $starttime):?>
					<div  class = "leftArrow"></div>
				<?php endif;?>
				<div class="event <?php echo (strpos($item->color,'bg') !== false) ? $item->color:('bgyellow '.$item->color)?>" style="margin-left:<?php echo (100/12)*($mleft-1);?>%; width:<?php echo (100/12)*($mright-$mleft+1);?>%;  border:1px #ccc solid;" title="<?php echo $item->SoPhieu?> <?php echo $item->LoaiBaoTri?>" onclick="openCalendar('<?php echo $item->formcode;?>','<?php echo $item->IFID?>','<?php echo $item->DepartmentID?>', {},reloadCalendar)"><?php echo $item->MaThietBi?></div>
				<?php if($end > $endtime):?>
					<div  class = "rightArrow"></div>
				<?php endif;?>
			</div>
		<?php for($i=1;$i<=12;$i++):?>
			<div class="cols cols_12">
				&nbsp;
			</div><!-- end .cols -->
		<?php endfor;?>
		</div>
	<?php $j++;?>
	<?php $group1 =  $item->Ref_MaDVBT?>
	<?php $group2 =  $item->Ref_NguoiThucHien?>
	<?php endforeach;?>	
	
     <?php while($j<30):?>
		<div class="rows">
			<?php for($i=1;$i<=12;$i++):?>
			<div class="cols cols_12">
				&nbsp;
			</div><!-- end .cols -->
			<?php endfor;?>
		</div>
		<?php $j++;?>
    <?php endwhile;?>
</div><!-- end .cal_content_grid -->



