<?php
$excel_col      = array_flip(Qss_Lib_Const::$EXCEL_COLUMN);
$bg             = Qss_Lib_Extra_Const::REPORT_EXCEL_THEAD_COLOR;
$row            = 2;
$totalColumn    = 7;
$colWidths      = array(100, 100, 150, 200, 500);
$excelColWidths = Qss_Lib_Report::convertPxColumnWidthToExcelWidth($colWidths);
$autoFit        = Qss_Lib_Report::changeWidthToFitScreen($colWidths);
?>

<form id="excel" method="post" action="/report/index/excel" target="new">
    <input type="hidden" id="content" name="content" value="">
</form>

<div class="portrait">
    <excel
        orientation="<?php echo Qss_Lib_Extra_Const::REPORT_ORIENTATION_PORTRAIT;?>"
        font-name="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_FONT_NAME;?>"
        font-size="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_FONT_SIZE;?>"
        margin-left="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_MARGIN_LEFT;?>"
        margin-right="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_MARGIN_RIGHT;?>"
        margin-top="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_MARGIN_TOP;?>"
        margin-bottom="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_MARGIN_BOTTOM;?>"  />

    <!-- REPORT TITLE -->
	<div id="head_print">
		<?php echo $this->views->Common->Portrait() ?>
        <center>
            <h2>
                <xls
                    row="<?php echo $row ?>"
                    column="A"
                    column-merge="<?php echo $excel_col[$totalColumn] ?>"
                    font-size="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_TITLE_FONT_SIZE;?>"
                    wrap-text="1"
                    bold="1"
                    h-align="center"
                    v-align="center" ><?php echo $this->_translate(1);?>  </xls>
            </h2>
        </center>
        <?php $row++ ?>

        <center>
            <p class="bold">
                <xls
                    row="<?php echo $row ?>"
                    column="A"
                    column-merge="<?php echo $excel_col[$totalColumn] ?>"
                    font-size="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_TITLE_FONT_SIZE;?>"
                    wrap-text="1"
                    bold="1"
                    h-align="center"
                    v-align="center" ><?php echo $this->_translate(2);?>..............................<?php echo $this->_translate(3);?>..............................  </xls>
            </p>
        </center>
        <?php $row++ ?>
	</div><!-- end div#head_print -->
	<?php $row++ ?>

    <!-- REPORT DATA -->
    <div id="container">

        <table cellpadding="0" cellspacing="0" border="0" class="border" style="">

            <?php $begin = 0;?>
            <tr class="bggrey">
                <!-- TT -->
                <th  rowspan="2"  style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        row-merge="1"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(4)?></xls>
                </th>

                <!-- Tên phiếu YCCC -->
                <th  rowspan="2"  style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        row-merge="1"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(5)?></xls>
                </th>

                <!-- Nội dung các hạng mục vật tư" -->
                <th  rowspan="2"  style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        row-merge="1"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(6)?></xls>
                </th>

                <!-- Code Vật tư -->
                <th  rowspan="2"  style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        row-merge="1"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(7)?></xls>
                </th>

                <!-- Đơn vị tính -->
                <th  rowspan="2"  style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        row-merge="1"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(8)?></xls>
                </th>
                <?php $begin2 = $begin; ?>

                <!-- Vật tư nhập -->
                <th  colspan="3">
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        column-merge="<?php echo $excel_col[($begin+2)]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(20)?></xls>
                </th>
                <?php $begin = $begin + 2;?>

                <!-- Vật tư xuất/Tiêu hao -->
                <th  colspan="3">
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        column-merge="<?php echo $excel_col[($begin+2)]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(21)?></xls>
                </th>
                <?php $begin = $begin + 2;?>

                <!-- Số lượng tồn kho -->
                <th  rowspan="2"   style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        row-merge="1"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(22)?></xls>
                </th>

                <!-- Ghi chú -->
                <th  rowspan="2"   style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        row-merge="1"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(15)?></xls>
                </th>
            </tr>
            <?php $row++;?>

            <tr class="bggrey">
                <?php $begin = $begin2;?>
                <!-- Số lượng nhận <br/> (VT mua) -->
                <td   style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(9)?></xls>
                </td>

                <!-- Số lượng nhận <br/> (VT xuất kho) -->
                <td   style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(10)?></xls>
                </td>

                <!-- Tổng SL vật tư nhận -->
                <td   style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(11)?></xls>
                </td>

                <!-- Số lượng vật tư đã sử dụng -->
                <td   style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(12)?></xls>
                </td>

                <!-- Số lượng vật tư mất mát -->
                <td   style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(13)?></xls>
                </td>

                <!-- Số lượng vật tư hư hỏng -->
                <td   style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(14)?></xls>
                </td>
            </tr>
            <?php $row++;?>

            <tr>
                <?php $begin = 0;?>
                <!-- TT -->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>">(1)</xls>
                </th>

                <!-- Tên phiếu YCCC -->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>">(2)</xls>
                </th>

                <!-- Nội dung các hạng mục vật tư -->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>">(3)</xls>
                </th>

                <!-- Code Vật tư -->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>">(4)</xls>
                </th>

                <!-- Đơn vị tính -->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>">(5)</xls>
                </th>

                <!-- Số lượng nhận <br/> (VT mua)-->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>">(6)</xls>
                </th>

                <!-- Số lượng nhận <br/> (VT xuất kho)-->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>">(7)</xls>
                </th>

                <!-- Tổng SL vật tư nhận -->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>">(8)=(6)+(7)</xls>
                </th>

                <!-- Số lượng vật tư đã sử dụng -->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>">(9)</xls>
                </th>

                <!-- Số lượng vật tư mất mát -->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>">(10)</xls>
                </th>

                <!-- Số lượng vật tư hư hỏng -->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>">(11)</xls>
                </th>

                <!-- Số lượng tồn kho -->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>">(12)=(8)-(9)-(10)-(11)</xls>
                </th>

                <!-- Ghi chu -->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>">(13)</xls>
                </th>
            </tr>
            <?php $row++;?>


            <!-- COLUMN DATA -->
            <?php foreach($this->report as $data): // In bao cao?>
            <tr>
                <?php $begin = 0;?>
                <!-- title -->
                <td class="left" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="left"
                        border="1"
                        repeat="1"><?php echo $data->GiaTri?></xls>
                </td>

                <!-- TT -->
                <td class="center" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="center"
                        border="1"><?php echo +$stt?></xls>
                </td>

                <!-- Tên phiếu YCCC -->
                <td class="left" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="left"
                        border="1"><?php echo $this->params->SoPhieu?></xls>
                </td>

                <!-- Nội dung các hạng mục vật tư -->
                <td class="left" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="left"
                        border="1"><?php echo $data->TenSP?></xls>
                </td>

                <!-- Code Vật tư -->
                <td class="left" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="left"
                        border="1"><?php echo $data->MaSP?></xls>
                </td>

                <!-- Đơn vị tính -->
                <td class="center" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="center"
                        border="1"><?php echo $data->DonViTinh?></xls>
                </td>

                <!-- Số lượng nhận <br/> (VT mua)-->
                <td class="center" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="center"
                        border="1"><?php echo $data->SoLuongMua?></xls>
                </td>

                <!-- Số lượng nhận <br/> (VT xuất kho)-->
                <td class="center" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="center"
                        border="1"><?php echo $data->SoLuongNhan?></xls>
                </td>

                <!-- Tổng SL vật tư nhận -->
                <td class="center" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="center"
                        border="1"><?php echo ($data->SoLuongNhan + $data->SoLuongMua)?></xls>
                </td>

                <!-- Số lượng vật tư đã sử dụng -->
                <td class="center" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="center"
                        border="1"><?php echo $data->SuDung?></xls>
                </td>

                <!-- Số lượng vật tư mất mát -->
                <td class="center" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="center"
                        border="1"><?php echo $data->Mat?></xls>
                </td>

                <!-- Số lượng vật tư hư hỏng -->
                <td class="center" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="center"
                        border="1"><?php echo $data->HuHong?></xls>
                </td>

                <!-- Số lượng tồn kho -->
                <td class="center" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="center"
                        border="1"><?php echo (($data->SoLuongNhan + $data->SoLuongMua) - $data->SuDung - $data->Mat - $data->HuHong)?></xls>
                </td>

                <!-- Ghi chu -->
                <td class="left" >
                    &nbsp;
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="left"
                        border="1"></xls>
                </td>
            </tr>
            <?php $row++;?>
            <?php endforeach; // Ket thuc in bao cao?>
        </table><!-- end table.border -->


        <?php $row++;?>
        <?php $row++;?>
        <br/>
        <br/>

        <table cellpadding="0" cellspacing="0" border="0" style="">
            <tr>
                <!-- Người báo cáo -->
                <th style="width: 33%;">
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[1]?>"
                        column-merge="<?php echo $excel_col[3]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        ><?php echo $this->_translate(16);  ?> </xls>
                </th>

                <!-- Người kiểm tra -->
                <th style="width: 33%;">
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[4]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        ><?php echo $this->_translate(17);  ?> </xls>
                </th>

                <!-- <b>Phòng kỹ thuật</b> <br/> (Thẩm định) -->
                <th style="width: 33%;">
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[6]?>"
                        column-merge="<?php echo $excel_col[8]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        ><?php echo $this->_translate(18);?></xls>
                </th>

                <!-- <b>Ban Giám Đốc</b> <br/> (Là một giấm đốc hoặc một PGĐ phụ trách lĩnh vực đã phân công) -->
                <th style="width: 33%;">
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[11]?>"
                        column-merge="<?php echo $excel_col[13]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        ><?php echo $this->_translate(19);?></xls>
                </th>

            </tr>
        </table>
    </div><!-- end div#container -->
</div><!-- END REPORT -->