<script>
    function printPreview(){
        var msg   = '';
        msg += common_checkEmpty($('#start').val(), '<?php echo $this->_translate(2) ?>');
        msg += common_checkEmpty($('#end').val(), '<?php echo $this->_translate(3) ?>');
        msg += common_checkEmpty($('#employee').val(), '<?php echo $this->_translate(4) ?>');

        if(msg != '')
        {
            qssAjax.alert(msg);
            return;
        }
        else
        {
            var url = sz_BaseUrl + '/static/m161/show';
            var data = $('#report').serialize();
            data += "&str_employee="  + encodeURIComponent($('#employee').text());
            qssAjax.getHtml(url, data, function(jreturn) {
                $('#print-area').html(jreturn);
                removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
            });
        }
    }
</script>



<div class="clear"></div>
<div id="view">
    <div class="line-hr">
        <span><?php echo Qss_Lib_System::getReportTitle('M161');?> </span>
    </div>

    <form id="report" method="get" action="/static/m161/show">
        <table class="detail">
            <tr>
                <!-- Từ ngày -->
                <th width="20%" class="report-param-label">
                    <?php echo $this->_translate(2)?>:
                </th>

                <!-- Đến ngày -->
                <td>
                    <?php echo $this->views->Report->Datepicker('start', date('d-m-Y'));?>
                    <span class="bold red">(*)</span>
                    <b><?php echo $this->_translate(3)?>:</b>
                    <?php echo $this->views->Report->Datepicker('end', date('d-m-Y',strtotime("+1 week")));?>
                    <span class="bold red">(*)</span>
                </td>
            </tr>

            <tr>
                <th class="report-param-label"><?php echo $this->_translate(4)?>:</th>
                <td>
                    <?php
                        $id            = array('id'=>'employee', 'require'=>1, 'size'=>300);
                        $getDataObject = array('ODanhSachNhanVien' => array('MaNhanVien', 'TenNhanVien'));
                        $getFields     = array('num' => 2,
                            'objects' => array('ODanhSachNhanVien' => array(
                                'id' => 'IOID'
                                , 'display1' => 'MaNhanVien'
                                , 'display2' => 'TenNhanVien')
                            )
                        );
                        $getLookupFilter = array();

                        echo $this->views->Report->ListBox($id, $getDataObject, $getFields, $getLookupFilter);
                    ?>
                </td>
            </tr>
        </table>
    </form>
    <p>


    <hr>
    <?php echo $this->views->Report->PrintToolbar();?>
    <div id="print-content">
        <div id="print-area"></div>
    </div>
</div>
