<script>    
function printPreview(){
//	common_selectDialBox('maintype'); // Danh dau toan bo dialbox, PrintToolbar	
//	var ngay   = $('#location').val();
//        var msg   = '';

        //msg += common_checkEmpty(ngay, '<?php echo $this->_translate(5) ?>');
        
        
//        if(msg != '')
//        {
//            qssAjax.alert(msg);
//            return;
//        }
//        else
//        {
            var url = sz_BaseUrl + '/static/m791/show';
            var data = $('#report').serialize();
            qssAjax.getHtml(url, data, function(jreturn) {
                    $('#print-area').html(jreturn);
                    removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
            });
//        }
}

</script>


<div class="clear"></div>
<div id="view">
	<div class="line-hr">
		<span><?php echo $this->_translate(3)?> </span>
	</div>
	<form id="report" method="get" action="/static/m791/show">
		<table class="detail">

			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(4)?>
				</th>
				<td><?php echo $this->views->Report->Datepicker('date', date('d-m-Y'));?>
				</td>
			</tr>
			<tr>
				<th class="report-param-label"><?php echo $this->_translate(5)?></th>
				<td><?php
				$id            = 'location';
				$getFields     = array('num'=>3,
                                       'objects'=>array('OKhuVuc'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'MaKhuVuc'
                                                            , 'display2'=>'Ten') ));
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
				</td>
			</tr>

			<tr>
				<th class="report-param-label"><?php echo $this->_translate(6)?></th>
				<td><?php
				$id            = 'workcenter';
				$getFields     = array('num'=>3,
                                       'objects'=>array('ODonViSanXuat'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'Ma'
                                                            , 'display2'=>'Ten') ));
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
				</td>
			</tr>

		</table>
	</form>
	<p>
	
	
	<hr>
	<?php echo $this->views->Report->PrintToolbar();?>
	<div id="print-content">
		<div id="print-area"></div>
	</div>
</div>
<script type="text/javascript">
<!--

//-->
</script>
