<?php
$widths         = array(1, 8, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5);
$totalColumn    = count($widths);
$excel_col      = array_flip(Qss_Lib_Const::$EXCEL_COLUMN);
$htmlWidth      = Qss_Lib_Report::changeWidthToFitScreen($widths, Qss_Lib_Extra_Const::PRINT_TYPE_LANDSCAPE);
$excelWidth     = Qss_Lib_Report::convertPxColumnWidthToExcelWidth($widths, Qss_Lib_Extra_Const::PRINT_TYPE_LANDSCAPE);
$row            = 9; // Row bat dau
$bg             = "#EEEEEE"; // Mau nen cua cot tieu de
$sttCot         = 0;
$stt            = 0;
?>

<div class="landscape">
    <form id="excel" method="post" action="/report/index/excel" target="new">
        <input type="hidden" id="content" name="content" value="">
    </form>

    <excel orientation="landscape"
           font-name="Arial"
           font-size="10"
           margin-left="0.5"
           margin-right="0.5"
           margin-top="0.75"
           margin-bottom="0.75" />

    <div id="head_print">
        <?php echo $this->views->Common->Landscape() ?>

        <center>
            <h2 class="report-title">
                <xls row="<?php echo $row ?>"
                     column="A"
                     column-merge="<?php echo $excel_col[$totalColumn] ?>"
                     font-size="14"
                     wrap-text="1"
                     h-align="center"
                     v-align="center"> BÁO CÁO THỰC HIỆN KẾ HOẠCH SCTX THIẾT BỊ CƠ ĐIỆN THÁNG <?php echo $this->month;?> NĂM <?php echo $this->year;?></xls>
            </h2>
            <?php $row++; ?>
        </center>
    </div>

    <br/>

    <div id="container">
        <table cellspacing="0" cellpadding="0" border="1" class="border">

            <?php $begin = 0;?>
            <tr class="bggrey">
                <!-- STT -->
                <th rowspan="2" class="center" style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        row-merge="1"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> STT </xls>
                </th>

                <!-- Loại thiết bị -->
                <th rowspan="2" class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        row-merge="1"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> Loại thiết bị </xls>
                </th>

                <!-- Đơn vị tính -->
                <th rowspan="2" class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        row-merge="1"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> Đơn vị tính </xls>
                </th>

                <!-- Số lượng -->
                <th rowspan="2" class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        row-merge="1"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> Số lượng </xls>
                </th>

                <!-- Số lần -->
                <th colspan="4" class="center">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        column-merge="<?php echo $excel_col[($begin + 3)] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> Số lần  </xls>
                </th>
                <?php $begin = $begin + 3;?>

                <!-- Giá trị thực hiện (đồng) -->
                <th colspan="3" class="center">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        column-merge="<?php echo $excel_col[($begin + 2)] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> Giá trị thực hiện (đồng)  </xls>
                </th>
                <?php $begin = $begin + 2;?>

                <!-- Ghi chú -->
                <th rowspan="2" class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        row-merge="1"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> Ghi chú </xls>
                </th>
            </tr>
            <?php $row++;?>

            <?php $begin = 4;?>
            <tr class="bggrey">

                <!-- Số lần: Bảo dưỡng 1 (B1)-->
                <th class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> Bảo dưỡng 1 (B1) </xls>
                </th>

                <!-- Số lần: Bảo dưỡng 2 (B2)-->
                <th class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> Bảo dưỡng 2 (B2) </xls>
                </th>

                <!-- Số lần: Tiểu tu (Tt)-->
                <th class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> Tiểu tu (Tt) </xls>
                </th>

                <!-- Số lần: Tổng số lượt sc-bd -->
                <th class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> Tổng số lượt sc-bd </xls>
                </th>

                <!-- Giá trị thực hiện (đồng): Vật tự phụ tùng -->
                <th class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> Vật tự phụ tùng </xls>
                </th>

                <!-- Giá trị thực hiện (đồng): Nhân công -->
                <th class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> Nhân công </xls>
                </th>

                <!-- Giá trị thực hiện (đồng): Tổng giá trị t/h -->
                <th class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> Tổng giá trị t/h </xls>
                </th>
            </tr>
            <?php $row++;?>

            <!-- DÒNG TỔNG -->
            <?php $begin = 0;?>
            <tr>
                <!-- STT -->
                <td class="center">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1">  </xls>
                </td>

                <!-- Tên thiết bị -->
                <td class="center bold">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        bold="1"> TỔNG </xls>
                </td>

                <!-- Đơn vị tính -->
                <td class="left">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="left"
                        border="1">  </xls>
                </td>

                <!-- Số lượng -->
                <td class="right">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1">  </xls>
                </td>

                <!---------------------------------------------->

                <!-- Số lần: Bảo dưỡng 1 (B1)-->
                <td class="right bold">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1"
                        bold="1"> <?php echo $this->total->SoLanBaoTriB1;?> </xls>
                </td>

                <!-- Số lần: Bảo dưỡng 2 (B2)-->
                <td class="right bold">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1"
                        bold="1">  <?php echo $this->total->SoLanBaoTriB2;?> </xls>
                </td>

                <!-- Số lần: Tiểu tu (Tt)-->
                <td class="right bold">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1"
                        bold="1">  <?php echo $this->total->SoLanBaoTriTT;?> </xls>
                </td>

                <!-- Số lần: Tổng số lượt sc-bd -->
                <td class="right bold">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1"
                        bold="1"> <?php echo $this->total->SoLuotBaoTri;?> </xls>
                </td>

                <!-- Giá trị thực hiện (đồng): Vật tự phụ tùng -->
                <td class="right bold">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1"
                        bold="1"> <?php echo Qss_Lib_Util::formatMoney($this->total->ChiPhiVatTu);?> </xls>
                </td>

                <!-- Giá trị thực hiện (đồng): Nhân công -->
                <td class="right bold">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1"
                        bold="1">  <?php echo Qss_Lib_Util::formatMoney($this->total->ChiPhiNhanCong);?> </xls>
                </td>

                <!-- Giá trị thực hiện (đồng): Tổng giá trị t/h -->
                <td class="right bold">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1"
                        bold="1">  <?php echo Qss_Lib_Util::formatMoney($this->total->ChiPhi);?></xls>
                </td>

                <!---------------------------------------------->

                <!-- Ghi chú -->
                <td class="left">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="left"
                        border="1">  </xls>
                </td>
            </tr>
            <?php $row++;?>

            <?php foreach($this->report as $item):?>
            <?php $begin = 0;?>
            <tr>
                <!-- STT -->
                <td class="center">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"> <?php echo ++$stt;?> </xls>
                </td>

                <!-- Tên thiết bị -->
                <td class="left">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="left"
                        border="1"> <?php echo $item->TenLoai;?> </xls>
                </td>

                <!-- Đơn vị tính -->
                <td class="center">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"> TBị </xls>
                </td>

                <!-- Số lượng -->
                <td class="right">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1"> <?php echo $item->CountEquip;?> </xls>
                </td>

                <!---------------------------------------------->

                <!-- Số lần: Bảo dưỡng 1 (B1)-->
                <td class="right">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1"> <?php echo $item->SoLanBaoTriB1;?> </xls>
                </td>

                <!-- Số lần: Bảo dưỡng 2 (B2)-->
                <td class="right">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1">  <?php echo $item->SoLanBaoTriB2;?>  </xls>
                </td>

                <!-- Số lần: Tiểu tu (Tt)-->
                <td class="right">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1">  <?php echo $item->SoLanBaoTriTT;?>  </xls>
                </td>

                <!-- Số lần: Tổng số lượt sc-bd -->
                <td class="right">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1"> <?php echo ($item->SoLanBaoTriB1 + $item->SoLanBaoTriB2 + $item->SoLanBaoTriTT);?> </xls>
                </td>

                <!-- Giá trị thực hiện (đồng): Vật tự phụ tùng -->
                <td class="right">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1"> <?php echo Qss_Lib_Util::formatMoney($item->ChiPhiVatTu);?> </xls>
                </td>

                <!-- Giá trị thực hiện (đồng): Nhân công -->
                <td class="right">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1">  <?php echo Qss_Lib_Util::formatMoney($item->ChiPhiNhanCong);?> </xls>
                </td>

                <!-- Giá trị thực hiện (đồng): Tổng giá trị t/h -->
                <td class="right">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1">  <?php echo Qss_Lib_Util::formatMoney($item->ChiPhi);?> </xls>
                </td>

                <!---------------------------------------------->

                <!-- Ghi chú -->
                <td class="left">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="left"
                        border="1">  </xls>
                </td>
            </tr>
            <?php $row++;?>
            <?php endforeach;?>
        </table>
    </div>

    <div class="clear"></div>
    <br/>
    <br/>

    <table cellspacing="0" cellpadding="0" border="0" >
        <tr>
            <?php $endLabel1 = (int)($totalColumn/3); ?>
            <?php $startLabel2 = $endLabel1 + 1; ?>
            <?php $endLabel2 = $startLabel2 + (int)($totalColumn/3) - 1; ?>
            <?php $startLabel3 = $endLabel2 + 1; ?>

            <td style="width: 33%; text-align: center; font-weight: bold;">
                <xls
                    row="<?php echo $row ?>"
                    column="<?php echo $excel_col[1]; ?>"
                    column-merge="<?php echo $excel_col[$endLabel1]; ?>"
                    wrap-text="1"
                    v-align="center"
                    h-align="center"> LẬP BIỂU </xls>
            </td>

            <td style="width: 33%; text-align: center; font-weight: bold;">
                <xls
                    row="<?php echo $row ?>"
                    column="<?php echo $excel_col[$startLabel2]; ?>"
                    column-merge="<?php echo $excel_col[$endLabel2]; ?>"
                    wrap-text="1"
                    v-align="center"
                    h-align="center"> QUẢN ĐỐC PX </xls>
            </td>

            <td style="width: 33%; text-align: center; font-weight: bold;">
                <xls
                    row="<?php echo $row ?>"
                    column="<?php echo $excel_col[$startLabel3]; ?>"
                    column-merge="<?php echo $excel_col[$totalColumn]; ?>"
                    wrap-text="1"
                    v-align="center"
                    h-align="center"> PHÒNG CĐ</xls>
            </td>
        </tr>
        <?php $row++;?>
    </table>
</div>