<?php
$width = array(1, 3, 4, 3, 5, 5, 2, 4, 4, 2, 3);
$width = Qss_Lib_Report::changeWidthToFitScreen3($width);
?>

    <script>
        $(document).ready(function(){
            $('.datepicker').each(function(){
                $(this).datepicker({ dateFormat: "dd-mm-yy" });
            });
        });
    </script>


    <div class="clear"></div>
    <div class="fr">
        <a href="#1" onclick="$('#nextBack').val(0); $('#nextStart').val('<?php echo $this->nextStart;?>'); m759_plans_button.show();" > << Quay lại </a> |
        <a href="#1" onclick="$('#nextBack').val(1); $('#nextStart').val('<?php echo $this->nextStart;?>'); m759_plans_button.show();" > Tiếp theo >> </a>
    </div>
    <div class="clear"></div>
    <br/>

    <table cellspacing="0" cellpadding="0" class="border_table grid" id="grid" border="0" style="margin-bottom: 10px;">
        <?php $begin = 0;?>
        <thead>
            <tr>
                <th class="center" style="width: <?php echo $width[$begin++];?>%"><input type="checkbox" onclick="common_check_all_table_line(this, '.cwpo_line_checkbok', '.cwpo_line_checkbok_val')"/></th>
                <th class="center" style="width: <?php echo $width[$begin++];?>%">Mã thiết bị</th>
                <th class="center" style="width: <?php echo $width[$begin++];?>%">Tên thiết bị</th>
                <th class="center" style="width: <?php echo $width[$begin++];?>%">Bộ phận</th>
                <th class="center" style="width: <?php echo $width[$begin++];?>%">Tên công việc</th>
                <th class="center" style="width: <?php echo $width[$begin++];?>%">Chu kỳ</th>
                <th class="center" style="width: <?php echo $width[$begin++];?>%">Ưu tiên</th>
                <th class="center" style="width: <?php echo $width[$begin++];?>%" title="Ngày bắt đầu dự kiến">Ngày bắt đầu <br/> dự kiến</th>
                <th class="center" style="width: <?php echo $width[$begin++];?>%" title="Ngày kết thúc dự kiến">Ngày kết thúc <br/> dự kiến</th>
                <th class="center" style="width: <?php echo $width[$begin++];?>%" title="">Bảo trì <br/> lần cuối</th>
                <th class="center" style="width: <?php echo $width[$begin++];?>%" title="">Kế hoạch <br/> tổng thể</th>
            </tr>
        </thead>


        <tbody>
        	<?php $i = 0?>
            <?php foreach($this->plans as $detail): // In danh muc chi tiet theo IFID ?>
                <?php $begin = 0;?>
                <?php $detail->SoNgay = $detail->SoNgay>1?$detail->SoNgay-1:0;?>
                <tr <?php echo ((int)$detail->GeneralPlanDetailIOID != 0)?' common_no_check="1" ':'';?>>
                    <td class="center">
                        <?php if((int)$detail->GeneralPlanDetailIOID == 0):?>
                            <input type="checkbox" class="cwpo_line_checkbok " onclick="common_check_table_line(this, '.cwpo_line_checkbok_val')">
                            <input type="hidden" class="table_line_disabled cwpo_line_checkbok_val" name="CheckBox[]"  value="0">
                        <?php endif;?>

                        <input class="table_line_disabled" type="hidden" value="<?php echo $detail->IFID_M724;?>" name="ifid[]" disabled>
                        <input class="table_line_disabled" type="hidden" value="<?php echo $detail->ChuKyIOID;?>" name="ref_chuky[]" disabled>
                        <input class="table_line_disabled" type="hidden" value="<?php echo $detail->IFID_M724;?>_<?php echo $detail->ChuKyIOID;?>_<?php echo $i;?>" name="key[]" disabled>
                    </td>
                    <td class="left"><?php echo $detail->MaThietBi;?></td>
                    <td class="left"><?php echo $detail->TenThietBi;?></td>
                    <td class="left"><?php echo $detail->BoPhan;?></td>
                    <td class="left"><?php echo $detail->MoTa;?></td>
                    <td class="left"><?php echo $detail->ChuKy;?></td>
                    <td class="left"><?php echo $detail->Ref_MucDoUuTien;?></td>
                    <td class="center">
                        <input type="text" class="datepicker table_line_disabled" name="start[]" value="<?php echo Qss_Lib_Date::mysqltodisplay($detail->Date);?>" disabled/>
                    </td>

                    <td class="center">
                        <input type="text" class="datepicker table_line_disabled" name="end[]" value="<?php echo date('d-m-Y', strtotime($detail->Date." + ".(int)$detail->SoNgay." days")); ?>" disabled/>
                    </td>
                    <td class="center"><?php echo Qss_Lib_Date::mysqltodisplay($detail->NgayBatDau);?></td>
                    <td class="left"><?php echo $detail->GeneralPlanNo;?></td>
                </tr>
				<?php $i++?>               
            <?php endforeach;?>
        </tbody>

    </table>

<br/>

<?php if(count($this->plans)):?>
    <div class="right">
        <button class="btn btn_main_top" id="M838_Save_Button" type="button" onclick="m759_plans_button.save()"> Tạo phiếu bảo trì </button>
    </div>
<?php else:?>
    <div class="right">
        <button class="btn btn_main_top btn-disabled" type="button" disabled> Tạo phiếu bảo trì </button>
    </div>
<?php endif;?>


<script>
    $(document).ready(function() {
        var height = $(window).height() - 230 - $('#grid thead').height();//-8
        $('#grid').tableScroll({height:height,width:'100%'});
    });
</script>

