<script>    
function printPreview(){
    var url  = sz_BaseUrl + '/static/m772/show';
    var data = $('#report').serialize();
    var msg  = '';

    msg += common_checkEmpty($('#start_date').val(), '<?php echo $this->_translate(2)?>');
    msg += common_checkEmpty($('#end_date').val(), '<?php echo $this->_translate(3)?>');
    msg += common_compareStartAndEnd($('#start_date').val(), $('#end_date').val());

    if(msg)
    {
        qssAjax.alert(msg);
        return;
    }
    else
    {
        qssAjax.getHtml(url, data, function(jreturn) {
            $('#print-area').html(jreturn);
            removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
        });        
    }
}

</script>


<div class="clear"></div>
<div id="view">
	<div class="line-hr">
		<span><?php echo Qss_Lib_System::getReportTitle('M772');?> </span>
	</div>
	<form id="report" method="get" action="/static/m772/show">
		<table class="detail">

			<!-- Ngày bắt đầu -->
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(2)?>
				</th>

				<td><?php echo $this->views->Report->Datepicker('start_date', date('d-m-Y'));?><span
					class="red bold">(*)</span>
				</td>
			</tr>

			<!-- Ngày kết thúc -->
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(3)?>
				</th>

				<td><?php echo $this->views->Report->Datepicker('end_date', date('d-m-Y'));?><span
					class="red bold">(*)</span>
				</td>
			</tr>


			<!-- Khu vực -->
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(20)?>
				</th>
				<td><?php
				$id            = 'location_ioid';
				$getFields     = array('num'=>3,
                                       'objects'=>array('OKhuVuc'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'MaKhuVuc'
                                                            ,'display2'=>'Ten') ));
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
				</td>
			</tr>

			<!-- Nhóm thiết bị -->
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(22)?>
				</th>
				<td><?php
				$id            = 'eq_group_ioid';
				$getFields     = array('num'=>3,
                                       'objects'=>array('ONhomThietBi'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'LoaiThietBi'
                                                            ) ));
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
				</td>
			</tr>


			<!-- Loại thiết bị -->
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(21)?>
				</th>
				<td><?php
				$id            = 'eq_type_ioid';
				$getFields     = array('num'=>2,
                                       'objects'=>array('OLoaiThietBi'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'TenLoai'
                                                            )) );
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
			
			</tr>

			<!-- Thiết bị -->
			<tr>
				<th class="report-param-label"><?php echo $this->_translate(4)?></th>
				<td><?php
				$id            = 'equip_ioid';
				$getDataObject = array('ODanhSachThietBi'=>array('MaThietBi', 'TenThietBi', 'LoaiThietBi'));
				//,'OKhuVuc'=>array('MaKhuVuc','Ten')
				$getFields     = array('num'=>2,
								   'objects'=>array('ODanhSachThietBi'=>array(
															'id'=>'IOID'
															,'display1'=>'MaThietBi'
															,'display2'=>'TenThietBi')) );
															?> <?php
															echo $this->views->Report->ListBox(
															$id
															, $getDataObject
															, $getFields  );
															?>
				</td>
			</tr>

			<!-- Sản phẩm -->
			<tr>
				<th class="report-param-label"><?php echo $this->_translate(6)?></th>
				<td><?php
				$id            = 'item_ioid';
				$getDataObject = array('OSanPham'=>array('MaSanPham', 'TenSanPham'));
				$getFields     = array('num'=>2,
								   'objects'=>array('OSanPham'=>array(
															'id'=>'IOID'
															,'display1'=>'MaSanPham'
															,'display2'=>'TenSanPham')) );
															?> <?php
															echo $this->views->Report->ListBox(
															$id
															, $getDataObject
															, $getFields  );
															?>
				</td>
			</tr>

		</table>
	</form>
	<hr />
	<?php echo $this->views->Report->PrintToolbar();?>
	<div id="print-content">
		<div id="print-area"></div>
	</div>
</div>
