<script>
    var m873_button_getbyrequest = {
        // Hiển thị bản ghi theo yêu cầu cung cấp
        show : function () {
            var data = $('#M873_Get_By_Request_Form').serialize();
            var url = sz_BaseUrl + '/button/m873/getmoved/show';
            qssAjax.getHtml(url, data, function(jreturn) {
                $('#M873_Get_By_Request_ShowTable').html(jreturn);
            });
        },

        // Lưu lại những bản ghi được chọn
        save : function () {
            var data = $('#M873_Get_By_Request_Form').serialize();
            var url  = sz_BaseUrl + '/button/m873/getmoved/save';
            qssAjax.call(url, data, function(jreturn){
                $('#qss_trace').dialog('close');
                rowObjectSearch('<?php echo $this->ifid;?>','<?php echo $this->deptid;?>','OThietBiDieuDongVe');
            }, function(jreturn){
                qssAjax.alert(jreturn.message);
            });
        }
    };

    $(document).ready(function () {
        m873_button_getbyrequest.show();
    });
</script>

<form id="M873_Get_By_Request_Form">
    <input type="hidden" name="M873_Get_By_Request_IFID" id="M873_Get_By_Request_IFID" value="<?php echo $this->ifid;?>"/>

    <div class="popup_wrap">
        <div class="popup_header">


            <table class="detail" border="0" cellpadding="0" cellspacing="0">
                <tr>
                    <td class="left">
                        <div class="overflow">
                            <div class="fl">
                                <input type="text" id="M873_Get_By_Request_Equip" name="M873_Get_By_Request_Equip" value="" placeholder="Tìm mã & tên thiết bị"/>
                                <button type="button" class="btn" onclick="m873_button_getbyrequest.show()"> Xem </button>
                            </div>

                            <div class="fr">
                                Trang:
                                <a title="Trang trước" class="bold" href="#"
                                   onclick="$('#M873_Get_By_Request_PageNo').val('1'); m873_button_getbyrequest.show();"
                                   id="M873_Get_By_Request_Prev">&lt;&lt;</a>
                                <input id="M873_Get_By_Request_PageNo" name="M873_Get_By_Request_PageNo"
                                       onchange="M873_Get_By_Request.show();"
                                       style="width: 20px !important; text-align: center;" value="1">/
                                <span id="M873_Get_By_Request_TotalPage">1</span>
                                <a title="Trang sau" class="bold" href="#"
                                   onclick="$('#M873_Get_By_Request_PageNo').val('1'); m873_button_getbyrequest.show();"
                                   id="M873_Get_By_Request_Next">&gt;&gt;</a>
                                Hiển thị: <select id="M873_Get_By_Request_Display"
                                                  name="M873_Get_By_Request_Display" style="width: 100;"
                                                  onchange="m873_button_getbyrequest.show();;">
                                    <option value="5">5</option>
                                    <option value="10">10</option>
                                    <option selected="" value="20">20</option>
                                    <option value="50">50</option>
                                    <option value="100">100</option>
                                </select>
                                Tổng số: <span id="M873_Get_By_Request_Total">1</span>
                            </div>
                        </div>
                    </td>
                </tr>
            </table>

        </div>

        <div class="popup_content">
            <div id="M873_Get_By_Request_ShowTable">

            </div>

            <div class="overflow" style="padding-top: 10px;">
                <div class="fr">
                    <button type="button" class="btn" onclick="m873_button_getbyrequest.save()"> Cập nhật </button>
                </div>
            </div>
        </div>
    </div>
</form>