<?php
$widthTable = array(1,3,3,3,3,1);
$widthTable = Qss_Lib_Report::changeWidthToFitScreen3($widthTable);
?>

<script src="/js/common.js"></script>
<script src="/js/jquery.tablescroll.js"></script>

<table id="grid1" class="border_table" cellspacing="0" cellpadding="0" border="0">
    <thead>
    <?php $begin = 0;?>
    <tr class="bggrey">
        <th style="width: <?php echo $widthTable[$begin++];?>%"><input type="checkbox" onclick="common_check_all_table_line(this, '.cwpo_line_checkbok', '.cwpo_line_checkbok_val')"/> </th>
        <th style="width: <?php echo $widthTable[$begin++];?>%">Mã thiết bị</th>
        <th style="width: <?php echo $widthTable[$begin++];?>%">Tên thiết bị</th>
        <th style="width: <?php echo $widthTable[$begin++];?>%">Loại thiết bị</th>
        <th style="width: <?php echo $widthTable[$begin++];?>%">Đặt chỗ</th>
        <th style="width: <?php echo $widthTable[$begin++];?>%">Trên phiếu</th>
    </tr>
    </thead>

    <tbody>
    <?php foreach($this->OYeuCauThietBi as $item):?>
        <tr>
            <td class="center">
                <input type="checkbox" class="cwpo_line_checkbok " onclick="common_check_table_line(this, '.cwpo_line_checkbok_val')">
                <input type="hidden" class="table_line_disabled cwpo_line_checkbok_val" name=""  value="0">
                <input type="hidden" class="table_line_disabled" disabled name="M873_Get_By_Request_IOID[]" value="<?php echo @$item->IOID;?>"/>
            </td>
            <td class="left break"><?php echo @$item->MaThietBi;?></td>
            <td class="left"><?php echo @$item->TenThietBi;?></td>
            <td class="left"><?php echo @$item->LoaiThietBi;?></td>
            <td class="left"><?php echo @$item->SoPhieuDatCho;?></td>
            <td class="center <?php echo @$item->SoPhieuHienTai?'col-checked':'col-unchecked';?>">&nbsp;</td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>

<script>
    $(document).ready(function() {
        // SET LẠI CHIỀU CAO BẢNG
        $('#grid1').tableScroll({height:240,width:'100%'});

        /// SET LẠI TRANG
        $('#M873_Get_By_Request_Prev').attr('onclick', "$('#M873_Get_By_Request_PageNo').val('<?php echo @(int)$this->prev;?>'); m873_button_getbyrequest.show();");
        $('#M873_Get_By_Request_Next').attr('onclick', "$('#M873_Get_By_Request_PageNo').val('<?php echo @(int)$this->next;?>'); m873_button_getbyrequest.show();");
        $('#M873_Get_By_Request_PageNo').val('<?php echo $this->page;?>');
        $('#M873_Get_By_Request_TotalPage').text('<?php echo $this->totalPage;?>');
        $('#M873_Get_By_Request_Total').text('<?php echo $this->total;?>');
        $('#M873_Get_By_Request_Display').val('<?php echo $this->display;?>')
    });
</script>