<?php
$width = array(1, 3, 4, 3, 4, 5, 2, 4, 4, 2);
$width = Qss_Lib_Report::changeWidthToFitScreen3($width);
?>
<?php if($this->plans):?>
    <script>
        $(document).ready(function(){
            $('.datepicker').each(function(){
                $(this).datepicker({ dateFormat: "dd-mm-yy" });
            });
        });
    </script>

    <table cellspacing="0" cellpadding="0" class="border_table" border="0" style="margin-bottom: 10px;">
        <?php $begin = 0;?>
        <tr>
            <th class="center" style="width: <?php echo $width[$begin++];?>%"><input type="checkbox" onclick="common_check_all_table_line(this, '.cwpo_line_checkbok', '.cwpo_line_checkbok_val')"/></th>
            <th class="center" style="width: <?php echo $width[$begin++];?>%">Mã thiết bị</th>
            <th class="center" style="width: <?php echo $width[$begin++];?>%">Tên thiết bị</th>
            <th class="center" style="width: <?php echo $width[$begin++];?>%">Bộ phận</th>
            <th class="center" style="width: <?php echo $width[$begin++];?>%">Loại <br/> bảo trì</th>
            <th class="center" style="width: <?php echo $width[$begin++];?>%">Chu kỳ</th>
            <th class="center" style="width: <?php echo $width[$begin++];?>%">Ưu tiên</th>
            <th class="center" style="width: <?php echo $width[$begin++];?>%" title="Ngày bắt đầu dự kiến">Ngày bắt đầu <br/> dự kiến</th>
            <th class="center" style="width: <?php echo $width[$begin++];?>%" title="Ngày kết thúc dự kiến">Ngày kết thúc <br/> dự kiến</th>
            <th class="center" style="width: <?php echo $width[$begin++];?>%" title="">Bảo trì <br/> lần cuối</th>
        </tr>


        <?php foreach($this->plans as $detail): // In danh muc chi tiet theo IFID ?>
            <?php $begin = 0;?>
            <tr>
                <td class="center">

                    <input type="checkbox" class="cwpo_line_checkbok " onclick="common_check_table_line(this, '.cwpo_line_checkbok_val')">
                    <input type="hidden" class="table_line_disabled cwpo_line_checkbok_val" name="CheckBox[]"  value="0">
                    <input class="table_line_disabled" type="hidden" value="<?php echo $detail->IFID_M724;?>" name="ifid[]" disabled>
                    <input class="table_line_disabled" type="hidden" value="<?php echo $detail->ChuKyIOID;?>" name="ref_chuky[]" disabled>
                    <input class="table_line_disabled" type="hidden" value="<?php echo $detail->IFID_M724;?>_<?php echo $detail->ChuKyIOID;?>" name="key[]" disabled>
                </td>
                <td class="left"><?php echo $detail->MaThietBi;?></td>
                <td class="left"><?php echo $detail->TenThietBi;?></td>
                <td class="left"><?php echo $detail->BoPhan;?></td>
                <td class="left"><?php echo $detail->LoaiBaoTri;?></td>
                <td class="left"><?php echo $detail->ChuKy;?></td>
                <td class="left"><?php echo $detail->MucDoUuTien;?></td>
                <td class="center">
                    <input type="text" class="datepicker table_line_disabled" name="start[]" value="<?php echo date('d-m-Y');?>" disabled/>
                </td>

                <td class="center">
                    <input type="text" class="datepicker table_line_disabled" name="end[]" value="<?php echo date('d-m-Y', strtotime(date('d-m-Y')." + ".(int)$detail->SoNgay." days")); ?>" disabled/>
                </td>
                <td class="center"><?php echo Qss_Lib_Date::mysqltodisplay($detail->NgayBatDau);?></td>
            </tr>
        <?php endforeach;?>
    </table>

    <div class="right">
        <button class="btn btn_main_top" type="button" onclick="calendar_index_file.create_order_from_plans()"> Tạo phiếu bảo trì </button>
    </div>
<?php endif; // Kiem tra co detail de in detail?>