<script>
function printPreview(){

	var start = $('#start').val();
	var end   = $('#end').val();
	var msg   = '';

	msg += common_checkEmpty(start, '<?php echo $this->_translate(5)?>');
    msg += common_checkEmpty(end, '<?php echo $this->_translate(6)?>');
    msg += common_compareStartAndEnd(start, end, '<?php echo $this->_translate(5)?>', '<?php echo $this->_translate(6)?>');

	if(msg != '') {
		qssAjax.alert(msg);
		return;
	}
	else {
	    var url  = sz_BaseUrl + '/static/m859/show';
		var data = $('#report').serialize();
		qssAjax.getHtml(url, data, function(jreturn) {
			$('#print-area').html(jreturn);
            removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
		});
	}
}
</script>

<div class="clear"></div>
<div id="view">
	<div class="line-hr">
		<span><?php echo Qss_Lib_System::getReportTitle('M859');?> </span>
	</div>
	<form id="report" method="post" action="/static/m859/show">
		<table class="detail">
		    <?php $tomorrow = date('d-m-Y', strtotime('tomorrow'))?>
			<tr>
				<th width="20%" class="report-param-label">
					<!-- Ngày bắt đầu --> <?php echo $this->_translate(5)?></th>
				<td><?php echo $this->views->Report->Datepicker('start', $tomorrow);?><span
					class="bold red">(*)</span></td>
			</tr>

			<tr>
				<th width="20%" class="report-param-label">
					<!-- Ngày ket thuc --> <?php echo $this->_translate(6)?></th>
				<td><?php echo $this->views->Report->Datepicker('end', date('t-m-Y', strtotime($tomorrow. ' + 1 month')));?><span
					class="bold red">(*)</span></td>
			</tr>

			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(20)?>
				</th>
				<td><?php
				$id            = 'location';
				$getFields     = array('num'=>3,
                                       'objects'=>array('OKhuVuc'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'MaKhuVuc'
                                                            ,'display2'=>'Ten') ));
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
				</td>
			</tr>

			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(22)?>
				</th>
				<td><?php
				$id            = 'group';
				$getFields     = array('num'=>3,
                                       'objects'=>array('ONhomThietBi'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'LoaiThietBi'
                                                            ) ));
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
				</td>
			</tr>

			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(21)?>
				</th>
				<td><?php
				$id            = 'type';
				$getFields     = array('num'=>2,
                                       'objects'=>array('OLoaiThietBi'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'TenLoai'
                                                            )) );
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
			
			</tr>
		</table>
	</form>
	<p>
	
	
	<hr>
	<?php echo $this->views->Report->PrintToolbar();?>
	<div id="print-content">
		<div id="print-area"></div>
	</div>
</div>
