<?php $excel_col = array_flip(Qss_Lib_Const::$EXCEL_COLUMN);?>
<?php
// $widthArr   = array(1, 4, 5, 3, 2.5, 2.5, 2.5, 2.5, 2.5, 2, 2, 2, 2, 2, 3, 4);
$htmlWidth  = array(40, 160, 200, 120, 100, 100, 100, 100, 100, 80, 80, 80, 80, 80, 80, 120, 160);
$totalCol   = count($htmlWidth);
$excelWidth = Qss_Lib_Report::convertPxColumnWidthToExcelWidth($htmlWidth);
$row        = 1;
$bg         = "#EEEEEE"; // Mau nen cua cot tieu de
?>

<form id="excel" method="post" action="/report/index/excel" target="new">
    <input type="hidden" id="content" name="content" value="">
</form>

<div class="portrait" style="font-size: 13px !important;">
    <excel orientation="portrait" font-name="Times New Roman" font-size="12"
           margin-left="0.5" margin-right="0.5" margin-top="0.75"
           margin-bottom="0.75" />

    <div id="head_print">
        <?php  echo $this->views->Common->Portrait(); ?>

        <h1 style="text-align: center;">
            <xls row="<?php echo $row?>" column="A" column-merge="G" font-size="28" h-align="center" v-align="center" bold="1">
                Theo dõi sử dụng vật tư (<?php echo $this->start;?> - <?php echo $this->end;?>)
            </xls>
        </h1>
        <?php $row++;?>
    </div>

    <div id="container">
        <table cellspacing="0" cellpadding="0" border="0" class="border" style="table-layout: fixed !important;">
            <?php $beginHtml = 0;?>
            <tr class="bggrey">
                <th class="center" style="width: <?php echo $htmlWidth[$beginHtml];?>px !important;"> <div class="center" style="<?php echo $htmlWidth[$beginHtml++];?>px !important;<?php echo $htmlWidth[$beginHtml++];?>px !important;;">STT</div></th>
                <th class="center" style="width: <?php echo $htmlWidth[$beginHtml];?>px !important;"> <div class="center" style="<?php echo $htmlWidth[$beginHtml++];?>px !important;;">Mã vật tư</div></th>
                <th class="center" style="width: <?php echo $htmlWidth[$beginHtml];?>px !important;"> <div class="center" style="<?php echo $htmlWidth[$beginHtml++];?>px !important;;">Tên vật tư</div></th>
                <th class="center" style="width: <?php echo $htmlWidth[$beginHtml];?>px !important;"> <div class="center" style="<?php echo $htmlWidth[$beginHtml++];?>px !important;;">Đơn vị tính</div></th>
                <th class="center" style="width: <?php echo $htmlWidth[$beginHtml];?>px !important;"> <div class="center" style="<?php echo $htmlWidth[$beginHtml++];?>px !important;;">Số lượng kế hoạch tổng thể</div></th>
                <th class="center" style="width: <?php echo $htmlWidth[$beginHtml];?>px !important;"> <div class="center" style="<?php echo $htmlWidth[$beginHtml++];?>px !important;;">Số lượng thực tế</div></th>
                <th class="center" style="width: <?php echo $htmlWidth[$beginHtml];?>px !important;"> <div class="center" style="<?php echo $htmlWidth[$beginHtml++];?>px !important;;">Chênh lệch</div></th>
            </tr>

            <?php $stt = 0;?>
            <?php foreach($this->report as $item):?>
                <?php $beginHtml = 0;?>
                <?php
                $soLuongDinhKy  = @$item['SoLuongDinhKy']?$item['SoLuongDinhKy']:0;
                $soLuongTongThe = @$item['SoLuongTongThe']?$item['SoLuongTongThe']:0;
                $soLuongBaoTri  = @$item['SoLuongBaoTri']?$item['SoLuongBaoTri']:0;
                $chenhDinhKy    = $soLuongBaoTri - $soLuongDinhKy;
                $chenhTongThe   = $soLuongBaoTri - $soLuongTongThe;
                ?>
                <tr>
                    <!-- STT -->
                    <td class="center">
                        <div >
                            <?php echo ++$stt;?>
                        </div>
                    </td>

                    <!-- HẠNG MỤC TỒN TẠI VÀ CÁC SỰ CỐ - Tên thiết bị -->
                    <td class="left">
                        <div >
                            <?php echo @$item['MaVatTu'];?>
                        </div>
                    </td>

                    <!-- TÌNH TRẠNG TỒN TẠI VÀ CÁC SỰ CỐ -->
                    <td class="left">
                        <div >
                            <?php echo @$item['TenVatTu'];?>
                        </div>
                    </td>

                    <!-- HỆ THỐNG -->
                    <td class="left">
                        <div >
                            <?php echo @$item['DonViTinh'];?>
                        </div>
                    </td>

                    <!-- NGƯỜI PHÁT HIỆN -->
                    <td class="right">
                        <div >
                            <?php echo Qss_Lib_Util::formatNumber($soLuongTongThe);?>
                        </div>
                    </td>

                    <!-- NHÓM N.NHÂN -->
                    <td class="right">
                        <div >
                            <?php echo Qss_Lib_Util::formatNumber($soLuongBaoTri);?>
                        </div>
                    </td>

                    <!-- NHÓM GIẢI PHÁP -->
                    <td class="right">
                        <div >
                            <?php echo Qss_Lib_Util::formatNumber($chenhTongThe);?>]
                        </div>
                    </td>
                </tr>
            <?php endforeach;?>
        </table>
    </div>
</div>