<div id="portrait-company-header">
    <div style="width:100%">
        <p class="right">
            <?php if(isset($this->ini['bieumau'])):?>
                <?php echo $this->ini['bieumau'];?>
            <?php endif;?>

            <?php if(isset($this->ini['ngaybanhanh'])):?>
                <?php echo $this->ini['ngaybanhanh'];?>
            <?php endif;?>
        </p>
    </div>
    <br/>
</div>
<div class="clear">&nbsp;</div>

<?php /*
<xmg path="/data_viwasupco/images/landscape2.png" coordinates="A1" x="0" y="0" width="1000" height="82"/>
<!-- xmg width = 1200 -->
<img src="/data_viwasupco/images/landscape2.png" width="1181px" height="88px">
<xls row="1" column="A" height="82"></xls>
 */?>

 <xmg path="/data_viwasupco/images/landscape.png" coordinates="A1" x="0" y="0" width="1000" height="50"/>
<!-- xmg width = 1200 -->
<img src="/data_viwasupco/images/landscape.png" width="1160px" height="50px">
<xls row="1" column="A" height="55"></xls>

