<style>
    .clicked
    {
        background: yellow;
    }
    #m401_material_dial_box
    {
        overflow:hidden;
    }
    #select_m401_material_box
    {
        float:left;
        width:95%;
    }
    #select_m401_material_box .select
    {
        width:98%;
        overflow: auto;
    }
    #m401_material_button_box
    {
        width:10%;
        float:left;
    }

    #m401_material_box
    {
        width: 98%;
    }
</style>

<script type="text/javascript" src="/js/common.js"></script>

<script>
    var m401_material_button = {
        show : function()
        {
            var url  = sz_BaseUrl + '/button/m401/material/show';
            var data = $('#m401_material_form').serialize();

            qssAjax.getHtml(url, data, function(jreturn) {
                $('#m401_material_show').html(jreturn);
            });
        },

        select : function()
        {
            var url  = sz_BaseUrl + '/button/m401/material/select';
            var data = $('#m401_material_form').serialize();

            qssAjax.getHtml(url, data, function(jreturn) {
                $('#m401_material_select').html(jreturn);
            });
        },

        save : function()
        {
            var url  = sz_BaseUrl + '/button/m401/material/save';
            var data = $('#m401_material_form').serialize();

            qssAjax.confirm('Bạn có thực sự muốn lưu lại?',function(){
                qssAjax.call(url, data, function(jreturn) {
                    if(jreturn.message != '')
                    {
                        qssAjax.notice(jreturn.message);
                    }

                }, function(jreturn) {
                    qssAjax.alert(jreturn.message);
                });
            });
        },

        search : function()
        {
            // Gia tri tim kiem
            var xval = $('#m401_material_filter_dialbox').val();
            var text = '';
            var re;

            // Xoa nhung option trắng
            $('.m401_material_empty_option').each(function () {
                $(this).remove();
            });

            // An hien option theo gia tri tim kiem
            if(xval == '')
            {
                $('#select_m401_material_box select option').each(function(){
                    $(this).show();
                });
            }
            else
            {
                $('#select_m401_material_box select option').each(function(){
                    text = $(this).text();
                    re   = new RegExp(xval, "i");

                    if(text.search(re) !== -1){
                        $(this).show();
                    }
                    else
                    {
                        $(this).hide();
                    }
                });
            }

            // Them the trang vao trong truong hop so luog the bi hide bang dung so luong the dang co
            if($('#select_m401_material_box select option:hidden').length == $('#select_m401_material_box select option').length)
            {
                $('#select_m401_material_box select').append('<option class=\"m401_material_empty_option\" value=\"0\" disabled>&nbsp;</option>');
            }
        },

        add : function(all){
            var add;
            var addHtml = '';
            var groupmarker = 0;

            if(all != undefined && all)
            {
                add = $('#select_m401_material_box select  option[value!="0"]').filter(":not(:hidden)");
            }
            else
            {
                add = $('#select_m401_material_box select option[value!="0"]').filter(":selected").filter(":not(:hidden)");
            }

            $('.m401_material_empty_option').each(function () {
                $(this).remove();
            });

            add.each(function(){
                groupmarker = $(this).attr('groupmarker');

                addHtml  = '';
                addHtml += '<tr class="selected_line" onclick="m401_material_button.selectItem(this)">';
                addHtml += '<td class="center"><input type="checkbox" class="remov_line"></td>';
                addHtml += '<td class="left">'+$(this).attr('itemcode');
                addHtml += '<input type="hidden" value="'+$(this).attr('itemioid')+'" class="RefItem" name="RefItem[]" >';
                addHtml += '<input type="hidden" value="'+$(this).attr('uomioid')+'" class="RefUOM" name="RefUOM[]" >';
                addHtml += '<input type="hidden" value="'+$(this).attr('itemcode')+'" class="itemcode" >';
                addHtml += '<input type="hidden" value="'+$(this).attr('itemname')+'" class="itemname" >';
                addHtml += '<input type="hidden" value="'+$(this).attr('uom')+'" class="uom" >';
                addHtml += '<input type="hidden" value="'+$(this).attr('qty')+'" class="qty" >';
                addHtml += '<input type="hidden" value="'+$(this).attr('groupmarker')+'" class="groupmarker" >';
                addHtml += '<input type="hidden" value="'+$(this).attr('request')+'" class="request" >';
                addHtml += '<input type="hidden" value="'+$(this).attr('requestioid')+'" name="RefRequest[]" class="requestioid" >';
                addHtml += '<input type="hidden" value="'+$(this).attr('ordered')+'" class="ordered" >';
                addHtml += '</td>';
                addHtml += '<td class="left">'+$(this).attr('itemname')+'</td>';
                addHtml += '<td class="left">'+$(this).attr('request')+'</td>';
                addHtml += '<td class="left">'+$(this).attr('uom')+'</td>';
                addHtml += '<td class="center"><input type="text" size="5" class="right qty" value="'+$(this).attr('qty')+'" name="Qty[]" /></td>';
                addHtml += '</tr>';
                $('#m401_material_box').append(addHtml);
                $(this).remove();

                if($('#select_m401_material_box select optgroup[groupmarker="'+groupmarker+'"] option').length == 0)
                {
                    $('#select_m401_material_box select optgroup[groupmarker="'+groupmarker+'"]').remove();
                }
            });

            if($('#select_m401_material_box select option:hidden').length == $('#select_m401_material_box select option').length)
            {
                $('#select_m401_material_box select').append('<option class=\"m401_material_empty_option\" value=\"0\" disabled>&nbsp;</option>');
            }
        },

        remove : function(all){
            var remove;
            var html   = '';

            if(all != undefined && all)
            {
                remove = $('.selected_line');
            }
            else
            {
                remove = $('.selected_line').filter(".marker");
            }

            $('.m401_material_empty_option').each(function () {
                $(this).remove();
            });

            remove.each(function(){
                html  = '<option ';
                html += 'groupmarker="'+$(this).find('.groupmarker').val()+'" ';
                html += 'itemioid="'+$(this).find('.RefItem').val()+'" ';
                html += 'itemcode="'+$(this).find('.itemcode').val()+'" ';
                html += 'itemname="'+$(this).find('.itemname').val()+'" ';
                html += 'uomioid="'+$(this).find('.RefUOM').val()+'" ';
                html += 'uom="'+$(this).find('.uom').val()+'" ';
                html += 'value="'+$(this).find('.RefItem').val()+'" ';
                html += 'qty="'+$(this).find('.qty').val()+'" ';
                html += 'request="'+$(this).find('.request').val()+'" ';
                html += 'requestioid="'+$(this).find('.requestioid').val()+'" ';
                html += 'ordered="'+$(this).find('.ordered').val()+'"> ';
                html += $(this).find('.itemcode').val() + ' - ' + $(this).find('.itemname').val() + '(' + $(this).find('.uom').val() + ')'
                html += '</option>';

                if($(this).find('.groupmarker').val())
                {
                    if($('#select_m401_material_box select optgroup[groupmarker="'+$(this).find('.groupmarker').val()+'"]').length)
                    {
                        $('#select_m401_material_box select optgroup[groupmarker="'+$(this).find('.groupmarker').val()+'"]').prepend(html);
                    }
                    else
                    {
                        var extHtml = '<optgroup label="'+$(this).find('.request').val()+'" groupmarker="'+$(this).find('.groupmarker').val()+'">';
                        extHtml+= html;
                        extHtml+= '</optgroup>'

                        $('#select_m401_material_box select').prepend(extHtml);
                    }

                }
                else
                {
                    $('#select_m401_material_box select ').prepend(html);
                }

                $(this).remove();
            });

            if($('#m401_material_box select option').length == 0)
            {
                $('#m401_material_box select').append('<option class=\"m401_material_empty_option\" value=\"0\" disabled>&nbsp;</option>');
            }
        },

        checkItem : function(ele)
        {
            if($(ele).is(':checked'))
            {
                $(ele).parent().parent().addClass('marker');
                $(ele).attr('checked', true);
            }
            else
            {
                $(ele).parent().parent().removeClass('marker');
                $(ele).removeAttr('checked');
            }
        },

        checkAllItems : function(ele)
        {
            if($(ele).is(':checked'))
            {
                $('.remov_line').each(function(){
                    $(this).attr('checked', true);
                    $(this).parent().parent().addClass('marker');
                });
            }
            else
            {
                $('.remov_line').each(function(){
                    $(this).removeAttr('checked', true);
                    $(this).parent().parent().removeClass('marker');
                });
            }
        }
    };

    $(document).ready(function(){
        m401_material_button.show();
        m401_material_button.select();

        $('input[type="radio"][name="m401_material_filter"]').change(function(){
            m401_material_button.select();
        });
    });
</script>

<div id="wrapper">
    <form id="m401_material_form">
        <input type="hidden" name="ifid" value="<?php echo $this->ifid;?>">

        <p>
            <input type="radio" id="Checkbox_PhieuBaoTri_DonHang" name="m401_material_filter" value="1" checked />
            <label for="Checkbox_PhieuBaoTri_DonHang"> Yêu cầu mua sắm</label>

            <input type="radio" id="Checkbox_MatHang" name="m401_material_filter" value="2" />
            <label for="Checkbox_MatHang"> Mặt hàng </label>
        </p>

        <br/>

        <div id="">
            <div style="width: 37%;" class="fl" id="m401_material_select">

            </div>

            <div id="m401_material_button_box" class="fl">

                <div id="m401_material_add_button">
                    <button onclick="m401_material_button.add()"
                            class="btn-custom"
                            type="button"> &gt;&gt; </button>
                </div>

                <div id="">
                    <button onclick="m401_material_button.remove()"
                            class="btn-custom"
                            type="button"> &lt;&lt; </button>
                </div>

                <div id="">
                    <button onclick="m401_material_button.add(1)"
                            class="btn-custom"
                            type="button"> &gt;&gt;&gt;&gt; </button>
                </div>

                <div id="m401_material_remove_button">
                    <button onclick="m401_material_button.remove(1)"
                            class="btn-custom"
                            type="button"> &lt;&lt;&lt;&lt; </button>
                </div>
            </div>


            <div style="width: 53%;" class="fl" id="m401_material_show">

            </div>
        </div>
    </form>

    <br/>
    <div class="clear"></div>
    <br/>

    <div class="fr">
        <button type="button" class="btn btn-custom" onclick="m401_material_button.save()"> Cập nhật </button>
    </div>
</div>