<?php
$widths = array();
foreach ($this->fields as $field)
{
    if($field->bGrid && $field->intFieldType != 17)
    {
        $widths[] = $field->intFieldWidth;
    }
}

$widths = Qss_Lib_Report::changeWidthToFitScreen3($widths);
$begin  = 0;
?>

<?php /*
<link rel="stylesheet" href="/css/general.css" />
<script src="/js/jquery.min.1.8.2.js" type="text/javascript"></script>
<script src="/js/jquery.cookie.js" type="text/javascript"></script>
<script src="/js/ui/jquery-ui-1.8.1.custom.js" type="text/javascript"></script>
<script src="/js/core-ajax.js" type="text/javascript"></script>
<script src="/js/index.js" type="text/javascript"></script>
<script src="/js/jquery.tablescroll.js" type="text/javascript"></script>
<script src="/js/jquery.mask.number.js" type="text/javascript"></script>
<script src="/js/tag.js" type="text/javascript"></script>
<script src="/js/ajaxfileupload.js" type="text/javascript"></script>
<script src="/js/tabs.js" type="text/javascript"></script>
<script src="/js/form-list.js" type="text/javascript"></script>
<script src="/js/popup-select.js" type="text/javascript"></script>
 */?>

<div id="qs-drilldown">
    <script>
        var drilldown = {
            reload : function () {
                var sz_BaseUrl = 'http://' + location.host;
                var url = sz_BaseUrl + '/report/drilldown/index';
                var data = $('#drilldown-form').serialize();
                qssAjax.getHtml(url, data, function(jreturn) {
                    $('#qs-drilldown').html(jreturn);
                });
            }
        };
    </script>

    <form id="drilldown-form">
        <div class="clear fr">
            Trang:
            <a title="Trang trước" class="bold" href="#" onclick="$('#qss_form_pageno').val('<?php echo $this->prev;?>');drilldown.reload();">&lt;&lt;</a>
            <input id="qss_form_pageno" name="page" onchange="drilldown.reload();" style="width: 20px !important; text-align: center;" value="<?php echo $this->page;?>">/<?php echo $this->countPage;?>
            <a title="Trang sau" class="bold" href="#" onclick="$('#qss_form_pageno').val('<?php echo $this->next;?>');drilldown.reload();">&gt;&gt;</a>
            Hiển thị: <select id="qss_form_perpage" name="display" style="width: 100px;" onchange="drilldown.reload();">
                <option <?php echo ($this->display == 10)?'selected':'';?>>10</option>
                <option <?php echo ($this->display == 20)?'selected':'';?>>20</option>
                <option <?php echo ($this->display == 50)?'selected':'';?>>50</option>
                <option <?php echo ($this->display == 100)?'selected':'';?>>100</option>
            </select>


            <input type="hidden" name="fid" value="<?php echo $this->fid;?>" />
            <input type="hidden" name="ifid" value="<?php echo $this->ifid;?>" />
            <input type="hidden" name="objid" value="<?php echo $this->objid;?>" />

            <?php if(is_array($this->status) && count($this->status)):?>
                <?php foreach ($this->status as $status):?>
                    <input type="hidden" name="status[]" value="<?php echo $status;?>" />
                <?php endforeach;?>
            <?php endif;?>

            <?php foreach ($this->params as $key=>$val):?>
                <?php if(!in_array($key, array('fid', 'ifid', 'objid', 'status', 'page', 'display'))):?>
                    <input type="hidden" name="<?php echo $key;?>" value="<?php echo $val;?>" />
                <?php endif;?>
            <?php endforeach;?>
        </div>
    </form>

    <div class="">&nbsp;&nbsp; </div>
    <div class="clear">&nbsp;&nbsp; </div>
    <br/>

    <table class="border_table" cellpadding="0" cellspacing="0" border="0">
        <tr>
            <?php foreach ($this->fields as $field):?>
                <?php if(($field->bGrid & 1) && $field->intFieldType != 17):?>
                    <th style="width:<?php echo $widths[$begin++];?>%"><?php echo $field->szFieldName;?></th>
                <?php endif;?>
            <?php endforeach;?>
        </tr>

        <?php foreach($this->data as $item):?>
            <tr>
                <?php foreach ($this->fields as $field):?>
                    <?php if(($field->bGrid & 1) && $field->intFieldType != 17):?>
                        <?php $field->setValue($item->{$field->FieldCode});?>
                        <td class="<?php echo Qss_Lib_Const::$FIELD_ALIGN[$field->intFieldType];?>">

                            <?php if($field->intInputType != 5): ?>
                                <?php echo $field->getValue();?>
                            <?php else: ?>
                                <?php echo $field->sz_fGetDisplay();?>
                            <?php endif;?>
                        </td>
                    <?php endif;?>
                <?php endforeach;?>
            </tr>
        <?php endforeach;?>
    </table>
</div>
