<script>
function printPreview(){
	var ngaybd = $('#start').val();
	var ngaykt = $('#end').val();
	var ky     = $('#period').val();
	if(ngaybd == '' || ngaykt == '')	{
		qssAjax.alert('<?php echo $this->_translate(1)?>');
		return;
	}
	var firstValue = ngaybd.split('-');
	var secondValue = ngaykt.split('-');
	 var firstDate=new Date();
	 firstDate.setFullYear(firstValue[2],(firstValue[1] - 1 ),firstValue[0]);
	 var secondDate=new Date();
	 secondDate.setFullYear(secondValue[2],(secondValue[1] - 1 ),secondValue[0]);     

	 if (firstDate > secondDate)
	 {
		qssAjax.alert('<?php echo $this->_translate(2)?>');
		return;
	 }


	/*$('#report').submit(function() {
        window.open('', 'formpopup', 'statusbar=no,resizable=yes,scrollbars=yes, addressbar=no,maximize=yes');
        this.target = 'formpopup';
    });
	$('#report').submit();*/
	 var url = sz_BaseUrl + '/static/m734/show';
		var data = $('#report').serialize();
		qssAjax.getHtml(url, data, function(jreturn) {
			$('#print-area').html(jreturn);
                        removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
		});
}
</script>

<div class="clear"></div>
<div id="view">
	<div class="line-hr">
		<span><?php echo $this->_translate(3)?> </span>
	</div>
	<form id="report" method="get" action="/static/m734/show">
		<table class="detail">
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(4)?>
				</th>
				<td><?php echo $this->views->Report->Datepicker('start', '01-'.date('m').'-'.date('Y'));?><span
					class="bold red">(*)</span></td>
			</tr>
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(5)?>
				</th>
				<td><?php echo $this->views->Report->Datepicker('end', date('d-m-Y'));?><span
					class="bold red">(*)</span></td>
			</tr>

			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(20)?>
				</th>
				<td><?php
				$id            = 'location';
				$getFields     = array('num'=>3,
                                       'objects'=>array('OKhuVuc'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'MaKhuVuc'
                                                            ,'display2'=>'Ten') ));
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
				</td>
			</tr>


			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(22)?>
				</th>
				<td><?php
				$id            = 'group';
				$getFields     = array('num'=>3,
                                       'objects'=>array('ONhomThietBi'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'LoaiThietBi'
                                                            ) ));
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
				</td>
			</tr>



			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(21)?>
				</th>
				<td><?php
				$id            = 'type';
				$getFields     = array('num'=>2,
                                       'objects'=>array('OLoaiThietBi'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'TenLoai'
                                                            )) );
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
			
			</tr>
			
			
			<!-- Thiết bị -->
            <tr>
                <th width="20%" class="report-param-label">
                    Thiết bị
                </th>

                <td>
                    <?php
                    $getDataObject = array('ODanhSachThietBi' => array('MaThietBi', 'TenThietBi'));
                    //,'OKhuVuc'=>array('MaKhuVuc','Ten')
                    $getFields = array('num' => 2,
                        'objects' => array('ODanhSachThietBi' => array(
                            'id' => 'IOID'
                        , 'display1' => 'MaThietBi'
                        , 'display2' => 'TenThietBi')));
                    ?> <?php echo $this->views->Report->ListBox('equip', $getDataObject, $getFields); ?>
                </td>
            </tr>
			

			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(6)?>
				</th>
				<td><?php
				$id            = 'material';
				$getDataObject = array('OSanPham'=>array('MaSanPham', 'TenSanPham'));
				$getFields     = array('num'=>2,
                                       'objects'=>array('OSanPham'=>array(
                                                                'id'=>'IOID'
                                                                ,'display1'=>'MaSanPham'
                                                                ,'display2'=>'TenSanPham')) );
                                                                ?> <?php echo $this->views->Report->ListBox($id, $getDataObject,$getFields);?>

				</td>
			</tr>
			
			
		</table>
	</form>
	<p>
	
	
	<hr>
	<?php echo $this->views->Report->PrintToolbar();?>
	<div id="print-content">
		<div id="print-area"></div>
	</div>
</div>
