<?php
$excel_col = array_flip(Qss_Lib_Const::$EXCEL_COLUMN);
$no        = 1; // Số thứ tự
$countType = count((array)$this->typeLabel);
$countRea  = count((array)$this->reasonLabel);
$totalCol  = 7 + $countType + $countRea;
?>
<form id="excel" method="post" action="/report/index/excel" target="new">
	<input type="hidden" id="content" name="content" value="">
</form>
<div class="landscape">
	<excel orientation="landscape" font-name="Arial" font-size="9"
		margin-left="0.5" margin-right="0.5" margin-top="0.75"
		margin-bottom="0.75" />
	<div id="head_print">
	<?php echo $this->views->Common->Landscape()?>
	<?php $row = 2;?>
		<center>
			<h2>
				<xls row="<?php echo $row?>" column="A"
					column-merge="<?php echo $excel_col[$totalCol]?>" font-size="11"
					wrap-text="1" h-align="center" v-align="center"> <?php echo $this->_translate(1)?>
				(<?php echo $this->_translate(2)?> <?php echo $this->startDate?> <?php echo $this->_translate(3)?>
				<?php echo $this->endDate?>) </xls>
			</h2>
		</center>
	</div>
	<?php $row++?>


	<div id="container">
		<table cellpadding="0" cellspacing="0" class="border">
			<!--  Tiêu đề  -->
			<tr class="bggrey">
			<?php $col = 0;?>
				<th rowspan="2" width="30px">
					<!-- STT -->
					<div style="width: 30px;">
						<xls row="<?php echo $row?>" row-merge="1"
							column="<?php echo $excel_col[++$col]?>" width="4" wrap-text="1"
							h-align="center" v-align="center" border="1" bold="1"> <?php echo $this->_translate(4)?></xls>
					</div>
				</th>
				<th rowspan="2" width="80px">
					<!-- Thời gian -->
					<div style="width: 80px;">
						<xls row="<?php echo $row?>" row-merge="1"
							column="<?php echo $excel_col[++$col]?>" width="10" wrap-text="1"
							h-align="center" v-align="center" border="1" bold="1"> <?php echo $this->_translate(5)?>
						</xls>
					</div>
				</th>
				<th rowspan="2" width="80px">
					<!-- Mã mặt hàng -->
					<div style="width: 80px;">
						<xls row="<?php echo $row?>" row-merge="1"
							column="<?php echo $excel_col[++$col]?>" width="10" wrap-text="1"
							h-align="center" v-align="center" border="1" bold="1"> <?php echo $this->_translate(6)?>
						</xls>
					</div></th>
				<th rowspan="2" width="100px">
					<!-- Tên mặt hàng -->
					<div style="width: 100px;">
						<xls row="<?php echo $row?>" row-merge="1"
							column="<?php echo $excel_col[++$col]?>" width="10" wrap-text="1"
							h-align="center" v-align="center" border="1" bold="1"> <?php echo $this->_translate(7)?></xls>
					</div>
				</th>
				<th rowspan="2" width="50px">
					<!-- Tổng số -->
					<div style="width: 50px;">
						<xls row="<?php echo $row?>" row-merge="1"
							column="<?php echo $excel_col[++$col]?>" width="12" wrap-text="1"
							h-align="center" v-align="center" border="1" bold="1"> <?php echo $this->_translate(8)?></xls>
					</div>
				</th>
				<th rowspan="2" width="50px">
					<!-- Tổng số lỗi -->
					<div style="width: 50px;">
						<xls row="<?php echo $row?>" row-merge="1"
							column="<?php echo $excel_col[++$col]?>" width="12" wrap-text="1"
							h-align="center" v-align="center" border="1" bold="1"> <?php echo $this->_translate(9)?></xls>
					</div>
				</th>
				<th rowspan="2" width="50px">
					<!-- Số lượng -->
					<div style="width: 50px;">
						<xls row="<?php echo $row?>" row-merge="1"
							column="<?php echo $excel_col[++$col]?>" width="8" wrap-text="1"
							h-align="center" v-align="center" border="1" bold="1"> <?php echo $this->_translate(10)?></xls>
					</div></th>
				<th colspan="<?php echo $countType?>">
					<!-- Loại lỗi --> <?php $colMerge = ($col + $countType)?> <xls
						row="<?php echo $row?>" column="<?php echo $excel_col[++$col]?>"
						column-merge="<?php echo $excel_col[$colMerge]?>" width="8"
						wrap-text="1" h-align="center" v-align="center" border="1"
						bold="1"> <?php echo $this->_translate(11)?></xls></th>
				<th colspan="<?php echo $countRea?>">
					<!-- Nguyên nhân lỗi --> <?php $colMerge2 = $colMerge + $countRea;?>
					<xls row="<?php echo $row?>"
						column="<?php echo $excel_col[++$colMerge]?>"
						column-merge="<?php echo $excel_col[$colMerge2]?>" width="8"
						wrap-text="1" h-align="center" v-align="center" border="1"
						bold="1"> <?php echo $this->_translate(12)?></xls>
				</th>

			</tr>
			<?php $row++;// Lên một hàng?>

			<tr class="bggrey">
			<?php foreach ($this->typeLabel as $tc):?>
				<th width="50px">
					<div style="width: 50px;">
						<xls row="<?php echo $row?>"
							column="<?php echo $excel_col[$col++]?>" width="8" wrap-text="1"
							h-align="center" v-align="center" border="1" bold="1"> <?php echo $tc->MaLoi?></xls>
					</div>
				</th>
				<?php endforeach;?>

				<?php foreach ($this->reasonLabel as $tc):?>
				<th width="50px">
					<div style="width: 50px;">
						<xls row="<?php echo $row?>"
							column="<?php echo $excel_col[$col++]?>" width="8" wrap-text="1"
							h-align="center" v-align="center" border="1" bold="1"> <?php echo $tc->MaNguyenNhan?></xls>
					</div>
				</th>
				<?php endforeach;?>
			</tr>
			<?php $row++;// Lên một hàng?>

			<!-- Nội dung -->
			<?php foreach ($this->report as $val):?>
			<tr>
				<td colspan="<?php echo $totalCol?>" class="left bold"><xls
						row="<?php echo $row?>" column="<?php echo $excel_col[1]?>"
						column-merge="<?php echo $excel_col[$totalCol]?>" wrap-text="1"
						h-align="left" v-align="center" border="1" bold="1"> <?php echo $val['Group'];?></xls>
				</td>
			</tr>
			<?php $row++;// Lên một hàng?>

			<?php foreach ($val['Params'] as $item):?>
			<?php $col = 0;?>
			<tr>
				<td class="center"><xls row="<?php echo $row?>"
						column="<?php echo $excel_col[++$col]?>" wrap-text="1"
						h-align="center" v-align="center" border="1"> <?php echo $no;?></xls>
				</td>
				<td class="center"><xls row="<?php echo $row?>"
						column="<?php echo $excel_col[++$col]?>" wrap-text="1"
						h-align="center" v-align="center" border="1"> <?php echo $item['Time'];?></xls>
				</td>
				<td class="left"><xls row="<?php echo $row?>"
						column="<?php echo $excel_col[++$col]?>" wrap-text="1"
						h-align="left" v-align="center" border="1"> <?php echo $item['ItemCode'];?></xls>
				</td>
				<td class="left"><xls row="<?php echo $row?>"
						column="<?php echo $excel_col[++$col]?>" wrap-text="1"
						h-align="left" v-align="center" border="1"> <?php echo $item['ItemName'];?></xls>
				</td>
				<td class="right"><xls row="<?php echo $row?>"
						column="<?php echo $excel_col[++$col]?>" wrap-text="1"
						h-align="right" v-align="center" border="1"> <?php echo $item['TotalQty'];?></xls>
				</td>
				<td class="right"><xls row="<?php echo $row?>"
						column="<?php echo $excel_col[++$col]?>" wrap-text="1"
						h-align="right" v-align="center" border="1"> <?php echo $item['DefaceQty'];?></xls>
				</td>
				<td class="right"><xls row="<?php echo $row?>"
						column="<?php echo $excel_col[++$col]?>" wrap-text="1"
						h-align="right" v-align="center" border="1"> <?php echo $item['Qty'];?></xls>
				</td>
				<?php foreach ($this->typeLabel as $tc):?>
				<td class="right"><xls row="<?php echo $row?>"
						column="<?php echo $excel_col[++$col]?>" wrap-text="1"
						h-align="right" v-align="center" border="1"> <?php echo isset($item['DefaceType'][$tc->IOID]['Qty'])?$item['DefaceType'][$tc->IOID]['Qty']:0?></xls>
				</td>
				<?php endforeach;?>

				<?php foreach ($this->reasonLabel as $tc):?>
				<td class="right"><xls row="<?php echo $row?>"
						column="<?php echo $excel_col[++$col]?>" wrap-text="1"
						h-align="right" v-align="center" border="1"> <?php echo isset($item['DefaceReason'][$tc->IOID]['Qty'])?$item['DefaceReason'][$tc->IOID]['Qty']:0?></xls>
				</td>
				<?php endforeach;?>
			</tr>
			<?php $row++;// Lên một hàng?>
			<?php $no++;?>
			<?php endforeach;?>
			<?php endforeach;?>
		</table>
	</div>

	<?php
	$xAxis  = '';
	$series = '';
	$timeArray = array();

	if($this->groupby == 'time')
	{
		foreach ($this->report as $time=>$items)
		{
			foreach ($items['Params'] as $refItem=>$item)
			{
				$timeArray[$refItem][$item['TimeCode']]['Qty'] = $item['Qty'];
				$timeArray[$refItem][$item['TimeCode']]['Time'] = $item['ChartTime'];
				$timeArray[$refItem]['Item'] = $item['ItemCode'];
			}
		}
	}
	elseif($this->groupby == 'item')
	{
			
		foreach ($this->report as $item=>$dates)
		{
			foreach ($dates['Params'] as $date)
			{
				$timeArray[$item][$date['TimeCode']]['Qty']  = $date['Qty'];
				$timeArray[$item][$date['TimeCode']]['Time'] = $date['ChartTime'];
				$timeArray[$item]['Item'] = $date['ItemCode'];
			}
		}
	}

	foreach ($this->time as $key=>$time)
	{
		$xAxis .= ($xAxis != '')?",":"";
		$xAxis .= "'{$time['Display']}'";
	}
	foreach ($this->items as $item)
	{
		if(isset($timeArray[$item]))
		{
			$series .= ($series != '')?',':'';
			$series .= " {name:'{$timeArray[$item]['Item']}', data:[";
			$tmp     = '';
			foreach ($this->time as $key=>$time)
			{
				$tmp .= ($tmp != '')?',':'';
				$tmp .= isset($timeArray[$item][$key]['Qty'])?$timeArray[$item][$key]['Qty']:0;
			}
			$series .= "{$tmp} ]}";
		}
	}

	?>

	<br />
	<script type="text/javascript">
	<!--
	$(document).ready(function() {
		var chart;
	
		chart = new Highcharts.Chart({
	        chart: {
	        	renderTo: 'chart',
		         plotBackgroundColor: null,
		         plotBorderWidth: null,
		         plotShadow: false
	        },
	        title: {
	            text: '<?php echo $this->_translate(1)?>   (<?php echo $this->_translate(2)?> <?php echo $this->startDate?> <?php echo $this->_translate(3)?> <?php echo $this->endDate?>)',
	            x: -20 //center
	        },
	        xAxis: {
	            categories: [<?php echo $xAxis;?>],
	            labels: {
	                rotation: -45,
	                align:'right'
	            }
	        },
	        yAxis: {
	        	min: 0,
	            stackLabels: {
	                enabled: true,
	                style: {
	                    fontWeight: 'bold',
	                    color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
	                }
	            },
	            title: {
	                text: '<?php echo $this->_translate(14)?>'
	            },
	            plotLines: [{
	                value: 0,
	                width: 1,
	                color: '#808080'
	            }]
	        },
	        tooltip: {
	            valueSuffix: ''
	        },
	        series: [<?php echo $series;?>]
	    });
	});
	//-->
	</script>
	<div id="chart"></div>
</div>
