<?php
$width  = '1200';
$widths = array(1, 5, 5, 2, 3, 5, 3, 2, 1);
$fit    = Qss_Lib_Report::changeWidthToFitScreen2($widths, $width);
$month  = '';
$i      = 0;
$begin  = 0;
$stt    = 0;
?>




<table class="border_table" cellspacing="0" cellpadding="0" border="0" style="width:<?php echo $width;?>px">
    <tr>

        <th class="center" style="width: <?php echo $fit[$begin++];?>px">
            STT
        </th>




        <th class="center" style="width: <?php echo $fit[$begin++];?>px">
            Tên thiết bị
        </th>

        <th class="center" style="width: <?php echo $fit[$begin++];?>px">
            Số serial
        </th>

        <th class="center" style="width: <?php echo $fit[$begin++];?>px">
            Số lần trên năm
        </th>

        <th class="center" style="width: <?php echo $fit[$begin++];?>px">
            Dự kiến thực hiện
        </th>

        <th class="center" style="width: <?php echo $fit[$begin++];?>px">
            Nhà CCDV
        </th>

        <th class="center" style="width: <?php echo $fit[$begin++];?>px">
            Ngày bảo dưỡng thực tế
        </th>

        <th class="center" style="width: <?php echo $fit[$begin++];?>px">
            Chi tiết
        </th>

        <th class="center" style="width: <?php echo $fit[$begin++];?>px">
            <?php /*<input type="checkbox" onclick="common_check_all_table_line(this, '.cwpo_line_checkbok', '.cwpo_line_checkbok_val')"/> */?>
            Chọn
        </th>


    </tr>


    <?php foreach($this->detailPlans as $item):?>
        <tr class="<?php if($i%2==0):?>bgwhite<?php else:?>bglightblue<?php endif;?>">

            <td class="center">
                <?php echo ++$stt;?>
            </td>

            <td class="left">
                <?php echo $item->TenThietBi;?>
            </td>

            <td class="left">
                <?php echo $item->MaThietBi;?>
            </td>


            <td class="left">
                <?php echo $item->SoLanTrenNam;?>
            </td>

            <td class="left">
                <?php echo $item->DuKienThucHien;?>
            </td>

            <td class="left">
                <?php echo $item->DoiTac;?>
            </td>

            <td class="center">
                <?php echo Qss_Lib_Date::mysqltodisplay($item->NgayBaoDuongThucTe);?>
            </td>


            <td class="center">
                <a href="#1" title="Click để sửa!" onclick="popupWindowFormEdit(<?php echo $item->IFID_M837;?>, <?php echo $this->deptid;?>, {}, function(){ m838.listDetail('<?php echo $this->ifid;?>'); })">
                Sửa
                </a>
            </td>


            <td class="center">
                <input class="table_line_disabled OKeHoachChiTiet_IOID" type="hidden" value="<?php echo $item->IOID;?>" name="OKeHoachChiTiet_IOID[]" disabled>
                <input class="table_line_disabled OKeHoachChiTiet_IFID" type="hidden" value="<?php echo $item->IFID_M837;?>" name="OKeHoachChiTiet_IFID[]" disabled>
                <input class="table_line_disabled OKeHoachChiTiet_DeptID" type="hidden" value="<?php echo $this->deptid;?>" name="OKeHoachChiTiet_DeptID[]" disabled>


                <input type="checkbox" class="cwpo_line_checkbok " onclick="common_check_table_line(this, '.cwpo_line_checkbok_val')">
                <input type="hidden" class="table_line_disabled cwpo_line_checkbok_val" name="CheckBox[]"  value="0" disabled>
            </td>
        </tr>
    <?php endforeach;?>
</table>