<script src="/js/extra/button/m182.js"></script>

<form id="report">
    <input type="hidden" name="_ifid" id="_ifid" value="<?php echo $this->ifid;?>" />
    <input type="hidden" name="_deptid" id="_deptid" value="<?php echo $this->deptid;?>" />

    <div class="popup_wrap">
        <div class="popup_header">
            <table class="popup_detail">
                <tr>
                    <th style="width: 20%">
                        Nhân viên bàn giao:
                    </th>

                    <td>
                        <?php echo $this->views->Report->SimpleComboBox('_emp', $this->emps, ' style="width:200px;" ');?>
                    </td>
                </tr>

                <tr>
                    <th style="width: 20%">

                    </th>

                    <td>
                        <button onclick="m182_handover_button.printPreview();" type="button" class="btn">Xem biên bản</button>
                    </td>
                </tr>
            </table>
        </div>

        <div class="popup_content">

        </div>
    </div>
</form>
