<script type="text/javascript">
    function printPreview() {
        var ngaybd = $('#start').val();
        var ngaykt = $('#end').val();
        var msg = '';
        if(!$('#report input[type="checkbox"]').is(':checked'))
        {
            var cTitle = '<?php echo $this->_translate(6);?>';
            msg += cTitle;
        }
        msg += common_checkEmpty(ngaybd, '<?php echo $this->_translate(4);?>');
        msg += common_checkEmpty(ngaykt, '<?php echo $this->_translate(5);?>');
        msg += common_compareStartAndEnd(ngaybd, ngaykt);

        if(msg != '')
        {
            qssAjax.alert(msg);
            return;
        }
        else
        {
            var url = sz_BaseUrl + '/static/m849/show';
            var data = $('#report').serialize();

            qssAjax.getHtml(url, data, function (jreturn) {
                $('#print-area').html(jreturn);
                removePrintToolbarDisabled();
            });
        }
    }
</script>
<div class="clear"></div>
<div id="view">
    <div class="line-hr">
            <span><?php echo $this->_translate(1);?> </span>
    </div>
    <form id="report" method="post">
    <table class="detail">
        <tr>
            <th width="20%" class="report-param-label"><?php echo $this->_translate(2);?></th>
            <td>
                <?php
                $id = 'equipment';
                $getDataObject = array('ODanhSachThietBi' => array('MaThietBi', 'TenThietBi'));
                //$excludeObject = array('IFID_M705','IOID');
                $getFields = array('num' => 3,
                    'objects' => array('ODanhSachThietBi' => array(
                    'id' => 'IFID_M705'
                    , 'display1' => 'MaThietBi'
                    , 'display2' => 'TenThietBi'
                    , 'where'    => ' AND ODanhSachThietBi.IFID_M705 IN (SELECT IFID_M705 FROM ODanhSachDiemDo)'
                    , 'order'    => 'TenThietBi' )));
                ?>
                <?php echo $this->views->Report->ListBox($id, $getDataObject, $getFields);?>
            </td>
        </tr>
        <tr>
            <th width="20%" class="report-param-label"><?php echo $this->_translate(3);?>
                <span class="bold red">(*)</span></th>
        <td>
            <?php
            $id            = 'checkBox_diemDo';
            $getFields     = array('num'=>3,
                'objects'=>array('ODanhSachDiemDo'=>array(
                    'id'=>'IOID'
                ,'display1'=>'BoPhan'
                ,'display2'=>'Ma'
                ,'display3'=>'ChiSo'
                ,'order' =>'ChiSo'
                )));
            $filter         = array(
                0 => array(
                    'id' => 'equipment'
                , 'refField' => array(
                        'ODanhSachDiemDo' => 'IFID_M705'
                    )
                , 'required' => 1
                )
            );
            ?><?php echo $this->views->Report->CheckBox($id, $getFields,$filter);?>
        </td>
        </tr>
        <tr>
            <th width="20%" class="report-param-label"><?php echo $this->_translate(4)?>
                <span class="bold red">(*)</span></th>
            <td><?php echo $this->views->Report->Datepicker('start', '01-'.'01-'.date('Y'));?></td>
        </tr>
        <tr>
            <th width="20%" class="report-param-label"><?php echo $this->_translate(5)?>
                <span class="bold red">(*)</span></th>
            <td><?php echo $this->views->Report->Datepicker('end', '31-'.'12-'.date('Y'));?></td>
        </tr>
    </table>
    </form>
<hr>
    <?php $hidden = array('html'=>false, 'excel'=>true); echo $this->views->Report->PrintToolbar($hidden);?>
    <div id="print-content">
        <div id="print-area"></div>
    </div>
</div>
