<?php $oldIFID   = '';?>
<?php $oldDeptID = '';?>
<?php $depIndex  = 0;?>
<div id="task_content">
        <div id="task_day_content" style="float: left; width: 100%;">

            <table class="grid grid_edit border" style="border-left: 1px #ccc solid;">


                <tr class="bggrey">
                    <th style="width: 10%;"> Ngày </th>
                    <th style="width: 10%;"> Thời gian (Phút) </th>
                    <th style="width: 70%;"> Nội dung </th>
                    <th style="width: 10%;"> Kết quả </th>
                </tr>

                <?php foreach($this->data as $item):?>
                    <?php if($item->DeptID == $this->sdeptid):?>

                    <?php if($oldDeptID != $item->DeptID):?>
                        <tr class="">
                            <td colspan="4" class="left tree_level_1">
                                <b>
                                    <a href="#1">
                                        <?php echo $item->DeptName;?> - <?php echo $item->DeptCode;?>
                                    </a>
                                </b>
                            </td>
                        </tr>

                    <?php endif;?>

                    <?php if($oldIFID != $item->IFID):?>
                        <tr class="">
                            <td colspan="4" class="left tree_level_2">
                                <b>
                                    <?php echo $item->EquipName;?>
                                    (
                                    Mã TB: <?php echo $item->EquipCode;?>
                                    - Ngày BĐ: <?php echo Qss_Lib_Date::mysqltodisplay($item->NgayBatDau)?>
                                    <?php if($item->NgayKetThuc):?>- Ngày KT: <?php echo $item->NgayKetThuc?Qss_Lib_Date::mysqltodisplay($item->NgayKetThuc):'--- ';?><?php endif;?>
                                    - Loại BT: <?php echo $item->LoaiBaoTri;?>
                                    - TG DM: <?php echo $item->ThoiGianDungMay?$item->ThoiGianDungMay:0;?> giờ)
                                </b>
                            </td>
                        </tr>
                    <?php endif;?>

                    <tr class="">
                        <td class="center">
                            <?php echo Qss_Lib_Date::mysqltodisplay($item->Ngay);?>
                        </td>

                        <td class="right">
                            <?php echo $item->ThoiGian;?>
                        </td>

                        <td class="left">
                            <?php echo $item->MoTaCongViec;?>
                        </td>

                        <td class="right">
                            <?php echo @$item->KetQua?$item->KetQua:0;?>%
                        </td>
                    </tr>

                    <?php endif;?>

                    <?php $oldIFID   = $item->IFID;?>
                    <?php $oldDeptID = $item->DeptID;?>
                <?php endforeach;?>

            </table>

        </div>



        <div id="task_month_view" style="float: left; width: 22%;">
            <div style="float: right">
                <?php echo $this->monthView;?>
            </div>

        </div>
    </div>