<div class="box_das2">
    <div class="inside_das2 inside_das3" id="">
        <div class="dash_box_heading">
            Báo cáo công việc sửa chữa hàng ngày
        </div>

        <div style="clear: both; width: 100%">

        </div>

        <div style="clear: both; border-top: 1px #cccccc dotted; padding-top: 5px;" id="plantask_box"  class="dash_box_content">
            <?php echo $this->monthView;?>
        </div>
    </div>
</div>
