<link rel="stylesheet" href="/css/themes/base/jquery.ui.core.css" type='text/css'/>
<link rel="stylesheet" href="/css/themes/base/jquery.ui.base.css" type='text/css'/>
<link rel="stylesheet" href="/css/themes/base/jquery.ui.all.css" type='text/css'/>
<link rel="stylesheet" href="/css/themes/base/jquery.ui.dialog.css" type='text/css'/>
<link rel="stylesheet" href="/css/print.css" type='text/css'/>

<div id="hochua-wrap">
        <h2>
                <?php echo @$this->hochua->LopBanDo;?>
        </h2>
        <table border="1" cellpadding="0" cellspacing="0" class="">
               
                
                <tr>
                        <th> Mã </th>
                        <td> <?php echo @$this->hochua->Ma;?> </td>
                </tr>
                
                <tr>    
                        <th> Tên </th>
                        <td> <?php echo @$this->hochua->Ten;?> </td>
                </tr>         
                
                <tr>    
                        <th> Kinh độ </th>
                        <td> <?php echo @$this->hochua->OY;?> </td>
                </tr>                
                
                <tr>    
                        <th> Vĩ độ </th>
                        <td> <?php echo @$this->hochua->OX;?> </td>
                </tr>   
                
                <tr>    
                        <th> Năm vận hành </th>
                        <td> <?php echo @$this->hochua->NamVanHang;?> </td>
                </tr>                   
                
        </table>
</div><!-- end #hochua-wrap -->