<link rel="stylesheet" href="/css/themes/base/jquery.ui.core.css" type='text/css'/>
<link rel="stylesheet" href="/css/themes/base/jquery.ui.base.css" type='text/css'/>
<link rel="stylesheet" href="/css/themes/base/jquery.ui.all.css" type='text/css'/>
<link rel="stylesheet" href="/css/themes/base/jquery.ui.dialog.css" type='text/css'/>
<link rel="stylesheet" href="/css/print.css" type='text/css'/>

<div id="hokhoan-wrap">
        <h2>
                <?php echo @$this->hokhoan->LopBanDo;?>
        </h2>
        <table border="1" cellpadding="0" cellspacing="0" class="">
                
                <tr>
                        <th> Hố khoan</th>
                        <td> <?php echo @$this->hokhoan->HoKhoan;?> </td>
                </tr>
                
                <tr>    
                        <th> Năm </th>
                        <td> <?php echo @$this->hokhoan->Nam;?> </td>
                </tr>         
                
                <tr>    
                        <th> Tuyến sông </th>
                        <td> <?php echo @$this->hokhoan->TuyenSong;?> </td>
                </tr>       
                
                <tr>    
                        <th> Kinh độ  </th>
                        <td> <?php echo @$this->hokhoan->OY;?> </td>
                </tr>   
                
                <tr>    
                        <th> Vĩ độ  </th>
                        <td> <?php echo @$this->hokhoan->OX;?> </td>
                </tr>   
                
        </table>
</div><!-- end #hokhoan-wrap -->