<?php
$widths         = array(1, 5, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3);
$totalColumn    = count($widths);
$excel_col      = array_flip(Qss_Lib_Const::$EXCEL_COLUMN);
$htmlWidth      = Qss_Lib_Report::changeWidthToFitScreen($widths, Qss_Lib_Extra_Const::PRINT_TYPE_LANDSCAPE);
$excelWidth     = Qss_Lib_Report::convertPxColumnWidthToExcelWidth($widths, Qss_Lib_Extra_Const::PRINT_TYPE_LANDSCAPE);
$row            = 9; // Row bat dau
$bg             = "#EEEEEE"; // Mau nen cua cot tieu de
$sttCot         = 0;
$sttThietBi     = 0;
$sttLoaiTB      = 0;
$oldNhomTB      = '';
$oldThietBi     = '';

?>

<div class="landscape">
    <form id="excel" method="post" action="/report/index/excel" target="new">
        <input type="hidden" id="content" name="content" value="">
    </form>

    <excel orientation="landscape"
           font-name="Arial"
           font-size="10"
           margin-left="0.5"
           margin-right="0.5"
           margin-top="0.75"
           margin-bottom="0.75" />

    <div id="head_print">
        <?php echo $this->views->Common->Landscape() ?>

        <center>
            <h2 class="report-title">
                <xls row="<?php echo $row ?>"
                     column="A"
                     column-merge="<?php echo $excel_col[$totalColumn] ?>"
                     font-size="14"
                     wrap-text="1"
                     h-align="center"
                     v-align="center"> BÁO CÁO QUYẾT TOÁN SỬ DỤNG VẬT TƯ SCTX THIẾT BỊ CƠ ĐIỆN THÁNG <?php echo $this->month;?> NĂM <?php echo $this->year;?></xls>
            </h2>
            <?php $row++; ?>
        </center>
    </div>

    <br/>

    <div id="container">
        <table cellspacing="0" cellpadding="0" border="1" class="border">

            <?php $begin = 0;?>
            <tr class="bggrey">
                <!-- STT -->
                <th rowspan="2" class="center" style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        row-merge="1"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> STT </xls>
                </th>

                <!-- Loại thiết bị/Tên qui cách vật tư -->
                <th rowspan="2" class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        row-merge="1"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> Loại thiết bị/Tên qui cách vật tư </xls>
                </th>

                <!-- Số Sê ri, mã hiệu cũ -->
                <th rowspan="2" class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        row-merge="1"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> Số Sê ri, mã hiệu cũ </xls>
                </th>

                <!-- Số Sê ri, mã hiệu mới -->
                <th rowspan="2" class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        row-merge="1"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> Số Sê ri, mã hiệu mới </xls>
                </th>

                <!-- Vị trí sử dụng-->
                <th rowspan="2" class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        row-merge="1"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> Vị trí sử dụng </xls>
                </th>

                <!-- Ngày tháng s/c, thay thế liền kề gần nhất -->
                <th rowspan="2" class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        row-merge="1"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> Ngày tháng s/c, thay thế liền kề gần nhất </xls>
                </th>

                <!-- Ngày tháng s/c, thay mới -->
                <th rowspan="2" class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        row-merge="1"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> Ngày tháng s/c, thay mới </xls>
                </th>

                <!-- ĐVT -->
                <th rowspan="2" class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        row-merge="1"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> ĐVT </xls>
                </th>

                <!-- Số lượng -->
                <th rowspan="2" class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        row-merge="1"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> Số lượng </xls>
                </th>

                <!-- Đơn giá (Đồng) -->
                <th rowspan="2" class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        row-merge="1"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>">  Đơn giá (Đồng) </xls>
                </th>

                <!-- Giá trị thực hiện (Đồng) -->
                <th rowspan="2" class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        row-merge="1"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>">  Giá trị thực hiện (Đồng) </xls>
                </th>




                <!-- Kích thước cơ bản (mm) -->
                <th colspan="3" class="center">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        column-merge="<?php echo $excel_col[($begin + 2)] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> Kích thước cơ bản (mm)  </xls>
                </th>
                <?php $begin = $begin + 2;?>

                <!-- Ghi chú -->
                <th rowspan="2" class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        row-merge="1"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>">  Ghi chú </xls>
                </th>

            </tr>
            <?php $row++;?>

            <?php $begin = 2;?>
            <tr class="bggrey">

                <!-- Kích thước cơ bản (mm): L -->
                <th class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> L </xls>
                </th>

                <!-- Kích thước cơ bản (mm): W -->
                <th class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> W </xls>
                </th>

                <!-- Kích thước cơ bản (mm): H -->
                <th class="center"  style="width:<?php echo $htmlWidth[$begin]; ?>px">
                    <xls
                        row="<?php echo $row ?>"
                        width="<?php echo $excelWidth[$begin]; ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg; ?>"> H </xls>
                </th>
            </tr>
            <?php $row++;?>


            <?php foreach($this->report as $item):?>

            <?php if($oldNhomTB != $item->Ref_NhomThietBi):?>
                <?php $sttThietBi = 0;?>
                <tr>
                    <td class="bold center">
                        <xls row="<?php echo $row ?>"
                             column="A"
                             wrap-text="1"
                             h-align="center"
                             v-align="center"><?php echo Qss_Lib_Util::numberToRome(++$sttLoaiTB);?></xls>
                    </td>

                    <td class="bold left" colspan="<?php echo ($totalColumn-1);?>">
                        <xls row="<?php echo $row ?>"
                             column="B"
                             column-merge="<?php echo $excel_col[($totalColumn-1)] ?>"
                             wrap-text="1"
                             h-align="left"
                             v-align="center"><?php echo $item->TenNhomThietBi;?></xls>
                    </td>
                </tr>
                <?php $row++;?>
            <?php endif;?>

            <?php if($oldThietBi != $item->Ref_ThietBi):?>
                <?php $sttVatTu = 0;?>

                <tr>
                    <td class="bold center">
                        <xls row="<?php echo $row ?>"
                             column="A"
                             wrap-text="1"
                             h-align="center"
                             v-align="center"><?php echo ++$sttThietBi;?></xls>
                    </td>

                    <td class="bold left" colspan="<?php echo ($totalColumn-1);?>">
                        <xls row="<?php echo $row ?>"
                             column="B"
                             column-merge="<?php echo $excel_col[($totalColumn-1)] ?>"
                             wrap-text="1"
                             h-align="left"
                             v-align="center"><?php echo $item->TenThietBi;?></xls>
                    </td>
                </tr>
                <?php $row++;?>
            <?php endif;?>



            <?php $begin = 0;?>
            <tr>
                <!-- STT -->
                <td class="center">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"> <?php echo $sttThietBi;?>.<?php echo ++$sttVatTu;?> </xls>
                </td>

                <!-- Loại thiết bị/Tên qui cách vật tư -->
                <td class="left">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="left"
                        border="1"> <?php echo $item->TenSanPham;?> </xls>
                </td>

                <!-- Số Sê ri, mã hiệu cũ -->
                <td class="left">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="left"
                        border="1">Số Sê ri, mã hiệu cũ </xls>
                </td>

                <!-- Số Sê ri, mã hiệu mới -->
                <td class="left">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="left"
                        border="1"> Số Sê ri, mã hiệu mới </xls>
                </td>

                <!-- Vị trí sử dụng -->
                <td class="left">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="left"
                        border="1"> <?php echo $item->BoPhan;?> </xls>
                </td>

                <!-- Ngày tháng s/c, thay thế liền kề gần nhất -->
                <td class="center">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"><?php echo Qss_Lib_Date::mysqltodisplay($item->NgayGanKe);?> </xls>
                </td>

                <!-- Ngày tháng s/c, thay mới -->
                <td class="center">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"> <?php echo Qss_Lib_Date::mysqltodisplay($item->NgayThayMoi);?> </xls>
                </td>

                <!-- ĐVT -->
                <td class="left">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="left"
                        border="1"> <?php echo $item->DonViTinh;?> </xls>
                </td>

                <!-- Số lượng -->
                <td class="right">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1"> <?php echo Qss_Lib_Util::formatNumber($item->SoLuongVatTu);?> </xls>
                </td>

                <!-- Đơn giá (Đồng) -->
                <td class="right">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1">  <?php echo Qss_Lib_Util::formatMoney($item->GiaMua);?> </xls>
                </td>

                <!-- Giá trị thực hiện (Đồng) -->
                <td class="right">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1"> <?php echo Qss_Lib_Util::formatMoney($item->GiaMua * $item->SoLuongVatTu);?>  </xls>
                </td>




                <!-- Kích thước cơ bản (mm): L -->
                <td class="right">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1"> L  </xls>
                </td>

                <!-- Kích thước cơ bản (mm): W -->
                <td class="right">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1"> W  </xls>
                </td>


                <!-- Kích thước cơ bản (mm): W -->
                <td class="right">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="right"
                        border="1"> H  </xls>
                </td>


                <!-- Ghi chú -->
                <td class="left">
                    <xls
                        row="<?php echo $row ?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="left"
                        border="1"> Ghi chú  </xls>
                </td>
            </tr>
            <?php $row++;?>


            <?php $oldNhomTB  = $item->Ref_NhomThietBi;?>
            <?php $oldThietBi = $item->Ref_ThietBi;?>
            <?php endforeach;?>
        </table>
    </div>

    <div class="clear"></div>
    <br/>
    <br/>

    <div>
        <p class="right">
            <xls
                row="<?php echo $row ?>"
                column="<?php echo $excel_col[1]; ?>"
                column-merge="<?php echo $excel_col[$totalColumn]; ?>"
                wrap-text="1"
                v-align="center"
                h-align="center"> Cửa ông, ngày.......tháng........năm 201...... </xls>
        </p>
    </div>
    <br/>
    <?php $row++;?>

    <table cellspacing="0" cellpadding="0" border="0" >
        <tr>
            <?php $endLabel1 = (int)($totalColumn/3); ?>
            <?php $startLabel2 = $endLabel1 + 1; ?>
            <?php $endLabel2 = $startLabel2 + (int)($totalColumn/3) - 1; ?>
            <?php $startLabel3 = $endLabel2 + 1; ?>

            <td style="width: 33%; text-align: center; font-weight: bold;">
                <xls
                    row="<?php echo $row ?>"
                    column="<?php echo $excel_col[1]; ?>"
                    column-merge="<?php echo $excel_col[$endLabel1]; ?>"
                    wrap-text="1"
                    v-align="center"
                    h-align="center"> LẬP BIỂU </xls>
            </td>

            <td style="width: 33%; text-align: center; font-weight: bold;">
                <xls
                    row="<?php echo $row ?>"
                    column="<?php echo $excel_col[$startLabel2]; ?>"
                    column-merge="<?php echo $excel_col[$endLabel2]; ?>"
                    wrap-text="1"
                    v-align="center"
                    h-align="center"> PHÒNG CĐ </xls>
            </td>

            <td style="width: 33%; text-align: center; font-weight: bold;">
                <xls
                    row="<?php echo $row ?>"
                    column="<?php echo $excel_col[$startLabel3]; ?>"
                    column-merge="<?php echo $excel_col[$totalColumn]; ?>"
                    wrap-text="1"
                    v-align="center"
                    h-align="center"> QUẢN ĐỐC PX </xls>
            </td>
        </tr>
        <?php $row++;?>
    </table>
</div>