<script>
    function printPreview()
    {
        var start = $('#start').val();
        var end   = $('#end').val();
        var msg   = '';
//		var next  = true;
//		var warning = common_dateWarning('D'
//				, '<?php //echo json_encode(Qss_Lib_Extra_Const::$DATE_LIMIT);?>'
//				, start, end)

        msg += common_checkEmpty(start, '<?php echo $this->_translate(23) ?>');
        msg += common_checkEmpty(end, '<?php echo $this->_translate(24) ?>');
        msg += common_compareStartAndEnd(start, end);


        if(msg)
        {
            qssAjax.alert(msg);
            return;
        }
        else
        {
            var url = sz_BaseUrl + '/static/m790/show';
            var data = $('#report').serialize();
            qssAjax.getHtml(url, data, function(jreturn) {
                $('#print-area').html(jreturn);
                removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
            });
        }
    }
</script>

<div>
    <div class="clear"></div>
    <div id="view">
        <div class="line-hr">
            <span><?php echo $this->_translate(1) ?> </span>
        </div>
        <form id="report" method="get" action="/static/m790/show">
            <table class="detail">
                <!-- NGAY BAT DAU -->
                <tr>
                    <th width="20%" class="report-param-label"><?php echo $this->_translate(23) ?>
                    </th>
                    <td><?php echo $this->views->Report->Datepicker('start', date('01-m-Y')); ?><span
                            class="bold red">(*)</span></td>
                </tr>

                <!-- NGAY KET THUC -->
                <tr>
                    <th width="20%" class="report-param-label"><?php echo $this->_translate(24) ?>
                    </th>
                    <td><?php echo $this->views->Report->Datepicker('end', date('d-m-Y')); ?><span
                            class="bold red">(*)</span></td>
                </tr>

                <!-- KHU VUC -->
                <tr>
                    <th width="20%" class="report-param-label"><?php echo $this->_translate(28)?>
                    </th>
                    <td><?php
                        $id            = 'location';
                        $getFields     = array('num'=>3,
                            'objects'=>array('OKhuVuc'=>array(
                                'id'=>'IOID'
                            ,'display1'=>'MaKhuVuc'
                            ,'display2'=>'Ten') ));
                        ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
                    </td>
                </tr>


                <!-- NHOM THIET BI -->
                <tr>
                    <th width="20%" class="report-param-label"><?php echo $this->_translate(20)?>
                    </th>
                    <td><?php
                        $id            = 'group';
                        $getFields     = array('num'=>2,
                            'objects'=>array('ONhomThietBi'=>array(
                                'id'=>'IOID'
                            ,'display1'=>'LoaiThietBi'
                            )) );
                        ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>

                </tr>

                <!-- LOAI THIET BI -->
                <tr>
                    <th width="20%" class="report-param-label"><?php echo $this->_translate(21)?>
                    </th>
                    <td><?php
                        $id            = 'type';
                        $getFields     = array('num'=>2,
                            'objects'=>array('OLoaiThietBi'=>array(
                                'id'=>'IOID'
                            ,'display1'=>'TenLoai'
                            )) );
                        ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
                    </td>

                </tr>

                <!-- THIET BI -->
                <tr>
                    <th width="20%" class="report-param-label"><?php echo $this->_translate(22)?>
                    </th>
                    <td><?php
                        $id            = 'equip';
                        $getDataObject = array('ODanhSachThietBi'=>array('MaThietBi', 'LoaiThietBi'));
                        //,'OKhuVuc'=>array('MaKhuVuc','Ten')
                        $getFields     = array('num'=>2,
                            'objects'=>array('ODanhSachThietBi'=>array(
                                'id'=>'IOID'
                            ,'display1'=>'MaThietBi'
                            ,'display2'=>'LoaiThietBi')) );
                        $getLookupFilter = array( array('id'=>'group'
                        , 'refField'=>array('ODanhSachThietBi'=>'Ref_NhomThietBi') // Nhom TB
                        , 'required'=>0)
                        , array('id'=>'type'
                            , 'refField'=>array('ODanhSachThietBi'=>'Ref_LoaiThietBi') // Loai TB
                            , 'required'=>0)
                            //														 , array('id'=>'location'
                            //															, 'refField'=>array('ODanhSachThietBi'=>'Ref_KhuVuc')
                            //															, 'required'=>0)
                        );
                        ?> <?php echo $this->views->Report->ListBox($id, $getDataObject,$getFields, $getLookupFilter);?>
                    </td>
                </tr>
            </table>
        </form>
        <hr>
        <?php echo $this->views->Report->PrintToolbar(); ?>
        <div id="print-content">
            <div id="print-area"></div>
        </div>
    </div>
</div>

