<!-- CSS -->
<style>
<!--
.disabled {
	background: #999 !important;
	color: #ccc;
}

.disable_glass {
	position: absolute;
	top: 0px;
	left: 0px;
	width: 100%;
	height: 100%;
}

.getOut {
	display: none;
	visibility: visible;
}

.hidden {
	visibility: visible;
	display: none;
}

.marker {
	border: none;
	border: 1px orange double;
}

.width_100 {
	width: 100px;
}

.width_50 {
	width: 50px;
}

.tree_level_1 {
	padding-left: 15px;
	background: url(../images/tree_open.png) 0 no-repeat !important;
}

.tree_level_2 {
	padding-left: 25px;
	background: url(../images/tree_open.png) 0 no-repeat !important;
	background-position: 10px !important;
}

.tree_level_3 {
	padding-left: 35px;
	background: url(../images/tree_open.png) 0 no-repeat !important;
	background-position: 20px !important;
}

.tree_level_4 {
	padding-left: 45px;
	background: url(../images/tree_open.png) 0 no-repeat !important;
	background-position: 30px !important;
}

.tree_level_5 {
	padding-left: 55px;
	background: url(../images/tree_open.png) 0 no-repeat !important;
	background-position: 40px !important;
}

.tree_level_6 {
	padding-left: 65px;
	background: url(../images/tree_open.png) 0 no-repeat !important;
	background-position: 50px !important;
}

.tree_level_7 {
	padding-left: 75px;
	background: url(../images/tree_open.png) 0 no-repeat !important;
	background-position: 60px !important;
}

.tree_level_8 {
	padding-left: 85px;
	background: url(../images/tree_open.png) 0 no-repeat !important;
	background-position: 70px !important;
}

.tree_level_9 {
	padding-left: 95px;
	background: url(../images/tree_open.png) 0 no-repeat !important;
	background-position: 80px !important;
}

.tree_level_10 {
	padding-left: 105px;
	background: url(../images/tree_open.png) 0 no-repeat !important;
	background-position: 90px !important;
}

.bggrey {
	background: #eee;
}

.bggrey2 {
	background: #ddd;
}
/*
.bgorange
{
	background:#FFFE99;
}
*/
th {
	padding-top: 1px;
	padding-bottom: 1px;
}

#mrp a {
	color: red;
}

select option,select {
	line-height: 12px;
	font-size: 10px
}

.smallText {
	font-size: 9px;
}

.yellowBg {
	background: #FFFF33;
}

.redBg {
	background: red;
}

.left {
	padding-left: 1px;
}

.right {
	padding-right: 1px;
}

.selectFormat {
	width: 50px;
}

.selectText1Format {
	width: 60px;
}

.selectText2Format {
	width: 100px;
}

.borderX {
	border-top: 1px dotted #bbb;
	border-right: 1px dotted #bbb;
}

.borderX tr {
	border-bottom: 1px dotted #bbb;
}

.borderX td,.borderX th {
	border-left: 1px dotted #bbb;
	word-wrap: break-word;
}

#mrp {
	font-family: arial;
	font-size: 11px;
	margin-bottom: 30px;
}

#search_item .siElement {
	margin: -5px 5px;
}

#search_item .siButton {
	margin: -3px 1px;
}

.marker {
	border: none;
	border: 1px red solid;
}

.text_step_style {
	font-family: arial;
	font-size: 11px;
	line-height: 24px;
	color: #666;
	cursor: pointer;
}

.arrow_step {
	clear: both;
	position: relative;
}

.arrow_step {
	clear: both;
	height: 24px;
	overflow: hidden;
}

.arrow_step span {
	padding-left: 15px;
}

.first_step {
	background: url('/images/progress/first-step.png');
	width: 121px;
	height: 24px;
	position: absolute;
	z-index: 100;
}

.first_step_selected {
	background: url('/images/progress/first-step-selected.png');
	width: 120px;
	height: 24px;
	position: absolute;
	color: white;
	z-index: 120;
}

.middle_step {
	background: url('/images/progress/middle-step.png');
	width: 120px;
	height: 24px;
	position: absolute;
	z-index: 100;
}

.middle_step_selected {
	background: url('/images/progress/middle-step-selected.png');
	width: 120px;
	height: 24px;
	position: absolute;
	color: white;
	z-index: 120;
}

.last_step {
	background: url('/images/progress/last-step.png');
	width: 120px;
	height: 24px;
	position: absolute;
	z-index: 100;
}

.last_step_selected {
	background: url('/images/progress/last-step-selected.png');
	width: 120px;
	height: 24px;
	position: absolute;
	color: white;
	z-index: 120;
}

#purchase_plan_control label {
	padding: 0px 5px 0px 2px;
}
-->
</style>
<!-- End CSS -->

<!-- JS -->
<script type="text/javascript">
<!--
$(document).ready(function(){
	$('.hidden_div').hide();
	$('#general_plan').show();
});

/** General plan */
function generalPlan()
{
	// Danh dau buoc da chon
	$('.middle').removeClass('middle_step_selected').addClass('middle_step');
	$('.first_left').removeClass('first_step_selected').addClass('first_step');
	$('.last_right').removeClass('last_step_selected').addClass('last_step');
	$('.first_left').addClass('first_step_selected');

	// Hien thi ke hoach tong the
	$('.hidden_div').hide();
	$('#general_plan').show();	
}

// Danh sach don hang 
function searchGeneralItem(lamLai)
{
	var ext = {lamLai:lamLai};
	var url = sz_BaseUrl + '/extra/mrp/primary/search'; 
	var data = $('#search_item').serialize() +  '&' + $.param(ext);; 
	qssAjax.getHtml(url, data, function(jreturn) {
		$('#choose_item_table').html(jreturn);
	});
}

// End searchGeneralItem

// Khi nut kiem tra duoc an 
// Chay cho het cac cau thanh con
// Cho chon cau thanh, so luong san xuat, so luong mua hang
// Khi chay het chuyen sang in thong ke thoi gian yeu cau, kha nang, da dat truoc
// @Note: GroupID la dang ngay thang
// @Note: lineNo la like tiep theo, giup xac dinh cac ban ghi nao la ban ghi truoc do
function validateGeneralItems(groupID, lineNo) 
{
	// Thiet ke yeu cau bat buoc
	var msg = '';
	//var level = $('#current_level').val();
	var endValidation = $('#end-validation-'+groupID).val();

	// Thong bao loi neu thieu thiet ke tren dong nao do
	$('.bom-'+groupID).each(function(){
		if($(this).val() == '')
		{
			msg += 'Thiết kế trên dòng '+$(this).attr('lineno')+' yêu cầu bắt buộc!\n';
		}
	});

	// Khong the hoan thanh do co san pham co cau thanh khong co thanh phan
	var bomNoChildren = $('.bom-no-children-'+groupID).length;
	if( bomNoChildren > 0)
	{
		$('#end-validation-'+groupID).val(0);
		msg += 'Thiết kế trên dòng '+$('.bom-no-children-'+groupID).attr('lineno')+' chưa được thêm thành phần sản phẩm!\n';
	}

	// Bao loi neu co
	if(msg != '')
	{
		qssAjax.alert(msg); 
		return;
	}

	// Neu chua ket thuc viec in danh sach con
	// Thi tiep tuc
	// Neu da ket thuc in ra bang thong ke thoi gian
	if(endValidation == 0)
	{
		showChildrenOfGeneralItem(groupID, lineNo);
	}
	else if(endValidation == 1)
	{
		showTimeAnalytics(groupID, lineNo);
	}
}
// End validateGeneralItems

function checkEndMrpGeneralRun(groupID, lineNo)
{
	var endValidation = $('#end-validation-'+groupID).val();
	if(endValidation == 1)
	{
		//validateGeneralItems(groupID, lineNo);
	}
}

function showChildrenOfGeneralItem(groupID, lineNo)
{
	var url = sz_BaseUrl + '/extra/mrp/primary/children'; 
	//var ext = {issueDatex:groupID, lineNo: lineNo};
	var data = $('.date-'+groupID+', .filter').serialize(); //+  '&' + $.param(ext);
	
	qssAjax.getHtml(url, data, function(jreturn) {
		//qssAjax.alert(jreturn);
		$('.line-'+groupID).remove();
		$('#mrp_primary_table #heading-'+groupID).after(jreturn);
		checkEndMrpGeneralRun(groupID, lineNo);
	});
}
// End showChildrenOfGeneralItem()

function showTimeAnalytics(groupID, lineNo)
{
	var url = sz_BaseUrl + '/extra/mrp/primary/change'; 
	var ext = {issueDatex:groupID, lineNo: lineNo};
	var data = $('.date-'+groupID+', .filter').serialize()+  '&' + $.param(ext);
	var finishedAndChooseSave = true;
	
	qssAjax.getHtml(url, data, function(jreturn) {
		$('#group-'+groupID).html('');
		$('#group-'+groupID).append(jreturn);
		
		$('.line-'+groupID).each(function(){
			if(!$(this).hasClass('bggrey2'))
			{
				$(this).addClass('bggrey2');
				$(this).find('.production_qty_box').attr('readonly',true).addClass('.readonly');
				$(this).find('.purchase_qty_box').attr('readonly',true).addClass('.readonly');
			}

		});
		$('#qss_trace').scrollTop($('#group-'+groupID).position().top);

		$('.end_validation').each(function(){ if($(this).val == 0) finishedAndChooseSave == false; });;

		if(finishedAndChooseSave)
		{
			if($('#save_item_plan_button').length == 0)
			{
				$('#general_main_control' ).append('<button type="button" id="save_item_plan_button" class="btn-custom" onclick="saveGeneralPlan()"> Lưu lại </button>');
				$('#qss_trace').delay(1000).scrollTop($('#save_item_plan_button').position().top);
			}
		}
	});
}
// End showTimeAnalytics()

// Ham dung de lay ten bom theo gia tri select box
// Dien vao thao ro hay lap dat
function fillBomName(ele)
{
	var selected = $(ele).find('option:selected');
	var selectedValue = selected.val();
	var addingText = (selectedValue != 0)?selected.text():'';
	var realRefAttr = $(ele).parent().parent().find('.real_ref_attributes').val();
	var allAttrOption = selected.attr('all');
	
	$(ele).parent().parent().find('.bom_name').val($.trim(addingText));
	$(ele).parent().parent().find('.assembly').val(selected.attr('assembly'));

	// Dien ref thuoc tinh bang 0 neu cau thanh ap dung cho tat ca thuoc tinh
	if(allAttrOption == 1)
	{
		$(ele).parent().parent().find('.ref_attributes').val(0);
	}
	else
	{
		$(ele).parent().parent().find('.ref_attributes').val(realRefAttr);
	}
}
// End fillBomName


function changeQtyOfGeneralLine(ele, defaultLineQty, typeCheker)
{
	var parent = $(ele).parent().parent();
	var muaqty = parseInt(parent.find('.purchase_qty_box').val());
	var sxqty = parseInt(parent.find('.production_qty_box').val());
	var total = muaqty + sxqty;
	if(total <= defaultLineQty)
	{
		if(typeCheker == 1) // Sx
		{
			parent.find('.production_qty_box').val(sxqty);
			parent.find('.purchase_qty_box').val(defaultLineQty - sxqty);
		}
		else if(typeCheker == 2) // Mh
		{
			parent.find('.purchase_qty_box').val(muaqty);
			parent.find('.production_qty_box').val(defaultLineQty - muaqty);
		}
	}
	else if(total > defaultLineQty)
	{
			//$(ele).val(defaultLineQty);
			if(typeCheker == 1) // Sx
			{
				parent.find('.production_qty_box').val(muaqty);
				parent.find('.purchase_qty_box').val(defaultLineQty - muaqty);
			}
			else if(typeCheker == 2) // Mh
			{
				parent.find('.production_qty_box').val(sxqty);
				parent.find('.purchase_qty_box').val(defaultLineQty -sxqty);
			}
	}
}
// End changeQtyOfGeneralLine


function saveGeneralPlan()
{
	var data = $('#search_item').serialize();
	var url = sz_BaseUrl + '/extra/mrp/primary/save';
	qssAjax.call(url, data, function(jreturn) {
		if(jreturn.message != '')
		{
			qssAjax.alert(jreturn.message);
		}
		detailPlan();
	}, function(jreturn) {
		qssAjax.alert(jreturn.message);
	});
}


function getOldGeneralPlan(groupID)
{
	var url = sz_BaseUrl + '/extra/mrp/primary/old'; 
	//var ext = {issueDatex:groupID, lineNo: lineNo};
	var data = $('.date-'+groupID+', .filter').serialize(); //+  '&' + $.param(ext);
	
	qssAjax.getHtml(url, data, function(jreturn) {
		//qssAjax.alert(jreturn);
		if($.trim(jreturn) != 'false')
		{
			$('.line-'+groupID).remove();
			$('#mrp_primary_table #heading-'+groupID).after(jreturn);
		}
	});
}

function changeQtyAvailable(ele)
{
	var total = 0;
	var changeQty = $(ele).val();
	var warehouse = $(ele).attr('warehouseQty');
	var defaultQty = $(ele).attr('defaultQty');
	var classes = $(ele).attr('marker');
	var val = 0;
	// warehouse_marker

	// Tong so bao gom ca dong nay
	$('.'+classes).each(function(){ 
		val = (isNaN(parseFloat($(this).val())))?0:parseFloat($(this).val());
		$(this).val(val);
		total += val; 
	});
	
	if(total > warehouse)
	{
		$(ele).val(defaultQty);
		qssAjax.alert('Trong kho không đủ số lượng!');
		// co the bao loi rang ko du so luong o day
	}
	else
	{
		if(total == warehouse)
		{
			$('.'+classes).each(function(){ 
				if($(this).val() == 0)
				{
					$(this).attr('readonly',true); $(this).addClass('readonly'); 
				}
			});
		}
		else
		{
			$('.'+classes).each(function(){ 
				$(this).removeAttr('readonly',true); $(this).removeClass('readonly'); 
			});
		}
		$(ele).attr('defaultQty', changeQty);
		$('.warehouse_marker_'+classes).text(total+'/'+warehouse);
	}
}

/** Tab2: Detail plan */

// @todo: Truoc khi chuyen buoc phai kiem tra ke hoach da duoc hoan tong the da duoc hoan thien chua
 function detailPlan()
 {
 	// Chọn bước này trên thanh chuyển bươc
 	$('.middle').removeClass('middle_step_selected').addClass('middle_step');
 	$('.first_left').removeClass('first_step_selected').addClass('first_step');
 	$('.last_right').addClass('last_step_selected');

 	// Hiển thị kế hoạch chi tiết
 	$('.hidden_div').hide();
 	$('#detail_plan').show();
 }
 // End detailPlan

 function runDetailMrp()
 {
	var url  = sz_BaseUrl + '/extra/mrp/detail/run'; 
 	var data = { ifid:<?php echo $this->ifid;?>, startDate:'<?php echo $this->startDate;?>' };
 	qssAjax.getHtml(url, data, function(jreturn) {
 		$('#detail_show_request').html(jreturn);
 	}); 
 }
 // End runDetailMrp
 
 function saveMrp()
{
	var data = $('#detail_mrp_form').serialize();
	var url = sz_BaseUrl + '/extra/mrp/detail/save';
	qssAjax.call(url, data, function(jreturn) {
		if(jreturn.message != '')
		{
			qssAjax.alert(jreturn.message);
		}
	}, function(jreturn) {
		qssAjax.alert(jreturn.message);
	});
}

//-->
</script>
<!-- End JS -->

<!-- PHTML -->
<div
	id="mrp">
	<div id="mrp_step_by_step_button" class="arrow_step">
		<div class="first_left first_step_selected text_step_style"
			style="left: 0;" onclick="generalPlan()" title="Here!">
			<span>Kế hoạch tổng thể</span>
		</div>
		<div class="last_right last_step text_step_style" style="left: 105px;"
			onclick="detailPlan()">
			<span>Kế hoạch chi tiết</span>
		</div>
	</div>
	<!-- end #mrp_step_by_step_button -->

	<div id="general_plan" class="hidden_div">
		<div id="general_main_control">
			<button type="button" class="btn-custom"
				onclick="searchGeneralItem(1)">
				Làm lại
				<?php //echo $this->_translate(100);?>
			</button>
		</div>
		<!-- general_main_control -->

		<!-- <button type="button" class="btn-custom" onclick="searchGeneralItem(0)"> Khôi phục <?php //echo $this->_translate(100);?></button> -->
		<form method="post" id="search_item">
			<input type="hidden" name="ifid" value="<?php echo $this->ifid?>"
				class="filter" /> <input type="hidden" name="ioid"
				value="<?php echo $this->ioid?>" class="filter" /> <input
				type="hidden" name="module" value="<?php echo $this->module?>"
				class="filter" />

			<fieldset>
				<legend>Kế hoạch giao hàng</legend>
				<div id="choose_item_table"></div>
				<!-- end  div#choose_item_table-->
				<script type="text/javascript">searchGeneralItem(0);</script>
			</fieldset>
		</form>
	</div>
	<!-- end #general_plan -->

	<div id="detail_plan" class="hidden_div">
		<!--  Kế hoạch chi tiết -->
		<br />

		<form id="detail_show_request_form">
			<div id="detail_wrap">
				<div>
					<input type="hidden" name="ifid" id="detail_ifid" class="detail"
						value="<?php echo $this->params['ifid'];?>" /> <input
						type="hidden" name="module" id="detail_module" class="detail"
						value="<?php echo $this->params['module'];?>" /> <input
						type="hidden" name="startDate" id="detail_start" class="detail"
						value="<?php echo $this->params['startDate'];?>" />
					<button type="button" id="run_mrp_button" class="btn-custom"
						onclick="runDetailMrp()">
						Chạy kế hoạch
						<?php //echo $this->_translate(100);?>
					</button>
				</div>

				<div id="detail_show_request"></div>
				<!-- div#detail_show_request -->
			</div>
			<!-- end #detail_wrap -->
		</form>
		<!-- end form#detail_show_request -->
	</div>
	<!-- end #detail_plan -->
</div>
<!-- end #mrp -->
<!-- End PHTML -->
