<?php foreach($this->items as $item):?>
    <?php $temYeuCau = ($item->TongYeuCauMua > 0)?$item->TongYeuCauMua:0;?>
    <option value="<?php echo $item->IOID;?>"
            itemioid="<?php echo $item->IOID;?>"
            uomioid="<?php echo $item->Ref_DonViTinh;?>"
            itemcode="<?php echo $item->MaSanPham;?>"
            itemname="<?php echo $item->TenSanPham;?>"
            uom="<?php echo $item->DonViTinh;?>"
            min="0"
            qty="1"
            inv="<?php  echo Qss_Lib_Util::formatNumber(($item->SoLuongHC)) ;?>"
            req="<?php echo Qss_Lib_Util::formatNumber($temYeuCau);?>"
            order="0"
            in="0"
            stock=""
            stockIOID="">
        <?php echo $item->MaSanPham;?> - <?php echo $item->TenSanPham;?> (TK: <?php  echo Qss_Lib_Util::formatNumber(($item->SoLuongHC)) ;?> <?php echo $item->DonViTinh;?>)
    </option>
<?php endforeach;?>