<script>
        function printPreview() {
                var ngaybd = $('#start').val();
                var ngaykt = $('#end').val();
                var msg = '';
                
                msg += common_checkEmpty(ngaybd, '<?php echo $this->_translate(2);?>');
                msg += common_checkEmpty(ngaykt, '<?php echo $this->_translate(3);?>');
                msg += common_compareStartAndEnd(ngaybd, ngaykt);
                var warning = common_dateWarning('D', '<?php echo json_encode(Qss_Lib_Extra_Const::$DATE_LIMIT);?>', ngaybd, ngaykt);
                var next = true;

                if (msg != '')
                {
                        qssAjax.alert(msg);
                        return;
                }
                else
                {
					if(warning)
					{
						qssAjax.confirm(warning,function(){
							loadModule();
						});
					}
					else
					{
						loadModule();				
					}
                }


        }
		
		function loadModule()
		{
			var url = sz_BaseUrl + '/static/m781/show';
			var data = $('#report').serialize();
			qssAjax.getHtml(url, data, function(jreturn) {
				$('#print-area').html(jreturn);
				removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
			});		
		}
</script>
<div class="clear"></div>
<div id="view">
	<div class="line-hr">
		<span><?php echo $this->_translate(1) ?> </span>
	</div>
	<form id="report" method="post" action="static/m781/show">
		<table class="detail">
			<tr>
				<th width="20%" class="report-param-label">
					<!-- Ngày bắt đầu --> <?php echo $this->_translate(2) ?></th>
				<td><?php echo $this->views->Report->Datepicker('start',
        '01-' . date('m') . '-' . date('Y')); ?><span class="bold red">(*)</span>
				</td>
			</tr>
			<tr>
				<th width="20%" class="report-param-label">
					<!-- Ngày kết thúc --> <?php echo $this->_translate(3) ?></th>
				<td><?php echo $this->views->Report->Datepicker('end',
				date('t-m-Y')); ?><span class="bold red">(*)</span></td>
			</tr>
		</table>
	</form>
	<p>
	
	
	<hr>
	<?php echo $this->views->Report->PrintToolbar(); ?>
	<div id="print-content">
		<div id="print-area"></div>
	</div>
</div>
