<?php
/**
 *
 * @Author: thinh.tuan
 * @Date: 7/24/2015
 * @Time: 11:30 AMư
 * @Description: Phiếu xuất vật tư theo mẫu của Sà Lan - POS
 */
$excel_col      = array_flip(Qss_Lib_Const::$EXCEL_COLUMN);
$bg             = Qss_Lib_Extra_Const::REPORT_EXCEL_THEAD_COLOR;
$row            = 2;
$totalColumn    = 6;
$colWidths      = array(2, 6, 8, 3, 4, 4);
$excelColWidths = Qss_Lib_Report::convertPxColumnWidthToExcelWidth($colWidths);
$autoFit        = Qss_Lib_Report::changeWidthToFitScreen($colWidths);
$stt            = 0;
$docDate        = $this->params->NgayChungTu;
$microDocDate   = strtotime($docDate);
$totalMoney     = 0;
$common         = new Qss_Model_Extra_Extra();
?>

<form id="excel" method="post" action="/report/index/excel" target="new">
    <input type="hidden" id="content" name="content" value="">
</form>

<div
    class="portrait">
    <excel
        orientation="<?php echo Qss_Lib_Extra_Const::REPORT_ORIENTATION_PORTRAIT;?>"
        font-name="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_FONT_NAME;?>"
        font-size="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_FONT_SIZE;?>"
        margin-left="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_MARGIN_LEFT;?>"
        margin-right="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_MARGIN_RIGHT;?>"
        margin-top="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_MARGIN_TOP;?>"
        margin-bottom="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_MARGIN_BOTTOM;?>" />

    <!-- REPORT TITLE -->
    <div id="head_print">
        <?php echo $this->views->Common->Portrait() ?>
        <?php echo $this->views->Common->Legal() ?>


        <?php $row++ ?>

        <div class=" clearfix">
            <div class="fl">
                <xls row="<?php echo $row ?>" column="<?php echo $excel_col[1] ?>"
                     column-merge="<?php echo $excel_col[2] ?>"
                     wrap-text="1"  h-align="left"
                     v-align="center"> <b><?php echo $this->_translate(31);?>:</b> <?php echo @$this->workcenter->Ten;?></xls>
            </div>

            <div class="fr">
                <xls row="<?php echo $row ?>" column="<?php echo $excel_col[6] ?>"
                     wrap-text="1"  h-align="left"
                     v-align="center"> <b><?php echo $this->_translate(22);?>:</b> <?php echo $this->params->SoChungTu;?></xls>

            </div>
        </div>
        <!--        <p>&nbsp;</p>-->
        <br/>

        <?php $row++ ?>


        <center>
            <h2>
                <xls row="<?php echo $row ?>" column="A"
                     column-merge="<?php echo $excel_col[$totalColumn] ?>"
                     font-size="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_TITLE_FONT_SIZE;?>"
                     wrap-text="1" bold="1" h-align="center" v-align="center"> <?php echo mb_convert_case($this->_translate(1), MB_CASE_UPPER, "UTF-8");?></xls>
            </h2>
        </center>
        <?php $row++ ?>

        <center>
            <xls row="<?php echo $row ?>" column="A"
                 column-merge="<?php echo $excel_col[$totalColumn] ?>"
                 font-size="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_TITLE_FONT_SIZE;?>"
                 wrap-text="1" bold="1" h-align="center" v-align="center"> <?php echo $this->_translate(2);?>
                <?php echo date('d', $microDocDate);?> <?php echo $this->_translate(3);?>
                <?php echo date('m', $microDocDate);?> <?php echo $this->_translate(4);?>
                <?php echo date('Y', $microDocDate);?></xls>
        </center>
        <?php $row++ ?>
    </div>
    <!-- end div#head_print -->


    <!-- REPORT DATA -->
    <div id="container">
        <table cellpadding="0" cellspacing="0" border="0" class="" style="">
            <tr>
                <!-- Người giao dịch -->
                <td class="left" style="width: 18%"><xls row="<?php echo $row?>"
                                                         column="<?php echo $excel_col[2]?>" wrap-text="1" v-align="top"
                                                         h-align="left" border="0"> <b><?php echo $this->_translate(5);?>:</b></xls>
                </td>

                <td class="left"><xls row="<?php echo $row?>"
                                      column="<?php echo $excel_col[3]?>"
                                      column-merge="<?php echo $excel_col[5]?>" wrap-text="1"
                                      v-align="top" h-align="left" border="0"> <?php echo $this->params->NguoiNhan;?></xls>
                </td>
            </tr>
            <?php $row++ ?>

            <tr>
                <!-- Đơn vị -->
                <td class="left"><xls row="<?php echo $row?>"
                                      column="<?php echo $excel_col[2]?>" wrap-text="1" v-align="top"
                                      h-align="left" border="0"> <b><?php echo $this->_translate(6);?>:</b></xls>
                </td>

                <td class="left"><xls row="<?php echo $row?>"
                                      column="<?php echo $excel_col[3]?>"
                                      column-merge="<?php echo $excel_col[5]?>" wrap-text="1"
                                      v-align="top" h-align="left" border="0"> <?php echo @$this->partner->TenDoiTac;?></xls>
                </td>

            </tr>
            <?php $row++ ?>


            <?php /*
            <tr>
                <!-- Địa chỉ -->
                <td class="left"><xls row="<?php echo $row?>"
                                      column="<?php echo $excel_col[2]?>" wrap-text="1" v-align="top"
                                      h-align="left" border="0"> <b><?php echo $this->_translate(18);?>:</b></xls>
                </td>

                <td class="left"><xls row="<?php echo $row?>"
                                      column="<?php echo $excel_col[3]?>"
                                      column-merge="<?php echo $excel_col[5]?>" wrap-text="1"
                                      v-align="top" h-align="left" border="0"> <?php echo @$this->partner->DiaChi;?></xls>
                </td>

            </tr>
            <?php $row++ ?>
            */?>



            <tr>
                <!-- Lý do -->
                <td class="left"><xls row="<?php echo $row?>"
                                      column="<?php echo $excel_col[2]?>" wrap-text="1" v-align="top"
                                      h-align="left" border="0"> <b><?php echo $this->_translate(7);?>:</b></xls>
                </td>

                <td class="left"><xls row="<?php echo $row?>"
                                      column="<?php echo $excel_col[3]?>"
                                      column-merge="<?php echo $excel_col[5]?>" wrap-text="1"
                                      v-align="top" h-align="left" border="0"> <?php echo $this->params->MoTa;?></xls>
                </td>

            </tr>
            <?php $row++ ?>

            <?php /*
            <tr>
                <!-- Kho -->
                <td class="left"><xls row="<?php echo $row?>"
                                      column="<?php echo $excel_col[2]?>" wrap-text="1" v-align="top"
                                      h-align="left" border="0"> <b><?php echo $this->_translate(21);?>:</b></xls>
                </td>

                <td class="left"><xls row="<?php echo $row?>"
                                      column="<?php echo $excel_col[3]?>"
                                      column-merge="<?php echo $excel_col[5]?>" wrap-text="1"
                                      v-align="top" h-align="left" border="0"> <?php echo $this->params->Kho;?></xls>
                </td>

            </tr>
            <?php $row++ ?>

            <tr>
                <!-- Dạng nhập -->
                <td class="left"><xls row="<?php echo $row?>"
                                      column="<?php echo $excel_col[2]?>" wrap-text="1" v-align="top"
                                      h-align="left" border="0"> <b><?php echo $this->_translate(30);?>:</b></xls>
                </td>

                <td class="left"><xls row="<?php echo $row?>"
                                      column="<?php echo $excel_col[3]?>"
                                      column-merge="<?php echo $excel_col[5]?>" wrap-text="1"
                                      v-align="top" h-align="left" border="0"> <?php echo $this->params->LoaiNhapKho;?></xls>
                </td>

            </tr>
            <?php $row++ ?>
            <?php */?>
        </table>
        <?php $row++ ?>
        <br />

        <table cellpadding="0" cellspacing="0" border="0" class="border"
               style="">
            <!-- COLUMN TITLE -->
            <tr class="bggrey">
                <?php $begin = 0;?>
                <!-- STT -->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px"><xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
                        v-align="center" h-align="center" border="1" repeat="1" bold="1"
                        bgcolor="<?php echo $bg;?>"> <?php echo $this->_translate(9)?></xls>
                </th>

                <!-- Mã vật tư -->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px"><xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
                        v-align="center" h-align="center" border="1" repeat="1" bold="1"
                        bgcolor="<?php echo $bg;?>"> <?php echo $this->_translate(10)?></xls>
                </th>

                <!-- Tên vật tư -->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px"><xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
                        v-align="center" h-align="center" border="1" repeat="1" bold="1"
                        bgcolor="<?php echo $bg;?>"> <?php echo $this->_translate(11)?></xls>
                </th>

                <!-- ĐVT -->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px"><xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
                        v-align="center" h-align="center" border="1" repeat="1" bold="1"
                        bgcolor="<?php echo $bg;?>"> <?php echo $this->_translate(12)?></xls>
                </th>

                <!-- Số lượng -->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px"><xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
                        v-align="center" h-align="center" border="1" repeat="1" bold="1"
                        bgcolor="<?php echo $bg;?>"> <?php echo $this->_translate(13)?></xls>
                </th>

                <!-- Ghi chú-->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px"><xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
                        v-align="center" h-align="center" border="1" repeat="1" bold="1"
                        bgcolor="<?php echo $bg;?>"> <?php echo $this->_translate(33)?></xls>
                </th>

                <?php /*
                <!-- Giá-->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px"><xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
                        v-align="center" h-align="center" border="1" repeat="1" bold="1"
                        bgcolor="<?php echo $bg;?>"> <?php echo $this->_translate(19)?></xls>
                </th>

                <!-- Tiền -->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px"><xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
                        v-align="center" h-align="center" border="1" repeat="1" bold="1"
                        bgcolor="<?php echo $bg;?>"> <?php echo $this->_translate(20)?></xls>
                </th>
                */?>
            </tr>
            <?php $row++;?>

            <!-- COLUMN DATA -->
            <?php foreach($this->params->ODanhSachXuatKho as $item): // In bao cao?>
                <tr>
                    <?php $begin = 0;?>
                    <?php $totalMoney += $item->ThanhTien;?>

                    <!-- STT -->
                    <td class="center"><xls row="<?php echo $row?>"
                                            column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
                                            v-align="top" h-align="center" border="1"> <?php echo ++$stt?></xls>
                    </td>

                    <!-- Mã vật tư -->
                    <td class="left"><xls row="<?php echo $row?>"
                                          column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
                                          v-align="top" h-align="left" border="1"> <?php echo $item->MaSP;?></xls>
                    </td>

                    <!-- Tên vật tư -->
                    <td class="left"><xls row="<?php echo $row?>"
                                          column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
                                          v-align="top" h-align="left" border="1"> <?php echo $item->TenSP?></xls>
                    </td>

                    <!-- ĐVT -->
                    <td class="left"><xls row="<?php echo $row?>"
                                          column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
                                          v-align="top" h-align="left" border="1"> <?php echo $item->DonViTinh?></xls>
                    </td>

                    <!-- Số lượng -->
                    <td class="right"><xls row="<?php echo $row?>"
                                           column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
                                           v-align="top" h-align="right" border="1"> <?php echo $item->SoLuong?></xls>
                    </td>

                    <!-- Ghi Chu -->
                    <td class="right"><xls row="<?php echo $row?>"
                                           column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
                                           v-align="top" h-align="right" border="1"> <?php echo $item->MoTa;?></xls>
                    </td>

                    <?php /*
                    <!-- Gia -->
                    <td class="right"><xls row="<?php echo $row?>"
                                           column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
                                           v-align="top" h-align="right" border="1"> <?php echo Qss_Lib_Util::formatMoney($item->DonGia);?></xls>
                    </td>

                    <!-- Thanh tien -->
                    <td class="right"><xls row="<?php echo $row?>"
                                           column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
                                           v-align="top" h-align="right" border="1"> <?php echo Qss_Lib_Util::formatMoney($item->ThanhTien);?></xls>
                    </td>
                    */?>
                </tr>
                <?php $row++;?>
            <?php endforeach; // Ket thuc in bao cao?>

            <?php /*
            <tr>
                <!-- Tong tien bang so -->
                <td class="right" colspan="<?php echo $totalColumn;?>"><xls
                        row="<?php echo $row?>" column="<?php echo $excel_col[1]?>"
                        column-merge="<?php echo $excel_col[$totalColumn]?>" wrap-text="1"
                        v-align="top" h-align="right" border="1"> <b><?php echo $this->_translate(23);?>:</b>
                        <?php echo Qss_Lib_Util::formatMoney($totalMoney);?></xls></td>
            </tr>
            <?php $row++;?>
            */?>

        </table>
        <!-- end table.border -->
        <br />
        <?php $row++;?>

        <?php /*
        <table cellpadding="0" cellspacing="0" border="0">
            <tr>
                <!-- Tong tien bang chu -->
                <td class="right" colspan="<?php echo $totalColumn;?>"><xls
                        row="<?php echo $row?>" column="<?php echo $excel_col[1]?>"
                        column-merge="<?php echo $excel_col[$totalColumn]?>" wrap-text="1"
                        v-align="top" h-align="right" border="0"> <b><?php echo $this->_translate(24);?>:</b>
                        <?php echo Qss_Lib_Util::VndText($totalMoney/1000);?></xls></td>
            </tr>
            <?php $row++;?>
        </table>
        <?php $row++;?>
        <br />
        */?>
        <br />

        <?php /*
        <table cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td style="width: 60%;"></td>
                <!-- Ngay.... thang ... nam -->
                <td style="width: 40%;" class="center"><xls row="<?php echo $row?>"
                                                            column="<?php echo $excel_col[5]?>"
                                                            column-merge="<?php echo $excel_col[$totalColumn]?>" wrap-text="1"
                                                            v-align="top" h-align="center" border="0"> <?php echo $this->_translate(2);?>
                        ..... <?php echo $this->_translate(3);?> ..... <?php echo $this->_translate(4);?>
                        ..... </xls>
                </td>
            </tr>
            <?php $row++;?>
        </table>
        */?>

        <?php /*
        <table cellpadding="0" cellspacing="0" border="0">
            <tr>
                <!-- KẾ TOÁN -->
                <td class="center" style="width: 20%;"><xls row="<?php echo $row?>"
                                                            column="<?php echo $excel_col[1]?>"
                                                            column-merge="<?php echo $excel_col[2]?>" wrap-text="1"
                                                            v-align="top" h-align="center" border="0"> <b><?php echo $this->_translate(25);?>
                        </b></xls>
                </td>

                <!-- THỦ KHO -->
                <td class="center" style="width: 20%;"><xls row="<?php echo $row?>"
                                                            column="<?php echo $excel_col[3]?>" wrap-text="1" v-align="top"
                                                            h-align="center" border="0"> <b><?php echo $this->_translate(26);?>
                        </b></xls>
                </td>

                <!-- NGƯỜI NHẬN -->
                <td class="center" style="width: 20%;"><xls row="<?php echo $row?>"
                                                            column="<?php echo $excel_col[4]?>" wrap-text="1" v-align="top"
                                                            h-align="center" border="0"> <b><?php echo $this->_translate(27);?>
                        </b></xls>
                </td>


                <!-- PHÒNG KHĐT -->
                <td class="center" style="width: 20%;"><xls row="<?php echo $row?>"
                                                            column="<?php echo $excel_col[5]?>" wrap-text="1" v-align="top"
                                                            h-align="center" border="0"> <b><?php echo $this->_translate(28);?>
                        </b></xls>
                </td>

                <!-- GIÁM ĐỐC -->
                <td class="center" style="width: 20%;"><xls row="<?php echo $row?>"
                                                            column="<?php echo $excel_col[6]?>"
                                                            column-merge="<?php echo $excel_col[7]?>" wrap-text="1"
                                                            v-align="top" h-align="center" border="0"> <b><?php echo $this->_translate(29);?>
                        </b></xls>
                </td>

            </tr>
        </table>
        */?>

        <table cellpadding="0" cellspacing="0" border="0">
            <tr>
                <!-- Lãnh đạo đơn vị sản xuất -->
                <td class="center" style="width: 33%;"><xls row="<?php echo $row?>"
                                                            column="<?php echo $excel_col[1]?>"
                                                            column-merge="<?php echo $excel_col[2]?>" wrap-text="1"
                                                            bold="1"
                                                            v-align="top" h-align="center" border="0"> <b><?php echo $this->_translate(15);?>
                        </b></xls>
                </td>

                <!-- Người nhận -->
                <td class="center" style="width: 33%;">
                    <xls row="<?php echo $row?>"
                         column="<?php echo $excel_col[3]?>"
                         column-merge="<?php echo $excel_col[4]?>"
                         wrap-text="1" v-align="top"
                         h-align="center" border="0" bold="1"> <b><?php echo $this->_translate(32);?>
                        </b></xls>
                </td>

                <!-- Người giao -->
                <td class="center" style="width: 33%;">
                    <xls row="<?php echo $row?>"
                         column="<?php echo $excel_col[6]?>"
                         wrap-text="1" v-align="top"
                         h-align="center" border="0" bold="1"> <b><?php echo $this->_translate(34);?>
                        </b></xls>
                </td>
            </tr>
        </table>

    </div>
    <!-- end div#container -->
</div>
<!-- END REPORT -->
