<script>
    var m506_button_getbyrequest = {
        show : function() {
            var data = $('#M506_Get_By_Request_Form').serialize();
            var url = sz_BaseUrl + '/button/m506/getbyrequest/show';
            qssAjax.getHtml(url, data, function(jreturn) {
                $('#M506_Get_By_Request_ShowTable').html(jreturn);
            });
        },
        save : function() {
            var data = $('#M506_Get_By_Request_Form').serialize();
            var url  = sz_BaseUrl + '/button/m506/getbyrequest/save';
            qssAjax.call(url, data, function(jreturn){
                $('#qss_trace').dialog('close');
                rowObjectSearch('<?php echo $this->ifid;?>','<?php echo $this->deptid;?>','ODanhSachXuatKho');
            }, function(jreturn){
                qssAjax.alert(jreturn.message);
            });
        }
    };

    $(document).ready(function () {
        m506_button_getbyrequest.show();

        $('#M506_Get_By_Request_Item').on("keyup keypress", function(e) {
            var code = e.keyCode || e.which;
            if (code  == 13) {
                e.preventDefault();
                m506_button_getbyrequest.show();
                return false;
            }
        });

        $('#M506_Get_By_Request_PageNo').on("keyup keypress", function(e) {
            var code = e.keyCode || e.which;
            if (code  == 13) {
                e.preventDefault();
                m506_button_getbyrequest.show();
                return false;
            }
        });

    });
</script>

<form id="M506_Get_By_Request_Form">
    <input type="hidden" name="M506_Get_By_Request_IFID" id="M506_Get_By_Request_IFID" value="<?php echo $this->ifid;?>"/>

    <div class="popup_wrap">
        <div class="popup_header">


            <table class="detail" border="0" cellpadding="0" cellspacing="0">
                <tr>
                    <td class="left">
                        <div class="overflow">
                            <div class="fl">
                                <input type="text" id="M506_Get_By_Request_Item" name="M506_Get_By_Request_Item" value="" placeholder="Tìm mã & tên mặt hàng"/>

                                <input type="checkbox" id="M506_Get_By_Request_Tool" name="M506_Get_By_Request_Tool" value="1" />
                                <label for="M506_Get_By_Request_Tool">Công cụ</label>
                                <input type="checkbox" id="M506_Get_By_Request_Material" name="M506_Get_By_Request_Material" value="1" />
                                <label for="M506_Get_By_Request_Material">Vật tư</label>
                                <button type="button" class="btn" onclick="m506_button_getbyrequest.show()"> Xem </button>
                            </div>

                            <div class="fr">
                                Trang:
                                <a title="Trang trước" class="bold" href="#"
                                   onclick="$('#M506_Get_By_Request_PageNo').val('1'); m506_button_getbyrequest.show();"
                                   id="M506_Get_By_Request_Prev">&lt;&lt;</a>
                                <input id="M506_Get_By_Request_PageNo" name="M506_Get_By_Request_PageNo"
                                       onchange="m506_button_getbyrequest.show();"
                                       style="width: 20px !important; text-align: center;" value="1">/
                                <span id="M506_Get_By_Request_TotalPage">1</span>
                                <a title="Trang sau" class="bold" href="#"
                                   onclick="$('#M506_Get_By_Request_PageNo').val('1'); m506_button_getbyrequest.show();"
                                   id="M506_Get_By_Request_Next">&gt;&gt;</a>
                                Hiển thị: <select id="M506_Get_By_Request_Display"
                                                  name="M506_Get_By_Request_Display" style="width: 100;"
                                                  onchange="m506_button_getbyrequest.show();;">
                                    <option value="5">5</option>
                                    <option value="10">10</option>
                                    <option selected="" value="20">20</option>
                                    <option value="50">50</option>
                                    <option value="100">100</option>
                                </select>
                                Tổng số: <span id="M506_Get_By_Request_Total">1</span>
                            </div>
                        </div>
                    </td>
                </tr>
            </table>

        </div>

        <div class="popup_content">
            <div id="M506_Get_By_Request_ShowTable">

            </div>

            <div class="overflow" style="padding-top: 10px;">
                <div class="fr">
                    <button type="button" class="btn" onclick="m506_button_getbyrequest.save()"> Cập nhật </button>
                </div>
            </div>
        </div>
    </div>
</form>