<script>
    function printPreview() {
        var url = sz_BaseUrl + '/static/m160/show';
        var data = $('#report').serialize();
//        var eq = $('#equip').val();
//        var msg   = '';
//
//
//        msg += common_checkEmpty(eq, '<?php //echo $this->_translate(7) ?>//');
//
//        if(msg != '')
//        {
//            qssAjax.alert(msg);
//            return;
//        }
//        else
//        {
//            qssAjax.getHtml(url, data, function(jreturn) {
//                $('#print-area').html(jreturn);
//                removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
//            });
//        }

        qssAjax.getHtml(url, data, function(jreturn) {
            $('#print-area').html(jreturn);
            removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
        });
    }
</script>

<div class="clear"></div>
<div id="view">
    <div class="line-hr">
        <span><?php echo Qss_Lib_System::getReportTitle('M160');?> </span>
    </div>
    <form id="report" method="get" action="/static/m160/show">
        <table class="detail">


            <tr>
                <th width="20%" class="report-param-label"><?php echo $this->_translate(8) ?>
                </th>
                <td><?php
                    $id = 'location';
                    $getFields = array('num' => 3,
                        'objects' => array('OKhuVuc' => array(
                            'id' => 'IOID'
                        , 'display1' => 'MaKhuVuc'
                        , 'display2' => 'Ten')));
                    ?> <?php echo $this->views->Report->ComboBox($id, $getFields); ?>

            </tr>

            <?php if (Qss_Lib_System::fieldActive('ODanhSachThietBi', 'TrungTamChiPhi')): ?>
                <tr>
                    <th width="20%" class="report-param-label"><?php echo $this->_translate(2) ?>
                    </th>
                    <td><?php
                        $id = 'costcenter';
                        $getFields = array('num' => 3,
                            'objects' => array('OTrungTamChiPhi' => array(
                                'id' => 'IOID'
                            , 'display1' => 'Ten'
                            , 'display1' => 'Ma')));
                        ?> <?php echo $this->views->Report->ComboBox($id, $getFields); ?>
                    </td>
                </tr>
            <?php endif; ?>


            <tr>
                <th width="20%" class="report-param-label"><?php echo $this->_translate(5) ?>
                </th>
                <td><?php
                    $id = 'group';
                    $getFields = array('num' => 2,
                        'objects' => array('ONhomThietBi' => array(
                            'id' => 'IOID'
                        , 'display1' => 'LoaiThietBi'
                        )));
                    ?> <?php echo $this->views->Report->ComboBox($id, $getFields); ?>

            </tr>


            <?php if (Qss_Lib_Extra::checkFieldExists('ODanhSachThietBi', 'Ref_LoaiThietBi')): ?>
                <tr>
                    <th width="20%" class="report-param-label"><?php echo $this->_translate(6) ?>
                    </th>
                    <td><?php
                        $id = 'type';
                        $getFields = array('num' => 2,
                            'objects' => array('OLoaiThietBi' => array(
                                'id' => 'IOID'
                            , 'display1' => 'TenLoai'
                            )));
                        ?> <?php echo $this->views->Report->ComboBox($id, $getFields); ?>

                </tr>
            <?php endif; ?>

            <tr>
                <th width="20%" class="report-param-label"><?php echo $this->_translate(7) ?>
                </th>
                <td><?php
                    $id = array('id'=>'equip', 'require'=>0, 'size'=>300);
                    $getDataObject = array('ODanhSachThietBi' => array('MaThietBi', 'LoaiThietBi'));
                    //,'OKhuVuc'=>array('MaKhuVuc','Ten')
                    $getFields = array('num' => 2,
                        'objects' => array('ODanhSachThietBi' => array(
                            'id' => 'IOID'
                        , 'display1' => 'MaThietBi'
                        , 'display2' => 'LoaiThietBi')));
                    $getLookupFilter = array(array('id' => 'group'
                    , 'refField' => array('ODanhSachThietBi' => 'Ref_NhomThietBi') // Nhom TB
                    , 'required' => 0)
                    , array('id' => 'type'
                        , 'refField' => array('ODanhSachThietBi' => 'Ref_LoaiThietBi') // Loai TB
                        , 'required' => 0)
                    , array('id' => 'costcenter'
                        , 'refField' => array('ODanhSachThietBi' => 'Ref_TrungTamChiPhi') // TT Chi phi
                        , 'required' => 0)
                    , array('id' => 'location'
                        , 'refField' => array('ODanhSachThietBi' => 'Ref_MaKhuVuc') // Ma Khu vuc
                        , 'required' => 0));
                    ?> <?php echo $this->views->Report->ListBox($id, $getDataObject, $getFields, $getLookupFilter); ?>
                </td>
            </tr>
        </table>
    </form>
    <p>


    <hr>
    <?php echo $this->views->Report->PrintToolbar(); ?>
    <div id="print-content">
        <div id="print-area"></div>
    </div>
</div>
