<?php
$excel_col        = array_flip(Qss_Lib_Const::$EXCEL_COLUMN);
$bg               = Qss_Lib_Extra_Const::REPORT_EXCEL_THEAD_COLOR;
$row              = 2;
$colWidths        = array(1,3,2,3,1,1.2,1,3,1);
$totalColumn      = count($colWidths);
$excelColWidths   = Qss_Lib_Report::convertPxColumnWidthToExcelWidth($colWidths);
$htmlColWidths    = Qss_Lib_Report::changeWidthToFitScreen($colWidths);
$stt              = 0;
$oldEquipIOID     = '';
?>

<form id="excel" method="post" action="/report/index/excel" target="new">
    <input type="hidden" id="content" name="content" value="">
</form>


<div class="portrait">
    <excel
        orientation="<?php echo Qss_Lib_Extra_Const::REPORT_ORIENTATION_PORTRAIT;?>"
        font-name="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_FONT_NAME;?>"
        font-size="11"
        margin-left="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_MARGIN_LEFT;?>"
        margin-right="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_MARGIN_RIGHT;?>"
        margin-top="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_MARGIN_TOP;?>"
        margin-bottom="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_MARGIN_BOTTOM;?>"  />

    <!-- REPORT TITLE -->
    <div id="head_print">
        <?php  echo $this->views->Common->Portrait(); ?>

        <?php $row++ ?>
        <center>
            <h2>
                <xls
                    row="<?php echo $row ?>"
                    column="A"
                    column-merge="<?php echo $excel_col[$totalColumn] ?>"
                    font-size="16"

                    bold="1"
                    h-align="center"
                    v-align="center" ><!-- #1 -->BÁO CÁO PHỤ TÙNG THIẾT BỊ<!-- #1 --> <?php // echo $this->_translate(100); ?>  </xls>
            </h2>
        </center>
    </div><!-- end div#head_print -->
    <?php $row++ ?>
    <?php $row++ ?>

    <div id="container">
        <table class="border"  border="1" cellspacing="0" cellpadding="0" style="width: 100%; table-layout:inherit !important;" >

            <!-- REPORT TITLE -->
            <?php $begin = 0;?>
            <tr class="bggrey">

                <!-- TT -->
                <th class="center" style="width: <?php echo $htmlColWidths[$begin];?>px">
                    <xls
                        width="<?php echo $excelColWidths[$begin];?>"
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"> <!-- #1 -->STT<!-- #1 --> <?php // echo $this->_translate(100); ?></xls>
                </th>

                <!-- Bộ phận  -->
                <th class="center" style="width: <?php echo $htmlColWidths[$begin];?>px">
                    <xls
                        width="<?php echo $excelColWidths[$begin];?>"
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><!-- #1 -->Bộ phận <!-- #1 --> <?php // echo $this->_translate(101); ?></xls>
                </th>

                <!-- Mã  -->
                <th class="center" style="width: <?php echo $htmlColWidths[$begin];?>px">
                    <xls
                        width="<?php echo $excelColWidths[$begin];?>"
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><!-- #1 -->Mã <!-- #1 --> <?php // echo $this->_translate(101); ?></xls>
                </th>

                <!-- Tên -->
                <th class="center"  style="width: <?php echo $htmlColWidths[$begin];?>px">
                    <xls
                        width="<?php echo $excelColWidths[$begin];?>"
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><!-- #1 -->Tên <!-- #1 --> <?php // echo $this->_translate(102); ?> <?php echo $this->month;;?></xls>

                </th>

                <!-- Đơn vị tính -->
                <th class="center"  style="width: <?php echo $htmlColWidths[$begin];?>px">
                    <xls
                        width="<?php echo $excelColWidths[$begin];?>"
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><!-- #1 -->Đơn vị tính <!-- #1 --> <?php // echo $this->_translate(102); ?></xls>

                </th>

                <!-- SL Chuẩn -->
                <th class="center"  style="width: <?php echo $htmlColWidths[$begin];?>px">
                    <xls
                        width="<?php echo $excelColWidths[$begin];?>"
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><!-- #1 -->SL Chuẩn<!-- #1 --> <?php // echo $this->_translate(102); ?></xls>

                </th>


                <!-- SL Hiện có -->
                <th class="center"  style="width: <?php echo $htmlColWidths[$begin];?>px">
                    <xls
                        width="<?php echo $excelColWidths[$begin];?>"
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><!-- #1 -->SL Hiện có  <!-- #1 --> <?php // echo $this->_translate(102); ?> </xls>

                </th>

                <!-- Thay thế -->
                <th class="center"  style="width: <?php echo $htmlColWidths[$begin];?>px">
                    <xls
                        width="<?php echo $excelColWidths[$begin];?>"
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><!-- #1 -->Thay thế  <!-- #1 --> <?php // echo $this->_translate(102); ?></xls>

                </th>

                <!-- Số ngày cảnh báo -->
                <th class="center"  style="width: <?php echo $htmlColWidths[$begin];?>px">
                    <xls
                        width="<?php echo $excelColWidths[$begin];?>"
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"><!-- #1 -->Số ngày cảnh báo <!-- #1 --> <?php // echo $this->_translate(102); ?></xls>

                </th>

            </tr>
            <?php $row++;?>

            <!----------------------------------------------------------------------------------------------------------------->

            <!-- REPORT DATA -->
            <?php foreach($this->report as $item):?>
                <!-- IN THIET BI -->
                <?php if($oldEquipIOID != $item->EquipIOID):?>
                    <?php $stt = 0; // reset ?>
                    <tr>
                        <td colspan="<?php echo $totalColumn;?>" class="left bold">
                            <xls row="<?php echo $row?>"
                                 column="<?php echo $excel_col[1]?>"
                                 column-merge="<?php echo $excel_col[$totalColumn]?>"
                                 wrap-text="1"
                                 h-align="left"
                                 v-align="center"
                                 border="1"
                                 font-size="11"
                                 bold="1"> <?php echo "{$item->TenThietBi} ({$item->MaThietBi})";?> </xls>
                        </td>
                    </tr>
                    <?php $row++;?>
                <?php endif;?>

                <?php $begin = 0;?>
                <!-- IN PHU TUNG -->
                <tr>
                    <!-- TT -->
                    <td class="center">
                        <xls
                            row="<?php echo $row?>"
                            column="<?php echo $excel_col[++$begin]?>"
                            wrap-text="1"
                            v-align="top"
                            h-align="center"
                            font-size="11"
                            border="1"><?php echo ++$stt;?></xls>
                    </td>

                    <!-- Bộ phận  -->
                    <?php $componentTextAlign = $item->ComponentIOID?"left":"center";?>
                    <td class="<?php echo $componentTextAlign;?>">
                        <xls
                            row="<?php echo $row?>"
                            column="<?php echo $excel_col[++$begin]?>"
                            wrap-text="1"
                            v-align="top"
                            h-align="<?php echo $componentTextAlign;?>"
                            border="1"><?php echo $item->ComponentIOID?"{$item->BoPhan} ({$item->ViTri})":"-";?></xls>
                    </td>

                    <!-- Mã  -->
                    <td class="left">
                        <xls
                            row="<?php echo $row?>"
                            column="<?php echo $excel_col[++$begin]?>"
                            wrap-text="1"
                            v-align="top"
                            h-align="left"
                            border="1"><?php echo $item->MaSP;?></xls>
                    </td>

                    <!-- Tên -->
                    <td class="left">
                        <xls
                            row="<?php echo $row?>"
                            column="<?php echo $excel_col[++$begin]?>"
                            wrap-text="1"
                            v-align="top"
                            h-align="left"
                            border="1"><?php echo $item->TenSP;?></xls>
                    </td>

                    <!-- Đơn vị tính -->
                    <td class="left">
                        <xls
                            row="<?php echo $row?>"
                            column="<?php echo $excel_col[++$begin]?>"
                            wrap-text="1"
                            v-align="top"
                            h-align="left"
                            border="1"><?php echo $item->DonViTinh;?></xls>
                    </td>

                    <!-- SL Chuẩn -->
                    <td class="right">
                        <xls
                            row="<?php echo $row?>"
                            column="<?php echo $excel_col[++$begin]?>"
                            wrap-text="1"
                            v-align="top"
                            h-align="right"
                            border="1"><?php echo Qss_Lib_Util::formatNumber($item->SoLuongChuan);?></xls>
                    </td>


                    <!-- SL Hiện có -->
                    <td class="right">
                        <xls
                            row="<?php echo $row?>"
                            column="<?php echo $excel_col[++$begin]?>"
                            wrap-text="1"
                            v-align="top"
                            h-align="right"
                            border="1"><?php echo Qss_Lib_Util::formatNumber($item->SoLuongHC);?></xls>
                    </td>

                    <!-- Thay thế -->
                    <td class="left">
                        <xls
                            row="<?php echo $row?>"
                            column="<?php echo $excel_col[++$begin]?>"
                            wrap-text="1"
                            v-align="top"
                            h-align="left"
                            border="1"><?php echo trim($item->ThayThe, ',');?></xls>
                    </td>

                    <!-- Số ngày cảnh báo -->
                    <td class="right">
                        <xls
                            row="<?php echo $row?>"
                            column="<?php echo $excel_col[++$begin]?>"
                            wrap-text="1"
                            v-align="top"
                            h-align="right"
                            border="1"><?php echo Qss_Lib_Util::formatNumber($item->SoNgayCanhBao);?></xls>
                    </td>
                </tr>
                <?php $row++;?>

                <?php $oldEquipIOID = $item->EquipIOID;?>
            <?php endforeach; // In thông tin báo cáo <Nội dung chính> ?>
        </table>
    </div><!-- End #container -->
</div><!-- End report -->
