<script>    
function printPreview(){
    common_selectDialBox('equips'); // Danh dau toan bo dialbox, PrintToolbar
    var url  = sz_BaseUrl + '/static/m794/show';
    var data = $('#report').serialize();
    var msg  = '';

    msg += common_checkEmpty($('#eq_ioid').val(), '<?php echo $this->_translate(4)?>');

    if(msg)
    {
        qssAjax.alert(msg);
        return;
    }
    else
    {
        qssAjax.getHtml(url, data, function(jreturn) {
            $('#print-area').html(jreturn);
            removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
        });        
    }
}

</script>


<div class="clear"></div>
<div id="view">
	<div class="line-hr">
		<span><?php echo $this->_translate(1) ?> </span>
	</div>
	<form id="report" method="get" action="/static/m794/show">
		<table class="detail">
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(7) ?>
				</th>
				<td>
                    <?php echo $this->views->Report->DialBox('equips', $this->eqsDialbox);?>
				</td>
			</tr>
		</table>
	</form>
	<p>

	<hr>
	<?php $hidden = array('pdf'=>true, 'pdfdoc'=>true, 'excel'=>true, 'exceldoc'=>true);?>
	<?php echo $this->views->Report->PrintToolbar($hidden);?>
	<div id="print-content">
		<div id="print-area"></div>
	</div>
</div>