<style>
#print-content th, #print-content td, #print-html th, #print-html td, .default_size {
    font-size: 13px;
}
</style>

<?php
$excel_col      = array_flip(Qss_Lib_Const::$EXCEL_COLUMN);
$bg             = "#EEEEEE";
$row            = 2;
$totalColumn    = 15;
$colWidths      = array(47, 82, 82, 74, 59, 69, 98, 82, 134, 42, 51, 114, 48, 55, 193);
$excelColWidths = Qss_Lib_Report::convertPxColumnWidthToExcelWidth($colWidths);
$autoFit        = Qss_Lib_Report::changeWidthToFitScreen($colWidths);

// General Fit
$totalGenCol    = 4;
$genColWidths   = array(30, 20, 20, 20);
$genAutoFit     = Qss_Lib_Report::changeWidthToFitScreen($genColWidths);

// Param Fit
$paramNo        = 0;
$totalParamCol  = 5;
$paramColWidths = array(47, 366, 98, 216, 503);
$paramAutoFit   = Qss_Lib_Report::changeWidthToFitScreen($paramColWidths);

// Sparepart & Document
$SDNo        = 0;
$totalSDCol  = 6;
$SDColWidths = array(47, 366, 98, 82, 176, 461);
$SDAutoFit   = Qss_Lib_Report::changeWidthToFitScreen($SDColWidths);

// Work order history
$woHistoryNo        = 0;
$totalWoHistoryCol  = 8;
$woHistoryColWidths = array(47, 366, 98, 82, 82, 98, 98, 290);
$woHistoryAutoFit   = Qss_Lib_Report::changeWidthToFitScreen($woHistoryColWidths);

$status = '';

switch(@(int)$this->eq->TrangThai)
{
    case 0: $status = $this->_translate(71); break; // Hoạt động
    case 1: $status = $this->_translate(72); break; // Thanh lý
    case 2: $status = $this->_translate(73); break; // Mất
    case 3: $status = $this->_translate(74); break; // Hỏng
}

?>

<form id="excel" method="post" action="/report/index/excel" target="new">
    <input type="hidden" id="content" name="content" value="">
</form>

<div class="landscape">
    <excel 
        orientation="landscape" 
        font-name="Arial" 
        font-size="9" 
        margin-left="0.5" 
        margin-right="0.5" 
        margin-top="0.75" 
        margin-bottom="0.75"/>
    
    <!-- REPORT TITLE -->
	<div id="head_print">
		<?php echo $this->views->Common->Landscape() ?>
        <?php echo $this->views->Common->Legal() ?>
		<center>
		    <h2>
			<xls
			    row="<?php echo $row ?>"
			    column="A"
			    column-merge="<?php echo $excel_col[$totalColumn] ?>"
			    font-size="12"
			    wrap-text="1"
                bold="1"
			    h-align="center"
			    v-align="center" ><?php echo $this->_translate(1);?>  </xls>
		    </h2>
		</center>
	</div><!-- end div#head_print -->
	<?php $row++ ?>
    <?php $row++;?>
    <br/>

    <!-- REPORT DATA -->
    <div id="container">
        
        <!-- General -->
        <table cellpadding="0" cellspacing="0" border="0" class="" style="">
            <?php $begin = 0;?>
            <?php $genBegin = 0;?>
            <tr>
                <!-- Ten thiet bi -->
                <td class="left" 
                    style="width: <?php echo $genAutoFit[$genBegin++];?>px" 
                    valign="top">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin] ?>" 
                        column-merge="<?php echo $excel_col[($begin + 3)] ?>" 
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo $this->_translate(39);?>: <?php echo $this->eq->TenThietBi;?></xls>
                </td>      
                <?php $begin += 3;?>
                
                <!-- Ma so -->
                <td class="left" 
                    style="width: <?php echo $genAutoFit[$genBegin++];?>px" valign="top">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin] ?>" 
                        column-merge="<?php echo $excel_col[($begin + 3)] ?>" 
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo $this->_translate(2);?>: <?php echo $this->eq->MaThietBi;?></xls>
                </td>   
                <?php $begin += 3;?>
                
                <!-- Serial -->
                <td class="left" 
                    style="width: <?php echo $genAutoFit[$genBegin++];?>px" 
                    valign="top">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin] ?>" 
                        column-merge="<?php echo $excel_col[($begin + 3)] ?>" 
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo $this->_translate(40);?>: <?php echo $this->eq->Serial;?></xls>
                </td>   
                <?php $begin += 3;?>
                
                <!-- Model -->
                <td class="left" 
                    style="width: <?php echo $genAutoFit[$genBegin++];?>px" 
                    valign="top">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin] ?>" 
                        column-merge="<?php echo $excel_col[($begin + 2)] ?>" 
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo $this->_translate(5);?>: <?php echo $this->eq->Model;?></xls>
                </td>    
                <?php $begin += 2;?>
            </tr>
            <?php $row++;?>
            
            <?php $begin = 0;?>
            <?php $genBegin = 0;?>
            <tr>
                <!-- Nhà sản xuất -->
                <td class="left" 
                    style="width: <?php echo $genAutoFit[$genBegin++];?>px" valign="top">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin] ?>" 
                        column-merge="<?php echo $excel_col[($begin + 3)] ?>" 
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo $this->_translate(6);?>: <?php echo $this->eq->XuatXu;?></xls>
                </td>    
                <?php $begin += 3;?>
                
                <!-- Nam san xuat -->
                <td class="left" 
                    style="width: <?php echo $genAutoFit[$genBegin++];?>px" valign="top">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin] ?>" 
                        column-merge="<?php echo $excel_col[($begin + 3)] ?>" 
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo $this->_translate(7);?>: <?php echo $this->eq->NamSanXuat;?></xls>
                </td>   
                <?php $begin += 3;?>
                
                <!-- Ngày đưa vào sử dụng -->
                <td class="left" 
                    style="width: <?php echo $genAutoFit[$genBegin++];?>px" valign="top">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin] ?>" 
                        column-merge="<?php echo $excel_col[($begin + 3)] ?>" 
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo $this->_translate(8);?>: <?php echo Qss_Lib_Date::mysqltodisplay($this->eq->NgayDuaVaoSuDung);?></xls>
                </td> 
                <?php $begin += 3;?>
                
                <!-- Đơn vị quản lý -->
                <?php
                    $workcenters = array();
                    foreach($this->workcenter as $wc)
                    {
                        if($wc->IOID &&  !in_array($wc->Ten, $workcenters))
                        $workcenters[] = $wc->Ten;
                    }
                ?>
                <td class="left" 
                    style="width: <?php echo $genAutoFit[$genBegin++];?>px" valign="top">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin] ?>" 
                        column-merge="<?php echo $excel_col[($begin + 2)] ?>"  
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo $this->_translate(17);?>: <?php echo implode(' , ', $workcenters);?></xls>
                </td>    
                <?php $begin += 2;?>
            </tr>
            <?php $row++;?>

            <?php $begin = 0;?>
            <?php $genBegin = 0;?>
            <tr>
                <!-- Trang thai -->
                <td class="left"
                    style="width: <?php echo $genAutoFit[$genBegin++];?>px" valign="top">
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin] ?>"
                        column-merge="<?php echo $excel_col[($begin + 3)] ?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="left"
                        border="0" ><?php echo $this->_translate(70);?>: <?php echo $status;?></xls>
                </td>
                <?php $begin += 3;?>

                <td class="left"
                    style="width: <?php echo $genAutoFit[$genBegin++];?>px" valign="top">
                    &nbsp;
                </td>

                <td class="left"
                    style="width: <?php echo $genAutoFit[$genBegin++];?>px" valign="top">
                    &nbsp;
                </td>

                <td class="left"
                    style="width: <?php echo $genAutoFit[$genBegin++];?>px" valign="top">
                    &nbsp;
                </td>

            </tr>
            <?php $row++;?>
        </table><!-- end table.border -->
        <?php $row++;?> 
        <!--------------------------------------------------------------------->
        
        <div class="left bold default_size">
            <br/>
            <xls 
                row="<?php echo $row?>" 
                column="<?php echo $excel_col[1];?>" 
                column-merge="<?php echo $excel_col[$totalColumn]; ?>"
                wrap-text="1"  
                v-align="center" 
                h-align="left" 
                border="0" 
                repeat="1" 
                bold="1" 
                ><?php echo $this->_translate(47)?></xls>        </div>
        <?php $row++;?>  
        <br/>
        
        <!-- Params -->
        <table cellpadding="0" cellspacing="0" border="0" class="border" style="">
            <!-- COLUMN TITLE -->
            <tr class="bggrey">
                <?php $begin = 0;?>
                <?php $paramBegin = 0;?>
                <!-- STT -->
                <th class="center" 
                    style="width:<?php echo $paramAutoFit[$paramBegin++];?>px">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>" 
                        wrap-text="1"  
                        v-align="center" 
                        h-align="center" 
                        border="0" 
                        repeat="1" 
                        bold="1" 
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(41)?></xls>
                </th>
                
                <!-- Thong so ky thuat -->
                <th class="center" 
                    style="width:<?php echo $paramAutoFit[$paramBegin++];?>px">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>" 
                        column-merge="<?php echo $excel_col[($begin + 4)] ?>"
                        wrap-text="1"  
                        v-align="center" 
                        h-align="center" 
                        border="0" 
                        repeat="1" 
                        bold="1" 
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(42)?></xls>
                </th> 
                <?php $begin += 4;?>
                
                <!-- Don vi -->
                <th class="center" 
                    style="width:<?php echo $paramAutoFit[$paramBegin++];?>px">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>" 
                        wrap-text="1"  
                        v-align="center" 
                        h-align="center" 
                        border="0" 
                        repeat="1" 
                        bold="1" 
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(43)?></xls>
                </th>     
                
                <!-- Gia tri -->
                <th class="center" 
                    style="width:<?php echo $paramAutoFit[$paramBegin++];?>px">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>" 
                        column-merge="<?php echo $excel_col[($begin + 1)] ?>"
                        wrap-text="1"  
                        v-align="center" 
                        h-align="center" 
                        border="0" 
                        repeat="1" 
                        bold="1" 
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(44)?></xls>
                </th>    
                <?php $begin += 1;?>
                
                <!-- Ghi chu -->
                <th class="center" 
                    style="width:<?php echo $paramAutoFit[$paramBegin++];?>px">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>" 
                        column-merge="<?php echo $excel_col[($begin + 5)] ?>"
                        wrap-text="1"  
                        v-align="center" 
                        h-align="center" 
                        border="0" 
                        repeat="1" 
                        bold="1" 
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(45)?></xls>
                </th>          
                <?php $begin += 5;?>
            </tr>
            <?php $row++;?>
            
            <!-- COLUMN DATA -->
            <?php foreach($this->eqParams as $data): // In bao cao?>
            
            <?php $begin = 0;?>
            <tr>
                <!-- stt -->
                <td class="left" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo ++$paramNo;?></xls>
                </td>       
                
                <!-- Thong so ky thuat -->
                <td class="left" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        column-merge="<?php echo $excel_col[($begin + 4)] ?>"
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo $data->ChiSo;?></xls>
                </td>  
                <?php $begin += 4;?>
                
                <!-- Don vi -->
                <td class="left" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo $data->DonViTinh;?></xls>
                </td>
                
                <!-- GiaTri -->
                <td class="right" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        column-merge="<?php echo $excel_col[($begin + 1)] ?>"
                        wrap-text="1"  
                        v-align="top" 
                        h-align="right" 
                        border="0" ><?php echo $data->GiaTri;?></xls>
                </td>  
                <?php $begin += 1;?>
                
                <!-- Ghi chu -->
                <td class="left" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        column-merge="<?php echo $excel_col[($begin + 5)] ?>"
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo '';?></xls>
                </td>   
                <?php $begin += 5;?>
            </tr>
            <?php $row++;?>
            <?php endforeach; // Ket thuc in bao cao?>
        </table><!-- end table.border -->
        <!--------------------------------------------------------------------->
        
        <div class="left bold default_size">
            <br/>
            <xls 
                row="<?php echo $row?>" 
                column="<?php echo $excel_col[1]?>" 
                column-merge="<?php echo $excel_col[$totalColumn] ?>"
                wrap-text="1"  
                v-align="center" 
                h-align="left" 
                border="0" 
                repeat="1" 
                bold="1" 
                ><?php echo $this->_translate(48)?></xls>        
        </div>
        <?php $row++;?>       
        <br/>
        
        <!-- Sparepart & document -->
        <table cellpadding="0" cellspacing="0" border="0" class="border" style="">
            <!-- COLUMN TITLE -->
            <tr class="bggrey">
                <?php $begin = 0;?>
                <?php $SDBegin = 0;?>
                <!-- stt -->
                <th class="center" 
                    style="width:<?php echo $SDAutoFit[$SDBegin++];?>px">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>" 
                        wrap-text="1"  
                        v-align="center" 
                        h-align="center" 
                        border="0" 
                        repeat="1" 
                        bold="1" 
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(46)?></xls>
                </th>
                
                <!-- Ten phu tung tai lieu -->
                <th class="center" 
                    style="width:<?php echo $SDAutoFit[$SDBegin++];?>px">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>" 
                        column-merge="<?php echo $excel_col[($begin + 4)] ?>"
                        wrap-text="1"  
                        v-align="center" 
                        h-align="center" 
                        border="0" 
                        repeat="1" 
                        bold="1" 
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(49)?></xls>
                </th>    
                <?php $begin += 4;?>
                
                <!-- Quy cach -->
                <th class="center" 
                    style="width:<?php echo $SDAutoFit[$SDBegin++];?>px">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>" 
                        wrap-text="1"  
                        v-align="center" 
                        h-align="center" 
                        border="0" 
                        repeat="1" 
                        bold="1" 
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(50)?></xls>
                </th>          
                
                <!-- So Luong -->
                <th class="center" 
                    style="width:<?php echo $SDAutoFit[$SDBegin++];?>px">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>" 
                        wrap-text="1"  
                        v-align="center" 
                        h-align="center" 
                        border="0" 
                        repeat="1" 
                        bold="1" 
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(51)?></xls>
                </th>     
                
                <!-- Ma so -->
                <th class="center" 
                    style="width:<?php echo $SDAutoFit[$SDBegin++];?>px">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>" 
                        column-merge="<?php echo $excel_col[($begin + 1)] ?>"
                        wrap-text="1"  
                        v-align="center" 
                        h-align="center" 
                        border="0" 
                        repeat="1" 
                        bold="1" 
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(52)?></xls>
                </th>  
                <?php $begin += 1;?>
                
                <!-- Ghi chu -->
                <th class="center" 
                    style="width:<?php echo $SDAutoFit[$SDBegin++];?>px">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>" 
                        column-merge="<?php echo $excel_col[($begin + 4)] ?>"
                        wrap-text="1"  
                        v-align="center" 
                        h-align="center" 
                        border="0" 
                        repeat="1" 
                        bold="1" 
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(53)?></xls>
                </th>  
                <?php $begin += 4;?>
            </tr>
            <?php $row++;?>
            
            <?php if(count($this->sparepart)):?>
            <tr>
                <!-- Phu tung -->
                <th class="left" colspan="<?php echo $totalSDCol;?>">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[1]?>"  
                        column-merge="<?php echo $excel_col[$totalColumn]?>" 
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo $this->_translate(68)?></xls>
                </th> 
            </tr>
            <?php $row++;?>
            <?php endif;?>
            
            <!-- COLUMN DATA -->
            <?php foreach($this->sparepart as $data): // In bao cao?>
            <?php $begin = 0;?>
            <tr>
                <!-- stt -->
                <td class="left" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo ++$SDNo?></xls>
                </td>                    
                
                <!-- Ten phu tung tai lieu -->
                <td class="left" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        column-merge="<?php echo $excel_col[($begin + 4)] ?>"
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo $data->TenSP;?></xls>
                </td>                   
                <?php $begin += 4;?>
                
                <!-- Quy cach -->
                <td class="left" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo $data->DacTinhKyThuat;?></xls>
                </td>                  
                
                <!-- So Luong -->
                <td class="right" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        wrap-text="1"  
                        v-align="top" 
                        h-align="right" 
                        border="0" ><?php echo $data->SoLuongHC;?></xls>
                </td>                   
                
                <!-- Ma so -->
                <td class="left" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        column-merge="<?php echo $excel_col[($begin + 1)] ?>"
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo $data->MaSP;?></xls>
                </td>                 
                <?php $begin += 1;?>
                
                <!-- Ghi chu -->
                <td class="left" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        column-merge="<?php echo $excel_col[($begin + 4)] ?>"
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo '';?></xls>
                </td>                   
                <?php $begin += 4;?>                
            </tr>
            <?php $row++;?>
            <?php endforeach; // Ket thuc in bao cao?>
            
            <?php if(count($this->document)):?>
            <tr>
                <!-- Tai lieu -->
                <th class="left"  colspan="<?php echo $totalSDCol;?>">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[1]?>"  
                        column-merge="<?php echo $excel_col[$totalColumn]?>" 
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo $this->_translate(69)?></xls>
                </th> 
            </tr>
            <?php $row++;?>
            <?php endif;?>     
            
            <?php foreach($this->document as $data): // In bao cao?>
            <?php $begin = 0;?>
            <tr>
                <!-- stt -->
                <td class="left" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo ++$SDNo?></xls>
                </td>                    
                
                <!-- Ten phu tung tai lieu -->
                <td class="left" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        column-merge="<?php echo $excel_col[($begin + 4)] ?>"
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo $data->Type;?></xls>
                </td>                   
                <?php $begin += 4;?>
                
                <!-- Quy cach -->
                <td class="left" >
                    &nbsp;
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ></xls>
                </td>                  
                
                <!-- So Luong -->
                <td class="right" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        wrap-text="1"  
                        v-align="top" 
                        h-align="right" 
                        border="0" ><?php echo $data->Total;?></xls>
                </td>                   
                
                <!-- Ma so -->
                <td class="left" >
                    &nbsp;
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        column-merge="<?php echo $excel_col[($begin + 1)] ?>"
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ></xls>
                </td>                 
                <?php $begin += 1;?>
                
                <!-- Ghi chu -->
                <td class="left" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        column-merge="<?php echo $excel_col[($begin + 4)] ?>"
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo '';?></xls>
                </td>                   
                <?php $begin += 4;?>                
            </tr>
            <?php $row++;?>
            <?php endforeach; // Ket thuc in bao cao?>            
        </table><!-- end table.border -->  
        <!--------------------------------------------------------------------->
        
        <!-- Ngay... thang ... nam -->
        <div class="left default_size" 
             style="text-align:right; margin-right:100px;">
            <br/>
            <xls 
                row="<?php echo $row?>" 
                column="L" 
                column-merge="<?php echo $excel_col[$totalColumn] ?>"
                wrap-text="1"  
                v-align="center" 
                h-align="center" 
                border="0" 
                repeat="1" 
                bold="1" 
                ><?php echo $this->_translate(63)?>......<?php echo $this->_translate(64)?>......<?php echo $this->_translate(65)?>......</xls>        
        </div>
        <?php $row++;?> 
        
        <div class="default_size bold overflow clearfix">
            <!-- Nguoi lap -->
            <div class="fl"  style="padding-left: 138px;">
                <xls 
                    row="<?php echo $row?>" 
                    column="B" 
                    column-merge="D"
                    wrap-text="1"  
                    v-align="center" 
                    h-align="center" 
                    border="0" 
                    repeat="1" 
                    bold="1" 
                    ><?php echo $this->_translate(67)?></xls>      
            </div>
            
            <!-- Don vi quan ly -->
            <div class="fr" style="padding-right: 138px;">
                <xls 
                    row="<?php echo $row?>" 
                    column="L" 
                    column-merge="<?php echo $excel_col[$totalColumn] ?>"
                    wrap-text="1"  
                    v-align="center" 
                    h-align="center" 
                    border="0" 
                    repeat="1" 
                    bold="1" 
                    ><?php echo $this->_translate(66)?></xls>      
            </div>            
        </div>
        <?php $row++;?>  
        <?php $row++;?> 
        <?php $row++;?> 
        <br/>
        <br/>
        <br/>
        
        <!--------------------------------------------------------------------->
        
        <div class="left bold default_size">
            <br/>
            <xls 
                row="<?php echo $row?>" 
                column="<?php echo $excel_col[1]?>" 
                column-merge="<?php echo $excel_col[$totalColumn] ?>"
                wrap-text="1"  
                v-align="center" 
                h-align="left" 
                border="0" 
                repeat="1" 
                bold="1" 
                ><?php echo $this->_translate(54)?></xls>        
        </div>
        <?php $row++;?>  
        <br/>
        
        <!-- Work Order History -->
        <table cellpadding="0" cellspacing="0" border="0" class="border" style="">
            <!-- COLUMN TITLE -->
            <tr class="bggrey">
                <?php $begin = 0;?>
                <?php $woHistoryBegin = 0;?>
                <!-- stt -->
                <th class="center" 
                    style="width:<?php echo $woHistoryAutoFit[$woHistoryBegin++];?>px">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>" 
                        wrap-text="1"  
                        v-align="center" 
                        h-align="center" 
                        border="0" 
                        repeat="1" 
                        bold="1" 
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(55)?></xls>
                </th>
                
                <!-- Noi dung bao duong sua chua -->
                <th class="center" 
                    style="width:<?php echo $woHistoryAutoFit[$woHistoryBegin++];?>px">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>" 
                        column-merge="<?php echo $excel_col[($begin + 4)] ?>"
                        wrap-text="1"  
                        v-align="center" 
                        h-align="center" 
                        border="0" 
                        repeat="1" 
                        bold="1" 
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(56)?></xls>
                </th>    
                <?php $begin +=  4;?>
                
                <!-- Ngay bao duong -->
                <th class="center" 
                    style="width:<?php echo $woHistoryAutoFit[$woHistoryBegin++];?>px">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>" 
                        wrap-text="1"  
                        v-align="center" 
                        h-align="center" 
                        border="0" 
                        repeat="1" 
                        bold="1" 
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(57)?></xls>
                </th>    
                
                <!-- Trong KH -->
                <th class="center" 
                    style="width:<?php echo $woHistoryAutoFit[$woHistoryBegin++];?>px">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>" 
                        wrap-text="1"  
                        v-align="center" 
                        h-align="center" 
                        border="0" 
                        repeat="1" 
                        bold="1" 
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(58)?></xls>
                </th>               
                
                <!-- Ngoai KH -->
                <th class="center" 
                    style="width:<?php echo $woHistoryAutoFit[$woHistoryBegin++];?>px">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>" 
                        wrap-text="1"  
                        v-align="center" 
                        h-align="center" 
                        border="0" 
                        repeat="1" 
                        bold="1" 
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(59)?></xls>
                </th>        
                
                <!-- Nguoi thuc hien -->
                <th class="center" 
                    style="width:<?php echo $woHistoryAutoFit[$woHistoryBegin++];?>px">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>" 
                        column-merge="<?php echo $excel_col[($begin + 1)] ?>"
                        wrap-text="1"  
                        v-align="center" 
                        h-align="center" 
                        border="0" 
                        repeat="1" 
                        bold="1" 
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(60)?></xls>
                </th>   
                <?php $begin += 1;?>
                
                <!-- Nguoi kiem tra -->
                <th class="center" 
                    style="width:<?php echo $woHistoryAutoFit[$woHistoryBegin++];?>px">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>" 
                        wrap-text="1"  
                        v-align="center" 
                        h-align="center" 
                        border="0" 
                        repeat="1" 
                        bold="1" 
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(61)?></xls>
                </th>   
                
                <!-- Ghi chu -->
                <th class="center" 
                    style="width:<?php echo $woHistoryAutoFit[$woHistoryBegin++];?>px">
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>" 
                        column-merge="<?php echo $excel_col[($begin + 2)] ?>"
                        wrap-text="1"  
                        v-align="center" 
                        h-align="center" 
                        border="0" 
                        repeat="1" 
                        bold="1" 
                        bgcolor="<?php echo $bg;?>"><?php echo $this->_translate(62)?></xls>
                </th>       
                <?php $begin += 2;?>
                
                
            </tr>
            <?php $row++;?>

            
            <!-- COLUMN DATA -->
            <?php foreach($this->history as $data): // In bao cao?>

            <?php
                //echo '<pre>'; print_r($data); die;
                $trongKH = ($data['Info']['TypeCode'] == Qss_Lib_Extra_Const::MAINT_TYPE_PREVENTIVE)?'x':'';
                $ngoaiKH = ($data['Info']['TypeCode'] == Qss_Lib_Extra_Const::MAINT_TYPE_PREVENTIVE)?'':'x';

                $ghiChu =  '';

                if($data['Info']['StatusNo'] == 5) // Tinh trang huy
                {
                    $ghiChu .= "Hủy phiếu bảo trì ". $data['Info']['DocNo'] . ": ".$data['Info']['Des'] ;
                }
            ?>

            <?php
                /*
                $workDetail = '';

                if(isset($data['Component']) && count($data['Component']))
                {
                    foreach($data['Component'] as $com1)
                    {
                        if(isset($com1['Work']) && count($com1['Work']))
                        {
                            foreach($com1['Work'] as $work1)
                            {
                                $workDetail .= $work1['MoTa'];
                                $workDetail .= '<br/>';
                            }
                        }
                    }
                }
                */
            ?>


            <?php if(isset($data['Component']) && count($data['Component'])):?>

            <?php foreach($data['Component'] as $com1):?>

            <?php if(isset($com1['Work']) && count($com1['Work'])):?>

            <?php foreach($com1['Work'] as $work1):?>

            
            
            <?php $begin = 0;?>
            <tr>
                <!-- stt -->
                <td class="left" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo ++$woHistoryNo?></xls>
                </td>                  

                <!-- Noi dung bao duong sua chua -->
                <td class="left" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        column-merge="<?php echo $excel_col[($begin + 4)] ?>"
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo $work1['MoTa'];?></xls>
                </td>                   
                <?php $begin +=  4;?>
                
                <!-- Ngay bao duong -->
                <td class="left" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo Qss_Lib_Date::mysqltodisplay(@$data['Info']['SDate']);?></xls>
                </td>                   
                
                <!-- Trong KH -->
                <td class="center" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        wrap-text="1"  
                        v-align="top" 
                        h-align="center" 
                        border="0" ><?php echo $trongKH;?></xls>
                </td>                   
                
                <!-- Ngoai KH -->
                <td class="center" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        wrap-text="1"  
                        v-align="top" 
                        h-align="center" 
                        border="0" ><?php echo $ngoaiKH;?></xls>
                </td>                 
                
                <!-- Nguoi thuc hien -->
                <td class="left" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        column-merge="<?php echo $excel_col[($begin + 1)] ?>"
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo $work1['NguoiThucHien']?></xls>
                </td>                  
                <?php $begin += 1;?>
                
                <!-- Nguoi kiem tra -->
                <td class="left" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo @$data['Info']['Employee']?></xls>
                </td>                  
                
                <!-- Ghi chu -->
                <td class="left" >
                    <xls 
                        row="<?php echo $row?>" 
                        column="<?php echo $excel_col[++$begin]?>"  
                        column-merge="<?php echo $excel_col[($begin + 2)] ?>"
                        wrap-text="1"  
                        v-align="top" 
                        h-align="left" 
                        border="0" ><?php echo $ghiChu?></xls>
                </td>                   
                <?php $begin += 2;?>                
            </tr>
            <?php $row++;?>

            <?php endforeach;?>

            <?php endif;?>


            <?php endforeach;?>

            <?php endif;?>


            <?php endforeach; // Ket thuc in bao cao?>
        </table><!-- end table.border -->        
    </div><!-- end div#container -->
</div><!-- END REPORT -->


