<script type="text/javascript">
$(document).ready(function() {
	$(".ui_box").hide();
	$(".ui_box").first().fadeIn();
	$(".tabs-menu a").click(function(event) {
	        event.preventDefault();
	        $(this).parent().addClass("active");
	        $(this).parent().siblings().removeClass("active");
	        var tab = $(this).attr("href");
	        $(".ui_box").not(tab).css("display", "none");
	        $(tab).find('fieldset').show();
	        $(tab).fadeIn();
	});
	$.cookie('form_selected','<?php echo $this->form->i_IFID?>',{path:'/'});
	$(function() {
		// Display the first tab content
		// Set the first tab as start tab onload: if you want to set no start tab
		// comment it.
		// DisplayTabContent(10);
		// get index of the clicked navigation item in the list
		$("ul.tabslist_sub li a").click(
				function() {
					// if animation has finished: meaning size()==0 then allow for
					// other clicks
					var ifid = $('#ifid').val();
					var deptid = $('#deptid').val();
					if(ifid && ifid != 0){
						if ($('div.tabscontent_container > div.tabcontent:animated')
								.size() == 0) {
							$("ul.tabslist_sub li").removeClass('current');
							var $listItem = $(this).parent().addClass('current');
							var objid = $(this).parent().attr('objid');
							var fieldid = $(this).parent().attr('fieldid');
							var vid = $(this).parent().attr('vid');
							var ioid = $(this).parent().attr('ioid');
							var html = $(this).children().html();
							if (ifid && deptid && objid) {
								DisplayTabContent(ifid, deptid, objid, fieldid, vid,
										ioid, html);
							}
						}	
					}
				});
		return false;
	});
});
</script>
<div id="qss_form">
	<input type="hidden" id="fid"
		value="<?php echo $this->form->FormCode?>"> <input type="hidden"
		id="ifid" value="<?php echo $this->form->i_IFID?>"> <input
		type="hidden" id="deptid"
		value="<?php echo $this->form->i_DepartmentID?>">
		<?php echo $this->formdetail;?>
</div>
<div
	id="qss_trace" title="<?php echo $this->form->sz_Name?>"></div>
