<script>
function printPreview(){
	var start = $('#start').val();
	var end   = $('#end').val();
	var eq    = $('#eqOrLoc').val();
	var msg    = '';
	var warning = common_dateWarning('D', '<?php echo json_encode(Qss_Lib_Extra_Const::$DATE_LIMIT);?>', start, end);
	var next    = true;
	
	msg += common_checkEmpty(start, '<?php echo $this->_translate(5);?>');
	msg += common_checkEmpty(end, '<?php echo $this->_translate(6);?>');
	msg += common_compareStartAndEnd(start, end);

	
	if(msg)
	{
		qssAjax.alert(msg);
		return;
	}
	else
	{
		if(warning)
		{
			qssAjax.confirm(warning,function(){
				loadModule();
			});
		}
		else
		{
			loadModule();
		}	
	}  
}

function loadModule()
{
	var url = sz_BaseUrl + '/static/m730/show';
	var data = $('#report').serialize();
	qssAjax.getHtml(url, data, function(jreturn) {
			$('#print-area').html(jreturn);
			removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
	});
}
</script>

<div class="clear"></div>
<div id="view">
	<div class="line-hr">
		<span><?php echo $this->_translate(4)?> </span>
	</div>
	<form id="report" method="get" action="/static/m730/show">
		<table class="detail">

			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(5)?>:</th>
				<td><?php echo $this->views->Report->Datepicker('start', '01-'.date('m-Y'));?><span
					class="bold red">(*)</span></td>
			</tr>
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(6)?>:</th>
				<td><?php echo $this->views->Report->Datepicker('end', date('d-m-Y'));?><span
					class="bold red">(*)</span></td>
			</tr>
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(20)?>
				</th>
				<td><?php
				$id            = 'location';
				$getFields     = array('num'=>3,
                                       'objects'=>array('OKhuVuc'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'MaKhuVuc'
                                                            ,'display2'=>'Ten') ));
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
				</td>
			</tr>


			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(22)?>
				</th>
				<td><?php
				$id            = 'group';
				$getFields     = array('num'=>3,
                                       'objects'=>array('ONhomThietBi'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'LoaiThietBi'
                                                            ) ));
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
				</td>
			</tr>


			<?php if(Qss_Lib_Extra::checkFieldExists('ODanhSachThietBi', 'Ref_LoaiThietBi')):?>
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(21)?>
				</th>
				<td><?php
				$id            = 'type';
				$getFields     = array('num'=>2,
                                       'objects'=>array('OLoaiThietBi'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'TenLoai'
                                                            )) );
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
			
			</tr>
			<?php endif;?>
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(7)?>:</th>
				<td><?php
				$id            = 'eqOrLoc';
				$getDataObject = array('ODanhSachThietBi'=>array('MaThietBi', 'LoaiThietBi'));
				//,'OKhuVuc'=>array('MaKhuVuc','Ten')
				$getFields     = array('num'=>2,
                                       'objects'=>array('ODanhSachThietBi'=>array(
                                                                'id'=>'IOID'
                                                                ,'display1'=>'MaThietBi'
                                                                ,'display2'=>'LoaiThietBi')) );
                                                                $getLookupFilter = array(array('id'=>'group'
                                                                , 'refField'=> array('ODanhSachThietBi'=>'Ref_NhomThietBi')
                                                                , 'required'=>0)
                                                                , array('id'=>'type'
                                                                , 'refField'=> array('ODanhSachThietBi'=>'Ref_LoaiThietBi')
                                                                , 'required'=>0));
                                                                //                ,'OKhuVuc'=>array('id'=>'IOID'
                                                                //                ,'display1'=>'MaKhuVuc'
                                                                //                ,'display2'=>'Ten'))
                                                                ?> <?php echo $this->views->Report->ListBox($id, $getDataObject,$getFields, $getLookupFilter);?>
				</td>
			</tr>
		</table>
	</form>
	<p>
	
	
	<hr>
	<?php echo $this->views->Report->PrintToolbar();?>
	<div id="print-content">
		<div id="print-area"></div>
	</div>
</div>
