<?php
$excel_col = array_flip(Qss_Lib_Const::$EXCEL_COLUMN);
$bg = Qss_Lib_Extra_Const::REPORT_EXCEL_THEAD_COLOR;
$row = 2;
$totalColumn = 3;
$colWidths = array(2, 1, 1);
$excelColWidths = Qss_Lib_Report::convertPxColumnWidthToExcelWidth($colWidths);
$autoFit = Qss_Lib_Report::changeWidthToFitScreen($colWidths);
?>

<!-- Xuat ra Exel -->
<form id="excel" method="post" action="/report/index/excel" target="new">
    <input type="hidden" id="content" name="content" value="">
</form>

<div
    class="portrait">
    <excel
        orientation="<?php echo Qss_Lib_Extra_Const::REPORT_ORIENTATION_PORTRAIT; ?>"
        font-name="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_FONT_NAME; ?>"
        font-size="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_FONT_SIZE; ?>"
        margin-left="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_MARGIN_LEFT; ?>"
        margin-right="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_MARGIN_RIGHT; ?>"
        margin-top="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_MARGIN_TOP; ?>"
        margin-bottom="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_MARGIN_BOTTOM; ?>" />

    <!-- REPORT TITLE -->
    <div id="head_print">
        <?php echo $this->views->Common->Portrait() ?>
        <?php //echo $this->views->Common->Legal() ?>
        <!-- Tiêu đề Báo Cáo Hư Hỏng/Mất Thiết Bị-->
        <center>
            <h2>
                <xls row="<?php echo $row ?>" column="A"
                     column-merge="<?php echo $excel_col[$totalColumn] ?>"
                     font-size="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_TITLE_FONT_SIZE; ?>"
                     wrap-text="1" bold="1" h-align="center" v-align="center"> Bảng nhập dữ liệu đo
                </xls>
            </h2>
        </center>
    </div>
    <!-- end div#head_print -->
    <?php $row++ ?>

    <!-- REPORT DATA -->
    <div id="container">
        <table cellpadding="0" cellspacing="0" border="0" class="border_table_none_bg" style="">
            <tr class="">
                <?php $begin = 0; ?>

                <!-- Thiết bị -->
                <th class="center" style="width:<?php echo $autoFit[$begin]; ?>px">
                    <xls row="<?php echo $row ?>"
                         width="<?php echo $excelColWidths[$begin]; ?>"
                         column="<?php echo $excel_col[++$begin] ?>"
                         wrap-text="1"
                         v-align="center"
                         h-align="center"
                         bold="1"
                         border="1"
                         repeat="1">Thiết bị</xls>
                </th>

                <th class="center" style="width:<?php echo $autoFit[$begin]; ?>px">
                    <xls row="<?php echo $row ?>"
                         width="<?php echo $excelColWidths[$begin]; ?>"
                         column="<?php echo $excel_col[++$begin] ?>"
                         wrap-text="1"
                         v-align="center"
                         h-align="center"
                         bold="1"
                         border="1"
                         repeat="1">Đơn vị tính</xls>
                </th>


                <!-- Số hoạt động -->
                <th class="center" style="width:<?php echo $autoFit[$begin]; ?>px">
                    <xls row="<?php echo $row ?>"
                         width="<?php echo $excelColWidths[$begin]; ?>"
                         column="<?php echo $excel_col[++$begin] ?>"
                         wrap-text="1"
                         v-align="center"
                         h-align="center"
                         bold="1"
                         border="1"
                         repeat="1">Kết quả</xls>
                </th>
            </tr>
            <?php $row++; ?>

            <?php foreach($this->tree as $locioid=>$detail):?>
                <?php $begin = 0; ?>
                <tr class="bggrey">
                    <th colspan="<?php echo $totalColumn;?>" class="left bold tree_level_<?php echo $detail['Level'];?> ">
                        <xls row="<?php echo $row ?>"
                             column="A"
                             column-merge="<?php echo $excel_col[$totalColumn] ?>"
                             wrap-text="1"
                             v-align="center"
                             h-align="left"
                             bold="1"
                             border="1"><?php echo $detail['Name'].' - '.$detail['Code'];?></xls>
                    </th>
                </tr>
                <?php $row++; ?>

                <?php if($locioid > 0 && isset($detail['Equip'])):?>
                    <?php $ik=0;?>

                    <?php foreach($detail['Equip'] as $item):?>
                        <?php $begin = 0; ?>
                        <?php $ik++; ?>
                        <tr class="<?php echo ($ik%2 == 0)?'bglightblue':'';?>" >
                            <td class="left tree_level_<?php echo ($detail['Level'] + 1);?>">

                                <label>
                                    <xls row="<?php echo $row ?>"
                                         column="<?php echo $excel_col[++$begin] ?>"
                                         wrap-text="1"
                                         v-align="center"
                                         h-align="left"
                                         border="1"><?php echo $item->TenThietBi.' - '.$item->MaThietBi;?> <?php if($item->BoPhan):?> - <?php echo $item->BoPhan;?><?php endif;?></xls>
                                </label>
                            </td>

                            <td class="center">
                                <xls row="<?php echo $row ?>"
                                     column="<?php echo $excel_col[++$begin] ?>"
                                     wrap-text="1"
                                     v-align="center"
                                     h-align="left"
                                     border="1"><?php echo $item->DonViTinh;?></xls>
                            </td>

                            <td class="right">
                                <xls row="<?php echo $row ?>"
                                     column="<?php echo $excel_col[++$begin] ?>"
                                     wrap-text="1"
                                     v-align="center"
                                     h-align="right"
                                     border="1"></xls>
                            </td>
                        </tr>
                        <?php $row++; ?>
                    <?php endforeach;?>
                <?php endif;?>


            <?php endforeach;?>

        </table>
    </div>
    <!-- end div#container -->
</div>
<!-- END REPORT -->
