<?php
$cost      = $this->cost;
$costArray = array();
$i         = '';
$solar     = new Qss_Model_Calendar_Solar();


foreach ($cost as $c)
{
	$c->ThanhTien = round($c->ThanhTien/1000,0)*1000;
	switch($this->period)
	{
		case 'D':
			$i = $c->Ngay;
			break;
		case 'W':
			$i = (int)$c->Tuan.'.'.$c->Nam;
			break;
		case 'M':
			$i = (int)$c->Thang.'.'.$c->Nam;
			break;
		case 'Q':
			$i = (int)$c->Quy.'.'.$c->Nam;
			break;
		case 'Y':
			$i = $c->Nam;
			break;
	}
	$costArray[$c->Ref_NhomThietBi]['MaThietBi']    = $c->MaThietBi ;
	$costArray[$c->Ref_NhomThietBi]['TenThietBi']   = $c->TenThietBi ;
	if(!isset($costArray[$c->Ref_NhomThietBi][$i]))
	{
		$costArray[$c->Ref_NhomThietBi][$i] = 0;
	}
	$costArray[$c->Ref_NhomThietBi][$i]             += $c->ThanhTien;
}
//echo'<pre>';print_r($costArray);die;
$timeEleWidth = 0;
switch($this->period)
{
	case 'D':
		$timeEleWidth = '80';
		break;
	case 'W':
		$timeEleWidth = '100';
		break;
	case 'M':
		$timeEleWidth = '80';
		break;
	case 'Q':
		$timeEleWidth = '80';
		break;
	case 'Y':
		$timeEleWidth = '50';
		break;
}
?>
<?php $countColumnAdd = count((array)$this->time); ?>
<?php $columnTotal = array();?>
<?php $excel_col = array_flip(Qss_Lib_Const::$EXCEL_COLUMN);?>
<?php $totalColumn = 2 + $countColumnAdd;?>
<form id="excel" method="post" action="/report/index/excel" target="new">
	<input type="hidden" id="content" name="content" value="">
</form>
<div class="landscape">
	<excel orientation="landscape" font-name="Arial" font-size="9"
		margin-left="0.5" margin-right="0.5" margin-top="0.75"
		margin-bottom="0.75" />
	<div id="head_print">
	<?php echo $this->views->Common->Landscape()?>
	<?php $row = 2;?>
		<center>
			<h2>
				<xls row="<?php echo $row?>" column="A"
					column-merge="<?php echo $excel_col[$totalColumn]?>" font-size="12"
					wrap-text="1" h-align="center" v-align="center"> <?php echo $this->_translate(1)?>
				(<?php echo $this->_translate(2)?> <?php echo $this->start?>
				<?php echo $this->_translate(3)?> <?php echo $this->end?>)
				</xls>
			</h2>
		</center>
	</div>
	<?php $row++?>


	<div id="container">
		<table width="" cellpadding="0" cellspacing="0" class="border"
			border="1">
			<tr class="bggrey">
				<th width="60px;"><div style="width: 60px;">
						<xls row="<?php echo $row?>" column="<?php echo $excel_col[1]?>"
							wrap-text="1" h-align="center" v-align="center" border="1"> <?php echo $this->_translate(9)?></xls>
					</div>
				</th>
				<th width="140px;"><div style="width: 140px;">
						<xls row="<?php echo $row?>" column="<?php echo $excel_col[2]?>"
							wrap-text="1" h-align="center" v-align="center" border="1"> <?php echo $this->_translate(10)?></xls>
					</div>
				</th>

				<?php $currentColumn = 3;?>
				<?php foreach($this->time as $time):?>
				<th width="<?php echo $timeEleWidth?>px;">
					<div style="width:<?php echo $timeEleWidth?>px;">
						<xls row="<?php echo $row?>"
							column="<?php echo $excel_col[$currentColumn]?>" wrap-text="1"
							h-align="center" v-align="center" border="1"> <?php echo $time['Display'];?></xls>
					</div>
				</th>
				<?php $columnTotal[$currentColumn] = 0;?>
				<?php $currentColumn++;?>
				<?php endforeach;?>
				<th width="80px">
					<div style="width: 80px;">
						<xls row="<?php echo $row?>"
							column="<?php echo $excel_col[$currentColumn]?>" wrap-text="1"
							h-align="center" v-align="center" border="1"> <?php echo $this->_translate(5)?></xls>
					</div>
				</th>
				<?php $columnTotal[$currentColumn] = 0;?>
			</tr>
			<?php $row++;?>

			<?php foreach ($costArray as $dt):?>
			<?php $total = 0;?>
			<tr>
				<td class="left"><xls row="<?php echo $row?>"
						column="<?php echo $excel_col[1]?>" wrap-text="1" h-align="center"
						v-align="center" border="1"> <?php echo $dt['MaThietBi'];?></xls>
				</td>
				<td class="left"><xls row="<?php echo $row?>"
						column="<?php echo $excel_col[2]?>" wrap-text="1" h-align="center"
						v-align="center" border="1"> <?php echo $dt['TenThietBi'];?></xls>
				</td>

				<?php $currentColumn = 3;?>
				<?php foreach($this->time as $time):?>
				<?php
				// gia tri
				$cost = isset($dt[$time['Key']])?$dt[$time['Key']]:0;
				$costFormat = isset($dt[$time['Key']])?Qss_Lib_Util::formatMoney($dt[$time['Key']], $this->currency):0;
				?>
				<td class="right"><xls row="<?php echo $row?>"
						column="<?php echo $excel_col[$currentColumn]?>" wrap-text="1"
						h-align="center" v-align="center" border="1"> <?php echo $costFormat; $total += $cost;$colVal=$cost;?></xls>
				</td>
				<?php $columnTotal[$currentColumn] = $columnTotal[$currentColumn]+$cost?>
				<?php $currentColumn++;?>
				<?php endforeach;?>


				<td class="right"><xls row="<?php echo $row?>"
						column="<?php echo $excel_col[$currentColumn]?>" wrap-text="1"
						h-align="center" v-align="center" border="1"> <?php echo Qss_Lib_Util::formatMoney($total, $this->currency);?></xls>
				</td>
				<?php $columnTotal[$currentColumn] = $columnTotal[$currentColumn]+$total?>
			</tr>
			<?php $row++;?>
			<?php endforeach;?>

			<tr>
				<td class="center"><xls row="<?php echo $row?>"
						column="<?php echo $excel_col[1]?>" wrap-text="1" h-align="center"
						v-align="center" border="1">x</xls></td>
				<td class="center"><xls row="<?php echo $row?>"
						column="<?php echo $excel_col[3]?>" wrap-text="1" h-align="center"
						v-align="center" border="1"> <?php echo $this->_translate(5)?></xls>
				</td>
				<?php $currentColumn=3;?>
				<?php foreach ($columnTotal as $val):?>
				<td class="right"><xls row="<?php echo $row?>"
						column="<?php echo $excel_col[$currentColumn]?>" wrap-text="1"
						h-align="center" v-align="center" border="1"> <?php echo Qss_Lib_Util::formatMoney($val, $this->currency);?></xls>
				</td>
				<?php $currentColumn++;?>
				<?php endforeach;?>
			</tr>
		</table>
		<br />

		<script>
		<!--
		$(document).ready(function() {
			var chart;
			chart = new Highcharts.Chart({
		        chart: {
		        	renderTo: 'Bieu_Do',
			         plotBackgroundColor: null,
			         plotBorderWidth: null,
			         plotShadow: false
		        },
	            title: {
	                text: '<?php echo $this->_translate(1)?>',
	                x: -20 //center
	            },
	            subtitle: {
	                text: '',
	                x: -20
	            },
	            xAxis: {
                        labels: {
                        rotation: -45,
                        align: 'right'
                        },
	                categories: [
                                    <?php
                                        $cate = '';
                                        
                                        foreach($this->time as $time)
                                        {
                                            $cate .= $cate?',':'';
                                            $cate .= "'{$time['Display']}'";    
                                        }
                                        echo $cate;
                                    ?>
	         	            ]
	            },
	            yAxis: {
	                title: {
	                    text: '<?php echo $this->currency?>'
	                },
	                plotLines: [{
	                    value: 0,
	                    width: 1,
	                    color: '#808080'
	                }]
	            },
	            tooltip: {
	                valueSuffix: ' '
	            },
	            legend: {
	                layout: 'vertical',
	                align: 'center',
	                verticalAlign: 'bottom',
	                borderWidth: 0
	            },
	            series: [{
	                name: '<?php echo $this->_translate(7)?>',
	                data: [
                                    <?php $last = array_pop($columnTotal); // delete column 'total'?>
                                    <?php $seriesData = 0?>
                                    <?php foreach ($columnTotal as $val):?>
                                    <?php $val = $val/1000;?>
                                    <?php if($seriesData):?>
                                            <?php echo ", $val";?>
                                    <?php else:?>
                                    <?php echo " $val"; $seriesData=1;?>
                                    <?php endif;?>
                                    <?php endforeach;?>
		   	        ]
	            }]
		    });
		});
		-->
		</script>

		<div id="Bieu_Do" style="width: 95%; margin: 10px auto;"></div>
	</div>
</div>
