<?php
/**
 * @author: Thinh Tuan <thinh.tuan@quasoft.vn>
 * @description: Module giup hien thi thong tin thiet bi
 */
?>
<link
	rel="stylesheet" href="/css/extra/maintenance/equip/info.css" />
<link
	rel="stylesheet" href="/js/jstree/themes/default/style.min.css" />
<script
	type="text/javascript" src="/js/hightchart/highcharts.js"></script>
<script
	type="text/javascript" src="/js/extra/maintenance/equip/info.js"></script>
<script
	type="text/javascript" src="/js/jstree/jstree.js"></script>
<script
	src='/js/popup-select.js' type='text/javascript'></script>

<!-- PHTML -->
<div class="clear"></div>
<div id="view">
	<div id="einfo-wrap">
		<!-- PARAMS -->
		<input type="hidden" name="einfo_deptid" id="einfo_deptid"
			value="<?php echo $this->deptid ?>">

		<!-- LOC THIET BI -->
		<div id="einfo-search-eq">
			<!-- HIEN THI CAY THIET BI  -->
			<div id="einfo-search-eq-table"></div>
			<!-- end #einfo-search-eq-table -->
		</div>
		<!-- end #einfo-search-eq -->

		<!-- HIEN THI THONG TIN  -->
		<div id="einfo-show-info">
			<!--			<div id="einfo-show-equip-info" 
				 style="padding: 0px 5px;">
			</div>-->
		</div>
		<!-- end #einfo-show-info -->
	</div>
	<!-- end #einfo-wrap -->

	<div class="clear"></div>

	<div style="padding: 1px 5px; line-height: 16px;">
		<img src="/images/jstree/location.png" /> &nbsp;
		<?php echo $this->_translate(4)?>
		&nbsp; <img src="/images/jstree/eq_type.png" /> &nbsp;
		<?php echo $this->_translate(2)?>
		&nbsp; <img src="/images/jstree/eq_group.png" /> &nbsp;
		<?php echo $this->_translate(47)?>
		&nbsp; <img src="/images/jstree/eq.png" /> &nbsp;
		<?php echo $this->_translate(45)?>
		&nbsp; <img src="/images/jstree/component.png" /> &nbsp;
		<?php echo $this->_translate(23)?>
		&nbsp; <span style="color: green; font-weight: bold; font-size: 14px;">(x/y/z):</span>
		<?php echo $this->_translate(48)?>
		/
		<?php echo $this->_translate(49)?>
		/
		<?php echo $this->_translate(50)?>
	</div>
</div>
<div id="qss_trace"></div>
