	<div class="fl" style="width: 50%">
		<p class="center bold">
			CÔNG TY CỔ PHẦN DỊCH VỤ LẮP ĐẶT
		</p>
		<p class="center bold">
			VẬN HÀNH & BẢO DƯỠNG 
		</p>		
		<p class="center bold">
		CÔNG TRÌNH DẦU KHÍ BIỂN PTSC 
		</p>
		<br/>
	</div>
	

	<div class="fr" style="width: 50%">
		<p class="center bold">
			CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM
		</p>
		<p class="center bold">
			Độc Lập - Tự Do - Hạnh Phúc
		</p>		
		<p class="center bold">
		_____________________________
		</p>
		<br/>
	</div>	