<?php ?>
<script src="/js/import-list.js"></script>
<script src="/js/extra/button/m765.js"></script>

<div class="popup_wrap">
    <div class="popup_header">
        <form id="m765_param_button_form" action="/button/m765/param/excel" method="post">
            <input type="hidden" name="fid" id="fid" value="M765" />
            <input type="hidden" id="ifid" name="ifid" value="0">
            <input type="hidden" id="deptid" name="deptid" value="0">
            <input type="hidden" id="objid" name="objid" value="">
            <input type="hidden" id="popup" name="popup" value="1">


            <table class="popup_detail">
                <tr>
                    <th colspan="2">IMPORT DỮ LIỆU  </th>
                </tr>

                <tr>
                    <th>Chọn file excel: </th>
                    <td>
                        <input type="file" id="excel_import_file" name="excel_import_file" size="30" onchange="return uploadFile('excel_import');" style="width:200px;">
                        <input type="hidden" id="excel_import" name="excel_import" value="">
                        <a href="#1" onclick="m765_params_button.export()" STYLE="color: blue !important;">Tải mẫu</a>
                    </td>

                </tr>

                <tr>
                    <th>Cập nhật lại nếu bản ghi đã tồn tại: </th>
                    <td>
                        <input type="checkbox" id="ignore" name="ignore" value="1">
                    </td>

                </tr>

                <tr>
                    <th>Không cập nhật nếu có 1 dòng lỗi: </th>
                    <td>
                        <input type="checkbox" id="checkall" name="checkall" value="1" checked="">
                    </td>
                </tr>

                <tr>
                    <th>Xóa dữ liệu cũ: </th>
                    <td>
                        <input type="checkbox" id="deleteOld" name="deleteOld" value="1" checked="">
                    </td>
                </tr>


                <tr>
                    <th>&nbsp;</th>
                    <td>
                        <button id="btnUPDATE" type="button" class="btn btn_main_top" onclick="m765_params_button.import();">Import dữ liệu.	</button>
                    </td>
                </tr>


            </table>

            <div id="statement"></div>
            <div id="container"></div>
        </form>


    </div>

    <div class="popup_content" id="">
        <div id="qss_import"></div>
    </div>
</div>

<div id="m765_export"></div>