<script>
function printPreview()
{
    if(checkError())
    {
        qssAjax.alert(msg);
        return;
    }
    else
    {
        var url = sz_BaseUrl + '/static/m749/show';
        var data = $('#report').serialize();
        qssAjax.getHtml(url, data, function(jreturn) {
        	$('#print-area').html(jreturn);
            removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
        });		 
    }
}

/**
 * Check Error
 */
function checkError()
{
	var msg = '';

    msg += common_checkEmpty($('#start').val(), '<?php echo $this->_translate(4)?>');
    msg += common_checkEmpty($('#end').val(), '<?php echo $this->_translate(5)?>');
    msg += common_compareStartAndEnd(
	    $('#start').val(), 
	    $('#end').val(), 
	    '<?php echo $this->_translate(4)?>', 
	    '<?php echo $this->_translate(5)?>'
    );	

    return msg;
}
</script>

<div class="clear"></div>
<!-- End .clear -->

<div id="view">
	<div class="line-hr">
		<span> <?php echo $this->_translate(3)?> </span>
	</div>

	<form id="report" method="post"
		action="/report/maintenance/oee/general1">
		<table class="detail">

			<!-- Ngày bắt đầu -->
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(4)?>
				</th>

				<td><?php echo $this->views->Report->Datepicker('start', '01-'.date('m').'-'.date('Y'));?>
					<span class="bold red">(*)</span>
				</td>
			</tr>

			<!-- Ngày kết thúc -->
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(5)?>
				</th>

				<td><?php echo $this->views->Report->Datepicker('end', date('d-m-Y'));?>
					<span class="bold red">(*)</span>
				</td>
			</tr>

			<!-- Thiết bị -->
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(6)?>
				</th>

				<td><?php
				$id        = 'equip_ioid';
				$getData   = array('ODanhSachThietBi'=>array('MaThietBi', 'TenThietBi'));
				$getFields = array(
                            'num'=>3,  
                            'objects'=>array(
                                'ODanhSachThietBi'=>array(
                                    'id'=>'IOID'
                                    ,'display1'=>'MaThietBi'
                                    ,'display2'=>'TenThietBi'
                                    )
                                    )
                                    );
                                    ?> <?php echo $this->views->Report->ListBox($id, $getData, $getFields);?>
				</td>
			</tr>
		</table>
	</form>

	<hr>
	<?php echo $this->views->Report->PrintToolbar();?>
	<div id="print-content">
		<div id="print-area"></div>
	</div>
</div>
