<script>
function printPreview(){
	var ngaybd = $('#start').val();
	var ngaykt = $('#end').val();
	var ky     = $('#period').val();
        var msg    = '';
        
        
        msg += common_checkEmpty(ngaybd, '<?php echo $this->_translate(2) ?>');
        msg += common_checkEmpty(ngaykt, '<?php echo $this->_translate(3) ?>');
        msg += common_checkEmpty(ky, '<?php echo $this->_translate(4) ?>');
        msg += common_compareStartAndEnd(ngaybd, ngaykt);

        
        if(msg != '')
        {
            qssAjax.alert(msg);
            return;
        }
        else
        {
            var warning = common_dateWarning(ky, '<?php echo json_encode(Qss_Lib_Extra_Const::$DATE_LIMIT); ?>', ngaybd, ngaykt);
			if(warning)
			{
				qssAjax.confirm(warning,function(){
					loadModule();
				});
			}
			else
			{
				loadModule();
			}
        }
}

function loadModule()
{
	var url = sz_BaseUrl + '/static/m755/show';
	var data = $('#report').serialize();
	qssAjax.getHtml(url, data, function(jreturn) {
	$('#print-area').html(jreturn);
		  removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
	});
}
</script>
<div class="clear"></div>
<div id="view">
	<div class="line-hr">
		<span><?php echo Qss_Lib_System::getReportTitle('M755');?> </span>
	</div>
	<form id="report" method="get" action="/static/m755/show">
		<table class="detail">
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(2)?>
				</th>
				<td><?php echo $this->views->Report->Datepicker('start', '01-'.date('m-Y'));?><span
					class="bold red">(*)</span></td>
			</tr>
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(3)?>
				</th>
				<td><?php echo $this->views->Report->Datepicker('end', date('d-m-Y'));?><span
					class="bold red">(*)</span></td>
			</tr>
			<tr>
				<th width="20%" class="report-param-label">
					<!-- Kỳ --> <?php echo $this->_translate(4)?></th>
				<td><?php echo $this->views->Report->SelectPeriod('period', 'period'); ?>
					<span class="bold red">(*)</span>
				</td>
			</tr>
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(5)?>
				</th>
				<td><?php
				$id            = 'group';
				$getFields     = array('num'=>2,
                                       'objects'=>array('ONhomThietBi'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'LoaiThietBi'
                                                            )) );
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
			
			</tr>
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(6)?>
				</th>
				<td><?php
				$id            = 'type';
				$getFields     = array('num'=>2,
                                       'objects'=>array('OLoaiThietBi'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'TenLoai'
                                                            )) );
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
			
			</tr>
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(7)?>
				</th>
				<td><?php
				$id            = 'equip';
				$getDataObject = array('ODanhSachThietBi'=>array('MaThietBi', 'LoaiThietBi'));
				//,'OKhuVuc'=>array('MaKhuVuc','Ten')
				$getFields     = array('num'=>2,
                                       'objects'=>array('ODanhSachThietBi'=>array(
                                                                'id'=>'IOID'
                                                                ,'display1'=>'MaThietBi'
                                                                ,'display2'=>'LoaiThietBi')) );
                                                                $getLookupFilter = array( array('id'=>'group'
                                                                , 'refField'=>array('ODanhSachThietBi'=>'Ref_NhomThietBi') // Nhom TB
                                                                , 'required'=>0)
                                                                , array('id'=>'type'
                                                                , 'refField'=>array('ODanhSachThietBi'=>'Ref_LoaiThietBi') // Loai TB
                                                                , 'required'=>0));
                                                                ?> <?php echo $this->views->Report->ListBox($id, $getDataObject,$getFields, $getLookupFilter);?>
				</td>
			</tr>
		</table>
	</form>
	<p>
	
	
	<hr>
	<?php echo $this->views->Report->PrintToolbar();?>
	<div id="print-content">
		<div id="print-area"></div>
	</div>
</div>
