<?php
$oldRequest      = '';
$requestWidthArr = array(1,4,4,2,3);
$width           = 780;
$padding         = 2;
$formNo          = 0;

$fit = Qss_Lib_Report::changeWidthToFitScreen2($requestWidthArr, $width, $padding);

//     if(!count($this->quotations))
//     {
//         echo 'Không có sản phẩm nào cần báo giá!';
//         die;
//     }
?>

<div id="M415_step5_quotation_wrap">
    <form id="M415_step5_quotation1_form">

        <table cellpadding="0" cellspacing="0" border="0">
            <!-- Kế hoạch -->
            <tr>
                <th class="left" width="100px">
                    <?php echo $this->_translate(13);?>:
                </th>

                <td class="left" width="">
                    <?php echo $this->planNo;?>
                    <input type="hidden" name="planioid" value="<?php echo $this->planioid;?>"/>
                </td>
            </tr>

            <!-- Nhà cung cấp -->
            <tr>
                <th class="left" width="100px">
                    <?php echo $this->_translate(11);?>:
                </th>

                <td class="left required" width="">
                    <?php echo $this->views->Report->SimpleComboBox('partnerioid', $this->suppliers);?>
                </td>
            </tr>

        </table>




        <div class="clear"></div>
        <br/>

        <table class="border_table" cellpadding="0" cellspacing="0" border="0" style="width:<?php echo $width;?>px">
            <!-- Title -->
            <?php $begin = 0; ?>
            <tr class="bggrey">
                <!-- STT -->
                <th style="width:<?php echo $fit[$begin++];?>px;">
                    <input type="checkbox" onclick="common_check_all_table_line(this, '.M415_step5_quotation_line_checkbok', '.M415_step5_quotation_line_checkbok_val')"/>
                </th>

                <!-- Mã mặt hàng -->
                <th style="width:<?php echo $fit[$begin++];?>px;">
                    <?php echo $this->_translate(2);?>
                </th>

                <!-- Tên mặt hàng -->
                <th style="width:<?php echo $fit[$begin++];?>px;">
                    <?php echo $this->_translate(3);?>
                </th>

                <!-- ĐVT -->
                <th style="width:<?php echo $fit[$begin++];?>px;">
                    <?php echo $this->_translate(4);?>
                </th>

                <!-- Số lượng  -->
                <th style="width:<?php echo $fit[$begin++];?>px;">
                    <?php echo $this->_translate(5);?>
                </th>
            </tr>

            <?php $no = 0;?>


            <?php foreach ($this->quotations as $dat):?>


                <tr>
                    <!-- STT -->
                    <td class="center">
                        <input type="checkbox" class="M415_step5_quotation_line_checkbok " onclick="common_check_table_line(this, '.M415_step5_quotation_line_checkbok_val')">
                        <input type="hidden" class="table_line_disabled M415_step5_quotation_line_checkbok_val" name="check[]"  value="0">
                        <input class="table_line_disabled" type="hidden" name="itemioid[]" value="<?php echo $dat->Ref_MaSP;?>"  disabled/>
                        <input class="table_line_disabled" type="hidden" name="uomioid[]" value="<?php echo $dat->Ref_DonViTinh;?>" disabled/>

                    </td>

                    <!-- Mã mặt hàng -->
                    <td class="left">
                        <?php echo $dat->MaSP;?>
                    </td>

                    <!-- Tên mặt hàng -->
                    <td class="left">
                        <?php echo $dat->TenSP;?>
                    </td>

                    <!-- ĐVT -->
                    <td class="left">
                        <?php echo $dat->DonViTinh;?>
                    </td>

                    <!-- Số lượng -->
                    <td class="center">
                        <input size="12" class="table_line_disabled right" type="text" name="qty[]" value="<?php echo $dat->SoLuongYeuCau;?>" disabled/>
                    </td>
                </tr>
            <?php endforeach;?>


        </table>
    </form>


    <div class="clear"></div>
    <br/>


    <div>
        <!-- Button: Tạo đơn hàng-->
        <button type="button" class="btn btn-custom" onclick="M415.step5.createQuotation();">
            <?php echo $this->_translate(8);?>
        </button>
    </div>

    <br/>
    <hr/>
    <br/>



</div><!-- END #M415_step5_quotation_wrap -->