<?php
$id = 'filter_phongban';
$getDataObject = array('OPhongBan' => array('MaPhongBan', 'TenPhongBan'));
$getFields = array('num' => 2,
    'objects' => array('OPhongBan' => array(
        'id' => 'IOID'
    , 'display1' => 'MaPhongBan'
    , 'display2' => 'TenPhongBan')));
$placeHolder = 'Chọn phòng ban';

?>

<?php
$idKyCong = 'filter_kycong';
$getDataObjectKyCong = array('OKyCong' => array('MaKyCong', 'TenKyCong'));
$getFieldsKyCong = array('num' => 2,
    'objects' => array('OKyCong' => array(
        'id' => 'IOID'
    , 'display1' => 'MaKyCong'
    , 'display2' => 'TenKyCong')));
$placeHolderKyCong = 'Chọn kỳ công';

?>

<div class="fl">
    <div class="fl">
        <?php
        echo $this->views->Report->ListBox(
            $id
            , $getDataObject
            , $getFields
            , array()
            , array()
            , ' onchange="rowSearch(\'M317\');" '
            , $this->selectedTextPhongBan
            , $this->selectedPhongBan
            , $placeHolder
        );
        ?>
    </div>

    <div class="fl">
        <?php
        echo $this->views->Report->ListBox(
            $idKyCong
            , $getDataObjectKyCong
            , $getFieldsKyCong
            , array()
            , array()
            , ' onchange="rowSearch(\'M317\');" '
            , $this->selectedTextKyCong
            , $this->selectedKyCong
            , $placeHolderKyCong
        );
        ?>
    </div>

</div>

