<table cellpadding="0" cellspacing="0" class="border_table" border="1">
    <!-- Tieu de -->
    <tr>
        <th >
            <input type="checkbox" onclick="common_check_all_table_line(this, '.cwpo_line_checkbok', '.cwpo_line_checkbok_val')"/>
        </th>
        <th> Mã MH</th>
        <th> Tên MH</th>
        <th> Đơn vị tính</th>
        <th> Số lượng </th>
    </tr>

    <?php foreach($this->workorder as $item):?>
        <tr>
            <td class="center" style="width: 5%;">
                <input type="checkbox" class="cwpo_line_checkbok " onclick="common_check_table_line(this, '.cwpo_line_checkbok_val')">
                <input type="hidden" class="table_line_disabled cwpo_line_checkbok_val" name="CheckBox[]"  value="0">

                <input class="table_line_disabled" type="hidden" value="<?php echo $item->Ref_MaVatTu;?>" name="RefItem[]" disabled>
                <input class="table_line_disabled" type="hidden" value="<?php echo $item->Ref_DonViTinh;?>" name="RefUOM[]" disabled>
            </td>

            <td class="left" style="width: 30%;"> <?php echo $item->MaVatTu;?></td>
            <td class="left" style="width: 35%;"> <?php echo $item->TenVatTu;?></td>
            <td class="left" style="width: 20%;"> <?php echo $item->DonViTinh;?></td>
            <td class="left" style="width: 10%;">
                <input type="text" name="Qty[]" class="table_line_disabled right" value="<?php echo ($item->SoLuongDuKien - $item->SoLuong);?>" disabled/>
            </td>
        </tr>
    <?php endforeach;?>
</table>
