	<div class="fl" style="width: 50%">
		<p class="center bold">
			CÔNG TY CỔ PHẦN VIGLACERA TIÊN SƠN
		</p>
        <p class="center bold"><b><?php echo mb_strtoupper($this->CongTy, 'UTF-8');?></b></p>
        
		<br/>
	</div>
	

	<div class="fr" style="width: 50%">
		<p class="center bold">
			CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM
		</p>
		<p class="center bold">
			Độc Lập - Tự Do - Hạnh Phúc
		</p>		
		<p class="center bold">
		_____________________________
		</p>
		<br/>
	</div>	