<style>
#container {
	
}

.import-bar {
	margin: 5px 0px;
	overflow: hidden;
}

.title {
	font-weight: bold;
}

.process {
	position: relative;
	background: none repeat scroll 0 0 #ccc;
	font-size: 10px;
	line-height: 14px;
	width: 300px;
	font-weight: bold;
}

.process_bar {
	background: #6DB03C;
	width: 0px;
}

.process_percent {
	position: absolute;
	top: 0px;
	left: 140px;
}

.total {
	
}

.imported {
	
}

.error-import {
	
}

.error-log-title {
	clear: both;
}

.error-log {
	clear: both;
	font-size: 10px;
	line-height: 16px;
	min-height: 16px;
	max-height: 90px;
	overflow: auto;
	padding-top: 5px;
	border-bottom: 1px #ccc solid;
	border-top: 1px #ccc solid;
}

.process-element {
	margin-left: 15px;
	padding: 1px 0px;
	min-width: 60px;
}
</style>
<script>
function uploadFile(field) {
	/* Upload file by ajax */
	disabledLayout();
	$.ajaxFileUpload({
		url : sz_BaseUrl + '/user/field/uploadfile',
		secureuri : false,
		fileElementId : $('#' + field + '_file'),
		dataType : 'json',
		success : function(data, status) {
			/* Upload file successfully */
			if (data.error) {
				qssAjax.alert(data.message);
				enabledLayout();
			} else {
				$('#' + field).val(data.image);
				enabledLayout();
				$('#btnUPDATE').prop('disabled',false);
			}
		},
		error : function(data, status, e) {
			/* If upload error */
			qssAjax.alert(e);
		}
	});
}
function excelImport() {
	if (isDisabled('btnUPDATE')) {
		return;
	}
	$('#btnUPDATE').prop('disabled',true);
	disabledLayout();
	$('#qss_combo').data('saved',true);
	var url = sz_BaseUrl + '/button/m602_viwasupco/import';
	var data = $('#qss_object_excel').serialize();
	qssAjax.getHtml(url, data, function(jreturn) {
		$('#qss_import').html(jreturn);
		enabledLayout();
	});
}
</script>

<input type="hidden"
	value="1" name="readay" />
<div style="height: 40px;">
	<button id="btnUPDATE" type="button" class="btn btn_main_top" disabled
		onclick="excelImport();">
		Import
	</button>
</div>
<div class="clear"></div>
<div>
	<form method="post" id="qss_object_excel">
		<input type="file" id="excel_import_file" name="excel_import_file"
				size="40" onchange="return uploadFile('excel_import');" /> 
		<input type="hidden" id="excel_import" name="excel_import" value="" /> 
		<hr />
		<div id="statement"></div>
		<div id="container"></div>
	</form>
	<div id="qss_import"></div>
</div>
