<form id="einfo_period">
	<div class="ui_box_s100">
		<input type="hidden" name="OChuKyBaoTri_IFID" id="OChuKyBaoTri_IFID" class="OChuKyBaoTri_Element" value="<?php echo @(int)$this->ifid;?>"/>
		<input type="hidden" name="OChuKyBaoTri_IOID" id="OChuKyBaoTri_IOID" class="OChuKyBaoTri_Element" value="<?php echo @(int)$this->lastChuKy->IOID;?>"/>
		<input type="hidden" name="OChuKyBaoTri_DeptID" id="OChuKyBaoTri_DeptID" class="OChuKyBaoTri_Element" value="<?php echo @(int)$this->lastChuKy->DeptID;?>"/>
        <input type="hidden" name="OChuKyBaoTri_ID" id="OChuKyBaoTri_ID" value="<<?php echo @(int)$this->lastChuKy->ID;?>" />
		<fieldset>
			<legend>
				Chu kỳ
			</legend>

			<div class="ui_box_line">
				<div class="label" style="width: 30% !important;" >
					<label><?php echo $this->object->getFieldByCode("CanCu")->szFieldName;?></label>
				</div>

				<div class="element">
					<select name="OChuKyBaoTri_CanCu" id="OChuKyBaoTri_CanCu" class="OChuKyBaoTri_Element" onchange="einfo_loadPeriod();">
						<option value="-1">&nbsp;</option>
						<?php foreach($this->canCu as $key=>$value):?>
							<option value="<?php echo $key;?>"><?php echo $value;?></option>
						<?php endforeach;?>
					</select>
				</div>
			</div>

			<div id="einfo_loadPeriod">

			</div>
		</fieldset>
	</div>
</form>

<script>
	<?php if($this->lastChuKy):?>
		$(document).ready(function () {
			$('#OChuKyBaoTri_CanCu').val(<?php echo @(int)$this->lastChuKy->CanCu;?>);
			einfo_loadPeriod();
		});
	<?php endif;?>
</script>


<?php /*
<table width="100%">
	<tr>
		<th colspan="2">Chu kỳ</th>
	</tr>
	<?php $j = 0;?>
	<?php foreach($this->data as $data):?>
	<?php
	$editControl = ' <div class="einfo_plan_worktab_edit_control" style="display: none;">';
	$editControl .= '<div class="einfo_delete_eq" style="" onclick="einfo_delete_sub_plan_tab( \'OCongViecBT\', ' . $data->IFID_M724 . ',' . $data->IOID . ');"> </div>';
	$editControl .= '<div class="einfo_edit_eq" onclick="einfo_edit_sub_plan_tab(\'OCongViecBT\', ' . $data->IFID_M724 . ',' . $data->IOID . ')"> </div>';
	$editControl .= '</div>';
	?>
	<tr>
		<td class="center" style="width: 15%"><?php echo ++$j;?>.
		</td>
		<td class="left" style="position: relative;"><?php echo $data->ChuKy;?>
		<?php echo $editControl;?>
		</td>
		<td class="center" style="width: 15%"><a href="#" onclick="popupObjectEdit(<?php echo $data->IFID_M724; ?>, deptid, 'OChuKyBaoTri', <?php echo $data->IOID; ?>, {},function(){ einfo_load_period('<?php echo $data->IFID_M724?>');});">Sửa</a>
		</td>
	</tr>

	<?php endforeach;?>
</table>
*/ ?>

