<table cellpadding="0" cellspacing="0" class="border_table" border="1"
	style="width: 100%;" id="einfo_maintplan_worktab">
	<tr class="bggrey">
		<th style="width: 5%;"><?php echo $this->_translate(1);?>
			<!-- STT -->
		</th>
		<th style="width: 20%;"><?php echo $this->_translate(2);?>
			<!-- Loại --></th>
		<th style="width: 10%;"><?php echo $this->_translate(5);?>
			<!-- Thời gian (Phút) -->
		</th>
		<th style="width: 40%;"><?php echo $this->_translate(6);?>
			<!-- Mô tả --></th>
	</tr>

	<?php $j = 0;?>
	<?php foreach($this->data as $data):?>
	<tr>
		<td class="center"><?php echo ++$j;?>
		</td>
		<td class="left"><?php echo $data->Ten;?>
		</td>
		<td class="left"><?php echo $data->ThoiGian;?>
		</td>
		<td class="left"><?php echo $data->MoTa;?>
		</td>
	</tr>

	<?php endforeach;?>


	<?php if ($j < 10):?>
	<?php for ($k = $j; $k < 10; $k++):?>
	<tr>
		<td class="center">&nbsp;</td>
		<td class="center">&nbsp;</td>
		<td class="center">&nbsp;</td>
		<td class="center">&nbsp;</td>
	</tr>
	<?php endfor;?>
	<?php endif;?>
</table>

<script>
$('#einfo_maintplan_worktab tr').hover(function(){ $(this).addClass('marker'); }
, function(){ $(this).removeClass('marker'); });
</script>
