<select name="<?php echo $this->name;?>" id="<?php echo $this->id;?>">
        <option value="">--- <?php echo $this->_translate(11)?> ---</option>
        <option value="D" selected><?php echo $this->_translate(12)?></option>
        <option value="W"><?php echo $this->_translate(13)?></option>
        <option value="M"><?php echo $this->_translate(14)?></option>
        <option value="Q"><?php echo $this->_translate(15)?></option>
        <option value="Y"><?php echo $this->_translate(16)?></option>
</select>