<?php
/**
 * Bao cao nguon luc bao tri theo ngay - params
 * @author Thinh Tuan
 * @path report/maintenance/resource/workcenter
 */
?>

<script>
	function printPreview()
	{
		var ngaybd = $('#start').val();
		var ngaykt = $('#end').val();
		var msg = '';
		var warning = common_dateWarning('D', '<?php echo json_encode(Qss_Lib_Extra_Const::$DATE_LIMIT);?>', ngaybd, ngaykt);
		var next = true;
		
		msg += common_checkEmpty(ngaybd, '<?php echo $this->_translate(8);?>');
		msg += common_checkEmpty(ngaykt, '<?php echo $this->_translate(9);?>');
		msg += common_compareStartAndEnd(ngaybd, ngaykt);
		
		
		if(msg)
		{
			qssAjax.alert(msg);
			return;
		}
		else
		{
			if(warning)
			{
				qssAjax.confirm(warning,function(){
					loadModule();
				});
			}
			else
			{
				loadModule();				
			}
		}
	}
	
	function loadModule()
	{
		var url = sz_BaseUrl + '/static/m785/show';
		var data = $('#report').serialize();
		qssAjax.getHtml(url, data, function(jreturn) {
				$('#print-area').html(jreturn);
				removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
		});	
	}
</script>

<div>
	<div class="clear"></div>
	<div id="view">
		<div class="line-hr">
			<span><?php echo $this->_translate(20) ?> </span>
		</div>
		<form id="report" method="get" action="/static/m785/show">
			<table class="detail">
				<tr>
					<th width="20%" class="report-param-label"><?php echo $this->_translate(8) ?>
					</th>
					<td><?php echo $this->views->Report->Datepicker('start', date('01-m-Y')); ?><span
						class="bold red">(*)</span></td>
				</tr>
				<tr>
					<th width="20%" class="report-param-label"><?php echo $this->_translate(9) ?>
					</th>
					<td><?php echo $this->views->Report->Datepicker('end', date('d-m-Y')); ?><span
						class="bold red">(*)</span></td>
				</tr>

				<tr>
					<th width="20%" class="report-param-label"><?php echo $this->_translate(10) ?>:</th>
					<td><?php
					$id = 'workcenter';
					$getFields = array('num' => 2,
							'objects' => array('ODonViSanXuat' => array(
									'id' => 'IOID'
									, 'display1' => 'Ma'
									, 'display2' => 'Ten')));
									?> <?php echo $this->views->Report->ComboBox($id, $getFields); ?>
					</td>
				</tr>
			</table>
		</form>
		<hr>
		<?php echo $this->views->Report->PrintToolbar(); ?>
		<div id="print-content">
			<div id="print-area"></div>
		</div>
	</div>
</div>

