<script>
	function printPreview() {
//	$('#report').submit(function() {
//        window.open('', 'formpopup', 'statusbar=no,resizable=yes,scrollbars=yes, addressbar=no,maximize=yes');
//        this.target = 'formpopup';
//    });
//	$('#report').submit();
		var url = sz_BaseUrl + '/static/m726/show';
		var data = $('#report').serialize();
		
		// LAY GIA TRI DANG CHUOI CUA DIEU KIEN LOC
		data += "&locationStr="  + encodeURIComponent($('#location option:selected').text());
		data += "&costcenterStr="+ encodeURIComponent($('#costcenter option:selected').text());
		data += "&groupStr="     + encodeURIComponent($('#group option:selected'   ).text());
		data += "&typeStr="      + encodeURIComponent($('#type option:selected'    ).text());
		data += "&equipmentStr=" + encodeURIComponent($('#equip_tag'           ).val());		
		
		qssAjax.getHtml(url, data, function(jreturn) {
			$('#print-area').html(jreturn);
			removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
		});
	}
</script>

<div class="clear"></div>
<div id="view">
	<div class="line-hr">
		<span><?php echo $this->_translate(1) ?> </span>
	</div>
	<form id="report" method="get"
		action="/report/maintenance/equipment/costcenter1">
		<table class="detail">


			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(8) ?>
				</th>
				<td><?php
				$id = 'location';
				$getFields = array('num' => 3,
						'objects' => array('OKhuVuc' => array(
								'id' => 'IOID'
								, 'display1' => 'MaKhuVuc'
								, 'display2' => 'Ten')));
								?> <?php echo $this->views->Report->ComboBox($id, $getFields); ?>
			
			</tr>

			<?php if (Qss_Lib_System::fieldActive('ODanhSachThietBi', 'TrungTamChiPhi')): ?>
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(2) ?>
				</th>
				<td><?php
				$id = 'costcenter';
				$getFields = array('num' => 3,
						'objects' => array('OTrungTamChiPhi' => array(
								'id' => 'IOID'
								, 'display1' => 'Ten'
								, 'display1' => 'Ma')));
								?> <?php echo $this->views->Report->ComboBox($id, $getFields); ?>
				</td>
			</tr>
			<?php endif; ?>


			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(5) ?>
				</th>
				<td><?php
				$id = 'group';
				$getFields = array('num' => 2,
						'objects' => array('ONhomThietBi' => array(
								'id' => 'IOID'
								, 'display1' => 'LoaiThietBi'
								)));
								?> <?php echo $this->views->Report->ComboBox($id, $getFields); ?>
			
			</tr>


			<?php if (Qss_Lib_Extra::checkFieldExists('ODanhSachThietBi', 'Ref_LoaiThietBi')): ?>
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(6) ?>
				</th>
				<td><?php
				$id = 'type';
				$getFields = array('num' => 2,
						'objects' => array('OLoaiThietBi' => array(
								'id' => 'IOID'
								, 'display1' => 'TenLoai'
								)));
								?> <?php echo $this->views->Report->ComboBox($id, $getFields); ?>
			
			</tr>
			<?php endif; ?>

			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(7) ?>
				</th>
				<td><?php
				$id = 'equip';
				$getDataObject = array('ODanhSachThietBi' => array('MaThietBi', 'TenThietBi'));
				//,'OKhuVuc'=>array('MaKhuVuc','Ten')
				$getFields = array('num' => 2,
						'objects' => array('ODanhSachThietBi' => array(
								'id' => 'IOID'
								, 'display1' => 'MaThietBi'
								, 'display2' => 'TenThietBi')));
								$getLookupFilter = array(array('id' => 'group'
								, 'refField' => array('ODanhSachThietBi' => 'Ref_NhomThietBi') // Nhom TB
								, 'required' => 0)
								, array('id' => 'type'
								, 'refField' => array('ODanhSachThietBi' => 'Ref_LoaiThietBi') // Loai TB
								, 'required' => 0)
								, array('id' => 'costcenter'
								, 'refField' => array('ODanhSachThietBi' => 'Ref_TrungTamChiPhi') // TT Chi phi
								, 'required' => 0)
								);
								?> <?php echo $this->views->Report->ListBox($id, $getDataObject, $getFields, $getLookupFilter); ?>
				</td>
			</tr>


			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(9) ?>
				</th>
				<td><?php echo $this->_translate(6) ?> <input type="radio"
					name="sort" value="1" checked /> <?php echo $this->_translate(5) ?>
					<input type="radio" name="sort" value="2" /> <?php if (Qss_Lib_System::fieldActive('ODanhSachThietBi', 'TrungTamChiPhi')): ?>
					<?php echo $this->_translate(2) ?> <input type="radio" name="sort"
					value="3" /> <?php endif; ?> <?php echo $this->_translate(8) ?> <input
					type="radio" name="sort" value="4" />
				</td>
			</tr>
		</table>
	</form>
	<p>
	
	
	<hr>
	<?php echo $this->views->Report->PrintToolbar(); ?>
	<div id="print-content">
		<div id="print-area"></div>
	</div>
</div>
