<script>
    function printPreview()
    {
        var err   = '', url, data;
        var start = $('#start').val();
        var end   = $('#end').val();

        err += common_checkEmpty(start, '<?php echo $this->_translate(8) ?>');
        err += common_checkEmpty(end, '<?php echo $this->_translate(9) ?>');
        err += common_compareStartAndEnd(start, end);

        if(err)
        {
            qssAjax.alert(err);
            return;
        }
        else
        {
            url  = '/static/m229/show';
            data = $('#report').serialize();

            qssAjax.getHtml(url, data, function(jreturn) {
                $('#print-area').html(jreturn);
                // Viet trong $this->views->Report->PrintToolbar()
                removePrintToolbarDisabled();
            });
        }
    }
</script>

<div>
    <div class="clear"></div>
    <div id="view">
        <div class="line-hr">
            <span><?php echo Qss_Lib_System::getReportTitle('M229');?> </span>
        </div>
        <form id="report" method="get" action="/static/m618/show">
            <table class="detail">
                <tr>
                    <th width="20%" class="report-param-label"><?php echo $this->_translate(8) ?>
                    </th>
                    <td><?php echo $this->views->Report->Datepicker('start', '01-01-'.date('Y')); ?><span
                            class="bold red">(*)</span></td>
                </tr>
                <tr>
                    <th width="20%" class="report-param-label"><?php echo $this->_translate(9) ?>
                    </th>
                    <td><?php echo $this->views->Report->Datepicker('end', date('d-m-Y')); ?><span
                            class="bold red">(*)</span></td>
                </tr>

                <tr>
                    <th width="20%" class="report-param-label"><?php echo $this->_translate(10) ?>:</th>
                    <td><?php
                        $id = array('id'=>'project', 'require'=>0);
                        $getDataObject = array('ODuAn'=>array('MaDuAn', 'TenDuAn'));
                        $getFields = array('num' => 2,
                            'objects' => array('ODuAn' => array(
                                'id' => 'IOID'
                            , 'order' => 'MaDuAn'
                            , 'display1' => 'MaDuAn'
                            , 'display2' => 'TenDuAn')));
                        ?> <?php echo $this->views->Report->ListBox($id, $getDataObject, $getFields); ?>
                    </td>
                </tr>

            </table>
        </form>
        <hr>
        <?php echo $this->views->Report->PrintToolbar(); ?>
        <div id="print-content">
            <div id="print-area"></div>
        </div>
    </div>
</div>

