<div class="fl">
    <table cellpadding="0" cellspacing="0" class="border_table" border="1" id="m753_material_box" style="table-layout: fixed;">
        <!-- Tieu de -->
        <tr>
            <th style="width: 10%;"><input type="checkbox" onclick="m753_multi_button.checkAllItems(this)" class="remov_all_line"></th>
            <th style="width: 45%;"> Thiết bị</th>
            <th style="width: 45%;"> Bộ phận</th>
        </tr>
    </table>
</div>
