<table class="grid_navigator">
	<tr>
		<td align="center" style="border-right: 0; width: 100px">
		</td>
		<td align="right"><?php echo $this->_translate(26)?>: <select id="qss_object_groupby"
			onchange="DisplayTabContent('<?php echo $this->params['ifid'];?>', '<?php echo $this->params['deptid'];?>', '<?php echo $this->params['objid'];?>', '<?php echo $this->params['fieldid'];?>', '<?php echo $this->params['vid'];?>', '<?php echo $this->params['ioid'];?>', '<?php echo $this->object->sz_Name?>');">
			<option value="0"></option>
			<?php foreach ( $this->fields as $field):	?>
			<option value="<?php echo $field->FieldCode?>"
			<?php
			if ( $field->FieldCode === $this->groupby )
			echo 'selected';
			?>><?php
			echo $field->szFieldName;
			?></option>
			<?php endforeach;?>
		</select> <?php echo $this->_translate(30)?>: <select id="qss_object_pageno" style="width: 50"
			onchange="DisplayTabContent('<?php echo $this->params['ifid'];?>', '<?php echo $this->params['deptid'];?>', '<?php echo $this->params['objid'];?>', '<?php echo $this->params['fieldid'];?>', '<?php echo $this->params['vid'];?>', '<?php echo $this->params['ioid'];?>', '<?php echo $this->object->sz_Name?>');">
			<?php
			for ($i = 1; $i <= $this->pagecount; $i ++):?>
			<option
			<?php
			if ( $i == $this->currentpage )
			echo 'selected';
			?>><?php
			echo $i;
			?></option>
			<?php endfor;?>
		</select> / 1 <?php echo $this->_translate(28)?>: <select id="qss_object_perpage"
			style="width: 100;"
			onchange="DisplayTabContent('<?php echo $this->params['ifid'];?>', '<?php echo $this->params['deptid'];?>', '<?php echo $this->params['objid'];?>', '<?php echo $this->params['fieldid'];?>', '<?php echo $this->params['vid'];?>', '<?php echo $this->params['ioid'];?>', '<?php echo $this->object->sz_Name?>');">
			<?php
			$arr = array(10, 20, 50, 100);
			foreach ($arr as $val):?>
			<option
			<?php
			if ( $val == $this->limit )
			echo 'selected';
			?>><?php
			echo $val;
			?></option>
			<?php endforeach;?>
		</select></td>
	</tr>
</table>

