<table cellspacing="0" class="grid">
	<tr>
		<th class="nocount">STT</th>
		<?php if ( $this->object->bTrack ):?>
		<th><?php echo $this->_translate(50,'Người đăng')?></th>
		<?php endif;?>
		<?php foreach ($this->fields as $field):?>
			<?php if ( $field->bGrid & 1):?>
			<th>
				<a><?php echo $field->szFieldName;?></a>
			</th>
			<?php endif;?>
		<?php endforeach;?>
		<th width="50px">
			<a>Xóa</a>
		</th>
	</tr>
	<?php
	$i=1;
	foreach ($this->objects as $object)
	{
		$this->object->initData($this->object->i_IFID,$this->object->intDepartmentID,$object->IOID);
		$fields = $this->object->a_fLoadFields();
		?>
	<tr>
	<td class="center nocount"><?php echo $i?></td>
			<?php if ( $this->object->bTrack ):?>
				<td class=data style="border-left: 1px solid #CCCCCC"><?php	echo $object->UserName?></td>
			<?php endif;?>
		<?php $bFirst = true;?>
		<?php foreach ($fields as $field):?>
		<?php if ( $field->bGrid & 1):?>
		<td class="data <?php echo Qss_Lib_Const::$FIELD_ALIGN[$field->intFieldType-1]?>"
		<?php
		if ( $bFirst )
		echo 'style="border-left: 1px solid rgb(204, 204, 204);"'?>><?php
		echo $field->sz_fGetDisplay();
		?></td>

		<?php $bFirst = false;?>
		<?php endif;?>		
		<?php endforeach;?>
		 <td class="center"><a href="#!" onclick="mailReferDelete('<?php echo $this->object->FormCode?>','<?php echo $this->object->ObjectCode?>', <?php echo $this->mlid?>, <?php echo $object->IFID?>,<?php echo $object->IOID?>)">Xóa</a></td>
	</tr>
	<?php $i++;?>
	<?php }?>
</table>
