<?php
/**
 * @author: Thinh Tuan <thinh.tuan@quasoft.vn>
 * @description: Module giup hien thi thong tin thiet bi
 */
?>
<link
	rel="stylesheet" href="/css/extra/maintenance/equip/info.css" />
<link
	rel="stylesheet" href="/js/jstree/themes/default/style.min.css" />
<script
	type="text/javascript" src="/js/hightchart/highcharts.js"></script>
<script
	type="text/javascript" src="/js/extra/maintenance/equip/info.js"></script>
<script
	type="text/javascript" src="/js/jstree/jstree.js"></script>
<script
	src='/js/popup-select.js' type='text/javascript'></script>

<script>

</script>

<!-- PHTML -->
<div class="clear"></div>
<div id="view">
	<div id="einfo-wrap">
		<!-- PARAMS -->
		<input type="hidden" name="einfo_deptid" id="einfo_deptid"
			value="<?php echo $this->deptid ?>">

		<!-- LOC THIET BI -->
		<div id="einfo-search-eq">
			<div id="einfo-search-eq-box">
				<input id="einfo-search-eq-textbox" type="text" style="width: 96%;" placeholder="<?php echo $this->_translate(51)?>">
			</div>
			<!-- HIEN THI CAY THIET BI  -->
			<div id="einfo-search-eq-table"></div>
			<!-- end #einfo-search-eq-table -->
		</div>
		<!-- end #einfo-search-eq -->

		<!-- HIEN THI THONG TIN  -->
		<div id="einfo-show-info">
			<!--			<div id="einfo-show-equip-info" 
				 style="padding: 0px 5px;">
			</div>-->
		</div>
		<!-- end #einfo-show-info -->
	</div>
	<!-- end #einfo-wrap -->

	<div class="clear"></div>

	<div style="padding: 1px 5px; line-height: 16px;">
		<div class="fl">
			<img src="/images/jstree/location.png" /> &nbsp;
			<?php echo $this->_translate(4)?>

            <?php if(Qss_Lib_System::fieldActive('OLoaiThietBi', 'NhomThietBi')):?>
                &nbsp; <img src="/images/jstree/eq_group.png" /> &nbsp;
                <?php echo $this->_translate(3)?>
            <?php endif;?>

			&nbsp; <img src="/images/jstree/eq_type.png" /> &nbsp;
			<?php echo $this->_translate(2)?>
			&nbsp; <img src="/images/jstree/eq_group.png" /> &nbsp;
			<?php echo $this->_translate(47)?>
			&nbsp; <img src="/images/jstree/eq.png" /> &nbsp;
			<?php echo $this->_translate(45)?>
			&nbsp; <img src="/images/jstree/component.png" /> &nbsp;
			<?php echo $this->_translate(23)?>
			&nbsp; <span style="color: green; font-weight: bold; font-size: 14px;">(x/y/z):</span>
			<?php echo $this->_translate(48)?>
			/
			<?php echo $this->_translate(49)?>
			/
			<?php echo $this->_translate(50)?>
		</div>

		<div class="fr">
			<button class="btn" type="button" id="einfo-add-item-button" onclick="popupFormInsert('M705', {}, function() {einfo_refresh_tree();});"><?php echo $this->_translate(52)?></button>
			<button class="btn" type="button" id="einfo-change-view-button" onclick="einfo_setView(2);">Tree view</button>
		</div>

	</div>
</div>
<div id="qss_trace"></div>
