<script src="/js/extra/button/m759.js"></script>

<form id="m759_assign_button">
    <div class="popup_wrap">
        <div class="popup_header">
            <table class="popup_detail">
                <tr>
                    <th style="width: 20%">
                        Người giao:
                    </th>

                    <td>
                        <?php
                        $id = 'NguoiGiao';
                        $getDataObject = array('ODanhSachNhanVien'=>array('MaNhanVien', 'TenNhanVien'));
                        $getFields = array('num' => 2,
                            'objects' => array('ODanhSachNhanVien' => array(
                                'id' => 'IOID'
                            , 'order' => 'MaNhanVien'
                            , 'display1' => 'MaNhanVien'
                            , 'display2' => 'TenNhanVien')));
                        ?> <?php echo $this->views->Report->ListBox($id, $getDataObject, $getFields); ?>
                    </td>
                </tr>

                <tr>
                    <th style="width: 20%">
                        Người chịu trách nhiệm:
                    </th>

                    <td>
                        <?php
                        $id = 'NguoiChiuTrachNhiem';
                        $getDataObject = array('ODanhSachNhanVien'=>array('MaNhanVien', 'TenNhanVien'));
                        $getFields = array('num' => 2,
                            'objects' => array('ODanhSachNhanVien' => array(
                                'id' => 'IOID'
                            , 'order' => 'MaNhanVien'
                            , 'display1' => 'MaNhanVien'
                            , 'display2' => 'TenNhanVien')));
                        ?> <?php echo $this->views->Report->ListBox($id, $getDataObject, $getFields); ?>
                    </td>
                </tr>

                <tr>
                    <th style="width: 20%">
                        Xóa người giao việc:
                    </th>

                    <td>
                        <input type="checkbox" id="XoaNguoiGiaoViec" name="XoaNguoiGiaoViec" value="1" />
                    </td>
                </tr>

                <tr>
                    <th style="width: 20%">
                        Xóa người chịu trách nhiệm:
                    </th>

                    <td>
                        <input type="checkbox" id="XoaNguoiChiuTrachNhiem" name="XoaNguoiChiuTrachNhiem" value="1" />
                    </td>
                </tr>

                <tr>
                    <th style="width: 20%">
                        Ngày bắt đầu:
                    </th>

                    <td>
                        <?php echo $this->views->Report->Datepicker('NgayBatDau', '');?>
                    </td>
                </tr>

                <tr>
                    <th style="width: 20%">
                        Ngày hoàn thành:
                    </th>

                    <td>
                        <?php echo $this->views->Report->Datepicker('NgayHoanThanh', '');?>
                    </td>
                </tr>

                <?php /*
                <!-- Vật tư -->
                <tr>
                    <th width="20%">
                        Phiếu bảo trì
                    </th>
                    <td>
                        <?php echo $this->views->Report->AjaxDialBox(
                            'PhieuBaoTri'
                            , 'OPhieuBaoTri'
                            , 'SoPhieu'
                            , array('SoPhieu', 'MaThietBi', 'LoaiBaoTri', 'MoTa')
                            , array('SoPhieu', 'MaThietBi', 'MaKhuVuc', 'MaDVBT')
                            , array('qsiforms.Status = 1 ')
                            , ''
                            , ''
                            , array('SoPhieu DESC')
                            , 'INNER JOIN qsiforms ON OPhieuBaoTri.IFID_M759 = qsiforms.IFID'
                        );?>
                    </td>
                </tr>

                <tr>
                    <th width="20%">
                    </th>
                    <td>
                        <span class="red bold"> (*) </span> Tìm kiếm phiếu bảo trì ở tình trạng khởi tạo theo số phiếu, mã thiết bị, mã khu vực hoặc mã đơn vị bảo trì.
                    </td>
                </tr>
                */
                ?>

                <tr>
                    <th width="20%">
                    </th>
                    <td>
                        <button type="button" class="btn" onclick="m759_assign_button.save()"> Lưu lại </button>
                    </td>
                </tr
            </table>
        </div>

        <div class="popup_content">

        </div>
    </div>
</form>