<script>    
function printPreview(){
	var url  = sz_BaseUrl + '/static/m877/show';
	var data = $('#report').serialize();
    var err  = '';
	
	err  += common_checkEmpty($('year').val(), '<?php echo $this->_translate(2)?>');

	if(err != '')
	{
		qssAjax.alert(err);
		return;
	}
	else
	{
    	data += "&locationStr="  + encodeURIComponent($('#location option:selected').text());
    	data += "&groupStr="     + encodeURIComponent($('#group option:selected').text());
    	data += "&typeStr="      + encodeURIComponent($('#type option:selected').text());
    	data += "&equipmentStr=" + encodeURIComponent($('#equipment_tag').val());
    	data += "&yearStr="      + encodeURIComponent($('#year option:selected').val());
    	
    	qssAjax.getHtml(url, data, function(jreturn) {
    		$('#print-area').html(jreturn);
    		removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
    	});
	}
}
</script>



<div class="clear"></div>
<div id="view">
	<div class="line-hr">
		<span> <?php echo Qss_Lib_System::getReportTitle('M877');?> </span>
	</div>
	<form id="report" method="get" action="/static/m877/show">
		<table class="detail">

			<tr>
				<th class="report-param-label"><?php echo $this->_translate(2)?>
				</th>
				<td><?php echo $this->views->Report->SelectYear(); ?> <span
					class="bold red">(*)</span> <?php //echo $this->views->Report->DialBox('maintype', $this->loaiBaoTriDialBoxData);?>
				</td>
			</tr>

			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(20)?>
				</th>
				<td><?php
				$id            = 'location';
				$getFields     = array('num'=>3,
                                       'objects'=>array('OKhuVuc'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'MaKhuVuc'
                                                            ,'display2'=>'Ten') ));
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
				</td>
			</tr>


			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(22)?>
				</th>
				<td><?php
				$id            = 'group';
				$getFields     = array('num'=>3,
                                       'objects'=>array('ONhomThietBi'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'LoaiThietBi'
                                                            ) ));
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
				</td>
			</tr>


			<?php if(Qss_Lib_Extra::checkFieldExists('ODanhSachThietBi', 'Ref_LoaiThietBi')):?>
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(21)?>
				</th>
				<td>

                    <?php
                    $id            = 'type';
                    $getDataObject = array('OLoaiThietBi'=>array('TenLoai'));
                    $getFields     = array('num'=>2,
                        'objects'=>array('OLoaiThietBi'=>array(
                            'id'=>'IOID'
                        ,'display1'=>'TenLoai')) );
                    ?> <?php echo $this->views->Report->ListBox($id, $getDataObject,$getFields);?>
                </td>
			
			</tr>
			<?php endif;?>


			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(3)?>
				</th>
				<td><?php
				$id            = 'equipment';
				$getDataObject = array('ODanhSachThietBi'=>array('MaThietBi', 'LoaiThietBi'));
				$getFields     = array('num'=>2,
								   'objects'=>array('ODanhSachThietBi'=>array(
															'id'=>'IOID'
															,'display1'=>'MaThietBi'
															,'display2'=>'LoaiThietBi')) );
															?> <?php echo $this->views->Report->ListBox($id, $getDataObject,$getFields);?>
				</td>
			</tr>

            <?php /*
            <tr>
                <th width="20%" class="report-param-label"><?php echo $this->_translate(23)?>:</th>
                <td><?php echo $this->views->Report->Datepicker('start');?></td>
            </tr>
            <tr>
                <th width="20%" class="report-param-label"><?php echo $this->_translate(24)?>:</th>
                <td><?php echo $this->views->Report->Datepicker('end');?></td>
            </tr>
            */?>

            <tr>
                <th class="report-param-label"><?php echo $this->_translate(12)?></th>
                <td>
                    <?php
                    $id        = 'workcenter';
                    $getFields = array('num'=>3, 'objects'=>array('ODonViSanXuat'=>array('id'=>'IOID','display1'=>'Ma','display2'=>'Ten') ));
                    ?>
                    <?php echo $this->views->Report->ComboBox($id, $getFields);?>
                </td>
            </tr>


        </table>
	</form>
	<p>
	
	
	<hr>
	<?php echo $this->views->Report->PrintToolbar();?>
	<div id="print-content">
		<div id="print-area"></div>
	</div>
</div>
<script type="text/javascript">
<!--

//-->
</script>
