

    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript">
    var markers = [
		<?php foreach ($this->workstation as $tram):?>
		<?php if($tram->KinhDo && $tram->ViDo):?>
		['<?php echo $tram->TenTram; ?>', <?php echo $tram->KinhDo;?> , <?php echo $tram->ViDo;?>],
		<?php endif;?>
		<?php endforeach;?>
    ];
    
    function initializeMaps() {
        var myOptions = {
			center: new google.maps.LatLng(16.911397759664055, 106.73328399654997),
            zoom: 5,
            disableDefaultUI: false,
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            mapTypeControl: true
        };
        var map = new google.maps.Map(document.getElementById("show_map"),myOptions);
        var infowindow = new google.maps.InfoWindow();
        var marker, i;
        var bounds = new google.maps.LatLngBounds();

        if(markers.length  > 0)
        {
	        for (i = 0; i < markers.length; i++) {
	            var pos = new google.maps.LatLng( markers[i][2],markers[i][1]);
	            
	            marker = new google.maps.Marker({
	                position: pos,
	                map: map
	            });
	            google.maps.event.addListener(marker, 'click', (function(marker, i) {
	                return function() {
	                    infowindow.setContent(markers[i][0]);
	                    infowindow.open(map, marker);
	                }
	            })(marker, i));
                  bounds.extend(pos);
	        }
                
	        map.fitBounds(bounds);
        }
    }

    window.onload = initializeMaps;
    </script>


<div class="clear"></div>
<div id="view">



<div id="qss_form">
	<div id="show_map" style="height: 650px; ">
	
	</div><!-- end #map -->
</div>