<link rel="stylesheet" href="/css/themes/base/jquery.ui.core.css" type='text/css'/>
<link rel="stylesheet" href="/css/themes/base/jquery.ui.base.css" type='text/css'/>
<link rel="stylesheet" href="/css/themes/base/jquery.ui.all.css" type='text/css'/>
<link rel="stylesheet" href="/css/themes/base/jquery.ui.dialog.css" type='text/css'/>
<link rel="stylesheet" href="/css/print.css" type='text/css'/>

<div id="xoiloboitu-wrap">
        <h2>
                <?php echo @$this->xoiloboitu->LopBanDo;?>
        </h2>    
        <table border="1" cellpadding="0" cellspacing="0" class="">
                
                <tr>
                        <th> Mã </th>
                        <td> <?php echo @$this->xoiloboitu->Ma;?> </td>
                </tr>
                
                <tr>    
                        <th> Tỉnh </th>
                        <td> <?php echo @$this->xoiloboitu->Tinh;?> </td>
                </tr>         
                
                <tr>    
                        <th> Kinh độ </th>
                        <td> <?php echo @$this->xoiloboitu->OY;?> </td>
                </tr>                         
                
                <tr>    
                        <th> Vĩ độ </th>
                        <td> <?php echo @$this->xoiloboitu->OX;?> </td>
                </tr>                
                
        </table>
</div><!-- end #xoiloboitu-wrap -->