<?php
    if(!$this->OXuatKho || (int)$this->OXuatKho->Ref_Kho == 0) {
        echo '<h2>Chưa chọn kho cho phiếu xuất kho điều động.</h2>';
        die;
    }

?>


<?php
$widthTable = array(1,3,3,3,2,2,2,2,3);
$widthTable = Qss_Lib_Report::changeWidthToFitScreen3($widthTable);
?>

<script src="/js/common.js"></script>
<script src="/js/jquery.tablescroll.js"></script>

<table id="grid1" class="border_table" cellspacing="0" cellpadding="0" border="0">
    <thead>
    <?php $begin = 0;?>
    <tr class="bggrey">
        <th style="width: <?php echo $widthTable[$begin++];?>%"><input type="checkbox" onclick="common_check_all_table_line(this, '.cwpo_line_checkbok', '.cwpo_line_checkbok_val')"/> </th>
        <th style="width: <?php echo $widthTable[$begin++];?>%">Mã mặt hàng</th>
        <th style="width: <?php echo $widthTable[$begin++];?>%">Tên mặt hàng</th>
        <th style="width: <?php echo $widthTable[$begin++];?>%">Nhóm mặt hàng</th>
        <th style="width: <?php echo $widthTable[$begin++];?>%">Đơn vị tính</th>
        <th style="width: <?php echo $widthTable[$begin++];?>%">Số lượng tồn kho</th>
        <th style="width: <?php echo $widthTable[$begin++];?>%">Số lượng đã đặt chỗ</th>
        <th style="width: <?php echo $widthTable[$begin++];?>%">Số lượng trên phiếu</th>
        <th style="width: <?php echo $widthTable[$begin++];?>%">Số lượng xuất kho</th>
    </tr>
    </thead>

    <tbody>
    <?php foreach($this->OKho as $item):?>
        <?php

        if($item->RefXuatKhoHienTai) {
            $soLuongChon = Qss_Lib_Util::formatNumber(@$item->SoLuongDaLay);
        }
        else {
            $soLuongChon = ((@$item->SoLuongHC?$item->SoLuongHC:0) - (@$item->SoLuongXuatKhac?$item->SoLuongXuatKhac:0));

            if($soLuongChon > 0) {
                $soLuongChon = Qss_Lib_Util::formatNumber($soLuongChon);
            }
            else {
                $soLuongChon = 0;
            }
        }
        ?>
        <tr>
            <td class="center">
                <input type="checkbox" class="cwpo_line_checkbok " onclick="common_check_table_line(this, '.cwpo_line_checkbok_val')">
                <input type="hidden" class="table_line_disabled cwpo_line_checkbok_val" name=""  value="0">
                <input type="hidden" class="table_line_disabled" disabled name="M506_Get_By_Stock_IOID[]" value="<?php echo @$item->Ref_MaSanPham;?>"/>
                <input type="hidden" class="table_line_disabled" disabled name="M506_Get_By_Stock_Key[]" value="<?php echo @$item->Ref_MaSanPham.'_'.@$item->Ref_DonViTinh;?>"/>
                <input type="hidden" class="table_line_disabled " disabled name="M506_Get_By_Stock_Valid[]" value="<?php echo $item->SoLuongHC;?>"/>
            </td>
            <td class="left break"><?php echo @$item->MaSanPham;?></td>
            <td class="left"><?php echo @$item->TenSanPham;?></td>
            <td class="left"><?php echo @$item->NhomSanPham;?></td>
            <td class="left"><?php echo @$item->DonViTinh;?></td>

            <td class="right"><?php echo Qss_Lib_Util::formatNumber(@$item->SoLuongHC);?></td>
            <td class="right"><?php echo Qss_Lib_Util::formatNumber(@$item->SoLuongXuatKhac);?></td>
            <td class="right"><?php echo Qss_Lib_Util::formatNumber(@$item->SoLuongDaLay);?></td>

            <td class="left">

                <input type="text" class="table_line_disabled right" disabled name="M506_Get_By_Stock_SoLuongXuatKho[]" style="width: 80px;"

                       value="<?php echo $soLuongChon;?>"/>
            </td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>


<script>
    $(document).ready(function() {
        // SET LẠI CHIỀU CAO BẢNG
        $('#grid1').tableScroll({height:240,width:'100%'});

        /// SET LẠI TRANG
        $('#M506_Get_By_Stock_Prev').attr('onclick', "$('#M506_Get_By_Stock_PageNo').val('<?php echo @(int)$this->prev;?>'); m506_button_getbystock.show();");
        $('#M506_Get_By_Stock_Next').attr('onclick', "$('#M506_Get_By_Stock_PageNo').val('<?php echo @(int)$this->next;?>'); m506_button_getbystock.show();");
        $('#M506_Get_By_Stock_PageNo').val('<?php echo $this->page;?>');
        $('#M506_Get_By_Stock_TotalPage').text('<?php echo $this->totalPage;?>');
        $('#M506_Get_By_Stock_Total').text('<?php echo $this->total;?>');
        $('#M506_Get_By_Stock_Display').val('<?php echo $this->display;?>')
    });
</script>
