<?php
$widths = array(1, 5, 3, 3);
$widths = Qss_Lib_Report::changeWidthToFitScreen3($widths);
?>

<div class="fl">
    <table cellpadding="0" cellspacing="0" class="border_table" border="0" id="m412_material_box" style="table-layout: fixed;">
        <!-- Tieu de -->
        <?php $begin = 0;?>
        <tr>
            <th style="width: <?php echo $widths[$begin++];?>%;"><input type="checkbox" class="remov_all_line" onclick="m412_material_button.checkAllItems(this)"></th>

            <th style="width: <?php echo $widths[$begin++];?>%;"> Loại thiết bị </th>
            <th style="width: <?php echo $widths[$begin++];?>%;"> Đơn vị tính </th>
            <th style="width: <?php echo $widths[$begin++];?>%;"> Số lượng yêu cầu </th>
        </tr>

        <?php $i = 1;?>
        <?php foreach($this->data as $item):?>
            <tr class="selected_line inserted_line"  >
                <td class="center">

                </td>
                <td class="left"> <?php echo $item->LoaiThietBi;?></td>
                <td class="left"> <?php echo $item->DonViTinh;?></td>
                <td class="right"> <?php echo Qss_Lib_Util::formatNumber($item->SoLuong);?></td>
            </tr>
        <?php endforeach;?>
    </table>
</div>

