<?php if($this->component):?>

<?php

    $oldPhuTung = '';

// Hien thi hinh anh thiet bi


$imageResult = '';
$image       = "/user/field/picture?file={$this->component->Anh}";
$imageExists = file_exists(QSS_DATA_DIR
. "/documents/{$this->component->Anh}");

if ($imageExists && $this->component->Anh)
{
	$imageResult = '<img width="250" src="'.$image.'" />';
}
else
{
	$imageResult = '<div '
	. 'style="width: 100px; float:left; '
	. 'background: #fff; font-size: 36px;  '
	. 'line-height:  40px; color: #ccc; text-align: center;">'
	. ' NO IMAGE '
	. '</div>';
}

?>

<div class="ui_box">
	<div class="ui_box_s50_left">
		<fieldset>
			<legend>
			<?php echo $this->_translate(1);?>
				<!-- Vị trí -->
			</legend>
			<div class="ui_box_line">
				<div class="label">
					<label><?php echo $this->_translate(1);?> <!-- Vị trí --> </label>
				</div>
				<div class="element">
				<?php echo $this->component->ViTri; ?>
				</div>
			</div>

			<div class="ui_box_line">
				<div class="label">
					<label><?php echo $this->_translate(2);?> <!-- Bộ phận --> </label>
				</div>
				<div class="element">
				<?php echo $this->component->BoPhan; ?>
				</div>
			</div>

			<div class="ui_box_line">
				<div class="label">
					<label><?php echo $this->_translate(18);?> <!-- Bộ phận --> </label>
				</div>
				<div class="element">
				<?php echo $this->component->Serial; ?>
				</div>
			</div>
			
			<div class="ui_box_line">
				<div class="label">
					<label><?php echo $this->_translate(3);?> <!-- Trực thuộc --> </label>
				</div>
				<div class="element">
				<?php echo $this->component->TrucThuoc; ?>
				</div>
			</div>

			<div class="ui_box_line">
				<div class="label">
					<label><?php echo $this->_translate(4);?> <!-- Ánh --> </label>
				</div>
				<div class="element">
				<?php echo $imageResult; // Hien thi anh ?>
				</div>
			</div>

			<div class="ui_box_line">
				<div class="label">
					<label><?php echo $this->_translate(5);?> <!-- Mô tả --> </label>
				</div>
				<div class="element">
					<!--<textarea name="MoTa_109" id="MoTa_109">-->
				<?php echo $this->component->MoTa; ?>
					<!--</textarea>-->
				</div>
			</div>
		</fieldset>
	</div>

	<div class="ui_box_s50_right">
		<br />
		<button class="btn-custom"
			onclick="popupObjectInsert(<?php echo $this->nodeifid ?>, 1, 'OCauTrucThietBi', {OCauTrucThietBi_TrucThuoc: '<?php echo $this->component->IOID ?>'}, function() {$('#einfo-search-eq-table').jstree('load_node', $('#COMPONENT<?php echo $this->nodeioid ?>'));});"
			type="button" style="width: 120px;">
			<?php echo $this->_translate(6);?>
			<!-- Thêm bộ phận con -->
		</button>
		<br />

		<button class="btn-custom"
			onclick="popupObjectEdit(<?php echo $this->nodeifid ?>, 1, 'OCauTrucThietBi',<?php echo $this->nodeioid ?>, null, function() {$('#COMPONENT<?php echo $this->nodeioid ?>_anchor').click();});"
			type="button" style="width: 120px;">
			<?php echo $this->_translate(7);?>
			<!-- Sửa bộ phận -->
		</button>
		<br />


	</div>
</div>
<div class="ui_box">
	<div class="ui_box_s100">
		<fieldset>
			<legend>
			<?php echo $this->_translate(9);?>
				<!-- Danh sách phụ tùng -->
			</legend>
			<div style="float: left; width: 100%;position: relative;">
			<table cellspacing="0" cellpadding="0" border="0"
				style="width: 100%;" class="border_table"
				id="einfo_componentdetail_sparepart">
				<tr class="bggrey center">
					<th style="width: 10%;"><?php echo $this->_translate(10);?> <!-- Mã phụ tùng --></th>
					<th style="width: 15%;"><?php echo $this->_translate(11);?> <!-- Tên phụ tùng --></th>
					<th style="width: 5%;"><?php echo $this->_translate(12);?> <!-- ĐVT --></th>
					<th style="width: 5%;"><?php echo $this->_translate(13);?> <!-- Số lượng chuẩn --></th>
					<th style="width: 5%;"><?php echo $this->_translate(14);?> <!-- Số lượng HC --></th>
					<th style="width: 5%;"><?php echo $this->_translate(16);?> <!-- Số ngày cảnh báo --></th>
					<th style="width: 5%;"><?php echo $this->_translate(17);?> <!-- Tồn kho --></th>
					<th style="width: 5%;">&nbsp; <!-- Tồn kho --></th>
					<th style="width: 5%;">&nbsp; <!-- Tồn kho --></th>
                    <th style="width: 10%;">&nbsp; <!-- Tồn kho --></th>
				</tr>

				<?php $i = 0; ?>
				<?php foreach ($this->data as $d): ?>
                    <?php if(!$d->Ref_MaSP) { continue; } ?>

                    <?php if($oldPhuTung != $d->Ref_ViTri):?>
                        <?php $firstPhuTungThayTheRow = true;?>

                        <tr>
                            <td style="width: 10%" class="left"><?php echo $d->MaSP; ?></td>
                            <td style="width: 20%" class="left"><?php echo $d->TenSP; ?></td>
                            <td style="width: 10%" class="left"><?php echo $d->DonViTinh; ?></td>
                            <td style="width: 10%" class="right"><?php echo Qss_Lib_Util::formatNumber($d->SoLuongChuan); ?>
                            </td>
                            <td style="width: 10%" class="right"><?php echo Qss_Lib_Util::formatNumber($d->SoLuongHC); ?></td>
                            <td style="width: 10%;" class="right"><?php echo Qss_Lib_Util::formatNumber($d->SoNgayCanhBao); ?>
                            </td>
                            <td style="width: 10%;" class="right"><?php echo Qss_Lib_Util::formatNumber(@$d->TonKho); ?></td>
                            <td class="center"><a href="#" onclick="einfo_edit_component('OCauTrucThietBi', '<?php echo $d->IFID_M705?>','<?php echo $d->IOID?>')">Sửa</a>
                            </td>
                            <td class="center"><a href="#" onclick="einfo_delete_component( 'OCauTrucThietBi', '<?php echo $d->IFID_M705?>','<?php echo $d->IOID?>');">Xóa</a>
                            </td>
                            <td class="center">
                                <a href="#1"
                                   onclick="einfo_showSparepartHistory(<?php echo (int)$d->Ref_ThietBi;?>, <?php echo (int)$d->Ref_ViTri; ?>, <?php echo (int)$d->Ref_MaSP; ?>, 1)">
                                    <?php echo $this->_translate(19);?>
                                </a>

                            </td>
                        </tr>
                        <?php $i++; ?>
                    <?php endif;?>
                    <?php $oldPhuTung = $d->Ref_ViTri;?>

                    <?php if($d->MaPhuTungThayThe && ($d->MaSP != $d->MaPhuTungThayThe || $d->DonViTinh != $d->DVTPhuTungThayThe)):?>
                        <?php if($firstPhuTungThayTheRow):?>
                            <tr class="bggrey">
                                <th colspan="10" class="left">
                                    Phụ tùng thay thế
                                </th>
                            </tr>

                            <?php $firstPhuTungThayTheRow = false;?>
                        <?php endif;?>


                        <tr class="italic">
                            <td style="width: 10%" class="left"><?php echo $d->MaPhuTungThayThe; ?></td>
                            <td style="width: 15%" class="left"><?php echo $d->TenPhuTungThayThe; ?></td>
                            <td style="width: 5%" class="left"><?php echo $d->DVTPhuTungThayThe; ?></td>
                            <td style="width: 5%" class="center">-</td>
                            <td style="width: 5%" class="center">-</td>
                            <td style="width: 5%;" class="center">-</td>
                            <td style="width: 5%;" class="center">-</td>
                            <td style="width: 5%;" class="center">-</td>
                            <td style="width: 5%;" class="center">-</td>
                            <td style="width: 10%;" class="center">-</td>
                        </tr>
                        <?php $i++; ?>
                    <?php endif;?>
				<?php endforeach; ?>
 
				<?php if ($i < 10): ?>
				<?php for ($iTemp = $i; $iTemp <= 10; $iTemp++): ?>
				<tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
                    <td>&nbsp;</td>
				</tr>
				<?php endfor; ?>
				<?php endif; ?>
				</table>
				<div class="round-button">
				    <a class="round-button-circle" href="#" onclick="popupObjectInsert(<?php echo $this->nodeifid ?>, 1, 'OCauTrucThietBi', {OCauTrucThietBi_TrucThuoc: '<?php echo $this->component->IOID; ?>'}, function() {einfo_load_tab_for_component(1);});">+</a>
				</div>
				</div>
			</fieldset>
		</div>
	</div>

				<script>
	$('.einfo_componentdetail_edit_control').each(function(){ $(this).hide(); });
	$('#einfo_componentdetail_sparepart tr').hover(function(){ $(this).addClass('marker'); $(this).find('.einfo_componentdetail_edit_control').show();}
	, function(){ $(this).removeClass('marker'); $(this).find('.einfo_componentdetail_edit_control').hide();});
</script>

<?php endif;?>