<script>
    var m506_myoutputs_more =
    {
        editTask : function (ifid) {
            location.href = '/mobile/m506/myoutputs/edit?fid=M506&ifid='+ifid;
        }
    }

</script>

<?php $i = $this->end;?>
<?php foreach($this->list as $item):?>
    <?php $i++;?>
    <div class="mobile-box-data-line <?php echo $i%2==0?'bglightblue':'';?>" ifid="<?php echo $item->IFID_M506;?>"
         onclick="m506_myoutputs_more.editTask(<?php echo $item->IFID_M506;?>)">
        <div>

                <span class="title" >
                    <?php echo $i;?>. <?php echo $item->SoChungTu;?></span> <span class="<?php echo $item->Color;?>">(<?php echo $item->Name;?>)
                    <span>
        </div>

        <div>
            <table cellpadding="0" cellspacing="0" border="0" style="width: 100%;">
                <tr>
                    <td style="width: 100px;">
                        Kho:
                    </td>

                    <td>
                        <?php echo $item->Kho;?>
                    </td>
                </tr>

                <tr>
                    <td>
                        Loại xuât kho:
                    </td>

                    <td>
                        <?php echo $item->LoaiXuatKho;?>
                    </td>
                </tr>

                <tr>
                    <td>
                        Ngày:
                    </td>

                    <td>
                        <?php echo Qss_Lib_Date::mysqltodisplay($item->NgayChungTu);?>
                    </td>
                </tr>

                <tr>
                    <td>
                        Mô tả:
                    </td>

                    <td class="left">
                        <?php echo $item->MoTa;?>
                    </td>
                </tr>


                <tr>
                    <td>
                        Vật tư:
                    </td>

                    <td>
                        &nbsp;
                    </td>
                </tr>
            </table>

        </div>

        <div>
            <?php if($item->VatTuYeuCauDangTable):?>
                <table cellpadding="0" cellspacing="0" border="0" style="width: 100%;" class="vattu_table">
                    <tr>
                        <td style="width: 20%"></td>
                        <td style="width: 50%"></td>
                        <td style="width: 15%"></td>
                        <td style="width: 15%"></td>
                    </tr>

                    <?php echo $item->VatTuYeuCauDangTable;?>
                </table>
            <?php endif;?>
        </div>
    </div>
<?php endforeach;?>