<script>
    var m506_approve = {
        approveList : function () {
            openModule('', '/user/form?fid=M506&filter_uid=0');
        }
    };


</script>

<div id="m000_content">
    <div class="mobile-box-wrap">
        <?php if($this->rightApproveM506):?>
            <div class="mobile-box-sub-line">
                <span href="#1" onclick="m506_approve.approveList();">Duyệt yêu cầu xuất kho (<span class="red bold"><?php echo $this->countOut;?></span>)</span>
            </div>
        <?php endif;?>
    </div>
</div>