<script>
    var m506_myoutputs = {
        myList : function () {
            openModule('', '/user/form?fid=M506&filter_uid=<?php echo $this->userinfo->user_id;?>');
        },

        addOutput : function () {
            location.href = '/mobile/m506/myoutputs/edit?fid=M506';
        }
    };
</script>

<div id="m000_content">
    <div class="mobile-box-wrap">
        <?php if($this->rightCreateM506):?>
            <div class="mobile-box-sub-line">
                <span href="#1" onclick="m506_myoutputs.myList();">Phiếu xuất kho của tôi (<span class="red bold"><?php echo $this->countOutByUser;?></span>)</span>

                <button type="button" style=" position: absolute; top:auto; right: 10px; font-weight: bold"
                        class="btn btn_main_top" onclick="rowInsert('M506');">
                    Thêm
                </button>
            </div>
        <?php endif;?>
    </div>
</div>