<div id="horizontal-toolbar" class="horizontal-toolbar">
	<div title="<?php echo $this->_translate(12)?>"
		onclick="rowParamInsert()" class="btn_main_top">
		<a class="icon-32-new" href="#1"></a>
	</div>
	<div ID="Update" onClick="rowParamEdit()"
		title="<?php echo $this->_translate(13)?>"
		class="btn_main_top btn_disabled">
		<a class="icon-32-edit" href="#1"></a>
	</div>
	<div ID="Delete" onClick="rowParamDelete()"
		title="<?php echo $this->_translate(14)?>"
		class="btn_main_top btn_disabled">
		<a class="icon-32-delete" href="#1"></a>
	</div>
</div>
<div class="clear"></div>
<div id="view">
	<div id="item-actions">
		<ul>
			<li class="item-action active"><a href="#1"><span><?php echo $this->_translate(67)?>
				</span> </a></li>
		</ul>
	</div>
	<table class="grid">
		<tr>
			<th><?php echo $this->_translate(68)?></th>
			<th><?php echo $this->_translate(69)?></th>
			<th><?php echo $this->_translate(64)?></th>
		</tr>
		<?php foreach($this->params as $param):?>
		<tr id="<?php echo $param->PID?>" onclick="rowCLK(this);">
			<td><?php echo $param->PID?></td>
			<td><?php echo $param->Value?></td>
			<td><?php echo $param->Description?></td>
		</tr>
		<?php endforeach;?>
	</table>
</div>
