<div class="navmenutab tabs-menu"><ul><li class="splash"></li><li class="active normal"><a href="#form_tab_0"><span><?php echo Qss_Lib_System::getUIGroupName(0,$this->user->user_lang);?></span></a></li></ul></div><div style="border-top: 1px solid #999; clear: both;"></div><div class="ui_box" id="form_tab_0"><div class="ui_box_s50_left"><fieldset><div class="ui_box_line ODuLieuChamCongHangNgay_MaNhanVien" >
												<div class="label">
												<label><?php echo $this->objects["ODuLieuChamCongHangNgay"]->getFieldByCode("MaNhanVien")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODuLieuChamCongHangNgay"]->sz_fGetFormFieldElement("MaNhanVien",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODuLieuChamCongHangNgay_TenNhanVien" >
												<div class="label">
												<label><?php echo $this->objects["ODuLieuChamCongHangNgay"]->getFieldByCode("TenNhanVien")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODuLieuChamCongHangNgay"]->sz_fGetFormFieldElement("TenNhanVien",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODuLieuChamCongHangNgay_NgayCong" >
												<div class="label">
												<label><?php echo $this->objects["ODuLieuChamCongHangNgay"]->getFieldByCode("NgayCong")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODuLieuChamCongHangNgay"]->sz_fGetFormFieldElement("NgayCong",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODuLieuChamCongHangNgay_CaLamViec" >
												<div class="label">
												<label><?php echo $this->objects["ODuLieuChamCongHangNgay"]->getFieldByCode("CaLamViec")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODuLieuChamCongHangNgay"]->sz_fGetFormFieldElement("CaLamViec",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODuLieuChamCongHangNgay_CaDiLamThucTe" >
												<div class="label">
												<label><?php echo $this->objects["ODuLieuChamCongHangNgay"]->getFieldByCode("CaDiLamThucTe")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODuLieuChamCongHangNgay"]->sz_fGetFormFieldElement("CaDiLamThucTe",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODuLieuChamCongHangNgay_LoaiNgayNghi" >
												<div class="label">
												<label><?php echo $this->objects["ODuLieuChamCongHangNgay"]->getFieldByCode("LoaiNgayNghi")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODuLieuChamCongHangNgay"]->sz_fGetFormFieldElement("LoaiNgayNghi",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODuLieuChamCongHangNgay_NgayVao" >
												<div class="label">
												<label><?php echo $this->objects["ODuLieuChamCongHangNgay"]->getFieldByCode("NgayVao")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODuLieuChamCongHangNgay"]->sz_fGetFormFieldElement("NgayVao",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODuLieuChamCongHangNgay_GioVao" >
												<div class="label">
												<label><?php echo $this->objects["ODuLieuChamCongHangNgay"]->getFieldByCode("GioVao")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODuLieuChamCongHangNgay"]->sz_fGetFormFieldElement("GioVao",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODuLieuChamCongHangNgay_NgayRa" >
												<div class="label">
												<label><?php echo $this->objects["ODuLieuChamCongHangNgay"]->getFieldByCode("NgayRa")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODuLieuChamCongHangNgay"]->sz_fGetFormFieldElement("NgayRa",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODuLieuChamCongHangNgay_GioRa" >
												<div class="label">
												<label><?php echo $this->objects["ODuLieuChamCongHangNgay"]->getFieldByCode("GioRa")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODuLieuChamCongHangNgay"]->sz_fGetFormFieldElement("GioRa",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODuLieuChamCongHangNgay_LyDoThieuInOut" >
												<div class="label">
												<label><?php echo $this->objects["ODuLieuChamCongHangNgay"]->getFieldByCode("LyDoThieuInOut")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODuLieuChamCongHangNgay"]->sz_fGetFormFieldElement("LyDoThieuInOut",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODuLieuChamCongHangNgay_VaoMuon" >
												<div class="label">
												<label><?php echo $this->objects["ODuLieuChamCongHangNgay"]->getFieldByCode("VaoMuon")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODuLieuChamCongHangNgay"]->sz_fGetFormFieldElement("VaoMuon",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODuLieuChamCongHangNgay_RaSom" >
												<div class="label">
												<label><?php echo $this->objects["ODuLieuChamCongHangNgay"]->getFieldByCode("RaSom")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODuLieuChamCongHangNgay"]->sz_fGetFormFieldElement("RaSom",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODuLieuChamCongHangNgay_TongPhutMuonSom" >
												<div class="label">
												<label><?php echo $this->objects["ODuLieuChamCongHangNgay"]->getFieldByCode("TongPhutMuonSom")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODuLieuChamCongHangNgay"]->sz_fGetFormFieldElement("TongPhutMuonSom",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODuLieuChamCongHangNgay_LyDoMuonSom" >
												<div class="label">
												<label><?php echo $this->objects["ODuLieuChamCongHangNgay"]->getFieldByCode("LyDoMuonSom")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODuLieuChamCongHangNgay"]->sz_fGetFormFieldElement("LyDoMuonSom",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODuLieuChamCongHangNgay_SoGioTangCaTuan" >
												<div class="label">
												<label><?php echo $this->objects["ODuLieuChamCongHangNgay"]->getFieldByCode("SoGioTangCaTuan")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODuLieuChamCongHangNgay"]->sz_fGetFormFieldElement("SoGioTangCaTuan",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODuLieuChamCongHangNgay_SoGioTangCaThang" >
												<div class="label">
												<label><?php echo $this->objects["ODuLieuChamCongHangNgay"]->getFieldByCode("SoGioTangCaThang")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODuLieuChamCongHangNgay"]->sz_fGetFormFieldElement("SoGioTangCaThang",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODuLieuChamCongHangNgay_SoGioTangCaNam" >
												<div class="label">
												<label><?php echo $this->objects["ODuLieuChamCongHangNgay"]->getFieldByCode("SoGioTangCaNam")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODuLieuChamCongHangNgay"]->sz_fGetFormFieldElement("SoGioTangCaNam",$this->user,$this->dialog);?>
												</div>
												</div></fieldset></div></div>