<div class="navmenutab tabs-menu"><ul><li class="splash"></li><li class="active normal"><a href="#form_tab_0"><span><?php echo Qss_Lib_System::getUIGroupName(0,$this->user->user_lang);?></span></a></li></ul></div><div style="border-top: 1px solid #999; clear: both;"></div><div class="ui_box" id="form_tab_0"><div class="ui_box_s50_left"><fieldset><legend><span class="<?php echo $this->form->getStatusData($this->user->user_lang)->Color?>">(<?php echo $this->form->getStatusData($this->user->user_lang)->Name?>)</span></legend><div class="ui_box_line ODangKyLamThem_MaNhanVien" >
												<div class="label">
												<label><?php echo $this->objects["ODangKyLamThem"]->getFieldByCode("MaNhanVien")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODangKyLamThem"]->sz_fGetFormFieldElement("MaNhanVien",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODangKyLamThem_TenNhanVien" >
												<div class="label">
												<label><?php echo $this->objects["ODangKyLamThem"]->getFieldByCode("TenNhanVien")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODangKyLamThem"]->sz_fGetFormFieldElement("TenNhanVien",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODangKyLamThem_LoaiTangCa" >
												<div class="label">
												<label><?php echo $this->objects["ODangKyLamThem"]->getFieldByCode("LoaiTangCa")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODangKyLamThem"]->sz_fGetFormFieldElement("LoaiTangCa",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODangKyLamThem_GioDangKy" >
												<div class="label">
												<label><?php echo $this->objects["ODangKyLamThem"]->getFieldByCode("GioDangKy")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODangKyLamThem"]->sz_fGetFormFieldElement("GioDangKy",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODangKyLamThem_NgayDangKy" >
												<div class="label">
												<label><?php echo $this->objects["ODangKyLamThem"]->getFieldByCode("NgayDangKy")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODangKyLamThem"]->sz_fGetFormFieldElement("NgayDangKy",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODangKyLamThem_CaLamViec" >
												<div class="label">
												<label><?php echo $this->objects["ODangKyLamThem"]->getFieldByCode("CaLamViec")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODangKyLamThem"]->sz_fGetFormFieldElement("CaLamViec",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODangKyLamThem_ThoiGianBatDau" >
												<div class="label">
												<label><?php echo $this->objects["ODangKyLamThem"]->getFieldByCode("ThoiGianBatDau")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODangKyLamThem"]->sz_fGetFormFieldElement("ThoiGianBatDau",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODangKyLamThem_ThoiGianKetThuc" >
												<div class="label">
												<label><?php echo $this->objects["ODangKyLamThem"]->getFieldByCode("ThoiGianKetThuc")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODangKyLamThem"]->sz_fGetFormFieldElement("ThoiGianKetThuc",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODangKyLamThem_PhuongThucThanhToan" >
												<div class="label">
												<label><?php echo $this->objects["ODangKyLamThem"]->getFieldByCode("PhuongThucThanhToan")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODangKyLamThem"]->sz_fGetFormFieldElement("PhuongThucThanhToan",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODangKyLamThem_LyDoTangCa" >
												<div class="label">
												<label><?php echo $this->objects["ODangKyLamThem"]->getFieldByCode("LyDoTangCa")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODangKyLamThem"]->sz_fGetFormFieldElement("LyDoTangCa",$this->user,$this->dialog);?>
												</div>
												</div></fieldset></div></div>