<div class="navmenutab tabs-menu"><ul><li class="splash"></li><li class="active normal"><a href="#form_tab_3"><span><?php echo Qss_Lib_System::getUIGroupName(3,$this->user->user_lang);?></span></a></li></ul></div><div style="border-top: 1px solid #999; clear: both;"></div><div class="ui_box" id="form_tab_3"><div class="ui_box_s50_left"><fieldset><legend><?php echo Qss_Lib_System::getUIBoxName(7,$this->user->user_lang);?></legend><div class="ui_box_line ODanhSachNhanVien_MaNhanVien" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("MaNhanVien")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("MaNhanVien",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_TenNhanVien" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("TenNhanVien")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("TenNhanVien",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_CongTy" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("CongTy")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("CongTy",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_MaPhongBan" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("MaPhongBan")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("MaPhongBan",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_TenPhongBan" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("TenPhongBan")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("TenPhongBan",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_NgayVaoLam" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("NgayVaoLam")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("NgayVaoLam",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_ChucDanh" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("ChucDanh")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("ChucDanh",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_ChucVu" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("ChucVu")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("ChucVu",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_TenTruyCap" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("TenTruyCap")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("TenTruyCap",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_NgaySinh" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("NgaySinh")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("NgaySinh",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_GioiTinh" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("GioiTinh")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("GioiTinh",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_MSTCaNhan" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("MSTCaNhan")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("MSTCaNhan",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_SoCMND" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("SoCMND")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("SoCMND",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_TheCanCuoc" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("TheCanCuoc")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("TheCanCuoc",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_DanToc" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("DanToc")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("DanToc",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_TonGiao" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("TonGiao")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("TonGiao",$this->user,$this->dialog);?>
												</div>
												</div></fieldset></div><div class="ui_box_s50_right"><fieldset><legend><?php echo Qss_Lib_System::getUIBoxName(8,$this->user->user_lang);?></legend><div class="ui_box_line ODanhSachNhanVien_AnhDaiDien" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("AnhDaiDien")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("AnhDaiDien",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_DienThoai" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("DienThoai")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("DienThoai",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_Email" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("Email")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("Email",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_DiaChi" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("DiaChi")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("DiaChi",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_NguyenQuan" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("NguyenQuan")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("NguyenQuan",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_DiaChiTamChu" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("DiaChiTamChu")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("DiaChiTamChu",$this->user,$this->dialog);?>
												</div>
												</div></fieldset><fieldset><legend><?php echo Qss_Lib_System::getUIBoxName(9,$this->user->user_lang);?></legend><div class="ui_box_line ODanhSachNhanVien_LichLamViec" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("LichLamViec")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("LichLamViec",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_TrungTamChiPhi" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("TrungTamChiPhi")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("TrungTamChiPhi",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_ThoiViec" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("ThoiViec")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("ThoiViec",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODanhSachNhanVien_TaiKhoanNganHang" >
												<div class="label">
												<label><?php echo $this->objects["ODanhSachNhanVien"]->getFieldByCode("TaiKhoanNganHang")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODanhSachNhanVien"]->sz_fGetFormFieldElement("TaiKhoanNganHang",$this->user,$this->dialog);?>
												</div>
												</div></fieldset></div></div>