<div class="navmenutab tabs-menu"><ul><li class="splash"></li><li class="active normal"><a href="#form_tab_0"><span><?php echo Qss_Lib_System::getUIGroupName(0,$this->user->user_lang);?></span></a></li></ul></div><div style="border-top: 1px solid #999; clear: both;"></div><div class="ui_box" id="form_tab_0"><div class="ui_box_s50_left"><fieldset><div class="ui_box_line ODieuChinhLuong_MaNV" >
												<div class="label">
												<label><?php echo $this->objects["ODieuChinhLuong"]->getFieldByCode("MaNV")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODieuChinhLuong"]->sz_fGetFormFieldElement("MaNV",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODieuChinhLuong_TenNV" >
												<div class="label">
												<label><?php echo $this->objects["ODieuChinhLuong"]->getFieldByCode("TenNV")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODieuChinhLuong"]->sz_fGetFormFieldElement("TenNV",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODieuChinhLuong_Thang" >
												<div class="label">
												<label><?php echo $this->objects["ODieuChinhLuong"]->getFieldByCode("Thang")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODieuChinhLuong"]->sz_fGetFormFieldElement("Thang",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODieuChinhLuong_Nam" >
												<div class="label">
												<label><?php echo $this->objects["ODieuChinhLuong"]->getFieldByCode("Nam")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODieuChinhLuong"]->sz_fGetFormFieldElement("Nam",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODieuChinhLuong_LoaiDieuChinh" >
												<div class="label">
												<label><?php echo $this->objects["ODieuChinhLuong"]->getFieldByCode("LoaiDieuChinh")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODieuChinhLuong"]->sz_fGetFormFieldElement("LoaiDieuChinh",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODieuChinhLuong_SoTien" >
												<div class="label">
												<label><?php echo $this->objects["ODieuChinhLuong"]->getFieldByCode("SoTien")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODieuChinhLuong"]->sz_fGetFormFieldElement("SoTien",$this->user,$this->dialog);?>
												</div>
												</div><div class="ui_box_line ODieuChinhLuong_PhanTram" >
												<div class="label">
												<label><?php echo $this->objects["ODieuChinhLuong"]->getFieldByCode("PhanTram")->szFieldName;?></label>
												</div>
												<div class="element" >
												<?php echo $this->objects["ODieuChinhLuong"]->sz_fGetFormFieldElement("PhanTram",$this->user,$this->dialog);?>
												</div>
												</div></fieldset></div></div>