<?php
$excel_col   = array_flip(Qss_Lib_Const::$EXCEL_COLUMN);
$bg          = "#EEEEEE";
$row         = 2;
$title       = $this->_translate(1) . ' ('
. $this->_translate(2) . ' '
. $this->startDate . ' '
. $this->_translate(3)
. $this->endDate. ') ';
$countIn     = count((array)$this->InType);
$countOut    = count((array)$this->OutType);
$totalColumn = 8 + $countIn + $countOut;
?>
<form id="excel" method="post" action="/report/index/excel" target="new">
	<input type="hidden" id="content" name="content" value="">
</form>
<div class="landscape">
	<excel orientation="landscape" font-name="Arial" font-size="9"
		margin-left="0.5" margin-right="0.5" margin-top="0.75"
		margin-bottom="0.75" />

	<div id="head_print">
	<?php echo $this->views->Common->Landscape() ?>

		<center>
			<h2>
				<xls row="<?php echo $row?>" column="A"
					column-merge="<?php echo $excel_col[$totalColumn]?>" font-size="12"
					wrap-text="1" h-align="center" v-align="center"> <?php echo $title;?></xls>
			</h2>
		</center>
	</div>
	<?php $row++ ?>


	<div id="container">
		<table cellspacing="0" cellpadding="0" border="1" id="" class="border">

		<?php $begin = 0; ?>
			<tr class="bggrey">
			<?php /*
			<th style="width:2%;"
			class="<?php echo 'col'.$begin;?>"

			rowspan="2">
			<!-- STT -->
			<xls row="<?php echo $row?>"
			row-merge ="1"
			column="<?php echo $excel_col[++$begin]?>"
			width="10"
			wrap-text="1" h-align="center"
			v-align="center"
			border="1"
			bold="1"
			repeat="1"><?php echo $this->_translate(8);?></xls>
			</th>
			*
			*/?>

				<th style="width: 12%;" class="<?php echo 'col'.$begin;?>"
					rowspan="2">
					<!-- Ten MH --> <xls row="<?php echo $row?>" row-merge="1"
						column="<?php echo $excel_col[++$begin]?>" width="10"
						wrap-text="1" h-align="center" v-align="center" border="1"
						bold="1" repeat="1"> <?php echo $this->_translate(5);?></xls>
				</th>

				<th style="width: 12%;" class="<?php echo 'col'.$begin;?>"
					rowspan="2">
					<!-- Ma MH--> <xls row="<?php echo $row?>" row-merge="1"
						column="<?php echo $excel_col[++$begin]?>" width="10"
						wrap-text="1" h-align="center" v-align="center" border="1"
						bold="1" repeat="1"> <?php echo $this->_translate(4);?></xls>
				</th>

				<th style="width: 5%;" class="<?php echo 'col'.$begin;?>"
					rowspan="2">
					<!-- DVT --> <xls row="<?php echo $row?>" row-merge="1"
						column="<?php echo $excel_col[++$begin]?>" width="10"
						wrap-text="1" h-align="center" v-align="center" border="1"
						bold="1" repeat="1"> <?php echo $this->_translate(6);?></xls>
				</th>

				<?php $beginRow2 = $begin;?>
				<th style="width: 5%;" class="<?php echo 'col'.$begin;?>"
					rowspan="2">
					<!-- Ton dau ky  --> <xls row="<?php echo $row?>" row-merge="1"
						column="<?php echo $excel_col[++$begin]?>" width="10"
						wrap-text="1" h-align="center" v-align="center" border="1"
						bold="1" repeat="1"> <?php echo $this->_translate(9);?></xls>
				</th>

				<?php $begin++;?>
				<th style="width: 31%;" class="<?php echo 'col'.$begin;?>"
					colspan="<?php echo $countIn?>">
					<!-- Nhap trong ky --> <xls row="<?php echo $row?>"
						column="<?php echo $excel_col[++$begin]?>"
						column-merge="<?php echo $excel_col[($begin + $countIn)]?>"
						width="10" wrap-text="1" h-align="center" v-align="center"
						border="1" bold="1" repeat="1"> <?php echo $this->_translate(10);?></xls>
				</th>

				<?php $begin += 1;?>
				<th style="width: 31%;" class="<?php echo 'col'.$begin;?>"
					colspan="<?php echo $countOut?>">
					<!-- Xuat trong ky --> <xls row="<?php echo $row?>"
						column="<?php echo $excel_col[++$begin]?>"
						column-merge="<?php echo $excel_col[($begin + $countOut)]?>"
						width="10" wrap-text="1" h-align="center" v-align="center"
						border="1" bold="1" repeat="1"> <?php echo $this->_translate(11);?></xls>
				</th>

				<?php $begin += 1;?>
				<th style="width: 5%;" class="<?php echo 'col'.$begin;?>"
					rowspan="2">
					<!-- Ton cuoi ky --> <xls row="<?php echo $row?>" row-merge="1"
						column="<?php echo $excel_col[++$begin]?>" width="10"
						wrap-text="1" h-align="center" v-align="center" border="1"
						bold="1" repeat="1"> <?php echo $this->_translate(12);?></xls>
				</th>
			</tr>
			<?php $row++?>

			<tr class="bggrey">
			<?php $begin = $beginRow2;?>
			<?php foreach($this->InType as $type):?>
				<th style="" class="<?php echo 'col'.$begin;?>">
					<!-- Nhap trong ky --> <xls row="<?php echo $row?>"
						column="<?php echo $excel_col[++$begin]?>" width="10"
						wrap-text="1" h-align="center" v-align="center" border="1"
						bold="1" repeat="1"> <?php echo $type->Ten;?></xls>
				</th>
				<?php endforeach;?>

				<?php foreach($this->OutType as $type):?>
				<th style="" class="<?php echo 'col'.$begin;?>">
					<!-- Xuat trong ky --> <xls row="<?php echo $row?>"
						column="<?php echo $excel_col[++$begin]?>" width="10"
						wrap-text="1" h-align="center" v-align="center" border="1"
						bold="1" repeat="1"> <?php echo $type->Ten;?></xls>
				</th>
				<?php endforeach;?>
			</tr>
			<?php $row++?>


			<?php $stt = 0;?>
			<?php foreach (@(array)$this->report as $item): // in report?>

			<?php $begin = 0; ?>
			<tr>
			<?php /*
			<td class="center <?php echo 'col'.$begin;?>">
			<!-- STT -->
			<xls row="<?php echo $row?>"
			column="<?php echo $excel_col[++$begin]?>"
			wrap-text="1"
			h-align="center"
			v-align="center"
			border="1"><?php echo ++$stt;?></xls>
			</td>
			*
			*/?>
				<td class="left <?php echo 'col'.$begin;?>">
					<!-- Ten MH --> <xls row="<?php echo $row?>"
						column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
						h-align="left" v-align="center" border="1"> <?php echo $item['ItemName'];?></xls>
				</td>


				<td class="left <?php echo 'col'.$begin;?>">
					<!-- Ma MH --> <xls row="<?php echo $row?>"
						column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
						h-align="left" v-align="center" border="1"> <?php echo $item['ItemCode']?></xls>
				</td>

				<td class="left <?php echo 'col'.$begin;?>">
					<!-- DVT --> <xls row="<?php echo $row?>"
						column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
						h-align="left" v-align="center" border="1"> <?php echo $item['UOM'];?></xls>
				</td>


				<td class="right <?php echo 'col'.$begin;?>">
					<!-- Ton dau ky --> <xls row="<?php echo $row?>"
						column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
						h-align="right" v-align="center" border="1"> <?php echo @(double)$item['OpeningStock'];?></xls>
				</td>

				<?php foreach($this->InType as $type):?>
				<td class="right <?php echo 'col'.$begin;?>">
					<!-- Nhap trong ky --> <xls row="<?php echo $row?>"
						column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
						h-align="right" v-align="center" border="1"> <?php echo @(double)$item['Input'][$type->IOID]?></xls>
				</td>
				<?php					endforeach;?>

				<?php foreach($this->OutType as $type):?>
				<td class="right <?php echo 'col'.$begin;?>">
					<!-- Xuat trong ky --> <xls row="<?php echo $row?>"
						column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
						h-align="right" v-align="center" border="1"> <?php echo @(double)$item['Output'][$type->IOID]?></xls>
				</td>
				<?php					endforeach;?>

				<td class="right <?php echo 'col'.$begin;?>">
					<!-- Ton cuoi ky --> <xls row="<?php echo $row?>"
						column="<?php echo $excel_col[++$begin]?>" wrap-text="1"
						h-align="right" v-align="center" border="1"> <?php echo @(double)$item['EndingStock'];?></xls>
				</td>
			</tr>
			<?php $row++ ?>
			<?php endforeach;// in report?>
		</table>
	</div>
</div>
