<?php
$excel_col      = array_flip(Qss_Lib_Const::$EXCEL_COLUMN);
$bg             = Qss_Lib_Extra_Const::REPORT_EXCEL_THEAD_COLOR;
$row            = 2;
$totalColumn    = 9;
$colWidths      = array(1, 3, 3, 2, 2, 5, 2, 2, 3);
$excelColWidths = Qss_Lib_Report::convertPxColumnWidthToExcelWidth($colWidths);
$autoFit        = Qss_Lib_Report::changeWidthToFitScreen($colWidths);
$stt            = 0;
?>

<form id="excel" method="post" action="/report/index/excel" target="new">
    <input type="hidden" id="content" name="content" value="">
</form>

<div class="portrait">
    <excel
        orientation="<?php echo Qss_Lib_Extra_Const::REPORT_ORIENTATION_PORTRAIT;?>"
        font-name="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_FONT_NAME;?>"
        font-size="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_FONT_SIZE;?>"
        margin-left="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_MARGIN_LEFT;?>"
        margin-right="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_MARGIN_RIGHT;?>"
        margin-top="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_MARGIN_TOP;?>"
        margin-bottom="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_MARGIN_BOTTOM;?>"  />

    <!-- REPORT TITLE -->
	<div id="head_print">
		<?php echo $this->views->Common->Portrait() ?>
		<center>
		    <h2>
			<xls
			    row="<?php echo $row ?>"
			    column="A"
			    column-merge="<?php echo $excel_col[$totalColumn] ?>"
			    font-size="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_TITLE_FONT_SIZE;?>"
			    wrap-text="1"
                bold="1"
			    h-align="center"
			    v-align="center" > DỰ TOÁN VẬT TƯ, PHỤ TÙNG, NHIÊN LIỆU     </xls>
		    </h2>
            <?php $row++ ?>

            <h2>
                <xls
                    row="<?php echo $row ?>"
                    column="A"
                    column-merge="<?php echo $excel_col[$totalColumn] ?>"
                    font-size="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_TITLE_FONT_SIZE;?>"
                    wrap-text="1"
                    bold="1"
                    h-align="center"
                    v-align="center" >  (Căn cứ vào biên bản giám định kỹ thuật bước 1) </xls>
            </h2>
            <?php $row++ ?>

            <h2>
                <xls
                    row="<?php echo $row ?>"
                    column="A"
                    column-merge="<?php echo $excel_col[$totalColumn] ?>"
                    font-size="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_TITLE_FONT_SIZE;?>"
                    wrap-text="1"
                    bold="1"
                    h-align="center"
                    v-align="center" >  Tên TSCĐ:...................................................... </xls>
            </h2>
            <?php $row++ ?>

            <h2>
                <xls
                    row="<?php echo $row ?>"
                    column="A"
                    column-merge="<?php echo $excel_col[$totalColumn] ?>"
                    font-size="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_TITLE_FONT_SIZE;?>"
                    wrap-text="1"
                    bold="1"
                    h-align="center"
                    v-align="center" >  Đơn vị quản lý:............................................... </xls>
            </h2>
            <?php $row++ ?>

            <h2>
                <xls
                    row="<?php echo $row ?>"
                    column="A"
                    column-merge="<?php echo $excel_col[$totalColumn] ?>"
                    font-size="<?php echo Qss_Lib_Extra_Const::REPORT_EXCEL_TITLE_FONT_SIZE;?>"
                    wrap-text="1"
                    bold="1"
                    h-align="center"
                    v-align="center" >  Đơn vị sửa chữa:............................................ </xls>
            </h2>
            <?php $row++ ?>
		</center>
	</div><!-- end div#head_print -->
    <?php $row++ ?>
    <br/>


    <!-- REPORT DATA -->
    <div id="container">
        <table cellpadding="0" cellspacing="0" border="0" class="border" style="">
            <!-- COLUMN TITLE -->
            <tr class="bggrey">
                <?php $begin = 0;?>
                <!-- title -->
                <th class="center"
                    rowspan="2"
                    style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        row-merge="1"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>">STT</xls>
                </th>

                <!-- TÊN CHI TIẾT -->
                <th class="center"
                    rowspan="2"
                    style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        row-merge="1"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>">MÃ VẬT TƯ</xls>
                </th>


                <!-- QUY CÁCH -->
                <th class="center"
                    rowspan="2"
                    style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        row-merge="1"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>">TÊN VÀ QUY CÁCH VẬT TƯ PHỤ TÙNG</xls>
                </th>

                <!-- ĐVT -->
                <th class="center"
                    rowspan="2"
                    style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        row-merge="1"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>">ĐVT</xls>
                </th>

                <!-- SỐ LƯỢNG -->
                <th class="center"
                    rowspan="2"
                    style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        row-merge="1"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>">SỐ LƯỢNG</xls>
                </th>

                <!-- TRỌNG LƯỢNG -->
                <th class="center"
                    rowspan="2"
                    style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        row-merge="1"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>">TRỌNG LƯỢNGT</xls>
                </th>

                <!-- DỰ KIẾN NỘP CŨ -->
                <th class="center"
                    colspan="2"
                    >
                    <xls
                        row="<?php echo $row?>"

                        column="<?php echo $excel_col[++$begin]?>"
                        column-merge="<?php echo $excel_col[($begin + 1)]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>">DỰ KIẾN NỘP CŨ</xls>
                </th>
                <?php $bienPhapXuLyRow = $begin;?>
                <?php $begin = $begin + 1;?>

                <!--  GHI CHÚ -->
                <th class="center"
                    rowspan="2"
                    style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        row-merge="1"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>">GHI CHÚ </xls>
                </th>
            </tr>
            <?php $row++;?>

            <tr class="bggrey">
                <?php $begin = $bienPhapXuLyRow - 1;;?>
                <!--  THAY MỚI-->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"> SỐ LƯỢNG</xls>
                </th>

                <!--  TRỌNG LƯỢNG-->
                <th class="center" style="width:<?php echo $autoFit[$begin];?>px">
                    <xls
                        row="<?php echo $row?>"
                        width="<?php echo $excelColWidths[$begin];?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="center"
                        h-align="center"
                        border="1"
                        repeat="1"
                        bold="1"
                        bgcolor="<?php echo $bg;?>"> TRỌNG LƯỢNG</xls>
                </th>

            </tr>
            <?php $row++;?>


            <!-- COLUMN DATA -->
            <?php //for($i = 0; $i <=5 ; $i++):?>
            <?php foreach($this->com as $data): // In bao cao?>
            <tr>
                <?php $begin = 0;?>
                <!-- STT -->
                <td class="center" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="center"
                        border="1"
                        ><?php echo ++$stt;?></xls>
                </td>


                <!-- MÃ VẬT TƯ -->
                <td class="left" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="left"
                        border="1"
                        ><?php echo @$this->detail[$data->IOID]->MaPhuTung;?></xls>
                </td>

                <!-- TÊN VÀ QUY CÁCH VẬT TƯ PHỤ TÙNG -->
                <td class="left" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="left"
                        border="1"
                        ><?php echo $data->BoPhan;;?></xls>
                </td>

                <!-- ĐVT-->
                <td class="left" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="left"
                        border="1"
                        ><?php echo @$this->detail[$data->IOID]->DonViTinh;?></xls>
                </td>

                <!-- SỐ LƯỢNG-->
                <td class="right" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="right"
                        border="1"
                        ><?php echo @$this->detail[$data->IOID]->SoLuong;?></xls>
                </td>

                <!-- TRỌNG LƯỢNG -->
                <td class="left" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="left"
                        border="1"
                        ><?php echo @$this->detail[$data->IOID]->TrongLuong;?></xls>
                </td>

                <!--  DỰ KIẾN NỘP CŨ SỐ LƯỢNG-->
                <td class="right" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="right"
                        border="1"
                        ><?php echo @$this->detail[$data->IOID]->DuKienSoLuongNopCu;?></xls>
                </td>

                <!-- DỰ KIẾN NỘP CŨ TRỌNG LƯỢNG -->
                <td class="right" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="right"
                        border="1"
                        ><?php echo @$this->detail[$data->IOID]->DuKienTrongLuongNopCu;?></xls>
                </td>


                <!-- GHI CHÚ-->
                <td class="left" >
                    <xls
                        row="<?php echo $row?>"
                        column="<?php echo $excel_col[++$begin]?>"
                        wrap-text="1"
                        v-align="top"
                        h-align="left"
                        border="1"
                        ><?php echo @$this->detail[$data->IOID]->GhiChu;?></xls>
                </td>
            </tr>
            <?php $row++;?>
            <?php endforeach; // Ket thuc in bao cao?>
            <?php //endfor;?>
        </table><!-- end table.border -->
    </div><!-- end div#container -->
    <br/>
    <?php $row++;?>




    <table>
        <tr>
            <th style="width: 20%;">
                <xls
                    row="<?php echo $row?>"

                    column="<?php echo $excel_col[1]?>"
                    column-merge="<?php echo $excel_col[2]?>"
                    wrap-text="1"
                    v-align="center"
                    h-align="center"
                    bold="1">ĐƠN VỊ SỬA CHỮA</xls></th>
            <th style="width: 20%;">
                <xls
                    row="<?php echo $row?>"
                    column="<?php echo $excel_col[3]?>"
                    column-merge="<?php echo $excel_col[5]?>"
                    wrap-text="1"
                    v-align="center"
                    h-align="center"
                    bold="1">ĐƠN VỊ QUẢN LÝ</xls>  </th>

            <th style="width: 20%;">
                <xls
                    row="<?php echo $row?>"
                    column="<?php echo $excel_col[6]?>"
                    column-merge="<?php echo $excel_col[7]?>"
                    wrap-text="1"
                    v-align="center"
                    h-align="center"
                    bold="1">PHÒNG KỸ THUẬT</xls> </th>
            <th style="width: 20%;">
                <xls
                    row="<?php echo $row?>"
                    column="<?php echo $excel_col[8]?>"
                    column-merge="<?php echo $excel_col[9]?>"
                    wrap-text="1"
                    v-align="center"
                    h-align="center"
                    bold="1">GIÁM ĐỐC</xls> </th>

        </tr>
        <?php $row++ ?>
    </table>
    <?php $row++ ?>
    <?php $row++ ?>
    <?php $row++ ?>
    <br/>
    <br/>
    <br/>

</div><!-- END REPORT -->