<table cellspacing="0" class="grid" id="selecttable">
	<tr>
		<th style="border-left: 1px solid rgb(204, 204, 204);"><?php echo $this->_translate(27,'STT')?></th>
		<?php if($this->o_Object->bTrack):?>
		<th><?php echo $this->_translate(29,'Người thực hiện')?></th>
		<?php $this->gridFieldCount++;?>
		<?php endif;?>
		<?php foreach ($this->fields as $field):?>
			<?php if ( $field->bGrid ):?>
		<th><a href="#"
			onclick="selectSort('<?php echo $this->o_Object->FormCode?>','<?php echo $this->o_Object->ObjectCode?>','<?php echo $field->FieldCode?>')"><?php
			echo $field->szFieldName;
			?> <?php if($this->orderfield == $field->FieldCode):?> <img
			border="0/"
			src="../../images/<?php echo ($this->ordertype=='ASC')?'up':'down';?>.gif" />
			<?php endif;?> </a></th>
			<?php endif;?>
		<?php endforeach;?>
		<?php if($this->form->i_Type == Qss_Lib_Const::FORM_TYPE_MODULE):?>
		<?php $this->gridFieldCount++;?>
		<th><a href="#"
			onclick="selectSort('<?php echo $this->o_Object->FormCode?>','<?php echo $this->o_Object->ObjectCode?>','-1')"><?php echo $this->_translate(31,'Tình trạng')?><?php if($this->orderfield == -1):?> <img border="0"
			src="../../images/<?php echo ($this->ordertype=='ASC')?'up':'down';?>.gif" />
			<?php endif;?> </a></th>
			<?php endif;?>
	</tr>
	<?php
	$groupbyvalue = '';
	$groupby = $this->groupby;
	$form_rights = $this->form->i_fGetRights($this->user->user_group_list);
	$i=1;
	?>
	<?php
	foreach ($this->objects as $object):
	?>
	<?php
	$this->o_Object->initData($this->o_Object->i_IFID,$this->o_Object->intDepartmentID,$object->IOID);
	?>
	<?php if($groupby > 0):?>
		<?php $groupbyfield = $this->o_Object->getFieldByCode($groupby);?>
		<?php if($groupbyfield && $groupbyfield->getValue() !== $groupbyvalue):?>
			<tr>
				<td class="groupby" colspan="<?php echo $this->gridFieldCount?>"><?php echo $groupbyfield->sz_fGetDisplay(false,true);?></td>
			</tr>
			<?php $i=1;?>
		<?php endif;?>
		<?php $groupbyvalue = $groupbyfield->getValue();?>
	<?php elseif ($groupby == -1 && $this->form->i_Type == Qss_Lib_Const::FORM_TYPE_MODULE):?>
		<?php if($object->Name !== $groupbyvalue):?>
			<tr>
				<td class="groupby" colspan="<?php echo $this->gridFieldCount?>"><?php echo $object->Name;?></td>
			</tr>
			<?php $i=1;?>
		<?php endif;?>
		<?php $groupbyvalue = $object->Name;?>
	<?php elseif ($groupby == -2):?>
		<?php if($object->UserName !== $groupbyvalue):?>
			<tr>
				<td class="groupby" colspan="<?php echo $this->gridFieldCount?>"><?php echo $object->UserName;?></td>
			</tr>
			<?php $i=1;?>
		<?php endif;?>
		<?php $groupbyvalue = $object->UserName;?>		
	<?php endif;?>
	<?php foreach ($fields as $field)
	{
		if($field->FieldCode == $this->fieldid)
		{
			$vid = $field->intRefIOID;
			$vdisplay = $field->sz_fGetDisplay();
		}
	}
	?>
	<tr class="<?php if($object->Error) echo 'error';?>"
		title="<?php if($object->Error) echo $object->ErrorMessage;?>"
		deptid="<?php echo $object->DepartmentID?>"
		id="<?php echo $object->IFID?>"
		ioid="<?php echo $object->IOID?>"
		vid="<?php echo $vid?>"
		vdisplay="<?php echo $vdisplay?>"
		ondblclick="selectTrace(); return false;" onclick="selectCLK(this);"
	<?php echo ($object->DepartmentID!=$this->user->user_dept_id)?'bgcolor="#f7f9f9"':""?>>
		<td class="nocount"><?php echo $i?></td>
		<?php if($this->o_Object->bTrack):?>
		<td class="data" style="border-left: 1px solid #CCCCCC"><?php echo $object->UserName?></td>
		<?php endif;?>
		<?php foreach ($fields as $field):?>
		<?php if ( $field->bGrid ):?>
		<td class="data <?php echo Qss_Lib_Const::$FIELD_ALIGN[$field->intFieldType-1]?>"><?php
		echo $field->sz_fGetDisplay(false,true);
		?></td>
		<?php endif;?>
		<?php endforeach;?>
		<?php if($this->form->i_Type == Qss_Lib_Const::FORM_TYPE_MODULE):?>
		<td style="width: 80px;"
			class="<?php if($object->Color) echo $object->Color; else echo 'data';?>"><?php echo $object->Name?></td>
			<?php endif;?>
	</tr>
	<?php
	$i++;
	?>
	<?php endforeach;?>
	<tr>
		<th style="border-left: 1px solid rgb(204, 204, 204);">&nbsp;</th>
		<?php foreach ($this->fields as $field):?>
		<?php if ( $field->bGrid ):?>
			<th>&nbsp;</th>
		<?php endif;?>
		<?php endforeach;?>
		<?php if($this->form->i_Type == Qss_Lib_Const::FORM_TYPE_MODULE):?>
		<th style="">&nbsp;</th>
		<?php endif;?>
		<?php if($this->o_Object->bTrack):?>
		<th style="">&nbsp;</th>
		<?php endif;?>
	</tr>
</table>
