<?php
$widths = array(1, 4, 4, 3, 3, 2, 2, 2);
$widths = Qss_Lib_Report::changeWidthToFitScreen3($widths);
$begin  = 0;
?>

<style>
<!--
#log {
	float: right;
	padding: 5px;
}
-->
</style>


<script type="text/javascript">
<!--
function addReport()
{
	var url  = sz_BaseUrl + '/report/dynamic/edit';
	qssAjax.getHtml(url, {}, function(jreturn) {
		$('#qss_combo').html(jreturn);
		$('#qss_combo').dialog({ width: 800,height:500 });
	});
}
function showReport(rid){
	var url  = sz_BaseUrl + '/report/dynamic/detail?reportid='+rid;
	window.location.href = url;
}
function editReport(rid){
	var url  = sz_BaseUrl + '/report/dynamic/edit?reportid='+rid;
	qssAjax.getHtml(url, {}, function(jreturn) {
		$('#qss_combo').html(jreturn);
		$('#qss_combo').dialog({ width: 1000,height:600 });
	});
}
function deleteReport(id)
{
	qssAjax.confirm('<?php echo $this->_translate(14);?>',function(){
		var url = sz_BaseUrl + '/report/dynamic/delete';
		var data = {id:id};
		qssAjax.call(url, data, function(jreturn) {
			var url  = sz_BaseUrl + '/report/dynamic';
			window.location.href = url;
		}, function(jreturn) {
			qssAjax.alert(jreturn.message);
		});
	});
}

//-->
</script>

<div class="clear"></div>
<div id="view">
	<div id="log">
		<button onclick="addReport()" class="btn-custom">Thêm báo cáo</button>
		<br />
	</div>

	<table class="border_table">
		<!-- title -->
		<tr>
			<th width="<?php echo $widths[$begin++];?>%" class="nocount" style="border-bottom: 1px solid #ccc"><?php echo $this->_translate(12); ?>
			</th>
			<th width="<?php echo $widths[$begin++];?>%" style="border-bottom: 1px solid #ccc"><?php echo $this->_translate(2); ?>
			</th>
			<th width="<?php echo $widths[$begin++];?>%" style="border-bottom: 1px solid #ccc"><?php echo $this->_translate(3); ?>
			</th>
			<th width="<?php echo $widths[$begin++];?>%" style="border-bottom: 1px solid #ccc"><?php echo $this->_translate(4); ?>
			</th>
			<th width="<?php echo $widths[$begin++];?>%" style="border-bottom: 1px solid #ccc"><?php echo $this->_translate(13); ?>
			</th>
			<th width="<?php echo $widths[$begin++];?>%" style="border-bottom: 1px solid #ccc">&nbsp;</th>
			<th width="<?php echo $widths[$begin++];?>%" style="border-bottom: 1px solid #ccc">&nbsp;</th>
			<th width="<?php echo $widths[$begin++];?>%" style="border-bottom: 1px solid #ccc">&nbsp;</th>
		</tr>
		<?php $i=1?>
		<?php foreach ($this->reports as $item):?>
		<tr id="<?php //echo $param->PID?>" onclick="">
			<td class="nocount center"><?php echo $i;?></td>
			<td><?php echo $item->Code;?></td>
			<td><?php echo $item->Name;?></td>
			<td><?php echo $item->GroupBy;?></td>
			<td><?php echo $item->OrderBy;?></td>
			<td class="center" style="padding: 1px;">
				<button type="button" class="btn-custom"
						onclick="editReport(<?php echo $item->RID?>)">
					<?php echo $this->_translate(8); ?>
				</button>
			</td>
			<td class="center" style="padding: 1px;">
				<button type="button" class="btn-custom"
					onclick="deleteReport(<?php echo $item->RID?>)">
					<?php echo $this->_translate(9); ?>
				</button>
			</td>
			<td class="center" style="padding: 1px;">
				<button type="button" class="btn-custom"
					onclick="showReport(<?php echo $item->RID?>)">
					<?php echo $this->_translate(11); ?>
				</button>
			</td>
		</tr>
		<?php $i++?>
		<?php endforeach;?>
	</table>
</div>

<div id="qss_trace"></div>
<div id="qss_combo"></div>
