<?php
$width  = 1200;
$widths = array(2,2,2,2,2,2,2,2,3);
$widths = Qss_Lib_Report::changeWidthToFitScreen3($widths);
?>
<div>
    <table id="grid" cellspacing="0" cellpadding="0" border="0" class="grid" >
        <?php $begin = 0;?>
        <thead>
            <tr>
                <th style="width:<?php echo $widths[$begin++];?>%">Số phiếu</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Mã thiết bị</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Tên thiết bị</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Ngày</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Thời gian</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Địa điểm</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Người chịu trách nhiệm</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Tình trạng xử lý</th>
                <th style="width:<?php echo $widths[$begin++];?>%">&nbsp;</th>
            </tr>
        </thead>

        <tbody>
            <?php $ci = 0;?>
            <?php foreach($this->data as $item):?>
                <tr class="" <?php echo ++$ci%2==0?'bgcolor="#f7f9f9"':'';?>>
                    <td class="left">
                        <a href="#1" onclick="popupFormDetail('<?php echo $item->IFID_M747;?>', '<?php echo $this->deptid;?>')"><?php echo $item->SoPhieu;?></a></td>
                    <td class="left"><?php echo $item->MaThietBi;?></td>
                    <td class="left"><?php echo $item->TenThietBi;?></td>
                    <td class="left"><?php echo Qss_Lib_Date::mysqltodisplay($item->Ngay);?></td>
                    <td class="left"><?php echo $item->ThoiGian;?></td>
                    <td class="left"><?php echo $item->DiaDiem;?></td>
                    <td class="center"><?php echo $item->NguoiChiuTranhNhiem;?></td>
                    <td class="center"><?php echo $item->TinhTrangXuLy;?></td>
                    <td class="center" style="padding: 1px;">
                        <button type="button" class="btn btn_main_top"
                                onclick="Static_M174.createOrderFromRequest(<?php echo $item->IFID_M747;?>);">
                            Tạo phiếu bảo trì
                        </button>
                    </td>
                </tr>
            <?php endforeach;?>
        </tbody>

    </table>
</div>

<script>
    $(document).ready(function() {
        var height = $(window).height() - 210 - $('#grid thead').height();//-8
        $('#grid').tableScroll({height:height,width:'100%'});
    });
</script>