<?php
$width  = 1200;
$widths = array(1,1,1,1,1,1,1,1,1);
$widths = Qss_Lib_Report::changeWidthToFitScreen3($widths);
$fields = Qss_Lib_System::getFieldsByObject('M759', 'OPhieuBaoTri');
?>
<div>
    <table id="grid" cellspacing="0" cellpadding="0" border="0" class="grid grid_edit " >
        <?php $begin = 0;?>

        <thead>
            <tr>
                <th style="width:<?php echo $widths[$begin++];?>%"><?php echo $fields->getFieldByCode('SoPhieu')->szFieldName;?></th>
                <th style="width:<?php echo $widths[$begin++];?>%"><?php echo $fields->getFieldByCode('MaThietBi')->szFieldName;?></th>
                <th style="width:<?php echo $widths[$begin++];?>%"><?php echo $fields->getFieldByCode('TenThietBi')->szFieldName;?></th>
                <?php if(Qss_Lib_System::fieldActive('OPhieuBaoTri', 'BoPhan')):?>
                    <th style="width:<?php echo $widths[$begin++];?>%"><?php echo $fields->getFieldByCode('BoPhan')->szFieldName;?></th>
                <?php endif;?>

                <th style="width:<?php echo $widths[$begin++];?>%"><?php echo $fields->getFieldByCode('LoaiBaoTri')->szFieldName;?></th>
                <th style="width:<?php echo $widths[$begin++];?>%"><?php echo $fields->getFieldByCode('TenDVBT')->szFieldName;?></th>
                <th style="width:<?php echo $widths[$begin++];?>%"><?php echo $fields->getFieldByCode('NgayYeuCau')->szFieldName;?></th>
                <th style="width:<?php echo $widths[$begin++];?>%"><?php echo $fields->getFieldByCode('NgayBatDau')->szFieldName;?></th>
                <th style="width:<?php echo $widths[$begin++];?>%"><?php echo $fields->getFieldByCode('Ngay')->szFieldName;?></th>
            </tr>
        </thead>

        <tbody>
            <?php $ci = 0;?>
            <?php foreach($this->dueOrders as $item):?>
                <tr class="" <?php echo ++$ci%2==0?'bgcolor="#f7f9f9"':'';?>>
                    <td class="left">
                        <a href="#1" onclick="popupFormDetail('<?php echo $item->IFID_M759;?>', '<?php echo $this->deptid;?>')"><?php echo $item->SoPhieu;?></a></td>
                    <td class="left"><?php echo $item->MaThietBi;?></td>
                    <td class="left"><?php echo $item->TenThietBi;?></td>
                    <?php if(Qss_Lib_System::fieldActive('OPhieuBaoTri', 'BoPhan')):?>
                        <td class="left"><?php echo $item->BoPhan;?></td>
                    <?php endif;?>
                    <td class="left"><?php echo $item->LoaiBaoTri;?></td>
                    <td class="left"><?php echo $item->TenDVBT;?></td>
                    <td class="center"><?php echo Qss_Lib_Date::mysqltodisplay($item->NgayYeuCau);?></td>
                    <td class="center"><?php echo Qss_Lib_Date::mysqltodisplay($item->NgayBatDau);?></td>
                    <td class="center"><?php echo Qss_Lib_Date::mysqltodisplay($item->Ngay);?></td>
                </tr>
            <?php endforeach;?>
        </tbody>

    </table>
</div>

<script>
    $(document).ready(function() {
        var height = $(window).height() - 210 - $('#grid thead').height();//-8
        $('#grid').tableScroll({height:height,width:'100%'});
    });
</script>