<style>
    .clicked
    {
        background: yellow;
    }
    #m412_material_dial_box
    {
        overflow:hidden;
    }
    #select_m412_material_box
    {
        float:left;
        width:95%;
    }
    #select_m412_material_box .select
    {
        width:98%;
        overflow: auto;
    }
    #m412_material_button_box
    {

        float:left;
    }

    #m412_material_box
    {
        width: 98%;
    }
</style>

<script type="text/javascript" src="/js/common.js"></script>

<script>
    var m412_material_button = {
        detail : function (ioid) {
            var url  = sz_BaseUrl + '/button/m412/material/detail';
            var data = {item:ioid};

            qssAjax.getHtml(url, data, function(jreturn) {
                $('#qss_m412_material_detail').html(jreturn);
                $('#qss_m412_material_detail').dialog({ width: 400,height:300 });
            });
        },

        show : function()
        {
            var url  = sz_BaseUrl + '/button/m412/material/show';
            var data = $('#m412_material_form').serialize();

            qssAjax.getHtml(url, data, function(jreturn) {
                $('#m412_material_show').html(jreturn);
            });
        },

        select : function()
        {
            var url  = sz_BaseUrl + '/button/m412/material/select';
            var data = $('#m412_material_form').serialize();

            qssAjax.getHtml(url, data, function(jreturn) {
                $('#m412_material_select').html(jreturn);
            });
        },

        save : function()
        {
            var url  = sz_BaseUrl + '/button/m412/material/save';
            var data = $('#m412_material_form').serialize();

            qssAjax.confirm('Bạn có thực sự muốn lưu lại?',function(){
                qssAjax.call(url, data, function(jreturn) {
                    if(jreturn.message != '')
                    {
                        qssAjax.notice(jreturn.message);
                    }

                }, function(jreturn) {
                    qssAjax.alert(jreturn.message);
                });
            });
        },

        search : function()
        {
            // Gia tri tim kiem
            var xval = $('#m412_material_filter_dialbox').val();
            var text = '';
            var re;

            // Xoa nhung option trắng
            $('.m412_material_empty_option').each(function () {
                $(this).remove();
            });

            // An hien option theo gia tri tim kiem
            if(xval == '')
            {
                $('#select_m412_material_box select option').each(function(){
                    $(this).show();
                });
            }
            else
            {
                $('#select_m412_material_box select option').each(function(){
                    text = $(this).text();
                    re   = new RegExp(xval, "i");

                    if(text.search(re) !== -1){
                        $(this).show();
                    }
                    else
                    {
                        $(this).hide();
                    }
                });
            }

            // Them the trang vao trong truong hop so luog the bi hide bang dung so luong the dang co
            if($('#select_m412_material_box select option:hidden').length == $('#select_m412_material_box select option').length)
            {
                $('#select_m412_material_box select').append('<option class=\"m412_material_empty_option\" value=\"0\" disabled>&nbsp;</option>');
            }
        },

        add : function(all){
            var add;
            var addHtml = '';
            var groupmarker = 0;
            var inv  = 0;
            var filter = parseInt($('input[type="radio"][name="m412_material_filter"]:checked').val());

            if(all != undefined && all)
            {
                add = $('#select_m412_material_box select  option[value!="0"]').filter(":not(:hidden)");
            }
            else
            {
                add = $('#select_m412_material_box select option[value!="0"]').filter(":selected").filter(":not(:hidden)");
            }

            $('.m412_material_empty_option').each(function () {
                $(this).remove();
            });

            add.each(function(){
                groupmarker = $(this).attr('groupmarker');
                inv         = parseFloat($(this).attr('inv'));
                min         = parseFloat($(this).attr('min'));

                addHtml  = '';
                addHtml += '<tr class="selected_line" >';
                addHtml += '<td class="center"><input type="checkbox" class="remov_line" onclick="m412_material_button.checkItem(this)"></td>';
                addHtml += '<td class="left">'+$(this).attr('itemcode');
                addHtml += '<input type="hidden" value="'+$(this).attr('itemioid')+'" class="RefItem" name="RefItem[]" >';
                addHtml += '<input type="hidden" value="'+$(this).attr('uomioid')+'" class="RefUOM" name="RefUOM[]" >';
                addHtml += '<input type="hidden" value="'+$(this).attr('itemcode')+'" class="itemcode" >';
                addHtml += '<input type="hidden" value="'+$(this).attr('itemname')+'" class="itemname" >';
                addHtml += '<input type="hidden" value="'+$(this).attr('uom')+'" class="uom" >';
                addHtml += '<input type="hidden" value="'+$(this).attr('stock')+'" class="stock" >';
                addHtml += '<input type="hidden" value="'+$(this).attr('qty')+'" class="qty" >';
                addHtml += '<input type="hidden" value="'+$(this).attr('min')+'" class="min" >';
                addHtml += '<input type="hidden" value="'+$(this).attr('inv')+'" class="inv" >';
                addHtml += '<input type="hidden" value="'+$(this).attr('req')+'" class="req" >';
                addHtml += '<input type="hidden" value="'+$(this).attr('order')+'" class="order" >';
                addHtml += '<input type="hidden" value="'+$(this).attr('in')+'" class="in" >';


                addHtml += '</td>';
                addHtml += '<td class="left">'+$(this).attr('itemname')+'</td>';
                addHtml += '<td class="left">'+$(this).attr('uom')+'</td>';

                if(filter == 1)
                {
                    addHtml += '<td class="left">'+$(this).attr('stock');
                    addHtml += '<input type="hidden" value="'+$(this).attr('stock')+'" class="stock" name="stock[]">';
                    addHtml += '</td>';
                }
                else
                {
                    addHtml += '<td class="left">';
                    addHtml += '<select name="stock[]" class="stock" onchange="m412_material_button.loadInventoryOfItem(this);">';
                    addHtml += '<option value="0"></option>';

                    <?php foreach ($this->stocks as $item):?>
                    addHtml += '<option value="<?php echo @(int)$item->IOID;?>"><?php echo $item->MaKho;?></option>';
                    <?php endforeach;?>

                    addHtml += '</td>';
                }

                addHtml += '<td class="center"><input type="text" size="3" class="right qty" value="'+$(this).attr('qty')+'" name="Qty[]" /></td>';

                addHtml += '<td class="right td_min">'+$(this).attr('min')+'</td>';

                if(inv > 0)
                {
                    addHtml += '<td class="right td_inv"><a href="#1" onclick="m412_material_button.detail('+parseInt($(this).attr('itemioid'))+')"> '+$(this).attr('inv')+' </a></td>';
                }
                else
                {
                    addHtml += '<td class="right">'+$(this).attr('inv')+'</td>';
                }
                addHtml += '<td class="right">'+$(this).attr('req')+'</td>';
                addHtml += '<td class="right">'+$(this).attr('order')+'</td>';
                addHtml += '<td class="right">'+$(this).attr('in')+'</td>';

                addHtml += '</tr>';
                $('#m412_material_box').append(addHtml);

                if(filter == 1)
                {
                    $(this).remove();
                }
            });

            if($('#select_m412_material_box select option:hidden').length == $('#select_m412_material_box select option').length)
            {
                $('#select_m412_material_box select').append('<option class=\"m412_material_empty_option\" value=\"0\" disabled>&nbsp;</option>');
            }
        },

        remove : function(all){
            var remove;
            var html   = '';
            var filter = parseInt($('input[type="radio"][name="m412_material_filter"]:checked').val());

            if(all != undefined && all)
            {
                remove = $('.selected_line');
            }
            else
            {
                remove = $('.selected_line').filter(".marker");
            }

            $('.m412_material_empty_option').each(function () {
                $(this).remove();
            });

            remove.each(function(){
                html  = '<option ';
                html += 'itemioid="'+$(this).find('.RefItem').val()+'" ';
                html += 'itemcode="'+$(this).find('.itemcode').val()+'" ';
                html += 'itemname="'+$(this).find('.itemname').val()+'" ';
                html += 'uomioid="'+$(this).find('.RefUOM').val()+'" ';
                html += 'uom="'+$(this).find('.uom').val()+'" ';
                html += 'value="'+$(this).find('.RefItem').val()+'" ';
                html += 'qty="'+$(this).find('.qty').val()+'" ';

                html += 'inv="'+$(this).find('.inv').val()+'" ';
                html += 'req="'+$(this).find('.req').val()+'" ';
                html += 'order="'+$(this).find('.order').val()+'" ';
                html += 'stock="'+$(this).find('.stock').val()+'" ';
                html += 'in="'+$(this).find('.in').val()+'"> ';



                html += $(this).find('.itemcode').val() + ' - ' + $(this).find('.itemname').val() + '(' + $(this).find('.uom').val() + ')'
                html += '</option>';

                if(filter == 1) {
                    $('#select_m412_material_box select').prepend(html);
                }
                $(this).remove();
            });

            if($('#m412_material_box select option').length == 0)
            {
                $('#m412_material_box select').append('<option class=\"m412_material_empty_option\" value=\"0\" disabled>&nbsp;</option>');
            }
        },

        checkItem : function(ele)
        {
            if($(ele).is(':checked'))
            {
                $(ele).parent().parent().addClass('marker');
                $(ele).attr('checked', true);
            }
            else
            {
                $(ele).parent().parent().removeClass('marker');
                $(ele).removeAttr('checked');
            }
        },

        checkAllItems : function(ele)
        {
            if($(ele).is(':checked'))
            {
                $('.remov_line').each(function(){
                    $(this).attr('checked', true);
                    $(this).parent().parent().addClass('marker');
                });
            }
            else
            {
                $('.remov_line').each(function(){
                    $(this).removeAttr('checked', true);
                    $(this).parent().parent().removeClass('marker');
                });
            }
        },
        
        loadInventoryOfItem : function (ele) {
            var tr    = $(ele).parent().parent();
            var item  = parseInt(tr.find('.RefItem').val());
            var stock = parseInt($(ele).val());

            var url = sz_BaseUrl + '/button/m412/material/inventory';
            var data = {item:item, stock:stock};
            var inv  = 0;
            var min  = 0;

            qssAjax.call(url, data, function(jreturn) {
                inv = parseFloat(jreturn.data.inv);
                min = parseFloat(jreturn.data.min);

                tr.find('.td_inv').text(inv);
                tr.find('.td_min').text(min);
            }, function(jreturn) {
                qssAjax.alert(jreturn.message);
            });
        }
    };

    $(document).ready(function(){
        m412_material_button.show();
        m412_material_button.select();

        $('input[type="radio"][name="m412_material_filter"]').change(function(){
            m412_material_button.select();
        });
    });
</script>

<div class="clear"></div>
<div class="view" id="view">
    <div id="wrapper">
        <form id="m412_material_form">
            <input type="hidden" name="ifid" value="<?php echo $this->ifid;?>">

            <p>
                <input type="radio" id="Checkbox_PhieuBaoTri_DonHang" name="m412_material_filter" value="1" checked />
                <label for="Checkbox_PhieuBaoTri_DonHang"> Dưới mức tối thiểu </label>

                <input type="radio" id="Checkbox_MatHang" name="m412_material_filter" value="2" />
                <label for="Checkbox_MatHang"> Mặt hàng </label>
            </p>

            <br/>

            <div id="">
                <div style="width: 40%;" class="fl" id="m412_material_select">
                    &nbsp;
                </div>

                <div id="m412_material_button_box" class="fl" style="width:6%;">

                    <div id="m412_material_add_button">
                        <button onclick="m412_material_button.add()"
                                class="btn-custom"
                                type="button"> &gt;&gt; </button>
                    </div>

                    <div id="">
                        <button onclick="m412_material_button.remove()"
                                class="btn-custom"
                                type="button"> &lt;&lt; </button>
                    </div>

                    <div id="">
                        <button onclick="m412_material_button.add(1)"
                                class="btn-custom"
                                type="button"> &gt;&gt;&gt;&gt; </button>
                    </div>

                    <div id="m412_material_remove_button">
                        <button onclick="m412_material_button.remove(1)"
                                class="btn-custom"
                                type="button"> &lt;&lt;&lt;&lt; </button>
                    </div>
                </div>


                <div style="width: 54%;" class="fl" id="m412_material_show">

                </div>
            </div>
        </form>

        <br/>
        <div class="clear"></div>
        <br/>

        <div class="fr">
            <button type="button" class="btn btn-custom" onclick="m412_material_button.save()"> Cập nhật </button>
        </div>
    </div>
</div>

<div id="qss_m412_material_detail" title="Chi tiết theo kho"></div>
