<?php
    $arrWidths = array(1, 3, 5, 3, 3, 3, 3, 5, 3, 3, 5);
    $totalCols = count($arrWidths);
    $arrWidths = Qss_Lib_Report::changeWidthToFitScreen3($arrWidths);
    $i         = 0;
?>

<table id="m878_show_table" class="border_table" cellpadding="0" cellspacing="0" border="0">
    <thead>
        <tr class="bggrey">
            <?php $begin = 0;?>
            <th style="width: <?php echo $arrWidths[$begin++];?>%">&nbsp;</th>
            <th style="width: <?php echo $arrWidths[$begin++];?>%">Mã nhân viên</th>
            <th style="width: <?php echo $arrWidths[$begin++];?>%">Tên nhân viên</th>
            <th style="width: <?php echo $arrWidths[$begin++];?>%">Phòng ban</th>
            <th style="width: <?php echo $arrWidths[$begin++];?>%">Chức danh</th>
            <th style="width: <?php echo $arrWidths[$begin++];?>%">Chức vụ</th>
            <th style="width: <?php echo $arrWidths[$begin++];?>%">Mã yêu cầu</th>
            <th style="width: <?php echo $arrWidths[$begin++];?>%">Tên yêu cầu</th>
            <th style="width: <?php echo $arrWidths[$begin++];?>%">Ngày yêu cầu</th>
            <th style="width: <?php echo $arrWidths[$begin++];?>%">Ngày cuối</th>
            <th style="width: <?php echo $arrWidths[$begin++];?>%">Đang theo học</th>
        </tr>
    </thead>


    <tbody>


        <?php $oldLoaiDaoTao = '';?>
        <?php foreach($this->data as $item):?>
            <?php if($oldLoaiDaoTao != $item->Ref_KhoaHoc):?>
                <?php ++$i;?>

                <tr class="bggreenyellow bold" style="background: greenyellow !important;">
                    <td class="center" style="width: <?php echo $arrWidths[0];?>%">
                        <input type="checkbox" onclick="common_check_all_table_line(this, '.cwpo_line_checkbok<?php echo $i;?>', '.cwpo_line_checkbok_val<?php echo $i;?>')"/>
                    </td>
                    <td colspan="<?php echo ($totalCols-1);?>" style="line-height: 24px; width: <?php echo (100 - $arrWidths[0]);?>% ">
                        <div class="fl">
                            <?php echo $item->KhoaHoc;?>
                        </div>

                        <div class="fr">
                            <div class="fl">
                                <button type="button" class="btn" onclick="m878.createClass('<?php echo $i;?>', '<?php echo $item->Ref_KhoaHoc;?>');"> Tạo lớp học </button>
                            </div>
                        </div>
                    </td>
                </tr>
            <?php endif;?>

            <tr class="">
                <td class="center">

                    <?php if(!$item->DangHocKhoaNay):?>

                        <input type="checkbox" class="m878Checkbox<?php echo $i;?> cwpo_line_checkbok<?php echo $i;?> " onclick="common_check_table_line(this, '.cwpo_line_checkbok_val<?php echo $i;?>')">
                        <input type="hidden" class="m878Checkbox<?php echo $i;?> table_line_disabled cwpo_line_checkbok_val<?php echo $i;?>" name="CheckBox[]"  value="0">
                        <input class="m878Checkbox<?php echo $i;?> table_line_disabled m878Form<?php echo $i;?>" type="hidden" value="<?php echo $item->Ref_MaNhanVien;?>" name="Employee[]" disabled>

                    <?php endif;?>
                </td>
                <td class="left"><?php echo $item->MaNhanVien;?></td>
                <td class="left"><?php echo $item->TenNhanVien;?></td>
                <td class="left"><?php echo $item->MaPhongBan;?></td>
                <td class="left"><?php echo $item->ChucDanh;?></td>
                <td class="left"><?php echo $item->ChucVu;?></td>
                <td class="left"><?php echo $item->MaYeuCau;?></td>
                <td class="left"><?php echo $item->TenYeuCau;?></td>
                <td class="center"><?php echo Qss_Lib_Date::mysqltodisplay($item->NgayYeuCau);?></td>
                <td class="center"><?php echo Qss_Lib_Date::mysqltodisplay($item->NgayCuoi);?></td>
                <td class="left"><?php echo $item->LopHoc;?></td>
            </tr>

            <?php $oldLoaiDaoTao = $item->Ref_KhoaHoc;?>
        <?php endforeach;?>
    </tbody>

</table>

<script>
    $(document).ready(function() {
        var height = $('#view').height() -30;
        //$('#m878_show_table').tableScroll({height:height,width:'100%'});
    });
</script>