<script>
    function printPreview(){

        var start = $('#sdate').val();
        var end   = $('#edate').val();
        var msg   = '';

        if(!start)
        {
            msg += '<?php echo $this->_translate(1)?>';
        }
        if(!end)
        {
            msg += '<?php echo $this->_translate(2)?>';
        }

        var firstValue = start.split('-');
        var secondValue = end.split('-');
        var firstDate=new Date();
        firstDate.setFullYear(firstValue[2],(firstValue[1] - 1 ),firstValue[0]);
        var secondDate=new Date();
        secondDate.setFullYear(secondValue[2],(secondValue[1] - 1 ),secondValue[0]);

        if (firstDate > secondDate)
        {
            msg += '<?php echo $this->_translate(3)?>';
        }


        if(msg != '')
        {
            qssAjax.alert(msg);
            return;
        }
        else
        {
            var url = sz_BaseUrl + '/static/m793/show';
            var data = $('#report').serialize();
            qssAjax.getHtml(url, data, function(jreturn) {
                $('#print-area').html(jreturn);
                removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
            });
        }
    }

</script>


<div class="clear"></div>
<div id="view">
    <div class="line-hr">
        <span><?php echo $this->_translate(4)?> </span>
    </div>
    <form id="report" method="post"
          action="/maintenancereport/plan/detail1">
        <table class="detail" style="margin: 10px">

            <tr>
                <th width="20%" class="report-param-label">
                    <!-- Ngày bắt đầu --> <?php echo $this->_translate(5)?></th>
                <td><?php echo $this->views->Report->Datepicker('sdate', date('d-m-Y'));?><span
                        class="bold red">(*)</span></td>
            </tr>

            <tr>
                <th width="20%" class="report-param-label">
                    <!-- Ngày ket thuc --> <?php echo $this->_translate(6)?></th>
                <td><?php echo $this->views->Report->Datepicker('edate', date('t-m-Y',strtotime('today')));?><span
                        class="bold red">(*)</span></td>
            </tr>

            <tr>
                <th class="report-param-label"><?php echo $this->_translate(10)?></th>
                <td><?php
                    $id            = 'loc_ioid';
                    $getFields     = array('num'=>3,
                        'objects'=>array('OKhuVuc'=>array(
                            'id'=>'IOID'
                        ,'display1'=>'MaKhuVuc'
                        , 'display2'=>'Ten') ));
                    ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
                </td>
            </tr>

            <tr>

                <th width="20%" class="report-param-label">
                    <!-- Loai bao tri --> <?php echo $this->_translate(11)?></th>
                <td><?php
                    $id            = 'maint_type_ioid';
                    $getFields     = array('num'=>3,
                        'objects'=>array('OPhanLoaiBaoTri'=>array(
                            'id'=>'IOID'
                        ,'display1'=>'Loai') ));
                    ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>

                </td>
            </tr>


            <tr>
                <th width="20%" class="report-param-label">
                    <!-- Nhom thiet bi --> <?php echo $this->_translate(7)?></th>
                <td><?php
                    $id            = 'eq_group_ioid';
                    $getFields     = array('num'=>3,
                        'objects'=>array('ONhomThietBi'=>array(
                            'id'=>'IOID'
                        ,'display1'=>'LoaiThietBi') ));
                    ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
                </td>
            </tr>

            <tr>

                <th width="20%" class="report-param-label">
                    <!-- Loai bao tri --> <?php echo $this->_translate(8)?></th>
                <td><?php
                    $id            = 'eq_type_ioid';
                    $getFields     = array('num'=>3,
                        'objects'=>array('OLoaiThietBi'=>array(
                            'id'=>'IOID'
                        ,'display1'=>'TenLoai') ));
                    ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>

                </td>
            </tr>

            <tr>
                <th width="20%" class="report-param-label"><?php echo $this->_translate(12)?>
                </th>
                <td><?php
                    $id            = 'eq_ioid';
                    $getDataObject = array('ODanhSachThietBi'=>array('MaThietBi', 'TenThietBi'));
                    $getFields     = array('num'=>2,
                        'objects'=>array('ODanhSachThietBi'=>array(
                            'id'=>'IOID'
                        ,'display1'=>'MaThietBi'
                        ,'display2'=>'TenThietBi')) );
                    ?> <?php echo $this->views->Report->ListBox($id, $getDataObject,$getFields);?>
                </td>
            </tr>




        </table>
    </form>
    <p>


    <hr>
    <?php echo $this->views->Report->PrintToolbar();?>
    <div id="print-content">
        <div id="print-area"></div>
    </div>
</div>
