<table cellpadding="0" cellspacing="0" border="0" class="grid" id="grid">
    <tr>
        <th style="width: 95%;">
            <?php echo $this->_translate(1);?>
        </th>

        <th style="width: 5%;">
            <input type="checkbox" onclick="common_check_all_table_line(this, '.cwpo_line_checkbok', '.cwpo_line_checkbok_val')"/>
        </th>
    </tr>

    <?php foreach ($this->oKhongDinhKy As $item):?>
        <tr>
            <td>
                <?php echo $item->MoTa;?>
                <input class="table_line_disabled" type="hidden" value="<?php echo $item->IOID;?>" name="ioidPhieuBaoTri[]" disabled>
            </td>
            <td class="center">
                <input type="checkbox" class="cwpo_line_checkbok " onclick="common_check_table_line(this, '.cwpo_line_checkbok_val')">
                <input type="hidden" class="table_line_disabled cwpo_line_checkbok_val" name="CheckBox[]"  value="0">
            </td>
        </tr>
    <?php endforeach;?>
</table>

<br/>

<div class="fr">
    <button type="button" onclick="m759_checklist_button.save();" class="btn"> <?php echo $this->_translate(3);?> </button>
</div>