<div class="ui_box"><div class="ui_box_s50_left"><fieldset><div class="ui_box_line OKinhNghiemNhanVien_TenCongTy">
											<div class="label">
											<label><?php echo $this->object->getFieldByCode("TenCongTy")->szFieldName;?></label>
											</div>
											<div class="element">
											<?php echo $this->object->sz_fGetFormFieldElement("TenCongTy",$this->user,$this->dialog);?>
											</div>
											</div><div class="ui_box_line OKinhNghiemNhanVien_NgayBatDau">
											<div class="label">
											<label><?php echo $this->object->getFieldByCode("NgayBatDau")->szFieldName;?></label>
											</div>
											<div class="element">
											<?php echo $this->object->sz_fGetFormFieldElement("NgayBatDau",$this->user,$this->dialog);?>
											</div>
											</div><div class="ui_box_line OKinhNghiemNhanVien_NgayKetThuc">
											<div class="label">
											<label><?php echo $this->object->getFieldByCode("NgayKetThuc")->szFieldName;?></label>
											</div>
											<div class="element">
											<?php echo $this->object->sz_fGetFormFieldElement("NgayKetThuc",$this->user,$this->dialog);?>
											</div>
											</div><div class="ui_box_line OKinhNghiemNhanVien_ViTriLamViec">
											<div class="label">
											<label><?php echo $this->object->getFieldByCode("ViTriLamViec")->szFieldName;?></label>
											</div>
											<div class="element">
											<?php echo $this->object->sz_fGetFormFieldElement("ViTriLamViec",$this->user,$this->dialog);?>
											</div>
											</div><div class="ui_box_line OKinhNghiemNhanVien_ViTriCuoiCung">
											<div class="label">
											<label><?php echo $this->object->getFieldByCode("ViTriCuoiCung")->szFieldName;?></label>
											</div>
											<div class="element">
											<?php echo $this->object->sz_fGetFormFieldElement("ViTriCuoiCung",$this->user,$this->dialog);?>
											</div>
											</div><div class="ui_box_line OKinhNghiemNhanVien_SoNamKinhNghiem">
											<div class="label">
											<label><?php echo $this->object->getFieldByCode("SoNamKinhNghiem")->szFieldName;?></label>
											</div>
											<div class="element">
											<?php echo $this->object->sz_fGetFormFieldElement("SoNamKinhNghiem",$this->user,$this->dialog);?>
											</div>
											</div></fieldset></div></div>