   <script>
function printPreview(){
	/*$('#report').submit(function() {
        window.open('', 'formpopup', 'statusbar=no,resizable=yes,scrollbars=yes, addressbar=no,maximize=yes');
        this.target = 'formpopup';
    });
	$('#report').submit();*/
	 var url = sz_BaseUrl + '/report/maintenance/maintain/period1';
		var data = $('#report').serialize();
		qssAjax.getHtml(url, data, function(jreturn) {
			$('#print-area').html(jreturn);
                        removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
		});
}
</script>
<div class="clear"></div>
<div id="view">
<div class="line-hr"><span><?php echo $this->_translate(1);?></span></div>
<form id="report" method="get" action="/report/maintenance/maintain/period1">
<table class="detail" style="margin: 10px">
<tr>
	<th width="20%" class="report-param-label"><?php echo $this->_translate(20)?></th>
	<td>
            
            <?php
                $id            = 'location';
                $getFields     = array('num'=>3, 
                                       'objects'=>array('OKhuVuc'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'MaKhuVuc'
                                                            ,'display2'=>'Ten') ));
            ?>
            <?php echo $this->views->Report->ComboBox($id,$getFields);?>
        </td>
</tr>    

    
<tr>
	<th width="20%" class="report-param-label"><?php echo $this->_translate(22)?></th>
	<td>
            
            <?php
                $id            = 'group';
                $getFields     = array('num'=>3, 
                                       'objects'=>array('ONhomThietBi'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'LoaiThietBi'
                                                            ) ));
            ?>
            <?php echo $this->views->Report->ComboBox($id,$getFields);?>
        </td>
</tr>
    

</table>
</form>
<p>
<hr>
    <?php echo $this->views->Report->PrintToolbar();?>
    <div id="print-content">
            <div id="print-area"></div>		
    </div>
</div>

