<!-- Báo cáo chấm công theo ngày  -->
<?php 
	$excel_col = array_flip(Qss_Lib_Const::$EXCEL_COLUMN);
	$no        = 1; // Số thứ tự
$pxWidthArr    = array(30, 150, 100, 120, 50, 100, 100, 150);
// px html to excel width
$excelWidthArr = Qss_Lib_Report::convertPxColumnWidthToExcelWidth($pxWidthArr);
// auto fit (px html)
$pxWidthArr    = Qss_Lib_Report::changeWidthToFitScreen($pxWidthArr);	
?>
<form id="excel" method="post" action="/report/index/excel" target="new">
	<input type="hidden" id="content" name="content" value="">
</form>
<div class="portrait">
	<excel orientation="portrait" font-name="Arial" font-size="9" margin-left="0.5" margin-right="0.5" margin-top="0.75" margin-bottom="0.75"/>
	<div id="head_print">
		<?php echo $this->views->Common->Portrait()?>
		<?php $row = 9;?>
		<center>
			<h2><xls row="<?php echo $row?>" column="A" column-merge="<?php echo $excel_col[8]?>"  font-size="11" wrap-text="1" h-align="center" v-align="center" bold="1" ><?php echo $this->_translate(1);?> <?php echo "({$this->_translate(12)} ".$this->start->format('d-m-Y')." {$this->_translate(13)} ".$this->end->format('d-m-Y').")";?>  </xls></h2>
			<?php $row++?>
		</center>
	</div>
	<br/>
	
	<div id="container">		
		<table  cellpadding="0" cellspacing="0" class="border" border="1">
			
			<!--  Tiêu đề  -->
			<tr class="bggrey"> 
				<th style="width:<?php echo $pxWidthArr[0];?>px"><!-- STT --><xls row="<?php echo $row?>"  column="<?php echo $excel_col[1]?>" width="<?php echo $excelWidthArr[0];?>"  wrap-text="1" h-align="center" v-align="center" border="1" bold="1"><?php echo $this->_translate(2)?></xls>   </th>
				<th style="width:<?php echo $pxWidthArr[1];?>px"><!-- TÊN THIẾT BỊ --><xls row="<?php echo $row?>"  column="<?php echo $excel_col[2]?>" width="<?php echo $excelWidthArr[1];?>"  wrap-text="1" h-align="center" v-align="center" border="1" bold="1"><?php echo $this->_translate(3)?> </xls> </th>
				<th style="width:<?php echo $pxWidthArr[2];?>px"><!-- MÃ HIỆU --> <xls row="<?php echo $row?>"  column="<?php echo $excel_col[3]?>" width="<?php echo $excelWidthArr[2];?>" wrap-text="1" h-align="center" v-align="center" border="1" bold="1"><?php echo $this->_translate(4)?></xls>  </th>
				<th style="width:<?php echo $pxWidthArr[3];?>px"><!-- Khu vực--> <xls row="<?php echo $row?>"  column="<?php echo $excel_col[4]?>" width="<?php echo $excelWidthArr[3];?>" wrap-text="1" h-align="center" v-align="center" border="1" bold="1"><?php echo $this->_translate(5)?></xls>  </th>
				<th style="width:<?php echo $pxWidthArr[4];?>px"><!-- Số lượng --> <xls row="<?php echo $row?>"  column="<?php echo $excel_col[5]?>" width="<?php echo $excelWidthArr[4];?>" wrap-text="1" h-align="center" v-align="center" border="1" bold="1"><?php echo $this->_translate(6)?></xls>  </th>
				<th style="width:<?php echo $pxWidthArr[5];?>px"><!-- Thời hạn --> <xls row="<?php echo $row?>"  column="<?php echo $excel_col[6]?>" width="<?php echo $excelWidthArr[5];?>" wrap-text="1" h-align="center" v-align="center" border="1" bold="1"><?php echo $this->_translate(7)?></xls> </th>
				<th style="width:<?php echo $pxWidthArr[6];?>px"><!-- Hình thức--> <xls row="<?php echo $row?>"  column="<?php echo $excel_col[7]?>" width="<?php echo $excelWidthArr[6];?>" wrap-text="8" h-align="center" v-align="center" border="1" bold="1"><?php echo $this->_translate(8)?></xls> </th>
				<th style="width:<?php echo $pxWidthArr[7];?>px"><!-- GHI CHÚ --><!-- Phút -->  <xls row="<?php echo $row?>"  column="<?php echo $excel_col[8]?>" width="<?php echo $excelWidthArr[7];?>" wrap-text="1" h-align="center" v-align="center" border="1" bold="1"><?php echo $this->_translate(9)?></xls> </th>
			</tr>
			<?php $row++;// Lên một hàng?>
			
			<!-- Nội dung -->
			<?php 
				$start = $this->start;
				$end = $this->end;
			?>
			<?php while($start <= $end):?>
			<?php $startToDate = $start->format('Y-m-d');?>
			<?php if(isset($this->print[$startToDate])): // Neu ton tai ngay bao tri nay?>
			<?php foreach ($this->print[$startToDate] as $pl):// In kh theo ngay?>
			<tr>
				<td class="center"><!-- STT --><xls row="<?php echo $row?>"  column="<?php echo $excel_col[1]?>"  wrap-text="1" h-align="center" v-align="center" border="1" ><?php echo $no?></xls></td>
				<td class="left"><!--TÊN THIẾT BỊ --><xls row="<?php echo $row?>"  column="<?php echo $excel_col[2]?>"  wrap-text="1" h-align="left" v-align="center" border="1" ><?php echo $pl['Name']?></td>
				<td class="left" ><!-- MÃ HIỆU --><xls row="<?php echo $row?>"  column="<?php echo $excel_col[3]?>"  wrap-text="1" h-align="left" v-align="center" border="1"> <?php echo $pl['Code'];?></td>
				<td class="left" ><!-- Khu vực--><xls row="<?php echo $row?>"  column="<?php echo $excel_col[4]?>"  wrap-text="1" h-align="left" v-align="center" border="1" ><?php echo $pl['Loc'];?></td>
				<td class="right" ><!--Số lượng --><xls row="<?php echo $row?>"  column="<?php echo $excel_col[5]?>"  wrap-text="1" h-align="right" v-align="center" border="1"><?php echo $pl['Qty'];?></td>
				<td class="center" ><!-- Thời hạn  --><xls row="<?php echo $row?>"  column="<?php echo $excel_col[6]?>"  wrap-text="1" h-align="center" v-align="center" border="1" > <?php echo Qss_Lib_Date::mysqltodisplay($pl['Date']);?></td>
				<td class="left" ><!-- Hình thức --><xls row="<?php echo $row?>"  column="<?php echo $excel_col[7]?>"  wrap-text="1" h-align="left" v-align="center" border="1" > <?php echo $pl['Out']?$this->_translate(10):$this->_translate(11);?></td>
				<td class="left" ><!-- GHI CHÚ --><xls row="<?php echo $row?>"  column="<?php echo $excel_col[8]?>"  wrap-text="1" h-align="left" v-align="center" border="1" ><?php echo $pl['Type'];?></td>
			</tr>
			<?php $no++;// Tăng số thứ tự?>
			<?php $row++; // Lên một hàng?>
			<?php endforeach; // In ke hoach theo ngay?>
			<?php endif; // Neu ton tai ngay bao tri nay?>
			
			<?php $start = Qss_Lib_Date::add_date($start, 1); // Cong ngay len mot ngay?>
			<?php endwhile;// Lap den het ngay thang?>
		</table>
		
		<!-- 
				Ngày……… tháng….….năm 20…
	P.TBC/P.TBĐ	                         KTV
		
		 -->
		 
		<table width="100%">
			<tr>
				<th width="75%" >&nbsp;</th>
				<th><xls row="<?php echo $row?>"  column="<?php echo $excel_col[7]?>" column-merge="<?php echo $excel_col[8]?>"  wrap-text="1" h-align="left" v-align="center"  ><?php echo $this->_translate(14)?>......<?php echo $this->_translate(15)?>......<?php echo $this->_translate(16)?>......</xls></th>
			</tr>
			<?php $row++; // Lên một hàng?>
		</table>
		<table width="100%">
			<tr>
				<th width="33%" class="center"><xls row="<?php echo $row?>"  column="<?php echo $excel_col[1]?>" column-merge="<?php echo $excel_col[3]?>"  wrap-text="1" h-align="center" v-align="center"  >BGĐ</xls></th>
				<th width="34%" class="center"><xls row="<?php echo $row?>"  column="<?php echo $excel_col[4]?>" column-merge="<?php echo $excel_col[6]?>"  wrap-text="1" h-align="center" v-align="center"  >P.TBC/ P.TBĐ</xls></th>
				<th width="33%" class="center"><xls row="<?php echo $row?>"  column="<?php echo $excel_col[7]?>" column-merge="<?php echo $excel_col[8]?>"  wrap-text="1" h-align="center" v-align="center"  >KTV</xls></th>
			</tr>
			<?php $row++; // Lên một hàng?>
		</table>
	</div>
</div>
