<div id="m728_wrap">
<?php
$begin  = 0;
$widths = array(5, 3, 3, 4, 5, 4, 3, 4, 2, 2);
$widths = Qss_Lib_Report::changeWidthToFitScreen3($widths);
?>

<style>
    .fly_table tr td, .fly_table tr th
    {
        height: 50px !important;
        line-height: 16px;
        font-size: 12px;
        font-weight: bold;
        padding: 0px 5px;
    }

    .fly_table {
        border: 1px solid #aaa;
    }

    .fly_table tr th {
        border: 1px solid #ccc;
        color: blue;
    }

    .fly_table tr td {
        border: 1px solid #ccc;
    }

    .fly_table tr td, .fly_table tr th {
        word-wrap: break-word;
    }
</style>

<script>
    var time = new Date().getTime();

    $(document.body).bind("mousemove keypress", function(e) {
        time = new Date().getTime();
    });

    function changePage() {
        var page    = $('#qss_form_pageno').val();
        var display = $('#qss_form_perpage').val();
        var total   = <?php echo (int)$this->count;?>;
        var newPage = parseInt(page) + 1;

        if(newPage > total)
        {
            newPage = 1;
        }

        $('#qss_form_pageno').val(newPage);
        trackBreakdown();
    }

    function refresh() {
        var newTime = new Date().getTime();

        if(newTime - time >= 30000)
        {
            changePage();
        }
        else
        {
            setTimeout(refresh, 1000)
        }
    }
    
    function trackBreakdown() {
        var url  = sz_BaseUrl + '/static/m728?start='+$('#start').val()+'&end='+$('#end').val()
            +'&page='+$('#qss_form_pageno').val()
            +'&display='+$('#qss_form_perpage').val();

        var data = {};
        var view_heigth = (parseInt($('#view').height));
        qssAjax.getHtml(url, data, function(jreturn) {
            $('#rightside').html(jreturn);
            $('#view').css({'height':view_heigth+'px'});
        });
    }

    function showHideMenu() {
        if($('#leftside').is(':hidden'))
        {
            $('#leftside, #header-menu,  .searchmodule, .ddsmoothmenu,.header-quick').show();

            if (document.cancelFullScreen) {
                document.cancelFullScreen();
            } else if (document.mozCancelFullScreen) {
                document.mozCancelFullScreen();
            } else if (document.webkitCancelFullScreen) {
                document.webkitCancelFullScreen();
            }
        }
        else
        {
            $('#leftside, #header-menu,   .searchmodule,  .ddsmoothmenu,.header-quick').hide();

            if (document.documentElement.requestFullScreen) {
                document.documentElement.requestFullScreen();
            } else if (document.documentElement.mozRequestFullScreen) {
                document.documentElement.mozRequestFullScreen();
            } else if (document.documentElement.webkitRequestFullScreen) {
                document.documentElement.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT);
            }
        }
    }

    $(document).ready(function () {
       $('#start').change(function () {
           trackBreakdown();
       });

        $('#end').change(function () {
            trackBreakdown();
        });
    });

    setTimeout(refresh, 1000);
</script>

<div class="clear"></div>

<div id="view">



    <div id="horizontal-toolbar" class="horizontal-toolbar clearfix">
        <div class="fl">
            <?php echo $this->_translate(1);?>: <?php  echo $this->views->Report->Datepicker('start', $this->start);?>
            <?php echo $this->_translate(2);?>: <?php  echo $this->views->Report->Datepicker('end', $this->end);?>
            <button type="button" onclick="showHideMenu(); " class="btn"> <?php echo $this->_translate(8);?></button>
        </div>

        <div class="fr">
            <?php echo $this->_translate(19);?>:
            <a title="Trang trước" class="bold" href="#" onclick="$('#qss_form_pageno').val('<?php echo $this->prev;?>'); trackBreakdown();">&lt;&lt;</a>
            <input id="qss_form_pageno" name="page" onchange="trackBreakdown();" style="width: 20px !important; text-align: center;" value="<?php echo $this->page;?>">/<?php echo $this->count;?>
            <a title="Trang sau" class="bold" href="#" onclick="$('#qss_form_pageno').val('<?php echo $this->next;?>'); trackBreakdown();">&gt;&gt;</a>

            <?php echo $this->_translate(20);?>: <select id="qss_form_perpage" name="display" style="width: 100;" onchange="trackBreakdown();">
                <option value="5"   <?php echo ($this->display == 5)?'selected':''; ?>>5</option>
                <option value="10"  <?php echo ($this->display == 10)?'selected':''; ?>>10</option>
                <option value="20"  <?php echo ($this->display == 20)?'selected':''; ?>>20</option>
                <option value="50"  <?php echo ($this->display == 50)?'selected':''; ?>>50</option>
                <option value="100" <?php echo ($this->display == 100)?'selected':''; ?>>100</option>
            </select>
        </div>
    </div>

    <div>
        <table cellpadding="0" cellspacing="0" border="0" class="fly_table">
            <tr class="bggrey">
                <!-- Tên thiết bị -->
                <th style="width:<?php echo $widths[$begin++];?>%">
                    Thiết bị
                    <br/>
                    Machine
                </th>

                <!--  Khu vực -->
                <th style="width:<?php echo $widths[$begin++];?>%">
                   Khu vực
                    <br/>
                    Department
                </th>

                <!-- Ngày sự cố -->
                <th style="width:<?php echo $widths[$begin++];?>%">
                    Ngày yêu cầu
                    <br/>
                    Request date
                </th>

                <!-- Người yêu cầu -->
                <th style="width:<?php echo $widths[$begin++];?>%">
                    Người yêu cầu
                    <br/>
                    Request by
                </th>

                <!-- Người yêu cầu -->
                <th style="width:<?php echo $widths[$begin++];?>%">
                    Nội dung sự cố
                    <br/>
                    Content
                </th>



                <!-- Người yêu cầu -->
                <th style="width:<?php echo $widths[$begin++];?>%">
                    Trạng thái máy
                    <br/>
                    Status
                </th>

                <!-- Tình trạng -->
                <th style="width:<?php echo $widths[$begin++];?>%">
                    Dự kiến hoàn thành
                    <br/>
                    Est. Completion
                </th>

                <!-- Tình trạng -->
                <th style="width:<?php echo $widths[$begin++];?>%">
                    Đảm nhiệm
                    <br/>
                    Responsible
                </th>

                <!-- Đảm nhiệm -->
                <th style="width:<?php echo $widths[$begin++];?>%">
                    Mức độ
                    <br/>
                    Level
                </th>


                <!-- Tình trạng -->
                <th style="width:<?php echo $widths[$begin++];?>%">
                   TG dừng máy (h)
                    <br/>
                    Downtime(h)
                </th>

            </tr>

            <?php $i = 0;?>

            <?php foreach($this->data as $item):?>

            <tr class="<?php echo (++$i%2==0)?'bglightblue':'bgwhite';?>">
                <!-- Tên thiết bị -->
                <td class="left">
                    <?php echo $item->TenThietBi;?>
                    <?php echo $item->TenKhac?"({$item->TenKhac})":"";?>
                </td>

                <!--  Khu vực -->
                <td class="left">
                    <?php echo $item->TenKhuVuc;?>
                </td>

                <!-- Ngày yêu cầu -->
                <td class="center">
                    <?php echo $item->ThoiGian?date('H:i', strtotime($item->ThoiGian)):'';?>
                    <?php echo $item->Ngay?date('d/m/y', strtotime($item->Ngay)):'';?>
                </td>

                <!-- Người yêu cầu -->
                <td class="left">
                    <?php
                        $nguoiYeuCau = '';

                        if($item->NguoiYeuCau)
                        {
                            $temp        = explode(' ', trim($item->NguoiYeuCau));
                            $temp2       = end($temp);
                            $titleName   = ($item->GioiTinh == 1)?'Mr.':'Ms.';
                            $nguoiYeuCau = $titleName .' '. $temp2;
                        }

                    ?>
                    <?php echo $nguoiYeuCau;?>
                </td>

                <!-- Nội dung sự cố -->
                <td class="left">
                    <?php echo $item->MoTa;?>
                </td>

                <!-- Tình trạng -->
                <td class="center <?php echo $item->Color;?>">
                    <?php echo $item->TinhTrang;?>
                </td>

                <!-- Dự kiến hoàn thành -->
                <td class="center">
                    <?php echo $item->ThoiGianKetThucDuKien?date('H:i', strtotime($item->ThoiGianKetThucDuKien)):'';?>
                    <?php echo $item->NgayDuKienHoanThanh?date('d/m/y', strtotime($item->NgayDuKienHoanThanh)):'';?>
                </td>

                <!-- Đảm nhiệm -->
                <td class="left">
                    <?php
                    $damNhiem = '';

                    if($item->NguoiChiuTranhNhiem)
                    {
                        $temp        = explode(' ', trim($item->NguoiChiuTranhNhiem));
                        $temp2       = end($temp);
                        $titleName   = ($item->GioiTinh == 1)?'Mr.':'Ms.';
                        $damNhiem    = $titleName .' '. $temp2;
                    }

                    ?>
                    <?php echo $damNhiem;?>

                </td>

                <!-- Mức độ ưu tiên -->
                <td class="left">
                    <?php echo @$item->MucDoUuTien;?>
                </td>

                <!-- Thời gian dừng máy-->
                <td class="right">
                    <?php  echo Qss_Lib_Util::formatNumber($item->ThoiGianDungMay);?>
                </td>
            </tr>
            <?php endforeach;?>
        </table>
    </div>
</div>

<div id="qss_trace"></div>
</div>
