<script>
function printPreview() {
	var ngay   = $('#date').val();
	var msg   = '';

    if(msg != '') {
        qssAjax.alert(msg);
        return;
    }
    else {
        var url = sz_BaseUrl + '/static/m779/show';
        var data = $('#report').serialize();
        qssAjax.getHtml(url, data, function(jreturn) {
                $('#print-area').html(jreturn);
                removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
        });
    }
}


function changePlanOrOrderInputVal(ele)
{
	if($(ele).is(':checked'))
	{
		$('#planOrOrder').val(1);
	}
	else
	{
		$('#planOrOrder').val(0);
	}
}

function changeDate()
{
	var date = $('#date').val();
}


</script>



<div class="clear"></div>
<div id="view">
	<div class="line-hr">
		<span><?php echo Qss_Lib_System::getReportTitle('M779');?> </span>
	</div>
	<form id="report" method="get"
		action="/report/maintenance/maintain/daily1">
		<table class="detail">
			<tr>
				<th width="20%" class="report-param-label">Từ ngày:
				</th>
				<td><?php echo $this->views->Report->Datepicker('date', date('d-m-Y'));?><span
					class="bold red">(*)</span>
					<b>Đến ngày:</b>
					<?php echo $this->views->Report->Datepicker('enddate', date('d-m-Y',strtotime("+1 week")));?><span
					class="bold red">(*)</span>
					</td>
			</tr>

			<tr>
				<th class="report-param-label"><?php echo $this->_translate(5)?></th>
				<td><?php
				$id            = 'location';
				$getFields     = array('num'=>3,
                                       'objects'=>array('OKhuVuc'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'MaKhuVuc'
                                                            ,'display2'=>'Ten'
                                                            ,'where'=>$this->where) ));
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields,array(),array(),false,'style="width:180px"',false);?>
				</td>
			</tr>

		</table>
	</form>
	<p>
	
	
	<hr>
	<?php echo $this->views->Report->PrintToolbar();?>
	<div id="print-content">
		<div id="print-area"></div>
	</div>
</div>
<script type="text/javascript">
<!--
$('#date').change(function(){
	var ngay   = $('#date').val();
	var firstValue = ngay.split('-');
	var firstDate = new Date(firstValue[2], firstValue[1], firstValue[0],0,0,0);
	firstDate.setDate(firstDate.getDate() + 6);
	var yyyy = firstDate.getFullYear().toString();
	var mm = (firstDate.getMonth()).toString(); // getMonth() is zero-based
	var dd  = firstDate.getDate().toString();
	$('#enddate').val(dd+'-'+mm+'-'+yyyy);
});
//-->
</script>
