<script>
	function printPreview() {
		var url = sz_BaseUrl + '/static/m726/show';
		var data = $('#report').serialize();
		
		qssAjax.getHtml(url, data, function(jreturn) {
			$('#print-area').html(jreturn);
			removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
		});
	}

    function excelRender()
    {
        $('#report').submit();
    }

    function removePrintToolbarDisabled()
    {
        $('.pt-button').each(function(){
            $(this).prop('disabled',false);
        });
    }
</script>

<div class="clear"></div>
<div id="view">
	<div class="line-hr">
		<span> <?php echo Qss_Lib_System::getReportTitle('M726');?> </span>
	</div>
	<form id="report" method="get"
		action="/static/m726/excel">
        <input type="hidden" name="popup" value="1" />
        <table class="detail">
            <input type="hidden" name="popup" value="1" />

            <?php if (Qss_Lib_System::fieldActive('ODanhSachThietBi', 'MaKhuVuc')): ?>
                <tr>
                    <th width="20%" class="report-param-label"><?php echo $this->_translate(8) ?>
                    </th>
                    <td><?php
                    $id = 'location';
                    $getFields = array('num' => 3,
                            'objects' => array('OKhuVuc' => array(
                                    'id' => 'IOID'
                                    , 'display1' => 'MaKhuVuc'
                                    , 'display2' => 'Ten')));
                                    ?> <?php echo $this->views->Report->ComboBox($id, $getFields); ?>

                </tr>
            <?php endif; ?>

			<?php if(Qss_Lib_System::fieldActive('ODanhSachThietBi', 'LoaiThietBi')): ?>
                <tr>
                    <th width="20%" class="report-param-label"><?php echo $this->_translate(6) ?>
                    </th>
                    <td><?php
                    $id = 'type';
                    $getFields = array('num' => 2,
                            'objects' => array('OLoaiThietBi' => array(
                                    'id' => 'IOID'
                                    , 'display1' => 'TenLoai'
                                    )));
                                    ?> <?php echo $this->views->Report->ComboBox($id, $getFields); ?>

                </tr>
			<?php endif; ?>

            <tr>
                <th width="20%" class="report-param-label">
                    <?php echo $this->_translate(11) ?>
                </th>

                <td>
                    <?php
                    $id = 'partner';
                    $getDataObject = array('ODoiTac' => array('MaDoiTac', 'TenDoiTac'));
                    //,'OKhuVuc'=>array('MaKhuVuc','Ten')
                    $getFields = array('num' => 2,
                        'objects' => array('ODoiTac' => array(
                            'id' => 'IOID'
                        , 'order'=> 'TenDoiTac'
                        , 'display1' => 'MaDoiTac'
                        , 'display2' => 'TenDoiTac')));
                    ?> <?php echo $this->views->Report->ListBox($id, $getDataObject, $getFields); ?>
                </td>
            </tr>

			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(7) ?>
				</th>
				<td><?php
				$id = 'equip';
				$getDataObject = array('ODanhSachThietBi' => array('MaThietBi', 'TenThietBi'));
				//,'OKhuVuc'=>array('MaKhuVuc','Ten')
				$getFields = array('num' => 2,
						'objects' => array('ODanhSachThietBi' => array(
								'id' => 'IOID'
								, 'display1' => 'MaThietBi'
								, 'display2' => 'TenThietBi')));
								$getLookupFilter = array(array('id' => 'group'
								, 'refField' => array('ODanhSachThietBi' => 'Ref_NhomThietBi') // Nhom TB
								, 'required' => 0)
								, array('id' => 'type'
								, 'refField' => array('ODanhSachThietBi' => 'Ref_LoaiThietBi') // Loai TB
								, 'required' => 0)
								, array('id' => 'costcenter'
								, 'refField' => array('ODanhSachThietBi' => 'Ref_TrungTamChiPhi') // TT Chi phi
								, 'required' => 0)
								);
								?> <?php echo $this->views->Report->ListBox($id, $getDataObject, $getFields, $getLookupFilter); ?>
				</td>
			</tr>



            <?php if (Qss_Lib_System::fieldActive('ODanhSachThietBi', 'TrangThai')): ?>
                <tr>
                    <th width="20%" class="report-param-label">
                        <?php echo $this->_translate(10) ?>
                    </th>

                    <td>
                        <?php foreach ($this->Status as $key=>$item):?>
                            <input type="checkbox" name="status[]" value="<?php echo $key;?>" id="status_<?php echo $key;?>">
                            <label for="status_<?php echo $key;?>"><?php echo $item;?></label>
                        <?php endforeach;?>
                    </td>
                </tr>
            <?php endif;?>

			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(9) ?>
				</th>
				<td>
                    <?php if (Qss_Lib_System::fieldActive('ODanhSachThietBi', 'LoaiThietBi')): ?>
                        <input type="radio" name="sort" value="1" checked id="check_1" />
                        <label for="check_1"><?php echo $this->_translate(6) ?></label>
                    <?php endif;?>

                    <?php if (Qss_Lib_System::fieldActive('ODanhSachThietBi', 'MaKhuVuc')): ?>
                        <input type="radio" name="sort" value="4" id="check_4"/>
                            <label for="check_4"><?php echo $this->_translate(8) ?></label>
                    <?php endif;?>
				</td>
			</tr>


		</table>
	</form>
	<p>
	
	
	<hr>
    <?php echo $this->views->Report->PrintToolbar();?>

	<div id="print-content">
		<div id="print-area"></div>
	</div>
</div>
