<script>
function printPreview(){
	var ngaybd = $('#start').val();
	var ngaykt = $('#end').val();
	var msg    = '';

	msg += common_checkEmpty(ngaybd, '<?php echo $this->_translate(4) ?>');
	msg += common_checkEmpty(ngaykt, '<?php echo $this->_translate(5) ?>');
	msg += common_compareStartAndEnd(ngaybd, ngaykt
	, '<?php echo $this->_translate(4) ?>'
	, '<?php echo $this->_translate(5) ?>');
	
	if(msg)
	{
		qssAjax.alert(msg);
		return;
	}
	else
	{
		var url = sz_BaseUrl + '/static/m756/show';
		var data = $('#report').serialize();

		// LAY GIA TRI DANG CHUOI CUA DIEU KIEN LOC
		data += "&locationStr="  + encodeURIComponent($('#location option:selected').text());
		data += "&groupStr="     + encodeURIComponent($('#group option:selected'   ).text());
		data += "&typeStr="      + encodeURIComponent($('#type option:selected'    ).text());
		data += "&materialStr="  + encodeURIComponent($('#material_tag'            ).val());
		
		qssAjax.getHtml(url, data, function(jreturn) {
			$('#print-area').html(jreturn);
						removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
		});		
	}
}
</script>

<div class="clear"></div>
<div id="view">
	<div class="line-hr">
		<span><?php echo Qss_Lib_System::getReportTitle('M756');?> </span>
	</div>
	<form id="report" method="get" action="/static/m756/show">
		<table class="detail">
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(4)?>
				</th>
				<td><?php echo $this->views->Report->Datepicker('start', '01-'.date('m').'-'.date('Y'));?><span
					class="bold red">(*)</span></td>
			</tr>
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(5)?>
				</th>
				<td><?php echo $this->views->Report->Datepicker('end', date('d-m-Y'));?><span
					class="bold red">(*)</span></td>
			</tr>

			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(20)?>
				</th>
				<td><?php
				$id            = 'location';
				$getFields     = array('num'=>3,
                                       'objects'=>array('OKhuVuc'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'MaKhuVuc'
                                                            ,'display2'=>'Ten') ));
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
				</td>
			</tr>


			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(22)?>
				</th>
				<td><?php
				$id            = 'group';
				$getFields     = array('num'=>3,
                                       'objects'=>array('ONhomThietBi'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'LoaiThietBi'
                                                            ) ));
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
				</td>
			</tr>


			<?php if(Qss_Lib_Extra::checkFieldExists('ODanhSachThietBi', 'Ref_LoaiThietBi')):?>
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(21)?>
				</th>
				<td><?php
				$id            = 'type';
				$getFields     = array('num'=>2,
                                       'objects'=>array('OLoaiThietBi'=>array(
                                                            'id'=>'IOID'
                                                            ,'display1'=>'TenLoai'
                                                            )) );
                                                            ?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
			
			</tr>
			<?php endif;?>

			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(6)?>
				</th>
				<td><?php
				$id            = 'material';
				$getDataObject = array('OSanPham'=>array('MaSanPham', 'TenSanPham'));
				$getFields     = array('num'=>2,
                                       'objects'=>array('OSanPham'=>array(
                                                                'id'=>'IOID'
                                                                ,'display1'=>'MaSanPham'
                                                                ,'display2'=>'TenSanPham')) );
                                                                ?> <?php echo $this->views->Report->ListBox($id, $getDataObject,$getFields);?>

				</td>
			</tr>
		</table>
	</form>
	<p>
	
	
	<hr>
	<?php echo $this->views->Report->PrintToolbar();?>
	<div id="print-content">
		<div id="print-area"></div>
	</div>
</div>
