<?php
    $oldRequest      = '';
    $requestWidthArr = array(1,3,3,4,2,2,6);
    $width           = 780;
    $padding         = 2;
    
    $fit = Qss_Lib_Report::changeWidthToFitScreen2($requestWidthArr, $width, $padding);
      
    if(!count($this->plan))
    {
        echo 'Tất cả mặt hàng đã được lập kế hoạch hoặc đặt hàng!';
        die;
    }
?>

<div id="M405_plan_wrap">

    <form id="M405_plan_form">
    
        <div>        
            <table>
                <tr>
                    <th class="left">Ngày:</th>
                    <td class="required">
                        <?php echo $this->views->Report->Datepicker('date', date('d-m-Y'));?>
                    </td>
                </tr>
                
                <tr>
                    <th class="left">Nội dung:</th>
                    <td class="left">
                        <textarea name="content" style="width: 500px; height: 100px;" class="left">Tạo tự động từ M405</textarea>
                    </td>
                </tr>                
            </table>
        </div>
        
        <div class="clear"></div>
        <br/>        
        
        <table class="border_table" cellpadding="0" cellspacing="0" border="0" style="width:<?php echo $width;?>px">
            <!-- Title -->
            <?php $begin = 0; ?>
            <tr class="bggrey">
                <th style="width:<?php echo $fit[$begin++];?>px;">
                    <input type="checkbox" onclick="common_check_all_table_line(this, '.cwpo_line_checkbok', '.cwpo_line_checkbok_val')"/>
                </th>
                    
            
                <!-- Số yêu cầu -->
                <th style="width:<?php echo $fit[$begin++];?>px;">
                    <?php echo $this->_translate(1);?>
                </th>
    
                <!-- Mã mặt hàng -->
                <th style="width:<?php echo $fit[$begin++];?>px;">
                    <?php echo $this->_translate(2);?>
                </th>
    
                <!-- Tên mặt hàng -->
                <th style="width:<?php echo $fit[$begin++];?>px;">
                    <?php echo $this->_translate(3);?>
                </th>
    
                <!-- ĐVT -->
                <th style="width:<?php echo $fit[$begin++];?>px;">
                    <?php echo $this->_translate(4);?>
                </th>
    
                <!-- Số lượng  -->
                <th style="width:<?php echo $fit[$begin++];?>px;">
                    <?php echo $this->_translate(5);?>
                </th>
    
                <!-- Mục đich -->
                <th style="width:<?php echo $fit[$begin++];?>px;">
                    <?php echo $this->_translate(6);?>
                </th>    
            </tr>
    
            <!-- Data -->
            <?php foreach($this->plan as $item):?>      
                <tr>
                    <td class="center">
                        <input type="checkbox" class="cwpo_line_checkbok " onclick="common_check_table_line(this, '.cwpo_line_checkbok_val')">
                        <input type="hidden" class="table_line_disabled cwpo_line_checkbok_val" name="CheckBox[]"  value="0">
                    </td>                
                
                    <!-- Số yêu cầu -->
                    <td class="center">
                        <?php echo $item['DocNo'];?>
                        
                        <input class="table_line_disabled" type="hidden" name="requestioid[]" value="<?php echo $item['RequestIOID'];?>" disabled/>
                        <input class="table_line_disabled" type="hidden" name="itemioid[]" value="<?php echo $item['ItemIOID'];?>" disabled/>
                        <input class="table_line_disabled" type="hidden" name="uomioid[]" value="<?php echo $item['UomIOID'];?>" disabled/>
                        <input class="table_line_disabled" type="hidden" name="reason[]" value="<?php echo $item['Reason'];?>" disabled/>
                    </td>
    
                    <!-- Mã mặt hàng -->
                    <td class="left">
                        <?php echo $item['ItemCode'];?>
                    </td>
    
                    <!-- Tên mặt hàng -->
                    <td class="left">
                        <?php echo $item['ItemName'];?>
                    </td>
    
                    <!-- ĐVT -->
                    <td class="left">
                        <?php echo $item['UOM'];?>
                    </td>
    
                    <!-- Số lượng -->
                    <td class="center">
                        <input type="text" class="table_line_disabled right" name="qty[]" value="<?php echo $item['Rest'];?>" size="10" disabled/>
                    </td>                    
    
                    <!-- Mục đich  -->
                    <td class="right">
                        <?php echo $item['Reason'];?>                       
                    </td>
                </tr>
            <?php endforeach;?>
        </table>
    </form>
    
</div><!-- END #M405_request_wrap -->

<div class="clear"></div>
<br/>

<div>
    <!-- Button: Lập kế hoạch -->
    <button type="button" class="btn btn-custom" onclick="M405.createPlan()">
        <?php echo $this->_translate(8);?>
    </button>
</div>