<?php if (!$this->filename || !file_exists(QSS_DATA_DIR . "/documents/" .  $this->filename)):?>
	<?php echo $this->_translate(3)?>
<?php else:?>
	<a target="new" href="#" onclick="downloadFile('<?php echo $this->filename?>'); return false;"><?php echo $this->_translate(1)?><<</a>
	<a onclick="deleteFile('<?php echo $this->field->FormCode?>','<?php echo $this->field->ObjectCode?>','<?php echo $this->field->FieldCode?>','<?php echo $this->field->intIFID?>','<?php echo $this->field->intIOID?>','<?php echo $this->filename?>')" href="#!" >>><?php echo $this->_translate(2)?></a>'
<?php endif;?>