<?php
    $oldRequest      = '';
    $requestWidthArr = array(1,4,4,2,2,2,2,2,2,2);
    $width           = 1200;
    $padding         = 2;
    
    $fit = Qss_Lib_Report::changeWidthToFitScreen2($requestWidthArr, $width, $padding)
?>

<div id="M405_request_wrap">

    <form id="M405_request_compare_form">
        <table class="border_table" cellpadding="0" cellspacing="0" border="0" style="width:<?php echo $width;?>px">
            <?php $begin = 0; ?>
        
            <!-- Title -->
            <tr class="bggrey">
                <!-- STT -->
                <th style="width:<?php echo $fit[$begin++];?>px;">
                    <?php echo $this->_translate(1);?>
                </th>
    
                <!-- Mã mặt hàng -->
                <th style="width:<?php echo $fit[$begin++];?>px;">
                    <?php echo $this->_translate(2);?>
                </th>
    
                <!-- Tên mặt hàng -->
                <th style="width:<?php echo $fit[$begin++];?>px;">
                    <?php echo $this->_translate(3);?>
                </th>
    
                <!-- ĐVT -->
                <th style="width:<?php echo $fit[$begin++];?>px;">
                    <?php echo $this->_translate(4);?>
                </th>
    
                <!-- Số lượng yêu cầu -->
                <th style="width:<?php echo $fit[$begin++];?>px;">
                    <?php echo $this->_translate(5);?>
                </th>
    
                <!-- Báo Giá -->
                <th style="width:<?php echo $fit[$begin++];?>px;">
                    <?php echo $this->_translate(7);?>
                </th>
    
                <!-- Đặt hàng -->
                <th style="width:<?php echo $fit[$begin++];?>px;">
                    <?php echo $this->_translate(8);?>
                </th>
    
                <!-- Nhận hàng -->
                <th style="width:<?php echo $fit[$begin++];?>px;">
                    <?php echo $this->_translate(9);?>
                </th>
    
                <!-- Còn lại -->
                <th style="width:<?php echo $fit[$begin++];?>px;">
                    <?php echo $this->_translate(10);?>
                </th>
            </tr>
    
            <!-- Data -->
            <?php foreach($this->plan as $item):?>
    
                <!-- GROUP TITLE: Số phiêu/Request no -->
                <?php if($oldRequest != $item['RequestIOID']):?>
                <tr>
                    <td colspan="10" class="large_td left" style="padding-left:1px;" >
                        <?php echo $item['RequestNo'];?>
                        <?php $no = 0;?>
                    </td>
                </tr>
                <?php endif;?>
                <?php $oldRequest = $item['RequestIOID'];?>
    
    
                <tr>
                    <!-- STT -->
                    <td class="center">
                        <?php echo ++$no;?>
                        
                        <input type="hidden" name="requests[]" value="<?php echo $item['RequestIOID'];?>" />
                        <input type="hidden" name="rest[<?php echo $item['RequestIOID'];?>][<?php echo $item['ItemIOID'];?>]" value="<?php echo $item['Rest'];?>" />
                    </td>
    
                    <!-- Mã mặt hàng -->
                    <td class="left">
                        <?php echo $item['ItemCode'];?>
                    </td>
    
                    <!-- Tên mặt hàng -->
                    <td class="left">
                        <?php echo $item['ItemName'];?>
                    </td>
    
                    <!-- ĐVT -->
                    <td class="left">
                        <?php echo $item['UOM'];?>
                    </td>
    
                    <!-- Số lượng yêu cầu -->
                    <td class="right">
                        <?php echo $item['Planed'];?>
                    </td>
    
                    <!-- Báo Giá -->
                    <td class="right">
                        <?php echo $item['AlreadyQuote'];?>
                    </td>
    
                    <!-- Đặt hàng -->
                    <td class="right">
                        <?php echo $item['Ordered'];?>
                    </td>
    
                    <!-- Nhận hàng -->
                    <td class="right">
                        <?php echo $item['Received'];?>
                    </td>
    
                    <!-- Còn lại -->
                    <td class="right">
                        <?php echo $item['Rest'];?>
                    </td>
                </tr>
            <?php endforeach;?>
        </table>
    </form>
    
</div><!-- END #M405_request_wrap -->

<div class="clear"></div>
<br/>

<div>
    <!-- Button: Kiểm tra hợp đồng nguyên tắc -->
    <button type="button" class="btn btn-custom" onclick="M411.agreement();">
        <?php echo $this->_translate(11);?>
    </button>

    <!-- Button: Lập báo giá -->
    <button type="button" class="btn btn-custom" onclick="M411.quotation1Index();">
        <?php echo $this->_translate(12);?>
    </button>
    
    <!-- Button: Xem báo giá -->
    <button type="button" class="btn btn-custom" onclick="M411.quotation2();">
        <?php echo $this->_translate(13);?>
    </button>
    
    
    <!-- Button: So sánh báo giá -->
    <button type="button" class="btn btn-custom" onclick="M411.quotation3();">
        <?php echo $this->_translate(14);?>
    </button>
</div>