<script type="text/javascript">
    function printPreview()
    {
        var url = sz_BaseUrl + '/static/m177/show';
        var data = $('#report').serialize();

        qssAjax.getHtml(url, data, function(jreturn) {
            $('#print-area').html(jreturn);
            removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
        });
    }
</script>

<div class="clear">&nbsp;</div>
<div id="view">
    <div class="line-hr">
        <span>  Danh mục thiết bị kiểm định, hiệu chuẩn<?php //echo $this->_translate(1)?> </span>
    </div>

    <form id="report" method="get"
          action="/static/m177/show">
        <table class="detail" style="margin: 10px">

            <tr>
                <th width="20%" class="report-param-label"> Loại thiết bị <?php //echo $this->_translate(3) ?>
                </th>
                <td><?php
                    $id = 'location';
                    $getFields = array('num' => 3,
                        'objects' => array('OKhuVuc' => array(
                            'id' => 'IOID'
                        , 'display1' => 'MaKhuVuc'
                        , 'display2' => 'Ten')));
                    ?> <?php echo $this->views->Report->ComboBox($id, $getFields); ?>
                </td>
            </tr>

            <tr>
                <th width="20%" class="report-param-label"> Nhóm thiết bị <?php //echo $this->_translate(22) ?>
                </th>
                <td><?php
                    $id = 'group';
                    $getFields = array('num' => 3,
                        'objects' => array('ONhomThietBi' => array(
                            'id' => 'IOID'
                        , 'display1' => 'LoaiThietBi'
                        )));
                    ?> <?php echo $this->views->Report->ComboBox($id, $getFields); ?>
                </td>
            </tr>


            <?php if (Qss_Lib_Extra::checkFieldExists('ODanhSachThietBi', 'Ref_LoaiThietBi')): ?>
                <tr>
                    <th width="20%" class="report-param-label"> Loại thiết bị <?php //echo $this->_translate(21) ?>
                    </th>
                    <td><?php
                        $id = 'type';
                        $getFields = array('num' => 2,
                            'objects' => array('OLoaiThietBi' => array(
                                'id' => 'IOID'
                            , 'display1' => 'TenLoai'
                            )));
                        ?> <?php echo $this->views->Report->ComboBox($id, $getFields); ?>
                    </td>
                </tr>
            <?php endif; ?>

            <tr>
                <th width="20%" class="report-param-label"> Thiết bị <?php //echo $this->_translate(7) ?>
                </th>
                <td><?php
                    $id = 'equipment';
                    $getDataObject = array('ODanhSachThietBi' => array('MaThietBi', 'LoaiThietBi'));
                    $getFields = array('num' => 2,
                        'objects' => array('ODanhSachThietBi' => array(
                            'id' => 'IOID'
                        , 'display1' => 'MaThietBi'
                        , 'display2' => 'LoaiThietBi')));
                    $getLookupFilter = array(array('id' => 'group'
                    , 'refField' => array('ODanhSachThietBi' => 'Ref_NhomThietBi')
                    , 'required' => 0)
                    , array('id' => 'type'
                        , 'refField' => array('ODanhSachThietBi' => 'Ref_LoaiThietBi')
                        , 'required' => 0));
                    ?> <?php echo $this->views->Report->ListBox($id, $getDataObject, $getFields, $getLookupFilter); ?>
                </td>
            </tr>
        </table>
    </form>
    <hr />

    <?php echo $this->views->Report->PrintToolbar();?>
    <div id="print-content">
        <div id="print-area"></div>
    </div>
</div>
