<script>
function printPreview(){
	var ro = $('#ro').val();
	if(ro == '')	{
		qssAjax.alert('<?php echo $this->_translate(1)?>');
		return;
	}

//	$('#report').submit(function() {
//        window.open('', 'formpopup', 'statusbar=no,resizable=yes,scrollbars=yes, addressbar=no,maximize=yes');
//        this.target = 'formpopup';
//    });
//	$('#report').submit();
	 var url = sz_BaseUrl + '/report/production/cost/plan1';
		var data = $('#report').serialize();
		qssAjax.getHtml(url, data, function(jreturn) {
			$('#print-area').html(jreturn);
                        removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
		});
}
</script>


<div class="clear"></div>
<div id="view">
	<div class="line-hr">
		<span><?php echo $this->_translate(2)?> </span>
	</div>
	<form id="report" method="post" action="/report/production/cost/plan1">
		<table class="detail">
			<tr>
				<th width="20%" class="report-param-label">
					<!--   --> <?php echo $this->_translate(3)?></th>
				<td><select id="ro" name="ro">
						<option value="">
						<?php echo $this->_translate(4); ?>
						</option>
						<?php foreach ($this->requireOrder as $val): ?>
						<option value="<?php echo $val->IFID_M761; ?>">
						<?php echo $val->Code ?>
						</option>
						<?php endforeach; ?>
				</select> <span class="red bold">(*)</span>
				</td>
			</tr>

		</table>
	</form>
	<p>
	
	
	<hr>
	<?php echo $this->views->Report->PrintToolbar();?>
	<div id="print-content">
		<div id="print-area"></div>
	</div>
</div>
