<script>
	function printPreview() {
		var url  = sz_BaseUrl + '/static/m757/show';
		var data = $('#report').serialize();

		// LAY GIA TRI DANG CHUOI CUA DIEU KIEN LOC
		data += "&locationStr=" + encodeURIComponent($('#location option:selected').text());
		data += "&groupStr=" + encodeURIComponent($('#group option:selected').text());
		data += "&typeStr=" + encodeURIComponent($('#type option:selected').text());
		
		qssAjax.getHtml(url, data, function(jreturn) {
			$('#print-area').html(jreturn);
			removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
		});
	}
</script>

<div class="clear"></div>
<div id="view">
	<div class="line-hr">
		<span><?php echo Qss_Lib_System::getReportTitle('M757');?> </span>
	</div>

	<form id="report" method="get" action="/static/m757/show">
		<table class="detail">

			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(20)?>
				</th>
				<td><?php
				$id            = 'location';
				$getFields     = array('num'=>3,
										   'objects'=>array('OKhuVuc'=>array(
																'id'=>'IOID'
																,'display1'=>'MaKhuVuc'
																,'display2'=>'Ten') ));
																?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
				</td>
			</tr>


			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(2)?>
				</th>
				<td><?php
				$id            = 'group';
				$getFields     = array('num'=>3,
										   'objects'=>array('ONhomThietBi'=>array(
																'id'=>'IOID'
																,'display1'=>'LoaiThietBi'
																) ));
																?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
				</td>
			</tr>



			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(21)?>
				</th>
				<td><?php
				$id            = 'type';
				$getFields     = array('num'=>2,
										   'objects'=>array('OLoaiThietBi'=>array(
																'id'=>'IOID'
																,'display1'=>'TenLoai'
																)) );
																?> <?php echo $this->views->Report->ComboBox($id,$getFields);?>
				</td>
			</tr>


		</table>
	</form>


	<hr />
	<?php echo $this->views->Report->PrintToolbar();?>
	<div id="print-content">
		<div id="print-area"></div>
	</div>
</div>
