<script>
    function printPreview() {
        var ngaybd = $('#start').val();
        var ngaykt = $('#end').val();
        var ky = $('#period').val();
        var msg = '';

        msg += common_checkEmpty(ngaybd, '<?php echo $this->_translate(2);?>');
        msg += common_checkEmpty(ngaykt, '<?php echo $this->_translate(3);?>');
        msg += common_compareStartAndEnd(ngaybd, ngaykt);

        if (msg != '') {
            qssAjax.alert(msg);
            return;
        }
        else {
            var url = sz_BaseUrl + '/static/m835/show';
            var data = $('#report').serialize();
            qssAjax.getHtml(url, data, function (jreturn) {
                $('#print-area').html(jreturn);
                removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
            });
        }
    }
</script>
<div class="clear"></div>
<div id="view">
    <div class="line-hr">
        <span><?php echo Qss_Lib_System::getReportTitle('M835');?> </span>
    </div>
    <form id="report" method="post" action="/staitc/m835/show">
        <table class="detail">

            <!-- Ngày bắt đầu -->
            <tr>
                <th width="20%" class="report-param-label">
                    <?php echo $this->_translate(2) ?>
                </th>

                <td>
                    <?php echo $this->views->Report->Datepicker('start','01-' . date('m') . '-' . date('Y')); ?><span class="bold red">(*)</span>
                </td>
            </tr>

            <!-- Ngày kết thúc -->
            <tr>
                <th width="20%" class="report-param-label">
                    <?php echo $this->_translate(3) ?>
                </th>

                <td>
                    <?php echo $this->views->Report->Datepicker('end',date('t-m-Y')); ?><span class="bold red">(*)</span>
                </td>
            </tr>

            <!-- Don vi thuc hien -->
            <tr>
                <?php
                $getFields = array(
                    'num' => 3
                    , 'objects' => array
                    (
                        'ODonViSanXuat' => array
                        (
                            'id' => 'IOID'
                            , 'display1' => 'Ma'
                            , 'display2' => 'Ten'
                        )
                    )
                );
                ?>
                <th width="20%" class="report-param-label">
                    <?php echo $this->_translate(6) ?>
                </th>

                <td>
                    <?php echo $this->views->Report->ComboBox('workcenter', $getFields); ?>
                </td>
            </tr>
        </table>
    </form>
    <p>


    <hr>
    <?php echo $this->views->Report->PrintToolbar(); ?>
    <div id="print-content">
        <div id="print-area"></div>
    </div>
</div>
