<?php
$widths = array(2, 5, 5, 4, 5, 5, 5, 5);
$widths = Qss_Lib_Report::changeWidthToFitScreen3($widths);
$stt    = 0;
?>

<div class="landscape">
    <!-- REPORT TITLE -->
    <div id="head_print">
        <?php echo $this->views->Common->Landscape() ?>
        <?php //echo $this->views->Common->Legal() ?>
        <h2 class="center"><?php echo @Qss_Lib_System::getUpperCaseReportTitle('M847');?></h2>
    </div><!-- end div#head_print -->
    <br/>

    <!-- REPORT DATA -->
    <div id="container">
        <table cellpadding="0" cellspacing="0" border="1" class="border" style="">
            <?php $begin = 0;?>
            <tr class="bggrey">
                <th style="width:<?php echo $widths[$begin++];?>%">Thứ tự</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Máy chuyển</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Máy nhận</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Thời gian</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Số phiếu</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Mã thiết bị</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Tên vật tư chuyển</th>
                <th style="width:<?php echo $widths[$begin++];?>%">Lý do chuyển</th>
            </tr>

            <?php foreach($this->report as $item):?>
                <tr>
                    <td class="center"><?php echo ++$stt;?></td>
                    <td class="left"><?php echo $item->MaThietBiChuyen;?></td>
                    <td class="left"><?php echo $item->MaThietBiNhan;?></td>
                    <td class="center"><?php echo $item->NgayChuyen?Qss_Lib_Date::mysqltodisplay($item->NgayChuyen):'';?></td>
                    <td class="left"><?php echo $item->SoPhieu;?></td>
                    <td class="left"><?php echo $item->ViTriNhan;?></td>
                    <td class="left"><?php echo $item->TenVatTu;?></td>
                    <td class="left"><?php echo @$item->TenCongViec;?></td>
                </tr>
            <?php endforeach;?>
        </table>

        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>

        </p>
    </div><!-- end div#container -->
</div><!-- END REPORT -->


