<?php $excel_col = array_flip(Qss_Lib_Const::$EXCEL_COLUMN);?>
<?php
$widthArr = array(1, 3, 3, 1, 2, 2, 2, 2, 2, 2, 2, 2);//, 2, 3, 2, 2,2, 2, 2
$totalCol = count($widthArr);
$widthArr = Qss_Lib_Report::changeWidthToFitScreen3($widthArr);
$excelWidth = Qss_Lib_Report::convertPxColumnWidthToExcelWidth($widthArr);
$bg             = "#EEEEEE"; // Mau nen cua cot tieu de
$row           =1;
?>

<form id="excel" method="post" action="/report/index/excel" target="new">
    <input type="hidden" id="content" name="content" value="">
</form>

<div class="portrait">
    <excel orientation="portrait" font-name="Times New Roman" font-size="11"
           margin-left="0.5" margin-right="0.5" margin-top="0.75"
           margin-bottom="0.75" />

    <div id="head_print">
        <table>
            <tr>
                <td style="width: 40%;" class="center">
                    <xls row="<?php echo $row?>" column="A" column-merge="C" font-size="11" h-align="center" v-align="center"> Công ty…………</xls>
                </td>
                <td  class="center">
                    <xls row="<?php echo $row?>" column="E" column-merge="L" font-size="11" h-align="center" v-align="center"> Cộng hòa xã hội chủ nghĩa Việt nam</xls>
                </td>
            </tr>
            <?php $row++;?>

            <tr>
                <td  class="center">
                    <xls row="<?php echo $row?>" column="A" column-merge="C" font-size="11" h-align="center" v-align="center"> Xí nghiệp:………………...……..</xls>
                </td>
                <td  class="center">
                    <xls row="<?php echo $row?>" column="E" column-merge="L" font-size="11" h-align="center" v-align="center"> Độc lập - Tự do - Hạnh phúc</xls>
                </td>
            </tr>
            <?php $row++;?>

            <tr>
                <td  class="center">
                    <xls row="<?php echo $row?>" column="A" column-merge="C" font-size="11" h-align="center" v-align="center"> Số:………./BC - KT</xls>
                </td>
                <td  class="center">
                    <xls row="<?php echo $row?>" column="E" column-merge="L" font-size="11" h-align="center" v-align="center"> …………, ngày……tháng……năm 20….</xls>
                </td>
            </tr>
            <?php $row++;?>
        </table>

        <h2 class="center">
            <xls row="<?php echo $row?>" column="A" column-merge="L" font-size="16" h-align="center" v-align="center" bold="1"> BÁO CÁO TỔNG HỢP GÀU NGOẠM</xls>
        </h2>
        <?php $row++;?>

        <p class="center">
            <xls row="<?php echo $row?>" column="A" column-merge="L" font-size="11" h-align="center" v-align="center" > Tính đến ngày …. tháng ... năm 20 </xls>
        </p>
        <?php $row++;?>
    </div>

    <div id="container">
        <p class="right">
            <xls row="<?php echo $row?>" column="A" column-merge="K" font-size="11" h-align="left" v-align="center" > Mẫu số: BC - KT 12 </xls>
        </p>
        <?php $row++;?>

        <table width="" cellpadding="0" cellspacing="0" class="border" border="0">
            <?php $begin = 0;?>
            <tr class="bggrey">
                <!-- STT -->
                <th style="width: <?php echo $widthArr[$begin];;?>%">
                    <xls row="<?php echo $row?>" width="<?php echo $excelWidth[$begin];?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1" wrap-text="1"> STT </xls>
                </th>
                <th style="width: <?php echo $widthArr[$begin];;?>%">
                    <xls row="<?php echo $row?>" width="<?php echo $excelWidth[$begin];?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1" wrap-text="1"> LOẠI, TÊN <br>    (SỐ ĐĂNG KIỂM) </xls>
                </th>
                <th style="width: <?php echo $widthArr[$begin];;?>%">
                    <xls row="<?php echo $row?>" width="<?php echo $excelWidth[$begin];?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1" wrap-text="1"> CÔNG DỤNG </xls>
                </th>
                <th style="width: <?php echo $widthArr[$begin];;?>%">
                    <xls row="<?php echo $row?>" width="<?php echo $excelWidth[$begin];?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1" wrap-text="1"> SL </xls>
                </th>
                <th style="width: <?php echo $widthArr[$begin];;?>%">
                    <xls row="<?php echo $row?>" width="<?php echo $excelWidth[$begin];?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1" wrap-text="1"> KIỂU (MODEL) </xls>
                </th>
                <th style="width: <?php echo $widthArr[$begin];;?>%">
                    <xls row="<?php echo $row?>" width="<?php echo $excelWidth[$begin];?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1" wrap-text="1"> CÔNG SUẤT ( M3) </xls>
                </th>
                <th style="width: <?php echo $widthArr[$begin];;?>%">
                    <xls row="<?php echo $row?>" width="<?php echo $excelWidth[$begin];?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1" wrap-text="1"> BỘ PHẬN SỬ DỤNG </xls>
                </th>
                <th style="width: <?php echo $widthArr[$begin];;?>%">
                    <xls row="<?php echo $row?>" width="<?php echo $excelWidth[$begin];?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1" wrap-text="1"> NƠI SẢN XUẤT</xls>
                </th>
                <th style="width: <?php echo $widthArr[$begin];;?>%">
                    <xls row="<?php echo $row?>" width="<?php echo $excelWidth[$begin];?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1" wrap-text="1"> NĂM SẢN XUẤT </xls>
                </th>
                <th style="width: <?php echo $widthArr[$begin];;?>%">
                    <xls row="<?php echo $row?>" width="<?php echo $excelWidth[$begin];?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1" wrap-text="1"> NĂM SỬ DỤNG </xls>
                </th>
                <th style="width: <?php echo $widthArr[$begin];;?>%">
                    <xls row="<?php echo $row?>" width="<?php echo $excelWidth[$begin];?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1" wrap-text="1"> TÌNH TRẠNG HIỆN TẠI </xls>
                </th>
                <th style="width: <?php echo $widthArr[$begin];;?>%">
                    <xls row="<?php echo $row?>" width="<?php echo $excelWidth[$begin];?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1" wrap-text="1"> GHI CHÚ </xls>
                </th>
            </tr>
            <?php $row++;?>

            <tr class="bggrey">
                <?php $begin = 0;?>
                <th>
                    <xls row="<?php echo $row?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1"  wrap-text="1"> 1 </xls>
                </th>
                <th>
                    <xls row="<?php echo $row?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1"  wrap-text="1"> 2 </xls>
                </th>
                <th>
                    <xls row="<?php echo $row?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1"  wrap-text="1"> 3 </xls>
                </th>
                <th>
                    <xls row="<?php echo $row?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1"  wrap-text="1"> 4 </xls>
                </th>
                <th>
                    <xls row="<?php echo $row?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1"  wrap-text="1"> 5 </xls>
                </th>
                <th>
                    <xls row="<?php echo $row?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1"  wrap-text="1"> 6 </xls>
                </th>
                <th>
                    <xls row="<?php echo $row?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1"  wrap-text="1"> 7 </xls>
                </th>
                <th>
                    <xls row="<?php echo $row?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1"  wrap-text="1"> 8 </xls>
                </th>
                <th>
                    <xls row="<?php echo $row?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1"  wrap-text="1"> 9 </xls>
                </th>
                <th>
                    <xls row="<?php echo $row?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1"  wrap-text="1"> 10 </xls>
                </th>
                <th>
                    <xls row="<?php echo $row?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1"  wrap-text="1"> 11 </xls>
                </th>
                <th>
                    <xls row="<?php echo $row?>" font-size="8" column="<?php echo $excel_col[++$begin];?>" bgcolor="<?php echo $bg;?>" h-align="center" v-align="center" bold="1" border="1"  wrap-text="1"> 12 </xls>
                </th>
            </tr>
            <?php $row++;?>

            <?php
            $oldKhuVuc      = '';
            $sttKhuVuc      = 0;
            $oldLoaiThietBi = '';
            $sttLoaiThietBi = 0;
            $oldThongSo     = '';
            $oldThietBi     = '';
            $sttThietBi     = 0;
            $tongSo         = 0;
            ?>

            <?php foreach ($this->equips as $item):?>
                <?php $tongSo += 1;?>
                <?php $begin = 0;?>
                <tr>
                    <td class="center">
                        <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="center" v-align="center" border="1" wrap-text="1"><?php echo ++$sttThietBi;?></xls>
                    </td>
                    <td class="left">
                        <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="left" v-align="center" border="1" wrap-text="1"><?php echo $item->TenThietBi;?></xls>
                    </td>
                    <td class="left">
                        <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="left" v-align="center" border="1" wrap-text="1"><?php echo @$item->CongDung;?></xls>
                    </td>
                    <td class="right">
                        <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="right" v-align="center" border="1" wrap-text="1"><?php echo @Qss_Lib_Util::formatNumber(1);?></xls>
                    </td>
                    <td class="left">
                        <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="left" v-align="center" border="1" wrap-text="1"><?php echo @$this->dacTinh[$item->IFID_M705]['Kiểu'];?></xls>
                    </td>

                    <td class="right">
                        <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="right" v-align="center" border="1" wrap-text="1"><?php echo @Qss_Lib_Util::formatNumber(@$this->dacTinh[$item->IFID_M705]['Công suất']);?></xls>
                    </td>

                    <td class="left">
                        <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="left" v-align="center" border="1" wrap-text="1"><?php echo $item->MaKhuVuc;?></xls>
                    </td>
                    <td class="left">
                        <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="left" v-align="center" border="1" wrap-text="1"><?php echo $item->XuatXu;;?></xls>
                    </td>

                    <td class="left">
                        <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="left" v-align="center" border="1" wrap-text="1"><?php echo $item->NamSanXuat;;?></xls>
                    </td>

                    <td class="left">
                        <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="left" v-align="center" border="1" wrap-text="1"><?php echo @$item->NgayDuaVaoSuDung;?></xls>
                    </td>
                    <td class="left">
                        <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="left" v-align="center" border="1" wrap-text="1"><?php echo @$item->Ref_TrangThai;?></xls>
                    </td>

                    <td class="left">
                        <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="left" v-align="center" border="1" wrap-text="1"><?php echo @$item->GhiChu;?></xls>
                    </td>
                </tr>
                <?php $row++;?>
            <?php endforeach;?>

            <?php $begin = 0;?>
            <tr>
                <td class="center">
                    <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="center" v-align="center" border="1" wrap-text="1"></xls>
                </td>
                <td class="center">
                    <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="center" v-align="center" border="1" wrap-text="1">Tổng cộng:</xls>
                </td>
                <td class="left">
                    <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="left" v-align="center" border="1" wrap-text="1"></xls>
                </td>
                <td class="right">
                    <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="right" v-align="center" border="1" wrap-text="1"><?php echo @Qss_Lib_Util::formatNumber($tongSo);?></xls>
                </td>
                <td class="left">
                    <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="left" v-align="center" border="1" wrap-text="1"></xls>
                </td>

                <td class="right">
                    <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="right" v-align="center" border="1" wrap-text="1"></xls>
                </td>

                <td class="left">
                    <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="left" v-align="center" border="1" wrap-text="1"></xls>
                </td>
                <td class="left">
                    <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="left" v-align="center" border="1" wrap-text="1"></xls>
                </td>

                <td class="left">
                    <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="left" v-align="center" border="1" wrap-text="1"></xls>
                </td>

                <td class="left">
                    <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="left" v-align="center" border="1" wrap-text="1"></xls>
                </td>
                <td class="left">
                    <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="left" v-align="center" border="1" wrap-text="1"></xls>
                </td>

                <td class="left">
                    <xls row="<?php echo $row?>" column="<?php echo $excel_col[++$begin];?>" h-align="left" v-align="center" border="1" wrap-text="1"></xls>
                </td>
            </tr>
            <?php $row++;?>
        </table>
    </div>
</div>