<?php $maintenance = new Qss_Model_Extra_Maintenance();?>
<script>
function printPreview(){
	var start = $('#start').val();
	var end   = $('#end').val();
	var equipment   = $('#equipment').val();

	if(start == '')
	{
		qssAjax.alert('<?php echo $this->_translate(6);?>');
		return;
	}

	if(end == '')
	{
		qssAjax.alert('<?php echo $this->_translate(7);?>');
		return;
	}
	
	if(start > end)
	{
		qssAjax.alert('<?php echo $this->_translate(8);?>');
		return;
	}
	if(equipment == '')
	{
		qssAjax.alert('<?php echo $this->_translate(24);?>');
		return;
	}
//	$('#report').submit(function() {
//        window.open('', 'formpopup', 'statusbar=no,resizable=yes,scrollbars=yes, addressbar=no,maximize=yes');
//        this.target = 'formpopup';
//    });
//	$('#report').submit();
	 var url = sz_BaseUrl + '/static/m750/show';
		var data = $('#report').serialize();
		qssAjax.getHtml(url, data, function(jreturn) {
			$('#print-area').html(jreturn);
                        removePrintToolbarDisabled(); // Viet trong $this->views->Report->PrintToolbar()
		});
}
</script>
<div class="clear"></div>
<div id="view">
	<div class="line-hr">
		<span> <?php echo Qss_Lib_System::getReportTitle('M750');?> </span>
	</div>
	<form id="report" method="get"
		action="/report/maintenance/breakdown/mtbfmttr1">
		<table class="detail">
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(2);?>
				</th>
				<td><?php echo $this->views->Report->Datepicker('start', '01-'.date('m').'-'.date('Y'));?><span
					class="bold red">(*)</span></td>
			</tr>
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(3);?>
				</th>
				<td><?php echo $this->views->Report->Datepicker('end', date('d-m-Y'));?><span
					class="bold red">(*)</span></td>
			</tr>
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(23)?>
				</th>
				<td><?php echo $this->views->Report->SelectPeriod('period', 'period'); ?>
					<span class="bold red">(*)</span>
				</td>

			</tr>
			<tr>
				<th width="20%" class="report-param-label"><?php echo $this->_translate(4)?>:</th>
				<td>
					<select id="equipment" name="equipment" style="width: 300px;">
						<?php foreach ($this->equipments as $item):?>
							<option value="<?php echo $item->IOID?>"><?php echo $item->MaThietBi?> - <?php echo $item->TenThietBi?></option>
						<?php endforeach;?>
					</select>
				</td>
			</tr>
		</table>
	</form>
	<p>
	
	
	<hr>
	<?php echo $this->views->Report->PrintToolbar();?>
	<div id="print-content">
		<div id="print-area"></div>
	</div>
</div>
